### ISSUE TITLE
Spring 2023 Cross-Root ARIA F2F

### ISSUE THREAD

**Issue by nolanlawson** [WICG/webcomponents#1005]
During the [Web Components F2F](https://github.com/WICG/webcomponents/issues/978#issuecomment-1471288572), we decided to have a breakout session to discuss [cross-root ARIA](https://github.com/leobalter/cross-root-aria-delegation) and related proposals ([preso](https://docs.google.com/presentation/d/1m4H--TKr6DN_gLZAGIhIcU0TcQGcPTt5OlOOj7Mx-yc/edit?usp=sharing)).

Please indicate your availability in [when2meet](https://www.when2meet.com/?19804123-XHtxZ).

**Update:** tentative schedule is two meetings, in these two timeslots:

- Monday, May 8th 3-5pm PDT / 10pm-12am UTC
- Thursday, May 11th 9am-11am PDT / 4pm-6pm UTC

## Agenda

- [Can we use CSS `::part`](https://github.com/leobalter/cross-root-aria-delegation/blob/main/explainer.md#22-parts) ? 
- What about [encapsulation-preserving element references](https://github.com/WICG/aom/issues/195) and [semantic delegate](https://gist.github.com/alice/54108d8037f865876702b07755f771a5#reify-the-idea-of-a-semantic-delegate)?
- What about a global ID?
- Preventing "friendly fire" vs strong encapsulation – are they distinct use cases? 
- Exporting a proxy/wrapper instead of the element itself
- Spillover topics from F2F:
  - https://github.com/leobalter/cross-root-aria-delegation/issues/5
  - https://github.com/leobalter/cross-root-aria-delegation/issues/13
  - https://github.com/leobalter/cross-root-aria-delegation/issues/14
  - https://github.com/leobalter/cross-root-aria-delegation/issues/21
  - https://github.com/leobalter/cross-root-aria-delegation/issues/22
  - https://github.com/leobalter/cross-root-aria-delegation/issues/23
  - https://github.com/leobalter/cross-root-aria-delegation/issues/24
- #924
- #916
- #1004

**Comment by justinfagnani** [comment]
Add to agenda: https://github.com/WICG/webcomponents/issues/924, https://github.com/WICG/webcomponents/issues/916

**Comment by bennypowers** [comment]
#1004 is tangentially related, insofar as declarative syntax unblocks noscript

**Comment by rniwa** [comment]
Looks like there is no time slot where everyone is available at once. Days most people are available are Monday, May 8th 2-5pm PDT and Thursday, May 11th 9-11am PDT.

Out of timezone fairness and the amount of discussion involved, I'd suggest we host this on these two days:
* Monday, May 8th 3-5pm PDT / 10pm-12am UTC
* Thursday, May 11th 9am-11am PDT / 4pm-6pm UTC

**Comment by mrego** [comment]
For a 2nd meeting on this topic, we at Igalia are arranging the [Web Engines Hackfest](https://webengineshackfest.org/2023/) where we'll have breakout sessions about different topics.

We could use one of the breakout sessions to discuss about this topic (actually we were already thinking about it), @alice would be happy to run that session.

Those sessions will happen on June 6th and 7th, though times are not set yet set we could try to find the best day/time for everyone (15:00-16:30 CEST or 16:30-18:00 CEST are probably the best slots for people in US west coast).

Of course people are invited to participate onsite or virtually on the event.

If you think that's a good idea, let's consider it one of the follow-up breakout sessions on the topic.

**Comment by nolanlawson** [comment]
@mrego That would be awesome! I'm happy to delegate to Igalia on this.

How do folks feel about delaying the breakout until June 6th/7th?

**Comment by rniwa** [comment]
@nolanlawson : FWIW, I won't be available on June 6th/7th as I'd be traveling then.

**Comment by nolanlawson** [comment]
(Sorry for the late reply)

In that case, let's continue with the suggestions @rniwa had:

- Monday, May 8th 3-5pm PDT / 10pm-12am UTC
- Thursday, May 11th 9am-11am PDT / 4pm-6pm UTC

We can do both, to allow for more discussion in more time zones. @justinfagnani @westbrook Could one of you please schedule the meeting? I don't believe I have access to create a meeting for this group.

**Comment by Westbrook** [comment]
For multi-hour session, it's better if @justinfagnani puts in on the calendar. While there is no "working group" calendar, I think it makes sense to try to keep these sessions at least somewhat discoverable by posting them to https://calendar.google.com/calendar/embed?src=o25bim5rvcu42mfnqilirpmp44%40group.calendar.google.com.

Can you support us in creating this event Justin?

**Comment by nolanlawson** [comment]
It's clearly too late notice now to do today (May 8th), but maybe we can still do May 11th? @justinfagnani Thanks in advance!

**Comment by justinfagnani** [comment]
Oh man... I'm sorry I missed this!

Can people do next Monday?

**Comment by rniwa** [comment]
Next Monday works but can we keep Thu, May 11th at 9am?

**Comment by mfreed7** [comment]
I don't think I'm required for these meetings, but I'd really like to attend if possible. So FYI, I have limited availability May 11 9-11am PST, but I can try to make as much of it work as possible. However, I can't make Monday the 15th at all, I'm OOO.
(Maybe it's worth another [whentomeet](https://www.when2meet.com/?19804123-XHtxZ) for the next couple weeks?)

**Comment by nolanlawson** [comment]
We only have two confirmed for next Monday, so I suggest we do Thursday, May 11th, and then decide during that meeting if we want a follow-up. At that point, we can do another whentomeet.

**Comment by EisenbergEffect** [comment]
@chrisdholt I think you may want to attend this since it's focused on cross-root aria.

**Comment by rniwa** [comment]
Alright, I've created a Google meet URL for tomorrow: meet.google.com/rgz-ikwe-bfg

**Comment by nolanlawson** [comment]
I don't have it in my calendar, but I'm happy to join tomorrow at 9am at https://meet.google.com/rgz-ikwe-bfg .

**Comment by alice** [comment]
Obviously I can't make it at that time, but I've been dumping my thoughts on the "semantic delegate" concept into a doc: https://github.com/alice/aom/blob/gh-pages/semantic-delegate.md

**Comment by nolanlawson** [comment]
Thanks to everyone who participated in today's F2F! Notes are captured in [this doc](https://docs.google.com/document/d/1lCsVPRIgFs9DAJQX4tIIIX8acsEFetkJkTRTDcyDwIQ/edit?usp=sharing).

[Here's a when2meet](https://www.when2meet.com/?20045629-FIwdM) for our follow-up meeting, tentatively scheduled between May 22nd and June 2nd.

**Comment by bennypowers** [comment]
EU hours are preferable for @annevk and myself

**Comment by rniwa** [comment]
I think we should do the next meeting in a time slot that's friendly to Asia Pacific folks to be fair.

**Comment by nolanlawson** [comment]
OK, that's fair. Here is [the updated when2meet](https://www.when2meet.com/?20078358-WdnLB) with Asia Pacific-friendly times.

**Comment by alice** [comment]
Ironically I'll be travelling to Europe on Monday 29 May (Sydney time) so I can attend the [Web Engines Hackfest](https://webengineshackfest.org/2023/) on 5-7 June the following week, where we do have a [session on cross-root ARIA](https://github.com/Igalia/webengineshackfest/issues/10) planned (as mentioned by @mrego https://github.com/WICG/webcomponents/issues/1005#issuecomment-1520803979).

I realise @rniwa sadly can't join for that, so I'm very happy to meet next week and then again in early June to continue the conversation if that's how it shakes out; I just want to reiterate that the Hackfest session in planned and will be in a Europe-friendly timezone (hopefully later in the day so folks in North America can also join).

**Comment by rniwa** [comment]
My travel schedule got changed up a bit so I think I can join June 5-7 if it's EDT friendly time.

**Comment by annevk** [comment]
@Alice that's great to hear! Looking forward to seeing you there.

**Comment by nolanlawson** [comment]
Looks like the best time is May 25, 9am-11am Tokyo time (May 24 5pm-7pm US Pacific time).

@justinfagnani Any chance you could set up a meeting? 🙇

**Comment by rniwa** [comment]
Should we still have a meeting on May 25th? Or are we consolidating it to June 5th~7th?

**Comment by nolanlawson** [comment]
I'm fine with consolidating, unless someone wants May 25th specifically.

**Comment by rniwa** [comment]
@Alice @mrego : what time & date is cross-ARIA session happening?

**Comment by nolanlawson** [comment]
At this point, let's cancel May 25th and do the Igalia one instead.

The Igalia session (https://github.com/Igalia/webengineshackfest/issues/10) is Tuesday June 6th at 16:30 CEST.

**Comment by bennypowers** [comment]
Cross linking to #1014, which was brought up earlier as a potential quick-fix, but hasn't seen much attention since then.

**Comment by alice** [comment]
> The Igalia session ([Igalia/webengineshackfest#10](https://github.com/Igalia/webengineshackfest/issues/10)) is Tuesday June 6th at 16:30 CEST.

Thank you for finding and adding the link, @nolanlawson! 

I've now updated it with a tentative agenda - everyone, please don't hesitate to comment there or here if you'd like me to make any changes.

**Comment by rniwa** [comment]
Proposing more time at TPAC breakout: https://github.com/w3c/tpac2023-breakouts/issues/14
