### ISSUE TITLE
[scoped-registries] What does `new` mean for elements in multiple registries?

### ISSUE THREAD

**Issue by keithamus** [WICG/webcomponents#1007]
This was [originally raised](https://github.com/WICG/webcomponents/issues/716#issuecomment-369368684) by @matthewp:

```js
class MyElement extends HTMLElement {}
customRegistry.define('my-element', MyElement);
new MyElement();
```

I can't see how the discussion concluded this point. Are elements allowed on multiple registries? What happens with the following?

```js
class MyElement extends HTMLElement {}
customElements.define('my-element', MyElement);
customRegistry1.define('my-element', MyElement);
customRegistry2.define('my-element', MyElement);
new MyElement();
```

/cc @xiaochengh @justinfagnani

**Comment by xiaochengh** [comment]
The same constructor is allowed on multiple registries. However, a direct constructor call will only look up the global registry, because otherwise it has no way to know which registry to use.

See: https://wicg.github.io/webcomponents/proposals/Scoped-Custom-Element-Registries#custom-element-constructors

**Comment by justinfagnani** [comment]
Yeah, this is spelled out, and was decided on at the Tokyo F2F (I think?).

The main requirement is that `new MyElement()` has the same behavior with and without the presence of scoped registries - we can't break existing code. So there's only one right answer: it succeeds if the element is registered in the global registry, and fails if it isn't.

**Comment by keithamus** [comment]
I’ll close this out as it has an answer now. Thanks both!

**Comment by trusktr** [comment]
Seems like this makes DSD of limited use to people who are using elements that require arguments, f.e. `new SomeEl(a, b, c)`.

We'll be able to do this currently when we don't know a name:

```js
customRegistry.createElement(
  customRegistry.getName(SomeEl)
)
```

Maybe we need a way to pass args too, f.e.

```js
customRegistry.createElement(
  customRegistry.getName(SomeEl), a, b, c
)
```

or

```js
customRegistry.createElement(
  customRegistry.getName(SomeEl),
  { args: [a, b, c] }
)
```

or 

```js
customRegistry.construct(SomeEl, a, b, c)
```
