### ISSUE TITLE
2023 TPAC F2F discussion?

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#1018]
Are folks interested in discussing web components at this year's W3C TPAC? If so, what are the topics of your interests?

**Comment by EisenbergEffect** [comment]
Absolutely would love to meet and discuss web components topics. The Web Components CG has started a thread to prepare the annual report and discussion topics here:

https://github.com/w3c/webcomponents-cg/discussions/66

In addition to what is discussed there, there's been a renewed discussion of WebKit's current stance on customizable built-ins and how we should proceed with the relevant scenarios. I pinged you on the issue. Feel free to chime in whenever you get a chance.

**Comment by rniwa** [comment]
Alright, I've migrated the list of topics from that page:
- [Cross Root ARIA](https://docs.google.com/presentation/d/1m4H--TKr6DN_gLZAGIhIcU0TcQGcPTt5OlOOj7Mx-yc/edit#slide=id.g18d29405784_357_748)
- [Scoped Element Registries](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/Scoped-Custom-Element-Registries.md)
- [DOM Parts](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/DOM-Parts.md)
- Custom Attributes / Element Behaviors
- https://github.com/WICG/webcomponents/issues/972, especially accessibility-related scenarios.
- https://github.com/WICG/webcomponents/issues/939
- https://github.com/WICG/webcomponents/issues/814
- https://github.com/dequelabs/axe-core/issues/4085
- https://github.com/WICG/webcomponents/issues/936

**Comment by justinfagnani** [comment]
How long are the sessions? Given the potentially very long list of WC topics, would it make sense to prioritize by those that have some sort of update or need consensus on a particular open question?

For instance, the Chrome team has been prototyping both scoped custom element registries and DOM Parts to gather early implementor feedback. That might be good to discuss (if we don't get them it at earlier meetings).

**Comment by rniwa** [comment]
Proposing DOM / Template parts breakout session: https://github.com/w3c/tpac2023-breakouts/issues/13

**Comment by rniwa** [comment]
Cross-Root ARIA breakout session: https://github.com/w3c/tpac2023-breakouts/issues/14

**Comment by rniwa** [comment]
Scoped custom element registry session: https://github.com/w3c/tpac2023-breakouts/issues/15

**Comment by EisenbergEffect** [comment]
@rniwa Could we do a session to explore alternatives to customized built-ins? There's a nice alternative proposal by @trusktr that I think we could use as a solid starting point for discussions.

https://github.com/lume/element-behaviors/tree/v3.1.0

**Comment by bahrus** [comment]
Respectfully, I think that proposal falls short in a number of ways:

1.  For each behavior, the vendor needs to fully dictate what goes into the initial settings of the attribute (whether it be JSON or some other format).  Sharing one attribute for all behaviors would be too limiting.
2.  Having separate attributes conforms much more closely to proven solutions across multiple frameworks and across multiple decades of development.
3.  There's no explicit support for providing a public way for external components to interact with the behavior.  Not having that would make the proposal fall short of providing a true alternative to customized built-ins. [Update:  there is - element.behaviors - I missed that].
4.  It isn't a formal proposal.

There *is* a formal [proposal](https://github.com/WICG/webcomponents/issues/1000) that addresses all these concerns.  Any flaws that you see with it?

**Comment by EisenbergEffect** [comment]
@bahrus Let's discuss both of these options then. I just wanted to make sure we have some way of moving the conversation forward.

**Comment by michaelwarren1106** [comment]
> Respectfully, I think that proposal falls short in a number of ways:

Just wanted to add a comment here on the topic of these custom enhancements/attributes to say that I think that scoping should be a first-party concern whenever the element in question has a "canonical name". I think that the global nature of the custom element registry is coming to bear as a problem rather than the desired end state, and as such I think that we should consider scoping as a first concern with any new feature where defining the thing starts with some name that must be unique.

IMO any feature like custom elements or custom behaviors/enhancements should have the ability to be scoped to a particular element/collection so that third party libraries can safely declare these without worrying about conflicts in consuming applications.

**Comment by justinfagnani** [comment]
Can we make sure to leave technical discussion to specific issues about proposals and keep this one focused on agenda setting?

**Comment by trusktr** [comment]
Hello you all, I'm new to this process. Anything I can do to help facilitate the TPAC session on customized built-ins alternatives? Totally willing to help out, but not sure if someone already has that covered or what would be particularly helpful.

**Comment by rniwa** [comment]
> Hello you all, I'm new to this process. Anything I can do to help facilitate the TPAC session on customized built-ins alternatives? Totally willing to help out, but not sure if someone already has that covered or what would be particularly helpful.

Proposed it in https://github.com/w3c/tpac2023-breakouts/issues/44
