### ISSUE TITLE
RFC: Element Handles for Cross-root ARIA (cross-post from wicg/aom)

### ISSUE THREAD

**Issue by behowell** [WICG/webcomponents#1020]
I've written a proposal for solving the cross-root ARIA problem with a new feature called handles. 

Element handles are a way to refer to an element inside a shadow tree from an ID reference attribute like aria-labelledby or for, while preserving shadow DOM encapsulation. Handles can be summed up as "like [shadow parts](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/part), but for ID references." Much of the API is designed to be parallel to the shadow parts API and follows similar syntax.

The RFC is on the Accessibility Object Model project, but I figured it would be helpful to cross-post it to the Web Components project as well.
* https://github.com/WICG/aom/pull/200

Please add comments on the above PR, rather than in replies to this issue, to keep the discussion in one place. Thanks!

**Comment by behowell** [comment]
This proposal has evolved from element handles to exported IDs. The new proposal is conceptually similar, but uses a boolean `exportid` attribute to make the element's ID available outside of the shadow DOM, rather than a `handle` attribute that requires a new name.
* https://github.com/WICG/aom/pull/204

**Comment by Westbrook** [comment]
Feels closed by https://github.com/WICG/webcomponents/blob/gh-pages/proposals/reference-target-explainer.md
