### ISSUE TITLE
Quarterly Face to Face Scheduling

### ISSUE THREAD

**Issue by Westbrook** [WICG/webcomponents#1031]
As part of the [really productive Web Components-centric discussions at TPAC this year](https://github.com/WICG/webcomponents/issues/1026), the consensus was that a quarterly virtual Face-to-face with a more formal resolution process would be a good way to encourage progress of the many issues and proposals in this repo. With this in mind, I'd like to propose a winter/spring/summer schedule with TPAC standing in for the fall session as part of the 2024 calendar.

To facilitate the many complex topics we've already resolved to follow up on at TPAC, how do we feel about establishing a baseline of 2 individual 2-hour sessions in the week on the 15th of January, April, and July? We can gather topics (many of which are almost preplanned for the first session) up until 2 weeks prior to the sessions and if we happen to have fewer topics to cover than expected can revise down to a single session for the week in question. However, with two sessions in the week, we could also schedule one to be Euro-centric and one to be Asia-centric in timing, if there is enough regionally diverse interest.

Let's discuss this larger overall idea for the year here. When we get a consensus, at least insofar as January is concerned, we can open separate issues to confirm the timing and agenda for the seasonal sessions individually.

Thoughts?

**Comment by rniwa** [comment]
Scheduling something in the week of January 15 sounds good but perhaps we could also consider the week of December 11th? That's more of 3 months from now. I'm fine with having it in January if enough people have holiday plans, etc... in December though.

**Comment by rniwa** [comment]
By the way, I had also filed https://github.com/WICG/webcomponents/issues/1027. We should probably close either issue.

**Comment by Westbrook** [comment]
@rniwa does DOM Parts have enough topics to cover as to require an entire session in and of itself? As the spec begins to branch into effects for libraries and consumers that do not leverage other WC APIs, would they be more comfortable to joining the larger conversation in that case, too?

**Comment by rniwa** [comment]
Here's [when2meet](https://www.when2meet.com/?22118208-OZe1N) for two weeks in January.

**Comment by Westbrook** [comment]
To get in two separate two-hour meetings, the 3pm ET slot on the Mondays are looking the best right now. When should we lockdown timing on this? The holidays are just beginning, but once they do, it'll be whirlwind.

**Comment by Westbrook** [comment]
Starting a rough agenda for this. Please share any other topics that you'd like to see visited during these sessions, please share below!

**Scheduling**
- Are we generally in agreement with a baseline of 2 individual 2-hour sessions in the week on the 15th of January, April, and July?

**Scoped Element Registries**
- explainer/spec edits regarding: https://github.com/WICG/webcomponents/issues/923#issuecomment-1760586024
- share out from the Chromium prototype, if there's anything to share...

**Cross ShadowRoot Aria**
- @annevk, @alice, and @behowell have driven some breakouts on this
  - positive progress to share?
  - new blockers?
- Ben had been looking at the possibility of doing some prototyping here, anything to share on that?

**AriaMixin**
- Already spec'd and could buy some time on Cross ShadowRoot Aria...
- See: https://w3c.github.io/aria/#ARIAMixin
  - String reflection (e.g. ariaLabel, role), which is currently implemented in Chromium and Webkit but [not Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1785412).
  - Element reflection (e.g. ariaLabelledByElements, ariaActiveDescendantElement), which is currently implemented in WebKit but still [behind a flag in Chromium](https://chromestatus.com/feature/6244885579431936) and [not Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1769586).
- Blockers other than resourcing? 

**CSS Slot Content Detection**
- Mozilla indicated starting with https://github.com/w3c/csswg-drafts/issues/6867 would be a way to address https://github.com/WICG/webcomponents/issues/936
  - can we move forward with explainer and spec text?
  - are any browsers interested in prototyping here?
- This feels related to https://bugs.chromium.org/p/chromium/issues/detail?id=1492458, is there unclear spec text on this feature?

**HTML Modules**
- Looking into getting documentation for https://github.com/w3ctag/design-reviews/issues/334 updated as per Import Attributes
  - review on updated syntax: https://github.com/WICG/webcomponents/pull/1039
  - Is anything missing?
  - any blockers?

**DOM Parts**
- [Currently has its own breakout](https://github.com/WICG/webcomponents/issues/1027)

---

Note: the [Web Components Community Group](https://github.com/w3c/webcomponents-cg) has two more monthly meetings before these face-to-face sessions, so if there is any homework that implementors would like to see brought to the conversation, that is not included above, please call that out as soon as possible.

**Comment by justinfagnani** [comment]
I would love to discuss the external styling topic, as partially covered by https://github.com/WICG/webcomponents/issues/909 and https://github.com/WICG/webcomponents/issues/864

**Comment by nolanlawson** [comment]
AriaMixin might not need much discussion. String reflection is now shipped in Firefox, the Chromium implementation of element reflection is in active development, and so that would just leave [Firefox implementing element reflection](https://bugzilla.mozilla.org/show_bug.cgi?id=1769586).

**Comment by Westbrook** [comment]
In that it's about one month from now, and most of that time is taken up by holidays, the currently "best available" times seem to be:

**Wednesday the 10th**: 1pm ET - 3pm ET
**Monday the 15th**: 3pm ET - 5pm ET

This allows for different-shaped availability gaps for the two sessions.

I'm happy to list these sessions on the [Web Component Community Group calendar](https://calendar.google.com/calendar/u/0/embed?src=o25bim5rvcu42mfnqilirpmp44@group.calendar.google.com) so they are easier to track. If both these times and that offer go unargued by the end of the week, let's get these set and I'll add them to the calendar. From there we can continue to break down the [agenda above](https://github.com/WICG/webcomponents/issues/1031#issuecomment-1822209060) into those times.

Thoughts? Concerns?

**Comment by rniwa** [comment]
Those two time slots seem good to me. @smaug---- @keithamus which topic(s) would you be most interested in?

**Comment by keithamus** [comment]
I can try to attend both sessions, so no need to shuffle things on my account.

**Comment by smaug----** [comment]
I should be able to attend those sessions.

**Comment by EisenbergEffect** [comment]
Right now, my calendar is open for those sessions as well. Hoping to attend.

**Comment by nolanlawson** [comment]
I can attend either time as well.

**Comment by Westbrook** [comment]
Both of these events have been added to the [Web Components Community Group Calendar](https://calendar.google.com/calendar/u/0/embed?src=o25bim5rvcu42mfnqilirpmp44@group.calendar.google.com). I'm happy to add you as specific invitees, but I'd need email addresses. You can find me on the [Web Components Community Group Discord](https://discord.gg/Zdy6HZNxPK) if you'd prefer to DM that sort of information.

If people have preferences for days or lengths of time for the topics above, please share as we gather an official agenda by the 5th of January.

Also, the topic of `::has-slotted()` has come up in discussion this week in various places. I know that there was some interest from implementors in addressing that at TPAC, it would be great for us to have a solid position on that to forward to the CSS Working Group as one of the take-aways for these sessions.

**Comment by rniwa** [comment]
Oh wait, Mon, Jan 15th is MLK day. Perhaps we should schedule it on Fri, Jan 12th instead.

**Comment by Westbrook** [comment]
Good catch!

Is it better to use Friday (which would put it at the same time of the day as the first session, 1pm-3pm ET/6pm-8pm UTC) or to move it a whole week forward so we can use the same 3pm-5pm ET/8pm-10pm UTC window on the 8th of January?

**Comment by rniwa** [comment]
You mean move a whole week ahead to Mon, Jan 8th at the same time? That sounds fine with me.

**Comment by Westbrook** [comment]
Moved. See everyon on 8 January: https://calendar.google.com/calendar/u/0/embed?src=o25bim5rvcu42mfnqilirpmp44@group.calendar.google.com

**Comment by rniwa** [comment]
So we're less than one week away from Jan 9th 3-5pm meeting. What's our agenda?

**Comment by justinfagnani** [comment]
@Westbrook does [this comment](https://github.com/WICG/webcomponents/issues/1031#issuecomment-1822209060) represent an live agenda, or should we make a document somewhere?

**Comment by Westbrook** [comment]
Here's a live document with the agenda: https://docs.google.com/document/d/1NRI_Ns8dw33LA21Fj2F21J-aTI-QbXW6jKWkiwsQA_Q/edit Ping me for editor permissions so we can get anything I've missed/notes/etc included as we move through the week.

I've added all the subjects from above to both days. Insight on the length of time we'd like to spend on various things can help sort out the days/orders. I've also reached out to @behowell directly as to which of the two days would be best for him to share the latest cross-route ARIA proposal.

**Comment by Westbrook** [comment]
I've broken the [agenda for the two days](https://docs.google.com/document/d/1NRI_Ns8dw33LA21Fj2F21J-aTI-QbXW6jKWkiwsQA_Q/edit) in the live agenda above into:

**Monday, 8 January**
3pm ET
- CSS Slot Content Detection
  - CCWG has been discussing this, too. Can we get to something presentable to them to close https://github.com/w3c/csswg-drafts/issues/6867
- Scoped Element Registries
  - ~will @xiaochengh or someone from their team be able to discuss the spec changes referenced in https://github.com/WICG/webcomponents/issues/923#issuecomment-1760586024~

4pm ET
- Cross ShadowRoot Aria (lead by Ben Howell)
  - https://github.com/WICG/aom/pull/207 
- AriaMixin
  - https://w3c.github.io/aria/#ARIAMixin
    - ~String reflection (e.g. ariaLabel, role), which is currently implemented in Chromium and Webkit but [not Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1785412).~
    - Element reflection (e.g. ariaLabelledByElements, ariaActiveDescendantElement), which is currently implemented in WebKit but still [behind a flag in Chromium](https://chromestatus.com/feature/6244885579431936) and [not Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1769586).

**Wednesday, 10 January**
1pm ET
- External Styling
  - often discussed as https://github.com/WICG/webcomponents/issues/909 but a recent "hot topic" for the growing HTML Web Components crowed.
- Container (Style) Queries
  - there's a lot of power here for element authors as seen in [`<std-switch>`](https://github.com/tkent-google/std-switch/blob/master/src/switch.mjs#L479-L501) (all JS at that point)
  - also this unexpected failure: https://codepen.io/miriamsuzanne/pen/BabNJBY?editors=1100
- @sheet 
  - https://github.com/w3c/csswg-drafts/issues/5629

2pm ET
- Import Attributes
  - https://tc39.es/proposal-import-attributes/
- @sheet 
  - https://github.com/w3c/csswg-drafts/issues/5629
  - just in case it falls off the calendar on Monday
- HTML Modules
  -  https://github.com/w3ctag/design-reviews/issues/334

**Extra credit topics**
- Persisting registrations across page loads: https://github.com/WICG/webcomponents/issues/1033
- Slotchange/Observer scale/flexibility: https://github.com/WICG/webcomponents/issues/1042 and https://github.com/WICG/webcomponents/issues/933

**Comment by rniwa** [comment]
Can we swap the agenda for 8th and 10th and schedule ARIA related topics at 4pm so that @alice and other folks from Australia could join?

**Comment by Westbrook** [comment]
@behowell is leading the cross-root presentation, but he did mention that he had availability on Monday, even if it wasn't his preference.

@alice, are you able to join us on Monday? It would be nice to have your input if so, but I know those times are still pretty early for Australia.

**Comment by alice** [comment]
3pm ET is 7am here (and 6am in Brisbane where @jcsteh is); that's manageable with enough coffee :) 

I'd like to join if you think my input will be helpful, and if @behowell can make it at such late notice.

**Comment by behowell** [comment]
Yes I'll be able to make the Monday session. Sounds like that'll work better schedule-wise for everyone. See you all Monday!

**Comment by Westbrook** [comment]
Amazing! Thanks everyone for you flexibility. I've swapped the 1pm ET hour on Wednesday with the 4pm ET hour on Monday, in the comment above and in the live agenda.

Have a great weekend, see yall on Monday!

**Comment by zcorpan** [comment]
> * String reflection (e.g. ariaLabel, role), which is currently implemented in Chromium and Webkit but [not Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1785412).

String reflection is supported since Firefox 119. (Element reflection is not supported.)

**Comment by Westbrook** [comment]
For any last-minute joiner, the first half of today's session with use [this video link](http://meet.google.com/azk-rgyo-kjc), and the second half will use [this video link](http://meet.google.com/dzd-ojci-ajs).

**Comment by rniwa** [comment]
Oh shoot, sorry, I miscalculated my timezone and missed today's meeting :(

**Comment by Westbrook** [comment]
Notes from this week's discussion: https://docs.google.com/document/d/1NRI_Ns8dw33LA21Fj2F21J-aTI-QbXW6jKWkiwsQA_Q/edit (I'll close this docs to edits in a couple of days, in case you've got any last minute notes you think we forgot)

Action Items from this week's discussions:
- [x] :has-slotted() comment back on issue with tighter scope and reach out to Tab/Fantasi on spec text writing
  - [https://github.com/w3c/csswg-drafts/issues/6867#issuecomment-1881899574](https://www.google.com/url?q=https://github.com/w3c/csswg-drafts/issues/6867%23issuecomment-1881899574&sa=D&source=docs&ust=1704843830475794&usg=AOvVaw3dh122upn8MgONv93Fon8K)
- [x] @sorvell to make an issue about micro-frameworks use-case for Scoped Element Registries…
  - [https://github.com/WICG/webcomponents/issues/1043](https://www.google.com/url?q=https://github.com/WICG/webcomponents/issues/1043&sa=D&source=docs&ust=1704843830474716&usg=AOvVaw3MedrmNkyvzHSEOrTwtNJ9)
- [x] Get the community to work with the prototype via the `ScopedCustomElementRegistry` flag or all Experimental Web Platform Features
> how people work is improved too fwiw. i showed my team the branch i had, explained scoped registries, etc. they found it a lot easier to understand scoping sub elements through a custom registry than they did just by convention

> i did branch off our main project and get it working in canary
basically lit + scoped registries, and didn't run into any obvious problems. so i didn't really have any strong feedback in the end other than the fact it helped out a lot
we have quite a lot of prefixed elements which never get used outside their area, so scoped registries clean it up a fair amount since we can group them together
- [x] @behowell to prototype in Chromium on referenceDelegate and referenceDelegateMap!
- [x] Community Group should investigate and clarify smaller “user stories” around external styling
- [ ] Sync web bundles, https://github.com/tc39/proposal-module-declarations, and https://github.com/w3c/csswg-drafts/issues/5629 discussions
- [x] Community Group should get more high-priority examples for HTML modules
- [x] Community Group should discuss and get thoughts together around declarative custom elements
- [x] Refocus for clarity: [Allow customElementRegistry definitions to persist across page loads #1033](https://github.com/WICG/webcomponents/issues/1033)

Thanks, everyone for joining in the conversation!

Reminder that the Web Components Community Group has monthly sessions on these topics AND MORE and you can track these events via: https://calendar.google.com/calendar/u/0/embed?src=o25bim5rvcu42mfnqilirpmp44@group.calendar.google.com

I'll be opening an issue for the Q2 gathering (scheduling, agenda-ing, etc) shortly, so be on the lookout!
