### ISSUE TITLE
DocumentOrShadowRoot.deepActiveElement

### ISSUE THREAD

**Issue by TakayoshiKochi** [WICG/webcomponents#104]
Takayoshi Kochi 2015-05-18 07:34:21 UTC

According to the current spec,
http://w3c.github.io/webcomponents/spec/shadow/#active-element
Document.activeElement returns "adjusted" element, i.e.
when the real focused element is within a shadow tree, it returns
the top-most shadow host in the Document treescope.

The real focused element can be retrieved by recursively applying
.activeElement against shadowRoots on the way, but it may be
convenient to have a way to directly retrieve the element from Document.

One use case is for accessibility plugins; when a web app is provided
as one custom element (e.g. `<topeka-app>` at https://polymer-topeka.appspot.com/),
Document.activeElement always points to `<topeka-app>`,  which does not make
much sense for accessibility plugins.
It may be also necessary to have another type of event than "focus", which
fires when Document.activeElement changes.

**Comment by annevk** [comment]
Why would a plugin not have access to privileged APIs?

**Comment by TakayoshiKochi** [comment]
Yeah, for screen readers and the like to be able to look into contents in closed shadow, probably some privileged APIs must be provided for them.  So accessibility feature isn't very compelling reason to want this.

`deepActiveElement` can be just a sugar for _O(depth)_ loop of `activeElement`, but platform may provide this in _O(1)_, so if this is proven to be a performance bottleneck for some use case, this is worth considering.

**Comment by robdodson** [comment]
Probably a dumb question, but if I can recursively call `shadowRoot.activeElement` how will I know when I've hit the "real" activeElement? Will it eventually return null or undefined?

**Comment by hayatoito** [comment]
When `activeElement.shadowRoot` returns null, it reaches the _end_ too, I think. 

The following should work.  Please correct me If I miss something.

``` js
  function deepActiveElement() {
      let a = document.activeElement;
      while (a && a.shadowRoot && a.shadowRoot.activeElement) {
          a = a.shadowRoot.activeElement;
      }
      return a;
  }
```

**Comment by hayatoito** [comment]
I am triaging open issues. Let me close this.
