### ISSUE TITLE
.

### ISSUE THREAD

**Issue by titoBouzout** [WICG/webcomponents#1079]
.

**Comment by Westbrook** [comment]
In that you're including the `<!DOCTYPE html>\n` in your example, I wonder if it would be to the same benefit to add `getHTML()` on `document`? Not sure if that causes more, the same, or less trouble at the spec/implementation level.

**Comment by titoBouzout** [comment]
I am not sure we can add `document.getHTML()` for the same reason we do not have `document.outerHTML`, it just doesn't work like that
