### ISSUE TITLE
.

### ISSUE THREAD

**Issue by titoBouzout** [WICG/webcomponents#1080]
Nevermind

**Comment by Westbrook** [comment]
It's not so sexy, and will have different implications in the world of Scoped Registries, but you can `customElements.getName(el.constructor)` and get a string when it's a custom element or null when it is not...

**Comment by titoBouzout** [comment]
Thanks for input @Westbrook ! 

First, that's not what I am asking, and second nobody seems to be using it..... which should be hinting given what we are doing .. a `node.isCustomElement` would have sufficed for us, it seems.

**Comment by Westbrook** [comment]
Could you help clarify how `customElements.getName(el.constructor) !== null` is different than `el.isCustomElement`?

It's a [relatively new API](https://github.com/whatwg/html/pull/9195), I wouldn't be surprised by teams not actively following web components APIs to be unaware of it, which may point to why it's not being used in the context of frameworks today.

**Comment by titoBouzout** [comment]
Alright, so I opened the console into this very same page, `document.all` seems to produce 2589 elements. 

We can iterate the whole thing with the following and run the suggested `customElement.getName` thing

```js
const start = performance.now()
;[...document.all].forEach(element => {
	for (const attribute of element.attributes) {
		element.isCustomElement
	}
})
console.log('that took', performance.now() - start)
```


Then we can run the following

```js
const start = performance.now()
;[...document.all].forEach(element => {
	for (const attribute of element.attributes) {
		customElements.getName(element.constructor)
	}
})
console.log('that took', performance.now() - start)

```

`customElements.getName` takes around double than an `isCustomElement` check, from a performance point of view, and also provide worse DX and increased code size.

**Comment by EisenbergEffect** [comment]
I don't have a major issue with adding a flag like `isCustomElement` but I do worry about libraries/frameworks having increased branching in their code based on something like this. It's still not clear to me why it needs to be done. None of the templating engines I've written in the last ten years needed something like this, and they work fine with custom elements by treating them just like any other element.

Can we capture the library/framework use cases to better understand why this branching is needed? Perhaps there is a better way to address the specific concerns.

**Comment by titoBouzout** [comment]
@EisenbergEffect  TLDR: if you provide heuristics, you will do different heuristics if it's a custom element or not. Which is a valid use case. Then, you also have that `importNode` is slower than `cloneNode`, so there's that. Anyway, being able to tell one from another apart is a good thing. It adds no complexity and brings flexibility, for whatever reason.

**Comment by EisenbergEffect** [comment]
I think the import vs. clone node issue was discovered to be Chrome-only. That has been reported to Chrome as well, and I expect they will fix it. So, I'm not sure that should be taken into consideration, as it will be a non-issue across the board soon. Also, it's generally a bad idea to try to customize implementations based on point-in-time browser-specific perf. These things change quite a lot and often come back to bite.

Can you go into detail on what is happening around heuristics? What is being done differently for custom elements that doesn't apply to built-ins?

**Comment by rniwa** [comment]
I'd rather not add this property unless there is a **VERY** compelling reason to do so. Generally speaking, we shouldn't be treating custom elements differently from builtin elements.

**Comment by titoBouzout** [comment]
@rniwa  a good compelling reason is that you can special case all native elements properties vs attributes, but you cannot do the same for custom elements, as pretty much custom elements do whatever they want. So there's a very big difference. Btw, as far as I remember Safari doesn't support `is` so I suppose that doesn't bother you. :)

The real compelling reason: every single framework has some sort of "isCustomElement" function or some "includes('.')", that should be reason enough already.

**Comment by titoBouzout** [comment]
> Can you go into detail on what is happening around heuristics? What is being done differently for custom elements that doesn't apply to built-ins?

Thanks, @EisenbergEffect, and yes, the problem is that for native elements you pretty much know all cases. But with custom elements you have no way to know all cases, because they can choose to use a property or an attribute at will. When writing heuristics, the heuristics would be more approximate if you know if something is a custom element or not. 

```js
const setUnknown = (node, name, value) => {
  if (isCustomElement(node)) {
    // custom elements
    name in settersOf(node)
      ? setProperty(node, name, value)
      : setAttribute(node, name, value)
  } else {
    // native elements
    if (typeof value !== 'string' && name in settersOf(node)) {
      setProperty(node, name, value)
    } else {
      setAttribute(node, name, value)
    }
  }
}
```

**Comment by EisenbergEffect** [comment]
I see. Hmm. 

Technically any HTML element can have any attribute or property. And some libraries add them dynamically for their own use. So, I would tend not to rely on knowing what attrs/props anything has, as a general rule.

It also seems pretty strange to me to branch on setting an attr vs. prop based on the value type or inheritance hierarchy. That would potentially make the outcome unpredictable.

In general, I think the developer who is using the element should specify whether to set property, attribute, boolean attribute, etc. using some syntax in the template engine. Trying to get the templating engine to _guess_ the right mechanism seems like it will cause problems. Additionally, I'm even less sure how this will work with future potential standards like custom attributes.

**Comment by titoBouzout** [comment]
Right, this is not an issue, I am closing. Let's keep custom elements slow. I am starting to believe that would be the most productive thing in the long term, because time will tell.
