### ISSUE TITLE
Clonning shadowroot , example : element.cloneNode({ deep: true, includeShadowDOM: true });

### ISSUE THREAD

**Issue by Switcherfaiz** [WICG/webcomponents#1082]
Can i have the ability to clone the existed shadow root please just by using cloneNode method or by adding cloneable prop in the previous attachshadow like  element.attachShadow({mode: 'closed', cloneable: true}),i am trying to build a framework which is based on ceating web components from the server and i need that feature please

**Comment by rniwa** [comment]
clonable exists: https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/clonable
