### ISSUE TITLE
Migrate the bugs filed for Custom Elements from bugzilla to GitHub Issues, here.

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#119]
It would be better to migrate the custom elements bugs from bugzilla [1] into here, as the bugs for Shadow DOM were done, for the consistency.
[1] https://www.w3.org/Bugs/Public/showdependencytree.cgi?id=14968&hide_resolved=1

**Comment by hayatoito** [comment]
As per the discussion [1] in public-webapps, i'm going to migrate all open bugs of "Component Models" [2] in a few days. As of now, there are 151 bugs.

Note that if you are watching this Web Components repository, you might receive a lot of notifications.

[1] https://lists.w3.org/Archives/Public/public-webapps/2015JulSep/0006.html
[2] https://www.w3.org/Bugs/Public/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&component=Component%20Model&list_id=57902&query_format=advanced

**Comment by hayatoito** [comment]
I've finished the migration. The following 141 bugs have been migrated.

The bugzilla bug number: The GitHub Issue number

{
    "26656": "https://github.com/w3c/webcomponents/issues/196",
    "28541": "https://github.com/w3c/webcomponents/issues/139",
    "15053": "https://github.com/w3c/webcomponents/issues/259",
    "26583": "https://github.com/w3c/webcomponents/issues/201",
    "24042": "https://github.com/w3c/webcomponents/issues/221",
    "20973": "https://github.com/w3c/webcomponents/issues/177",
    "15148": "https://github.com/w3c/webcomponents/issues/258",
    "25669": "https://github.com/w3c/webcomponents/issues/162",
    "27643": "https://github.com/w3c/webcomponents/issues/169",
    "25566": "https://github.com/w3c/webcomponents/issues/217",
    "27496": "https://github.com/w3c/webcomponents/issues/173",
    "24178": "https://github.com/w3c/webcomponents/issues/168",
    "27375": "https://github.com/w3c/webcomponents/issues/181",
    "20683": "https://github.com/w3c/webcomponents/issues/149",
    "26065": "https://github.com/w3c/webcomponents/issues/206",
    "28092": "https://github.com/w3c/webcomponents/issues/144",
    "21253": "https://github.com/w3c/webcomponents/issues/235",
    "14976": "https://github.com/w3c/webcomponents/issues/255",
    "26682": "https://github.com/w3c/webcomponents/issues/197",
    "27978": "https://github.com/w3c/webcomponents/issues/151",
    "22038": "https://github.com/w3c/webcomponents/issues/234",
    "26576": "https://github.com/w3c/webcomponents/issues/202",
    "14960": "https://github.com/w3c/webcomponents/issues/270",
    "15478": "https://github.com/w3c/webcomponents/issues/257",
    "23864": "https://github.com/w3c/webcomponents/issues/232",
    "17591": "https://github.com/w3c/webcomponents/issues/250",
    "27914": "https://github.com/w3c/webcomponents/issues/155",
    "24866": "https://github.com/w3c/webcomponents/issues/222",
    "28547": "https://github.com/w3c/webcomponents/issues/133",
    "14963": "https://github.com/w3c/webcomponents/issues/268",
    "26681": "https://github.com/w3c/webcomponents/issues/198",
    "24570": "https://github.com/w3c/webcomponents/issues/176",
    "27379": "https://github.com/w3c/webcomponents/issues/180",
    "17089": "https://github.com/w3c/webcomponents/issues/251",
    "27977": "https://github.com/w3c/webcomponents/issues/153",
    "26213": "https://github.com/w3c/webcomponents/issues/204",
    "26898": "https://github.com/w3c/webcomponents/issues/193",
    "14956": "https://github.com/w3c/webcomponents/issues/249",
    "27366": "https://github.com/w3c/webcomponents/issues/182",
    "28158": "https://github.com/w3c/webcomponents/issues/143",
    "28051": "https://github.com/w3c/webcomponents/issues/148",
    "23018": "https://github.com/w3c/webcomponents/issues/236",
    "24603": "https://github.com/w3c/webcomponents/issues/187",
    "27770": "https://github.com/w3c/webcomponents/issues/161",
    "27405": "https://github.com/w3c/webcomponents/issues/163",
    "14959": "https://github.com/w3c/webcomponents/issues/271",
    "27769": "https://github.com/w3c/webcomponents/issues/164",
    "26233": "https://github.com/w3c/webcomponents/issues/205",
    "14984": "https://github.com/w3c/webcomponents/issues/263",
    "25610": "https://github.com/w3c/webcomponents/issues/215",
    "14975": "https://github.com/w3c/webcomponents/issues/265",
    "26845": "https://github.com/w3c/webcomponents/issues/178",
    "25696": "https://github.com/w3c/webcomponents/issues/213",
    "26643": "https://github.com/w3c/webcomponents/issues/199",
    "24876": "https://github.com/w3c/webcomponents/issues/224",
    "25319": "https://github.com/w3c/webcomponents/issues/141",
    "24578": "https://github.com/w3c/webcomponents/issues/154",
    "24579": "https://github.com/w3c/webcomponents/issues/186",
    "25924": "https://github.com/w3c/webcomponents/issues/207",
    "15479": "https://github.com/w3c/webcomponents/issues/256",
    "24106": "https://github.com/w3c/webcomponents/issues/228",
    "27437": "https://github.com/w3c/webcomponents/issues/175",
    "22056": "https://github.com/w3c/webcomponents/issues/239",
    "27976": "https://github.com/w3c/webcomponents/issues/147",
    "25563": "https://github.com/w3c/webcomponents/issues/183",
    "25470": "https://github.com/w3c/webcomponents/issues/218",
    "28544": "https://github.com/w3c/webcomponents/issues/134",
    "17761": "https://github.com/w3c/webcomponents/issues/146",
    "20466": "https://github.com/w3c/webcomponents/issues/159",
    "26846": "https://github.com/w3c/webcomponents/issues/194",
    "25715": "https://github.com/w3c/webcomponents/issues/188",
    "25830": "https://github.com/w3c/webcomponents/issues/211",
    "26934": "https://github.com/w3c/webcomponents/issues/192",
    "21916": "https://github.com/w3c/webcomponents/issues/229",
    "25818": "https://github.com/w3c/webcomponents/issues/209",
    "15058": "https://github.com/w3c/webcomponents/issues/247",
    "14968": "https://github.com/w3c/webcomponents/issues/132",
    "21169": "https://github.com/w3c/webcomponents/issues/245",
    "27016": "https://github.com/w3c/webcomponents/issues/189",
    "15013": "https://github.com/w3c/webcomponents/issues/241",
    "23278": "https://github.com/w3c/webcomponents/issues/220",
    "25916": "https://github.com/w3c/webcomponents/issues/208",
    "14987": "https://github.com/w3c/webcomponents/issues/262",
    "27325": "https://github.com/w3c/webcomponents/issues/184",
    "28542": "https://github.com/w3c/webcomponents/issues/138",
    "24629": "https://github.com/w3c/webcomponents/issues/227",
    "21499": "https://github.com/w3c/webcomponents/issues/238",
    "27611": "https://github.com/w3c/webcomponents/issues/170",
    "14973": "https://github.com/w3c/webcomponents/issues/246",
    "24087": "https://github.com/w3c/webcomponents/issues/140",
    "27440": "https://github.com/w3c/webcomponents/issues/174",
    "25484": "https://github.com/w3c/webcomponents/issues/219",
    "27780": "https://github.com/w3c/webcomponents/issues/158",
    "26943": "https://github.com/w3c/webcomponents/issues/191",
    "14962": "https://github.com/w3c/webcomponents/issues/254",
    "27017": "https://github.com/w3c/webcomponents/issues/190",
    "28902": "https://github.com/w3c/webcomponents/issues/131",
    "27260": "https://github.com/w3c/webcomponents/issues/185",
    "26713": "https://github.com/w3c/webcomponents/issues/195",
    "22900": "https://github.com/w3c/webcomponents/issues/237",
    "24020": "https://github.com/w3c/webcomponents/issues/214",
    "27836": "https://github.com/w3c/webcomponents/issues/157",
    "19685": "https://github.com/w3c/webcomponents/issues/248",
    "21915": "https://github.com/w3c/webcomponents/issues/242",
    "28449": "https://github.com/w3c/webcomponents/issues/142",
    "26638": "https://github.com/w3c/webcomponents/issues/200",
    "14981": "https://github.com/w3c/webcomponents/issues/266",
    "24756": "https://github.com/w3c/webcomponents/issues/203",
    "27380": "https://github.com/w3c/webcomponents/issues/179",
    "25473": "https://github.com/w3c/webcomponents/issues/150",
    "24398": "https://github.com/w3c/webcomponents/issues/230",
    "27975": "https://github.com/w3c/webcomponents/issues/152",
    "27768": "https://github.com/w3c/webcomponents/issues/165",
    "22409": "https://github.com/w3c/webcomponents/issues/225",
    "24577": "https://github.com/w3c/webcomponents/issues/210",
    "27751": "https://github.com/w3c/webcomponents/issues/166",
    "14972": "https://github.com/w3c/webcomponents/issues/244",
    "21913": "https://github.com/w3c/webcomponents/issues/243",
    "24655": "https://github.com/w3c/webcomponents/issues/226",
    "28546": "https://github.com/w3c/webcomponents/issues/135",
    "27835": "https://github.com/w3c/webcomponents/issues/156",
    "24848": "https://github.com/w3c/webcomponents/issues/223",
    "14961": "https://github.com/w3c/webcomponents/issues/269",
    "15018": "https://github.com/w3c/webcomponents/issues/260",
    "28545": "https://github.com/w3c/webcomponents/issues/136",
    "21914": "https://github.com/w3c/webcomponents/issues/240",
    "14977": "https://github.com/w3c/webcomponents/issues/267",
    "14983": "https://github.com/w3c/webcomponents/issues/264",
    "14949": "https://github.com/w3c/webcomponents/issues/172",
    "25568": "https://github.com/w3c/webcomponents/issues/216",
    "23861": "https://github.com/w3c/webcomponents/issues/233",
    "27762": "https://github.com/w3c/webcomponents/issues/160",
    "14974": "https://github.com/w3c/webcomponents/issues/252",
    "15012": "https://github.com/w3c/webcomponents/issues/261",
    "27538": "https://github.com/w3c/webcomponents/issues/171",
    "28543": "https://github.com/w3c/webcomponents/issues/137",
    "25007": "https://github.com/w3c/webcomponents/issues/212",
    "22836": "https://github.com/w3c/webcomponents/issues/231",
    "28086": "https://github.com/w3c/webcomponents/issues/145",
    "15501": "https://github.com/w3c/webcomponents/issues/253",
    "26852": "https://github.com/w3c/webcomponents/issues/167"
}

**Comment by Sebine35** [comment]
Legal search network websites information private video foto sexsual social media network my Sebine Murselova all information internet services network websites Legally.
Privacy and Terms other network websites Legal.
All network-not block not script not null not exchange not integrated.
All network websites search information Legal,Origin,Release
