### ISSUE TITLE
importNode and adoptNode should throw with passed a ShadowRoot

### ISSUE THREAD

**Issue by inscriber** [WICG/webcomponents#125]
Given that cloneNode throws with a shadow root, importNode should also throw because one of the steps in the import algorithm it to clone the node. Also, adoptNode should also throw because the host and shadow root shouldn't have different node documents.

**Comment by samgiles** [comment]
Does this necessitate a change in the DOM L4 spec? https://dom.spec.whatwg.org/#dom-document-importnodenode-deep to something along these lines (also adding the caveat for `adoptNode`):

> The _importNode(node, deep)_ method must run these steps:
> - If _node_ is a `document` **or `ShadowRoot`**, throw a `NotSupportedError` exception.
> - Return a clone of `node`, with context object and the `clone children flag` set if deep is true.

**Comment by domenic** [comment]
In general basically all of the shadow DOM spec is a giant patch on the DOM spec, so that wouldn't be surprising. I would expect eventual integration once we get something shipping in multiple browsers...

**Comment by hayatoito** [comment]
Yeah, upstreaming Shadow DOM spec to DOM spec has been a long term goal for years.

For a small change like this, I think it's okay to update DOM spec directly rather than Shadow DOM spec.

**Comment by hayatoito** [comment]
BTW, we can use `LayoutRoot` here, rather than `document or ShadowRoot`.
See https://www.w3.org/Bugs/Public/show_bug.cgi?id=28748
Though `LayoutRoot` is still in the air. No one has started to work on this, I guess.

**Comment by annevk** [comment]
@samgiles would you be willing to submit a PR to https://github.com/whatwg/dom?

**Comment by hayatoito** [comment]
Thanks. Let me close this issue.
