### ISSUE TITLE
[Meta]: Specify how custom elements work (bugzilla: 14968)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#132]
Title: [Meta]: Specify how custom elements work (bugzilla: 14968)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=14968

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=14968#c0
_Dimitri Glazkov_ wrote on 2011-11-28 22:40:32 +0000.

This is an umbrella bug to track all spec work related to custom elements.

**Comment by rniwa** [comment]
Do we really need this meta bug?

**Comment by annevk** [comment]
Nah, this is just the collection of v1 issues.
