### ISSUE TITLE
[Shadow] Replace node distribution mechanism by the named slot proposal (bugzilla: 28542)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#138]
Title: [Shadow] Replace node distribution mechanism by the named slot proposal (bugzilla: 28542)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28542

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28542#c0
_Ryosuke Niwa_ wrote on 2015-04-22 23:28:26 +0000.

Proposed here: https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0184.html

https://github.com/w3c/webcomponents/wiki/Proposal-for-changes-to-manage-Shadow-DOM-content-distribution

**Comment by othermaciej** [comment]
More detailed proposal here: https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Slots-Proposal.md

**Comment by hayatoito** [comment]
I think we can merge this issue with #128.
