### ISSUE TITLE
Custom elements should use ES6 class constructor (bugzilla: 28541)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#139]
Title: Custom elements should use ES6 class constructor (bugzilla: 28541)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28541

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28541#c0
_Ryosuke Niwa_ wrote on 2015-04-22 23:25:19 +0000.

As discussed, docuemnt.regsiterElement currently replaces the constructor so that it rips out any static methods defined using the ES6 class syntax.  We shouldn't do that.

We should preserve the original constructor/class object defiend by the author.

**Comment by rniwa** [comment]
Per Jan F2F, this will be done in the issues #366 and #403.
