### ISSUE TITLE
[Custom]: inflexible extends as fixed element type (bugzilla: 28158)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#143]
Title: [Custom]: inflexible extends as fixed element type (bugzilla: 28158)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28158

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28158#c0
_Dimitri Glazkov_ wrote on 2015-03-07 00:10:02 +0000.

From: https://github.com/w3c/webcomponents/issues/33

rjharmon commented on Jan 25

I'd like to be able to specify any type (or perhaps certain types) of tags, with is= to augment functionality of any element. The initialization sequence I'm imagining is passed the native element instance, and then the component would be able to add its own capabilities to that instance's prototype chain (could also choose to prepare the prototype chain so that element.prototype is already distinguished from that element's native prototype, as a helpful refinement to developers).

A similar technique could be used to add multiple mixins to a tag, assuming they'd been designed them to be complementary/concerned with orthogonal aspects of the markup/content. I think of that as with= rather than is=.

**Comment by annevk** [comment]
It's not entirely clear to me what this means.

**Comment by domenic** [comment]
I think this is solved by using a factory that returns custom element classes/registering them. You could easily write the function

``` js
function makeSuperElement(BaseClass, baseTagName) {
  class SuperElement extends BaseClass { ... };
  document.registerElement(SuperElement, { extends: baseTagName });
  return SuperElement;
});
```

and then call it many times.
