### ISSUE TITLE
[Custom]: Clarify in informative note that cloning/importing also enqueues created callback (bugzilla: 28092)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#144]
Title: [Custom]: Clarify in informative note that cloning/importing also enqueues created callback (bugzilla: 28092)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28092

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28092#c0
_Dimitri Glazkov_ wrote on 2015-02-24 15:50:47 +0000.

"a conforming UA must run enqueue created callback whenever creating a custom element."

The section title and informative note only talk about parser-driven element creation, but it doesn't mention cloning/importing that is also affected by the normative statement.

**Comment by rniwa** [comment]
Per Jan F2F, this should happen for all other DOM APIs.

@annevk : perhaps DOM or WebIDL specs need to provide some hooks for custom elements to use here?

**Comment by annevk** [comment]
Yeah, we should add syntax to IDL that allows us to run callbacks when IDL wants to return a specification-defined value to JavaScript. @heycam would it be best to file an issue or a bug against IDL for that?

**Comment by domenic** [comment]
I think since this spec is just a giant monkeypatch anyway we should define the IDL syntax here (and any monkeypatches to use it, unless we want to move those sooner rather than later). We can move it into IDL as part of the larger merge effort.

**Comment by heycam** [comment]
I think long term I would rather all places (like DOM, HTML, etc.) that create and return elements to explicitly enqueue the callback. Having a hook in IDL that can be invoked for every IDL-to-JS conversion feels like opening a big hole that we don't really need.

I'm fine with @domenic's suggestion to define something in Custom Elements for now.

**Comment by domenic** [comment]
Can you explain? The plan of record was to use `[CallsCustomElementCallbacks]` or something on attributes and methods, instead of inserting a prose step at the bottom of all getter/setter/method definitions. IDL seems perfect for automating these kind of prose-gen things; it's certainly how implementations will be doing this.

**Comment by heycam** [comment]
Sorry, I misread Anne's comment and skipped over the "add syntax" bit and thought the suggestion was to have a prose hook.  Defining an extended attribute in Custom Elements to monkeypatch the IDL-to-JS conversion sounds OK.
