### ISSUE TITLE
[Imports]: Write HTML Imports spec (bugzilla: 20683)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#149]
Title: [Imports]: Write HTML Imports spec (bugzilla: 20683)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=20683

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=20683#c0
_Dimitri Glazkov_ wrote on 2013-01-16 18:36:36 +0000.

This is the umbrella bug that is tracking development of the specification to enable loading resources such as scripts, stylesheets, and web components from separate document files and combining them in one main document.

**Comment by TakayoshiKochi** [comment]
The original bug is an umbrella bug, and here we will use "html-imports" tag (and possibly in combination with "v1" etc.)

Closing this.
