### ISSUE TITLE
[Custom]: No way to unregister a component (bugzilla: 27975)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#152]
Title: [Custom]: No way to unregister a component (bugzilla: 27975)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27975

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27975#c0
_Randy Harmon_ wrote on 2015-02-07 18:40:51 +0000.

When writing unit tests, I'd like to be able to unregister a component, so that I can test various scenarios of the registration process.  The spec doesn't deal at all with removal of custom elements.

I'm writing code that actually performs element registration depending on backbone configurations, if that helps with context.

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27975#c1
_Dimitri Glazkov_ wrote on 2015-02-07 18:54:44 +0000.

I think the solution is in being able to create/discard registries. See bug 24578.

---

comment: 2
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27975#c2
_Olli Pettay_ wrote on 2015-02-07 19:01:04 +0000.

Would using separate iframes be enough for testing?

---

comment: 3
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27975#c3
_Elliott Sprehn_ wrote on 2015-02-08 02:00:15 +0000.

(In reply to Olli Pettay from comment #2)

> Would using separate iframes be enough for testing?

Yes, existing test frameworks use iframes.

---

comment: 4
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27975#c4
_Dimitri Glazkov_ wrote on 2015-02-08 02:03:25 +0000.

https://github.com/Polymer/web-component-tester

**Comment by domenic** [comment]
I'll close this as the real solution is https://github.com/w3c/webcomponents/issues/154 but in the meantime iframes suffice.
