### ISSUE TITLE
[Custom]: define registry primitive; ("namespace" support needed?) (bugzilla: 24578)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#154]
Title: [Custom]: define registry primitive; ("namespace" support needed?) (bugzilla: 24578)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24578

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24578#c0
_Anne_ wrote on 2014-02-07 10:47:10 +0000.

See bug 20567 comment 69. Exposing the registry would make it easier for components to be supported across documents and globals.

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24578#c1
_Arthur Barstow_ wrote on 2015-02-06 11:51:29 +0000.

See also:
- The February 2015 "Are web components _seriously_ not namespaced?" thread <https://lists.w3.org/Archives/Public/public-webapps/2015JanMar/0454.html\>

and: 
- Dimitri's comment on that thread to see this bug <https://lists.w3.org/Archives/Public/public-webapps/2015JanMar/0454.html\>

**Comment by annevk** [comment]
I don't think we have an idea how registries are going to help with namespacing and this issue is not really actionable as is, so closing.

**Comment by kevinSuttle** [comment]
Why not allow XML namespaces in the names themselves? 

`<foo:Button>` 

This is much more preferable for styling themes and avoiding that required dash character.

**Comment by kevinSuttle** [comment]
Example from [Adobe's FXG drawing library](http://help.adobe.com/en_US/flex/using/WSda78ed3a750d6b8f26c150d412357de3591-8000.html):

``` xml
<Graphic xmlns="http://ns.adobe.com/fxg/2008" version="2">    
     <Rect id="rect1" width="200" height="200">
          <fill>
             <SolidColor color="#FFFFCC"/>
          </fill>
          <stroke>
             <SolidColorStroke color="#660099" weight="2"/>
          </stroke>
     </Rect>
</Graphic>
```
