### ISSUE TITLE
[Custom]: Typo instantation ---> instantiation (bugzilla: 27914)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#155]
Title: [Custom]: Typo instantation ---> instantiation (bugzilla: 27914)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27914

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27914#c0
_Jeff Robbins_ wrote on 2015-01-28 01:49:38 +0000.

"instantation" looks like a typo -- "instantiation" likely intended.

**Comment by domenic** [comment]
No longer appears in the current spec.
