### ISSUE TITLE
registerElement() should be scoped to modules (bugzilla: 27835)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#156]
Title: registerElement() should be scoped to modules (bugzilla: 27835)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27835

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27835#c0
_Ian 'Hixie' Hickson_ wrote on 2015-01-14 23:31:00 +0000.

I'm not sure exactly how this should look, but we need to scope custom element registrations. Otherwise, importing two unrelated libraries will lead to their internals stomping on each other if they happen to register elements internally that use the same name, e.g. 'output' or something generic like that.

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27835#c1
_Boris Zbarsky_ wrote on 2015-01-15 01:06:05 +0000.

The hard part here is the interaction with parsing....

**Comment by annevk** [comment]
This is basically #154 and why we require a hyphen.
