### ISSUE TITLE
[Custom]: ES6 section needs to be updated (bugzilla: 27769)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#164]
Title: [Custom]: ES6 section needs to be updated (bugzilla: 27769)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27769

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27769#c0
_Dimitri Glazkov_ wrote on 2015-01-06 17:13:39 +0000.

The @@create-(this-is-inserted-to-avoid-notification-in-migration) seems to be gone from the ES6 spec. Need to figure out how this will work.

**Comment by rniwa** [comment]
We'll do this in the issue #403.
