### ISSUE TITLE
[Custom]: Integrate with the HTML Parser

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#165]
Title: [Custom]: Make "Parsing Custom Elements" section more explicit (bugzilla: 27768)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27768

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27768#c0
_Anne_ wrote on 2015-01-06 16:13:07 +0000.

This section does not define how these elements are instantiated.

I would assume these to be added to the unresolved set of elements, no?

**Comment by rniwa** [comment]
Per Jan F2F, parser constructs HTML elements synchronously. We need to rewrite this whole section.
