### ISSUE TITLE
[Custom]: Tone of note doesn't reflect severity (bugzilla: 27538)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#171]
Title: [Custom]: Tone of note doesn't reflect severity (bugzilla: 27538)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27538

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27538#c0
_Michiel Bijl_ wrote on 2014-12-08 17:45:15 +0000.

"The addition of in line event handlers are for demonstration purposes only. The event handlers could be added by the lifecycle callbacks imperatively, or maybe even not used at all."

As a lot of developers forget correct event handlers; I feel as if this note doesn't reflect the severity of the need for these event handlers.

I suggest something like:

"Developers **should** make sure event handlers are added for both keyboard and mouse users. The inline event handlers shown in this example are for demonstration purposes."

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27538#c1
_steve faulkner_ wrote on 2014-12-14 20:36:01 +0000.

(In reply to Michiel Bijl from comment #0)

> "The addition of in line event handlers are for demonstration purposes only.
> The event handlers could be added by the lifecycle callbacks imperatively,
> or maybe even not used at all."
> 
> As a lot of developers forget correct event handlers; I feel as if this note
> doesn't reflect the severity of the need for these event handlers.
> 
> I suggest something like:
> 
> "Developers **should** make sure event handlers are added for both keyboard
> and mouse users. The inline event handlers shown in this example are for
> demonstration purposes."

I have edited the note:

"The addition of in line event handlers are for demonstration purposes only. The event handlers could be added by the lifecycle callbacks imperatively, or maybe even not used at all. This example demonstrates one method for developers to ensure that a custom control is operable for keyboard users and meets the WCAG 2.0 criteria "All functionality of the content is operable through a keyboard interface"."

**Comment by domenic** [comment]
This looks to be resolved.
