### ISSUE TITLE
[Custom]: Be clear about whether attached callback should be enqueued when setting prototype (bugzilla: 27437)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#175]
Title: [Custom]: Be clear about whether attached callback should be enqueued when setting prototype (bugzilla: 27437)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27437

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27437#c0
_William Chen_ wrote on 2014-11-26 02:11:26 +0000.

http://w3c.github.io/webcomponents/spec/custom/#dfn-created-callback:

"The custom element prototype must be set just prior to invoking callback."

"If the created callback exists for an element, all other callbacks must not be enqueued until after this created callback's invocation had started."

In the steps to set the custom element prototype we have:

http://w3c.github.io/webcomponents/spec/custom/#dfn-set-prototype

3.1. "Enqueue attached callback for ELEMENT"

There is instruction to enqueue an attached callback and instruction to not enqueue the attached callback because it happens before invoking the created callback.

**Comment by domenic** [comment]
This should be sufficiently clear with the latest changes to the construction model.
