### ISSUE TITLE
Define how shadow DOM should be handled when host is adopted to a new document

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#182]
Title: Define how shadow DOM should be handled when host is adopted to a new document (bugzilla: 27366)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27366

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27366#c0
_Olli Pettay_ wrote on 2014-11-19 12:15:46 +0000.

The spec doesn't say what should happen to shadow DOM
if host is adopted to a new document.

The spec does have "The ownerDocument property of a node in a shadow tree must refers to the document of the shadow host which hosts the shadow tree."
but that misses 'adopting steps' from DOM spec which HTML relies on.

**Comment by hayatoito** [comment]
@annevk , I think this issue now should be addressed by DOM Standard directly.

**Comment by annevk** [comment]
@hayatoito does it match your understand that in https://dom.spec.whatwg.org/#concept-node-adopt I would change "inclusive descendant" to https://dom.spec.whatwg.org/#concept-shadow-root-including-inclusive-descendant. That way all the associated shadow trees would be adopted too. I'm assuming that's what's implemented.

**Comment by hayatoito** [comment]
Perfect. That would match my understanding and the implementation. Thank you.
