### ISSUE TITLE
[Shadow]: Define the impact of ordering on relevant HTML elements (bugzilla: 25563)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#183]
Title: [Shadow]: Define the impact of ordering on relevant HTML elements (bugzilla: 25563)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25563

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25563#c0
_Dimitri Glazkov_ wrote on 2014-05-05 22:00:40 +0000.

Splitting off from bug 25562: 

"We should further say that <script> elements execute. For inline scripts we need to define with order those script execute relative to <script> elements that are in the real document. I.e. if a out-of-document node is given <script> children as well as a Shadow DOM with <script> nodes, then which order do they execute in once the node is inserted into the document?"

See http://jsbin.com/jigoc/1/edit for an example. I intuitively would've have expected the scripts in shadow trees to execute first, but I don't care what we spec, as long as it is specified.

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25563#c1
_Jonas Sicking_ wrote on 2014-05-05 22:06:13 +0000.

I agree. I don't see any strong reasons for either order.

---

comment: 2
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25563#c2
_William Chen_ wrote on 2014-05-13 21:24:18 +0000.

In the current spec <script> would execute when they are inserted into the shadow tree even for host nodes that are out-of-document because it's caught by "All other HTML elements in the shadow trees must behave as if they were part of the document tree." in the Shadow DOM spec. But as Jonas's comment in bug 25562 points out, that wording should be removed, and however we decide to spec the behavior of <script> we should make sure that <script> is only executed when the host is in document.

**Comment by annevk** [comment]
This is a duplicate of https://github.com/whatwg/html/issues/762, right?

**Comment by hayatoito** [comment]
Yeah, closing.
