### ISSUE TITLE
[imports]: Unify loading and dependency resolution model with ES6 modules (bugzilla: 25715)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#188]
Title: [imports]: Unify loading and dependency resolution model with ES6 modules (bugzilla: 25715)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25715

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25715#c0
_Dimitri Glazkov_ wrote on 2014-05-14 18:00:41 +0000.

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25715#c1
_Dimitri Glazkov_ wrote on 2014-05-14 19:06:14 +0000.

Will start digging into https://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-loader-state.

It's nice and dense. Any help/guidance would be appreciated :)

---

comment: 2
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25715#c2
_Ian 'Hixie' Hickson_ wrote on 2014-05-22 22:22:19 +0000.

We should deal with this sooner rather than later because I'm about to add my own dependency system to HTML for <script needs> and so on. I _really_ don't want us to end up with three separate systems...

---

comment: 3
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25715#c3
_Ian 'Hixie' Hickson_ wrote on 2014-05-22 22:57:38 +0000.

I think what might make the most sense is for HTML to define the dependency fetching system, including things like delaying loads until something needs the dependency, precaching, deferring, etc, whether loads should block other scripts from executing, whether to early-execute or late-execute when there's a dependency chain, etc, and for the JS module system to just have hooks that HTML bootstraps into this system. (We're going to need to have hooks anyway for actually fetching things over HTTP.)

In the case of modules in particular, having all this would allow us to hook modules into the dependency tree before actually fetching any files, so that they could be lazily loaded without requiring multiple round-trips to fetch all the dependencies once they _are_ needed.

---

comment: 4
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25715#c4
_Ian 'Hixie' Hickson_ wrote on 2014-09-12 17:37:36 +0000.

Reassigning to dglazkov since he's organising a summit or something for this.

**Comment by TakayoshiKochi** [comment]
This is a good input for https://github.com/w3c/webcomponents/issues/645.
