### ISSUE TITLE
Custom elements spec lists the wrong lifecycle callbacks

### ISSUE THREAD

**Issue by robdodson** [WICG/webcomponents#19]
My understanding is the callbacks for Custom Elements are:

`createdCallback`
`attachedCallback`
`detachedCallback`
`attributeChangedCallback`

but the spec lists them as:

`created`
`attached`
`detached`
`attributeChanged`

**Comment by hayatoito** [comment]
Fixed in
https://github.com/w3c/webcomponents/commit/1344830399b58dffaece940fbcf412723763c7b8

I've also filed this in W3C bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26514

**Comment by dominiccooney** [comment]
FWIW I'm not sure this was a bug... The spec gave one logical name to the callbacks (created, attached, etc.) and another specific property name when it is retrieving them (createdCallback, attachedCallback, etc.)

Having the labels be exactly the same seems OK too.

**Comment by hayatoito** [comment]
Thank you. Now I understand the situation. The names of {created, attached, ..} are just logical names for the purpose of explanations in the spec. These don't mean the actual property name on propotype.

Yeah, having the labels be exactly the same might be better to avoid confusion.
That might prevent someone from filing a similar bug in the future.

For consistency in the spec, the spec might need to be updated further. Let me handle that.
