### ISSUE TITLE
[Custom] Should attachedCallback/detachedCallback callbacks be called when element is added to / removed from shadom dom which is attached to a in-document host? (bugzilla: 26943)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#191]
Title: [Custom] Should attachedCallback/detachedCallback callbacks be called when element is added to / removed from shadom dom which is attached to a in-document host? (bugzilla: 26943)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26943

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26943#c0
_Olli Pettay_ wrote on 2014-10-01 09:43:50 +0000.

Per the current spec attachedCallback/detachedCallback explicitly aren't
called if the element isn't inserted into / removed from a document.
I think we want the callbacks to be called also in shadow DOM case.

**Comment by rniwa** [comment]
Also see the issue #362.

**Comment by domenic** [comment]
I specced this per #362:

> If inclusiveDescendant is a custom element, and was previously in a composed document, but now is not, enqueue a custom element callback action with inclusiveDescendant, callback name "disconnectedCallback", and an arguments list containing the document which is parent's inclusive composed ancestor.

(and similarly for connectedCallback).

Please re-open or open a new issue/pull request if I got that wrong.

**Comment by annevk** [comment]
What about newAncestor/oldAncestor?

**Comment by domenic** [comment]
What about it? What is it?

**Comment by annevk** [comment]
It's the argument passed to "insertion steps" / "removing steps".

**Comment by domenic** [comment]
Why is that relevant here?

**Comment by annevk** [comment]
Because why should that primitive not be exposed to connected/disconnected?

**Comment by domenic** [comment]
Because connected/disconnected are different from inserted/removed, and we never discussed this previously, so you're proposing an entirely new feature?

**Comment by annevk** [comment]
The only difference is that connected/disconnected require the element's shadow-host-including root to be a document, right? How does that change what context you might need?

I guess I'm fine not exposing this for now, we can add it when there's a need.

**Comment by domenic** [comment]
Sounds good. Feel free to open a new issue proposing it for wider discussion.
