### ISSUE TITLE
Figure out how form owner should work in shadow DOM

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#196]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26643#c7

**Comment by annevk** [comment]
I'm guessing we want `<form>` to work inside a shadow tree, but we simply don't want to cross boundaries, correct? That should be a relatively straightforward change to HTML.

**Comment by rniwa** [comment]
Yeah, that makes sense to me.

**Comment by hayatoito** [comment]
Yeah, exactly.
