### ISSUE TITLE
[imports]: The relationship between import and browsing context should be stated more clearly (bugzilla: 26682)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#197]
Title: [imports]: The relationship between import and browsing context should be stated more clearly (bugzilla: 26682)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26682

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26682#c0
_Morrita Hajime_ wrote on 2014-08-27 18:17:16 +0000.

Raised by http://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0312.html

From "3 Terminology":

> In the import referrer, an import is represented as a Document, called the 
> imported document. The imported documents don't have browsing context.

It's not clear what this implies. 
We once attempted to rationalize how imports (should) work by giving
a "shared" browsing context / view to each import. It however didn't work out.

I'm currently inclined to explain it as a extension of module system. Such an 
idea is covered by https://www.w3.org/Bugs/Public/show_bug.cgi?id=25715.

**Comment by TakayoshiKochi** [comment]
We don't spend more time on the HTML Imports spec.

**Comment by clarkjoseph00** [comment]
😂
