### ISSUE TITLE
[imports]: Script execution order should be stated more clearly (bugzilla: 26681)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#198]
Title: [imports]: Script execution order should be stated more clearly (bugzilla: 26681)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26681

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26681#c0
_Morrita Hajime_ wrote on 2014-08-27 17:58:06 +0000.

Suggested at: 
http://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0312.html

> - it's extremly hard to see that script execution order is really defined, even when I know how it is defined... figuring it out from the current spec without any prior knowledge is... challanging to say the least. I think a detailed walk through on the graph would be a HUGE help. By that I mean explicitly defining the execution order for the example, and also maybe illustrating at some stages, what is blocking what.

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26681#c1
_Morrita Hajime_ wrote on 2014-08-27 17:59:04 +0000.

Should've been formatted better :-(

> - it's extremly hard to see that script execution order is really defined,
>   even when I know how it is defined... figuring it out from the current spec
>   without any prior knowledge is... challanging to say the least. I think a
>   detailed walk through on the graph would be a HUGE help. By that I mean
>   explicitly defining the execution order for the example, and also maybe
>   illustrating at some stages, what is blocking what.

**Comment by TakayoshiKochi** [comment]
We won't spend time on improving the HTML Imports spec any longer.
