### ISSUE TITLE
[Custom]: sorted element queue definition is not in sync with Imports (bugzilla: 26638)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#200]
Title: [Custom]: sorted element queue definition is not in sync with Imports (bugzilla: 26638)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26638

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26638#c0
_Gabor Krizsanits_ wrote on 2014-08-22 14:03:57 +0000.

"The import tree order of a given custom element of an import tree is determined by tree order in an import tree that was flattened by replacing every import link with the content of its imported document."

I think this is outdated. There is no such thing as import tree (circles, multiple parents)

**Comment by domenic** [comment]
Moving to HTML imports since per https://github.com/w3c/webcomponents/commit/6953f9f5a36d3221407b4c6735e6ff927f8cb45f now all this text is in HTML imports.

**Comment by TakayoshiKochi** [comment]
Closing this - we won't spend more time on the HTML Imports spec.
