### ISSUE TITLE
[Custom]: Add informative text about importNode (bugzilla: 26576)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#202]
Title: [Custom]: Add informative text about importNode (bugzilla: 26576)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26576

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26576#c0
_Dimitri Glazkov_ wrote on 2014-08-14 00:46:32 +0000.

Need a bit of explanation of how template document and main document interact, and how the right way to "light up" a template is by using importNode.

**Comment by domenic** [comment]
I am not sure how this bug is related to custom elements. I think the HTML Standard explains template pretty well. I will close but if @dglazkov disagrees happy to reopen.
