### ISSUE TITLE
[imports]: Typo: "overnride" (bugzilla: 26233)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#205]
Title: [imports]: Typo: "overnride" (bugzilla: 26233)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26233

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26233#c0
_Erik Charlebois_ wrote on 2014-06-30 03:08:14 +0000.

**Comment by TakayoshiKochi** [comment]
This typo seems already fixed in the past?
I don't see "overnride".
