### ISSUE TITLE
[Custom]: Need adopted callback (bugzilla: 24577)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#210]
Title: [Custom]: Need adopted callback (bugzilla: 24577)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24577

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24577#c0
_Anne_ wrote on 2014-02-07 10:45:19 +0000.

See bug 20567 comment 69. We should have a callback for adoption so you can deal with moving to a new document and prevent leaking an entire global. The callback should take the old and new document as arguments.

See bug 24570 for the equivalent bug on cloning.

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24577#c1
_Anne_ wrote on 2014-02-10 10:54:39 +0000.

New document is not needed as argument since you can get the node's ownerDocument (its node document).

---

comment: 2
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24577#c2
_Anne_ wrote on 2014-02-10 11:13:20 +0000.

If you cannot model this after http://dom.spec.whatwg.org/#concept-node-adopt-ext please tell me.

---

comment: 3
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24577#c3
_Anne_ wrote on 2014-02-10 11:13:46 +0000.

Obviously that callback in the DOM will need to be made asynchronous. Will do that once there's a proper hook in IDL or some such.

**Comment by rniwa** [comment]
@annevk : Do you think we need this in v1?

**Comment by rniwa** [comment]
Also, should we close this issue in favor of the issue #176?

**Comment by annevk** [comment]
This is a distinct issue. Adoption is different from cloning. No rush though I think. There's still controvery around exactly what we should do for adoption and whether or not leaking globals is acceptable.

**Comment by annevk** [comment]
This got fixed by #512.
