### ISSUE TITLE
[imports]: <link media> (bugzilla: 25696)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#213]
Title: [imports]: <link media> (bugzilla: 25696)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25696

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25696#c0
_Ian 'Hixie' Hickson_ wrote on 2014-05-13 21:51:23 +0000.

"The import is fetched and applied regardless of the media attribute of the link matches the environment or not"

Why are we not just reusing the normal <link> logic here?

**Comment by TakayoshiKochi** [comment]
Let me close this issue as we do not spend time on HTML Imports moving forward.
