### ISSUE TITLE
[imports]: Want an informative section about implications of how CSP + Imports is defined (bugzilla: 25610)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#215]
Title: [imports]: Want an informative section about implications of how CSP + Imports is defined (bugzilla: 25610)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25610

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25610#c0
_Morrita Hajime_ wrote on 2014-05-08 17:26:00 +0000.

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=25610#c1
_Dimitri Glazkov_ wrote on 2014-05-08 17:27:20 +0000.

https://github.com/Polymer/vulcanize#content-security-policy seems relevant.

**Comment by TakayoshiKochi** [comment]
Let me close this issue as we do not spend time on HTML Imports moving forward.
