### ISSUE TITLE
[imports]: Things to Consider in the Future (bugzilla: 23278)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#220]
Title: [imports]: Things to Consider in the Future (bugzilla: 23278)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=23278

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=23278#c0
_Dimitri Glazkov_ wrote on 2013-09-18 19:49:02 +0000.

Umbrella bug for various features that aren't going to make it into the latest iteration of the spec.

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=23278#c1
_Morrita Hajime_ wrote on 2014-02-06 00:40:26 +0000.

CC-ed gkrizsanits@ just FYI.

**Comment by TakayoshiKochi** [comment]
The original bug is an umbrella bug, and here we will use "html-imports" tag (and possibly in combination with "v1" etc.)

Closing this.
