### ISSUE TITLE
Custom elements need da (microtask) hookup (bugzilla: 22409)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#225]
Title: Custom elements need da (microtask) hookup (bugzilla: 22409)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=22409

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=22409#c0
_Dimitri Glazkov_ wrote on 2013-06-19 22:52:47 +0000.

The custom elements spec https://dvcs.w3.org/hg/webcomponents/raw-file/tip/spec/custom/index.html
needs a hook from HTML spec at the microtask checkpoint to:
1) invoke lifecycle callbacks
2) process declarations.
This could be just one hook, I'll manage how these two get invoked from it.

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=22409#c1
*\* wrote on 2013-11-11 22:10:22 +0000.

Checked in as WHATWG revision r8265.
Check-in comment: Provide integration hook for Custom Elements spec.
http://html5.org/tools/web-apps-tracker?from=8264&to=8265

---

comment: 2
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=22409#c2
_Ian 'Hixie' Hickson_ wrote on 2014-02-25 18:53:37 +0000.

The hook changed. Sending back for the other side to get updated. See bug 22296.

**Comment by annevk** [comment]
This is #186. Microtasks won't be used for custom elements.
