### ISSUE TITLE
[Custom]: Consider turning processing stack + queues into its own primitive (bugzilla: 24655)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#226]
Title: [Custom]: Consider turning processing stack + queues into its own primitive (bugzilla: 24655)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24655

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24655#c0
_Dimitri Glazkov_ wrote on 2014-02-13 17:49:52 +0000.

A sort of write barrier UAs can arbitrarily erect to protect integrity of their DOM operations. Maybe even something that authors can use eventually?

**Comment by annevk** [comment]
Let's consider this once there's several implementations and use cases pop up. We've only recently started debating a microtask API, seen no need for this so far.
