### ISSUE TITLE
[Explainer]: attachedCallback / detachedCallback are now enteredView and leftView? (bugzilla: 24629)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#227]
Title: [Explainer]: attachedCallback / detachedCallback are now enteredView and leftView? (bugzilla: 24629)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24629

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24629#c0
_Martin Naumann_ wrote on 2014-02-12 06:43:01 +0000.

In the lifecycle explanation it says "attachedCallback, which is called after a custom element is inserted into a document with a default view; detachedCallback" but according to the latest custom element spec those have been renamed into "enteredView" and "leftView", see http://w3c.github.io/webcomponents/spec/custom/index.html#types-of-callbacks for details.

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24629#c1
_Daniel Freedman_ wrote on 2014-02-12 18:54:14 +0000.

The spec has not been updated with the outcome of https://www.w3.org/Bugs/Public/show_bug.cgi?id=24314, the bug that changed the names from enteredViewCallback and leftViewCallback to attachedCallback and detachedCallback.

**Comment by domenic** [comment]
Explainer is gone.
