### ISSUE TITLE
bug-assist should use data-* attributes instead of <meta name> (bugzilla: 21916)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#229]
Title: bug-assist should use data-\* attributes instead of <meta name> (bugzilla: 21916)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=21916

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=21916#c0
_Simon Pieters_ wrote on 2013-05-02 22:45:49 +0000.

<meta name=bug.foo> is not valid HTML without registring bug.foo. Since these fields are only intended to be read by the script, it seems more appropriate to use data-\* attributes (e.g. on the root element or the script element).

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=21916#c1
_Robin Berjon_ wrote on 2013-06-05 22:31:43 +0000.

We have that: http://www.w3.org/TR/html51/bug-assist.js

---

comment: 2
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=21916#c2
_Dominic Cooney_ wrote on 2013-06-06 06:06:21 +0000.

I have updated the Explainer in <https://dvcs.w3.org/hg/webcomponents/rev/3f951ae02c0a\>

---

comment: 3
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=21916#c3
_Philip Jägenstedt_ wrote on 2014-01-26 17:28:52 +0000.

What's the canonical source for bug-assist.js? I want to get rid of the <meta> stuff in WebVTT, and http://w3c.github.io/webcomponents/explainer/bug-assist.js is what I can find.

---

comment: 4
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=21916#c4
_Dimitri Glazkov_ wrote on 2014-01-27 05:14:14 +0000.

(In reply to Philip Jägenstedt from comment #3)

> What's the canonical source for bug-assist.js? I want to get rid of the
> <meta> stuff in WebVTT, and
> http://w3c.github.io/webcomponents/explainer/bug-assist.js is what I can
> find.

https://github.com/w3c/webcomponents/blob/gh-pages/assets/scripts/spec-assist.js

:)

---

comment: 5
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=21916#c5
_Philip Jägenstedt_ wrote on 2014-01-27 07:18:30 +0000.

(In reply to Dimitri Glazkov from comment #4)

> (In reply to Philip Jägenstedt from comment #3)
> 
> > What's the canonical source for bug-assist.js? I want to get rid of the
> > <meta> stuff in WebVTT, and
> > http://w3c.github.io/webcomponents/explainer/bug-assist.js is what I can
> > find.
> 
> https://github.com/w3c/webcomponents/blob/gh-pages/assets/scripts/spec-
> assist.js
> 
> :)

That's spec-assist.js, but the bug-assist.js in the same place still relies on <meta>, so I guess the canonical source is not what I'm looking for :/

---

comment: 6
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=21916#c6
_Robin Berjon_ wrote on 2014-01-27 08:49:32 +0000.

(In reply to Philip Jägenstedt from comment #5)

> (In reply to Dimitri Glazkov from comment #4)
> 
> > (In reply to Philip Jägenstedt from comment #3)
> > 
> > > What's the canonical source for bug-assist.js? I want to get rid of the
> > > <meta> stuff in WebVTT, and
> > > http://w3c.github.io/webcomponents/explainer/bug-assist.js is what I can
> > > find.
> > 
> > https://github.com/w3c/webcomponents/blob/gh-pages/assets/scripts/spec-
> > assist.js
> > 
> > :)
> 
> That's spec-assist.js, but the bug-assist.js in the same place still relies
> on <meta>, so I guess the canonical source is not what I'm looking for :/

The one in:

```
https://github.com/w3c/html/tree/master/js
```

uses data-*. You can steal it from there. There is currently no canonical version that I know of, people just copy it. I plan to incorporate the functionality into:

```
https://github.com/darobin/specstatic
```

but at this point that's on standby until I have a day or two's time to hack.

---

comment: 7
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=21916#c7
_Philip Jägenstedt_ wrote on 2014-01-27 08:57:30 +0000.

OK, thanks Robin!

**Comment by sideshowbarker** [comment]
The experiment of having the HTML spec try to limit the valid values of `meta[name]` has turned out to be a (big) failure in practice. So while I have no opinion otherwise on the absolute merits of using `data-*` vs `meta[name]` in this particular case, when making any decision about it, I recommend everybody just ignore the requirements in the HTML spec on `meta[name]` values needing to be registered. The HTML validator no longer tries to enforce those requirements at least (because a few months ago I removed the code that was checking it).

**Comment by hayatoito** [comment]
Let me close this issue since we no longer use bug-assist.
