### ISSUE TITLE
Changing "href" attribute on <link> should trigger re-downloading hyperlink (bugzilla: 22038)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#234]
Title: Changing "href" attribute on <link> should trigger re-downloading hyperlink (bugzilla: 22038)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=22038

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=22038#c0
_Morrita Hajime_ wrote on 2013-05-15 02:48:51 +0000.

From this thread: http://lists.w3.org/Archives/Public/public-webapps/2013AprJun/0635.html

Currently it isn't clear what happens if @href-(this-is-inserted-to-avoid-notification-in-migration) is updated on the import <link>
elements. The spec should (probably informally) mentioned that 
it loads new import.

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=22038#c1
_Dimitri Glazkov_ wrote on 2013-07-18 21:18:37 +0000.

This should be addressed in HTML spec

---

comment: 2
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=22038#c2
_Ian 'Hixie' Hickson_ wrote on 2013-10-23 22:07:44 +0000.

Actually this should be addressed in whatever spec defines the rel="" attribute's value, whichever that is. That's not currently HTML.

See here for how it's done for rel=stylesheet:

   http://www.whatwg.org/specs/web-apps/current-work/#link-type-stylesheet

It's not necessarily the case that you want to do it the same way.

**Comment by TakayoshiKochi** [comment]
FYI a Chromium bug was also filed at
https://bugs.chromium.org/p/chromium/issues/detail?id=493832

As HTML Imports spec is no longer actively maintained, closing this.
