### ISSUE TITLE
[Custom]: Consider creating registries for HTML documents created through DOMImplementation in some cases (bugzilla: 23018)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#236]
Title: [Custom]: Consider creating registries for HTML documents created through DOMImplementation in some cases (bugzilla: 23018)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=23018

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=23018#c0
_Dominic Cooney_ wrote on 2013-08-20 01:43:15 +0000.

As written, if you have an document with a registry, then do

doc2 = document.implementation.createDocument(...)

to create a non-HTML, etc. document (ie one that does not get associated with a registry) and then turn around and do

doc3 = document.implementation.createHTMLDocument()

the speced behavior is for doc3 to not have a document/not process Custom Elements.

A possible alternative semantics is for doc3 to get a new, separate registry from the original document. The nice property this gives you is all documents that _could_ process Custom Elements (ie right kind of document) _do_ process Custom Elements, and just which registry they're associated with differs.

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=23018#c1
_Dominic Cooney_ wrote on 2013-08-20 01:53:56 +0000.

Oops, instead of

doc3 = document.implementation.createHTMLDocument()

Of course I meant

doc3 = doc2.implementation.createHTMLDocument()

**Comment by esprehn** [comment]
What's that status of this? It'd be really nice to spec that we create a new registration context for all HTMLDocuments if they're missing one, that fixes this bug and makes it possible to create new registration contexts in frameworks.

**Comment by annevk** [comment]
As long as browsers have different ideas on types of documents (see outstanding DOM Standard bugs) and the standards still say there's no such thing as `HTMLDocument`, is that really a good idea?

**Comment by rniwa** [comment]
It seems like we had a rough consensus to use a single registry per document (including one created by DOMImplementation)?

Regardless, we should resolve this in v1.

**Comment by domenic** [comment]
It seems like this has been duplicated a few times: #369 and #353. #369 contains the F2F resolution.

**Comment by rniwa** [comment]
Let's use the issue #369 to track these issues then.
