### ISSUE TITLE
I accidentally "git push -f" to w3c/webcomponents repository.

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#273]
My fault. Looks I used "git push -f" to this repository accidentally.
My command line history shows "git push -f" as the recent command.
I guess I used "git push -f" to this repository accidentally in the last week.

I'm now investigating which commits were lost, however, I'm afraid that I couldn't recover the commits in this situation.

If you find your commits were lost, I appreciate you could tell us.

See also https://github.com/w3c/webcomponents/pull/127

Let me investigate further.

**Comment by domenic** [comment]
git reflog is always helpful http://effectif.com/git/recovering-lost-git-commits

**Comment by hayatoito** [comment]
Unfortunately, I'm afraid that I didn't "git fetch" in the last week. I don't have the lost commits in the local repository. :(

According to the notification emails,  https://github.com/w3c/webcomponents/pull/127 is the only commit we lost.

I chatted with @TakayoshiKochi and he kindly sent a PR, https://github.com/w3c/webcomponents/pull/272, again. I've merged it.

**Comment by hayatoito** [comment]
I think I can close this bug. Sorry for the confusion. I apologize it.
