### ISSUE TITLE
Expose ShadowRoot object's encapsulation mode

### ISSUE THREAD

**Issue by TakayoshiKochi** [WICG/webcomponents#275]
Whether or not a shadow root is created 'open' or 'closed' cannot be distinguished
because no information is left in shadow root object.

A workaoround might be checking if `shadowRoot.host.shadowRoot === shadowRoot`
where `shadowRoot` is a ShadowRoot object.

Instead, shall we have a read-only `.mode` attribute which reflects the parameter
given at `createShadowRoot()`?

**Comment by annevk** [comment]
On `ShadowRoot`? Makes sense to me. Though we might want to wait adding one until we resolve how `ShadowRoot` is created and attached.

**Comment by TakayoshiKochi** [comment]
Yeah, as this can be easily polyfilled, it can be deferred to v2.

**Comment by annevk** [comment]
Given that we decided on attachment and such, I think we should just add this now. @rniwa @smaug----? Happy to add `ShadowRoot.prototype.mode` to DOM.

**Comment by smaug----** [comment]
(no idea what you mean with "attachment") but sounds ok.

**Comment by annevk** [comment]
Sorry, I meant that we decided on how a `ShadowRoot` is created and attached, i.e., through `attachShadow()`.

**Comment by rniwa** [comment]
`readonly DOMString attribute` on `ShadowRoot.prototype.mode`?

**Comment by smaug----** [comment]
I assume Anne meant just
`readonly attribute DOMString mode;`
in ShadowRoot interface (which then of course in practice means a `mode` getter in the prototype)

**Comment by annevk** [comment]
Right, what @smaug---- said.

**Comment by annevk** [comment]
See https://dom.spec.whatwg.org/#interface-shadowroot for its definition.

**Comment by dylanb** [comment]
I think this is a great enhancement to the spec. It will allow audits to detect when they cannot audit the custom element's shadow DOM.
