### ISSUE TITLE
delegatesFocus

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#276]
It seems to me this proposal is still rather vague as to what the processing model of focus is and how this alters it. E.g. ideally the definition of "autofocus" (and focus in general) is updated such that it is clear how it behaves in the presence of shadow trees.

And since we haven't really defined the focus processing model in lots of detail, it's unclear whether this is the right modification to it.

**Comment by TakayoshiKochi** [comment]
Do you think the currently speced focus navigation (without my delegatesFocus proposal)
still needs to be refined?
https://w3c.github.io/webcomponents/spec/shadow/#focus-navigation
At least it doesn't say anything about "autofocus" attribute.

Or "focus processing model" is different from "focus navigation"?

**Comment by annevk** [comment]
Does anyone even implement the "navigation order" thing? (Which is also not defined it seems, "auto" leaves everything up to the user agent.)

That algorithm has "as if HOST were assigned the value of auto for determining its position" with 'auto' pointing to a property that has been removed.

CSS UI doesn't seem like a good baseline for this. This would need to be defined in terms of https://html.spec.whatwg.org/#focus I think. And likely that model needs to be adjusted to account for the Shadow DOM.

**Comment by hayatoito** [comment]
I think we can merge this issue with https://github.com/w3c/webcomponents/issues/105

**Comment by annevk** [comment]
That issue doesn't really mention any of the concerns I raised, but okay, I hope you stay on top of it then.

**Comment by hayatoito** [comment]
Yeah, sorry for closing this issue earlier. I merged this issue with #105 after I confirmed it with @TakayoshiKochi . @TakayoshiKochi was aware of the raised concerns.

We just thought that it would be better to use one issue to discuss this kind of topic for a while so that everyone don't miss anything.

**Comment by hayatoito** [comment]
I meant to merge this issue with #126, rather than #105.
