### ISSUE TITLE
Shouldn't loadedmetadata also a scoped event?

### ISSUE THREAD

**Issue by kojiishi** [WICG/webcomponents#277]
From PR #274:

> I imagine we wouldn't want "loadedmetadata" to leak out of a shadow tree by default? Or is there a reason for not leaking load and error, but leaking that one?

**Comment by annevk** [comment]
Again, the real question here is whether we don't want to leak events dispatched by media elements. Looking at event names is the wrong way to approach this, since for some other element that dispatches an event of the same name we might very well make a different determination.

**Comment by rniwa** [comment]
Whether media elements are actually implemented using shadow DOM is an implementation detail, and we should spec it so that it won't leak any information out of its shadow DOM.

**Comment by annevk** [comment]
That's a separate question (but agreed). This is about using media elements inside a shadow tree.

**Comment by rniwa** [comment]
Oh, sorry, I misunderstood.  I do think making decisions based on event name/type makes a lot of sense at least for "universal" events like mouseup and mousedown.

On the other hand, it also makes sense to define the scoped-ness at the element level for element specific and other narrowly (semantically) scoped events such as `loadedmetadata`.

**Comment by annevk** [comment]
It's wrong to think of those as universal. They have a dispatcher too, the UI "thread". If some other dispatcher started dispatching events named "mouseup" for some reason we might make a different call there with respect to the scoped flag. (It's unlikely we'd reuse the event name, but who knows what the future brings.)

**Comment by rniwa** [comment]
But you're not certainly proposing to scope `mousemove` event differently based on element names, right?  It doesn't make any sense for events like `mouseup` to be scoped differently just because it's dispatched on a different element

**Comment by annevk** [comment]
The code dispatching that event is not an element. It's the "UI thread".

**Comment by rniwa** [comment]
That's beside the point. Even if "we don't want to leak events dispatched by media elements" as you've stated, we still want `mousemove` dispatched _on_, not _by_, media elements to be "leaked", right?

**Comment by kojiishi** [comment]
Most events behave the same way in terms of being scoped or not. Why don't we set default by event name/type, and differentiate only where to do so is needed? When all elements behave the same way, I do not think it's a good idea to copy the same sentence to every element.

So your question:

> for some other element that dispatches an event of the same name we might very well make a different determination

does not prevent defining the default.

**Comment by annevk** [comment]
Because we never set a default by event name/type. We don't do that for bubbling or canceling either.

**Comment by hayatoito** [comment]
It looks it might be okay to add `loadedmetadata` to here:  http://w3c.github.io/webcomponents/spec/shadow/#scoped-flag, so that we do not forget `loadedmetadata` as one of the events we must take care of in upstreaming.

When we upstream this section into HTML/DOM Standard, we will update each part of specifications where these events are explained.

**Comment by annevk** [comment]
I think before we upstream though we could make that section clearer. Especially as upstreaming will likely take a while. E.g., the "load" event that is dispatched on the global object or on XMLHttpRequest, should that have the scoped flag set? I don't think it should.
