### ISSUE TITLE
Custom element callbacks for builtins

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#291]
I think in general web developers would appreciate having these callbacks available for normal elements too. See e.g., https://www.w3.org/Bugs/Public/show_bug.cgi?id=23250.

However, in that case they'd probably be in addition to what the browser already does internally for the element. That is not different from what `is=""` does though, so the proponents of that should be okay with this too.

**Comment by travisleithead** [comment]
I wonder if we could keep lifecycle callbacks for normal elements, but drop the declarative `is=` syntax? Would this mean that we wouldn't create custom constructors/prototypes as well? Seems like a lot of the auto-hookup feature of custom elements would be lost... but that might be OK?

**Comment by annevk** [comment]
We discussed at the F2F and decided not to do this. Was too complicated.
