### ISSUE TITLE
Introduction section shouldn't refer to a Shadow DOM 101 article

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#301]
We should either remove the section or rewrite it.  It doesn't make much sense for the introduction of a spec to be referring to an article on a third party website.

**Comment by hayatoito** [comment]
Do you think we should not refer to an article on a third party website in any case, even if it's in non-normative section?

I don't have a strong opinion on that. We just thought it would be helpful for readers. AFAIR, we added the link to the article when we decided to discontinue to maintain "Introduction to Web Components" spec [1].

[1] http://www.w3.org/TR/components-intro/

**Comment by rniwa** [comment]
I don't think we should especially because the article is out-of-date.
