### ISSUE TITLE
The order of node trees is not well defined when one tree is not inside a shadow tree

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#302]
The ordering of trees A and B when they don't share the same parent is defined as follows:

> A comes before B if the shadow host which hosts A is preceding the shadow host which hosts B.

However, when either A or B is not inside a shadow tree but the other one is, the ordering is not well defined.  I think we need to refrain from using the term "shadow host" here and instead refer to the root node of the node tree that contains A or B.

**Comment by hayatoito** [comment]
The spec says A and B share the same parent tree, doesn't it?

> 1. Let A and B be node trees that share the same parent tree.
> 2. A comes before B if the shadow host which hosts A is preceding the shadow host which hosts B.

**Comment by rniwa** [comment]
It does. The problem is that the spec doesn't define the ordering of two trees when they don't share the same parent.

**Comment by hayatoito** [comment]
The spec also defines parent-child relationship:

> A node tree A is called a parent tree of a node tree B if B is a shadow tree and the shadow host which hosts B participates in A.

My intention is:
1. parent-child relationship
2. order between siblings

1 and 2 are enough to define the tree order. Maybe I should have explained this (implicit) intention more clearly in the spec. :(

**Comment by rniwa** [comment]
Oh I see. I think what's confusing here is that you're mentioning the ordering only when you started talking about siblings.  I think it's better to clarify it up front before talking about child-parent relationship or omit it altogether since once child-parent relationship and sibling relationships are established, then tree order is [well defined](https://dom.spec.whatwg.org/#concept-tree-order)

**Comment by hayatoito** [comment]
I've clarified it at
https://github.com/w3c/webcomponents/commit/cf0695df97cb5db87b25314c84426d07551c92d5
