### ISSUE TITLE
ownerDocument of a node in a shadow tree isn't well defined

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#303]
`ownerDocument` of a node in a shadow tree is defined as follows:

> The ownerDocument property of a node in a shadow tree must refers to the document of the shadow host which hosts the shadow tree.

However, the definition of "the document of the shadow host" isn't clear.  I think we need to instead define  [node document](https://dom.spec.whatwg.org/#concept-node-document) for each node in a shadow tree.  That definition can be recursive and the [definition of `ownerDocument` property in DOM4](https://dom.spec.whatwg.org/#dom-node-ownerdocument) will take care of the rest.

But quite frankly, I'm not even sure we need to redefine what the node document of a node inside shadow tree will become because the node document is set as soon as a shadow tree is created, which is defined later in the spec.

**Comment by rniwa** [comment]
Perhaps @annevk has some comments/advices here?

**Comment by annevk** [comment]
If you set the node document accurately while creating nodes there should be no problem. If it's not the same as the node document of the shadow host there might be problems though with base URLs and such.

**Comment by hayatoito** [comment]
Thanks. It sounds we can remove this paragraph:

> The ownerDocument property of a node in a shadow tree must refers to the document of the shadow host which hosts the shadow tree.

Let me remove it.
