### ISSUE TITLE
assignedSlot should be defined on Node

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#310]
It seems that there is nothing that prevents a comment node, ProcessingInstruction, etc... to be distributed into a slot so I don't think it makes sense to define `assignedSlot` on `Element` and `Text` interface separately.  We should just define it on `Node` instead.  And make `DocumentFragment`, `Document`, etc... return null by the virtue of them never being distributed to any slot.

**Comment by hayatoito** [comment]
I think this makes sense. Let me update the spec and close the issue.
If someone has a concern about this change, please feel free to re-open this.

**Comment by annevk** [comment]
FWIW, this is not how we've handled recent additions to DOM. We've instead only added members where they actually make sense. So I don't think we should do it this way.

**Comment by annevk** [comment]
You could extend the mixins DOM defines that group various set of nodes if you want to avoid duplication.

**Comment by rniwa** [comment]
So you suggest we add it to Element, CharacterData, and Comment?

**Comment by annevk** [comment]
It seems [`NonDocumentTypeChildNode`](https://dom.spec.whatwg.org/#nondocumenttypechildnode) is what you want (`CharacterData` includes `Comment`).

**Comment by rniwa** [comment]
Okay, that makes sense.
