### ISSUE TITLE
attachShadow must throw a TypeError when mode is omitted

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#311]
`attachShadow` must throw a TypeError when "mode" is omitted in `ShadowRootInit` as previously agreed in F2F.

**Comment by rniwa** [comment]
We should also throw when the value of `mode` doesn't match either "open" or "closed".

**Comment by domenic** [comment]
I think the correct way to do this is to make mode `required` in the definition of `ShadowRootInit`. Should be a one-line fix.

**Comment by domenic** [comment]
Actually the spec already takes care of this. When you convert a JS value to a ShadowRootMode, per IDL, first you do a ToString, and if it does not match `"open"` or `"closed"` (including if it is `"undefined"`), it will throw a TypeError.

**Comment by rniwa** [comment]
But it could still be omitted from the dictionary, right?

**Comment by domenic** [comment]
Yeah, I just re-read, and I was right the first time. Without `required`, if it is `undefined` (e.g. via omission from the JS object that gets converted into an IDL dictionary), the conversion to ShadowRootMode will not take place.

So yeah, just add `required` and it'll work as expected.

**Comment by hayatoito** [comment]
I thought it's required _by default_ unless `optional` is specified. What's weird. :(
Where can I read the definition of `required`?
Is this the latest spec we should use? https://heycam.github.io/webidl/

**Comment by annevk** [comment]
No, dictionary members are always optional unless prefixed with `required`. And yes, that is the latest IDL.
