### ISSUE TITLE
Disallow attachShadow on replaced elements

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#312]
It seems that the behavior of attaching shadow roots on [replaced elements](https://html.spec.whatwg.org/#replaced-elements) such as img, embed, object, etc... are not well defined.  We should probably disallow it in v1.

**Comment by rniwa** [comment]
In addition, `summary` element seem to create a user-agent shadow root in [Blink](https://chromium.googlesource.com/chromium/blink/+/master/Source/core/html/HTMLSummaryElement.cpp) and [WebKit](http://trac.webkit.org/browser/trunk/Source/WebCore/html/HTMLSummaryElement.cpp#L58) as well.

**Comment by domenic** [comment]
It seems this would be best rolled in to #110. In other words, all replaced elements, in addition to all elements currently specified as having a fictional "binding" property, should get the "allow shadow root: false" flag in the HTML spec (https://github.com/whatwg/html/issues/85).

**Comment by rniwa** [comment]
In addition, we may want to consider disallowing them on SVG tref and use elements.  In fact, we may want to consider allowing `attachShadow` only on `HTMLElement` and its subclasses.

**Comment by hayatoito** [comment]
It seems we can merge this to #110. Let's merge.
Please feel free to add comments to #110.
