### ISSUE TITLE
caretPositionFromPoint, elementFromPoint, and elementsFromPoint should respect shadow boundary

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#313]
We should make these functions not return an element outside of its node tree.  Also, we need to define what happens when an element from another node tree is overlaying on top of the node tree in which these functions are called.  Do we return null in that case?  Or do we somehow by-pass those overlapping elements?  (The latter is going to be hard to implement).

I'm also inclined to say we may not want to include this in v1 given how undefined its behaviors are.

**Comment by hayatoito** [comment]
> We should make these functions not return an element outside of its node tree.

The spec takes care of it, doesn't it? Quoted from the spec:

> Return the result of running the retargeting algorithm with context object and HIT as input

**Comment by rniwa** [comment]
As far as I can tell, only the definition of `elementFromPoint` says that.  `caretPositionFromPoint` and `elementsFromPoint` are entirely missing their definitions.

Also, the current definition of `elementFromPoint` refers to an undefined term "hit testing".  I think it's best to rely on the [corresponding functions on `Document`](https://drafts.csswg.org/cssom-view/#extensions-to-the-document-interface) instead.

In addition, the CSSOM also need to respect the shadow boundary and run the retargeting algorithm as well since we wouldn't be returning "associated elements" inside shadow boundaries.  At that point, we might as well as add these functions to both `Document` and `ShadowRoot` in CSSOM since CSSOM spec will depend on this shadow DOM API spec.

**Comment by hayatoito** [comment]
Thanks. Yeah, I remember that I had the same feeling when I investigated how "hit testing" is defined.
Definitely, we have to rewrite the spec so that it makes sense more.

My intention is "Do not leak any nodes in a shadow tree vis these APIs", frankly.
Until the spec is fixed, please implement these APIs so that it does not leak any nodes in a shadow tree.

**Comment by hayatoito** [comment]
Now these methods are defined in DocumentOrShadowRoot.
https://github.com/w3c/webcomponents/issues/91
Some clarifications were also done at https://github.com/w3c/webcomponents/commit/e04cb38d620bead422995e489df06f43604a6024
