### ISSUE TITLE
Clarify whether the empty string is a valid slot name or not

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#319]
It's not clear from reading the spec what happens to an element with an empty slot name; e.g. `<span slot=""></span>` or a slot with an empty name e.g. `<slot name=""></slot`>`

Is the empty string considered as a valid slot name?  I think this at least deserves an informal note if not a normative clarification.

**Comment by rniwa** [comment]
@annevk @travisleithead : Any opinions?

**Comment by annevk** [comment]
Both class/id require at least a single code point. I think it would make sense to follow that precedent. In other words, to ignore `slot=""` and `name=""` for the purposes of matching.

That would make `name=""` equal to omitting `name` (default slot), which doesn't so bad.

**Comment by rniwa** [comment]
I concur given that's how `name` on `a` and `input` behaves as far as I can tell.

**Comment by travisleithead** [comment]
I also agree- in general ="" is synonymous with an omitted value.

**Comment by hayatoito** [comment]
Let me close this issue. I assumed that slot="" means _empty_ because I remember this commit from @annevk: https://github.com/w3c/webcomponents/commit/65ef2b45742bd4b6fb344be95f2e5062ce51abf9

**Comment by annevk** [comment]
Well I was partially wrong there. It should explicitly check "If _name_ is the empty string or missing, ..." What was confusing with the original text was that null/undefined don't really make sense there.

**Comment by hayatoito** [comment]
Thanks. Let me update the spec.
