### ISSUE TITLE
Add getAssignedNodes

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#322]
We should be consistent with the terminology used elsewhere for `slot` attribute and `assignedSlot` and call this method `getAssignedNodes` instead.

Introducing new (or historical) terms like "distributed" would only confuse authors.

**Comment by hayatoito** [comment]
I don't have a strong opinion on this either.

My concern is that the semantics of the `assignedSlot` and `getAssignedNodes` are not _symmetry_.
Using _assigned_ for both might be confusing, however, I don't have any better name. :(

At least, I prefer getAssignedNodes to getComposedNodes, which was mentioned at https://github.com/w3c/webcomponents/issues/128.

**Comment by rniwa** [comment]
Right. The semantics will be same once we stop unwrapping slot (see #308) however.

**Comment by hayatoito** [comment]
#308 is not related since it only affects the composition algorithm, I think.

Anyway, I'll rename it to getAssignedNodes unless there is a better proposal.
If someone disagree the renaming, please let us know it.

**Comment by rniwa** [comment]
Well, it is related in that if #308 gets resolved in the favor of keeping slot elements wrapped, then the [get distributed nodes algorithm](https://w3c.github.io/webcomponents/spec/shadow/#dfn-distributed-nodes) should also be changed to not flatten the distributed nodes in inner slot elements for consistency since it's quite trivial for authors to _unwrap_ slots manually themselves.

**Comment by hayatoito** [comment]
It's not just renaming. That's yet another proposal, changing the semantics of the getDistributedNodes.

I think we should rename this issue, "Replace getDistributedNodes with getAssignedNodes" or "Add getAssignedNodes() API".

Anyway, I understand your intention. That' exactly the same API which I thought to add to v1, but I haven't.

**Comment by hayatoito** [comment]
If getAssignedNodes has the new semantics, I don't have any concern about its name.

**Comment by hayatoito** [comment]
I've renamed the issue. BTW, we can add getAssignedNodes without #308. #308 is not precondition of adding getAssingedNodes, I think.

**Comment by JanMiksovsky** [comment]
Naive question: instead of a function called `getAssignedNodes`, could this be a getter `assignedNodes`? To me, it feels similar to `childNodes` or `children`.

**Comment by rniwa** [comment]
The problem is that WebIDL doesn't allow [`sequence<T>`](http://www.w3.org/TR/WebIDL/#idl-sequence) to be used on an attribute so we'd have to use `NodeList` or `HTMLCollection` to add `assignedNodes` as a property as things stand.

**Comment by domenic** [comment]
You could use `FrozenArray<T>`.

I think the more relevant question is whether this is an O(n) operation (use a method) or O(1) (use a property).

**Comment by rniwa** [comment]
How does FrozenArray work given the list of assigned nodes change over time?  An array is either frozen or not frozen.  We shouldn't be modifying a frozen array magically under the hood.  If we're creating a new array on that attribute, then it's always O(n) regardless of whether it's a method or an attribute since we have to create a new array on each access.

**Comment by domenic** [comment]
You would return a different frozen array whenever it changes, but the same one while it remains the same.

**Comment by annevk** [comment]
I haven't really studied the details yet, but if the UA keeps an internal list of assigned nodes a property makes more sense. If it's something that is computed and we just return a snapshot a method makes more sense.

**Comment by hayatoito** [comment]
I've added `getAssignedNodes()` as a method which returns `sequence<Node>`.
It should return a _snapshot_.

**Comment by hayatoito** [comment]
I've not removed getDistributedNodes() yet.
