### ISSUE TITLE
Rename Distributed Nodes Algorithm to Slot Assignment Algorithm

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#323]
Like the issue #322, we should just get rid of the term "distribution" everywhere in the spec.  It's unwarranted use of a historical jargon that doesn't merit anyone.

**Comment by hayatoito** [comment]
One web-exposed API which is using the term "distribution" is `slot.getDistributedNodes()`.

http://w3c.github.io/webcomponents/spec/shadow/#widl-HTMLSlotElement-getDistributedNodes-sequence-Node

We need to rename this. How about `slot.getComposedNodes()`?

Regarding with other usage of the term "distribution" in the spec, we do not have to be in a hurry. We can fix that later.

**Comment by rniwa** [comment]
Now about `getAssignedNodes()` with a boolean argument specifying deep/flatten?

**Comment by hayatoito** [comment]
I'm fine with `getAssignedNodes()` with a boolean parameter:

``` idl
    sequence<Node> getAssignedNodes(optional boolean deep/flatten/oranythingelse);
```

`sequence<Node>` could be FrozenArray[Node], that is another issue.

**Comment by annevk** [comment]
Please no boolean parameter. Use a dictionary with a single member that defaults to false. We always find out over time we wanted more parameters. And it's better that boolean parameters are named.

**Comment by hayatoito** [comment]
+1. Let's use a dictionary even when only one parameter is expected, as of now.

**Comment by TakayoshiKochi** [comment]
As commented in https://github.com/w3c/webcomponents/issues/361#issuecomment-173465003
deepPath is for #361.
