### ISSUE TITLE
Consider adding a new node type for ShadowRoot

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#324]
We might want to consider adding a new node type like `SHADOW_ROOT` for `ShadowRoot`.

@annevk @travisleithead any opinions?

**Comment by annevk** [comment]
I think the only reason we had node types to begin with was Java. And perhaps it's useful for cross-global object instanceof-type things. Not particularly convinced it's worth it.

**Comment by domenic** [comment]
It seems weird not to have it... Every node in the DOM should have _some_ type, shouldn't it?

**Comment by rniwa** [comment]
I get that these type enums are legacy but not having one for shadow root will make the DOM API even less consistent and imposes unwarranted cognitive load on authors.

**Comment by travisleithead** [comment]
Their type today is 11, and name is "#document-fragment", right?

**Comment by annevk** [comment]
@travisleithead "today", yeah.

**Comment by travisleithead** [comment]
I see the argument for consistency with other DOM node types, but given that these tend to act more like document roots and are not ever going to be seen while traversing a node tree (where most code checks for nodeType/Name), then there doesn't seem a lot of value to adding the new type. So, I don't have strong feelings either way, but I'm leaning towards not adding one.

**Comment by hayatoito** [comment]
I don't have a strong opinion either. I'll close this issue in a week if we don't have more +1 for adding new node type. We can reopen this issue anytime.
