### ISSUE TITLE
Consider making ShadowRoot directly inherit from Node

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#325]
It seems strange that `ShadowRoot` inherits from `DocumentFragment` given that `ShadowRoot` could be in the document whereas `DocumentFragment` can't traditionally be in the document ever.

Given our preferred way of adding methods to multiple interfaces is defining interfaces like `NonElementParentNode` and `ParentNode` and make other interfaces implement them, it's totally fine for `ShadowRoot` to inherit directly from `Node` and then make it implement everything `DocumentFragment` implements.

**Comment by rniwa** [comment]
@annevk @travisleithead

**Comment by annevk** [comment]
> It seems strange that `ShadowRoot` inherits from `DocumentFragment` given that `ShadowRoot` could be in the document whereas `DocumentFragment` can't traditionally be in the document ever.

Doesn't seem too different from `CharacterData`, although `DocumentFragment` can exist on its own of course.

I guess the question is if we would ever add something to `DocumentFragment` that we wouldn't add to `ShadowRoot`.

**Comment by hayatoito** [comment]
If ShadowRoot is not DocumentFragment,  `div.appendChild(shadowRoot)` would be troublesome. :(

Shadow Root is intended to be the root node, always. How can we guarantee that if ShadowRoot is not DocumentFragment?

**Comment by rniwa** [comment]
That can be addressed by introducing a new concept in the DOM spec that applies to both `DocumentFragment` and `ShadowRoot`.

**Comment by domenic** [comment]
I think inheritance is the proper relationship here. Every context where you can use a document fragment, you can use a shadow root, right? That (LSP) is the best criterion here. 

Inheritance does not mean that everywhere a subclass can appear, the superclass must also be able to appear. (So a shadow root being able to appear in documents even though a document fragment cannot is fine.)

**Comment by hayatoito** [comment]
Just to make sure:
IMO, a shadow root can't _appear_ in documents, nor _could be in the document_. Although it depends on the definition of _in the document_ here.

In the strict sense, a shadow root is never in a document. A shadow root is never in a document composed tree.

**Comment by hayatoito** [comment]
FYI. I remember that we had several discussion in Google: Which ShadowRoot should be, DocumentFragment or Element.

@dglazkov , do you remember why we chose DocumentFragment?

BTW, I'm totally fine with DocumentFragment. It looks the proper relationship.

**Comment by annevk** [comment]
Yeah I don't think we need to revisit this either.

**Comment by travisleithead** [comment]
Let's leave it as-is. I think we have a good factoring in DOM right now, and I don't think it confuses anything to have ShadowRoot restrictions that don't apply to types that it inherits from.

**Comment by hayatoito** [comment]
Looks there is no strong objection to ShadowRoot as DocumentFragment.
Let me leave it as-is.

We can reopen this issue anytime if we find an issue of that.
