### ISSUE TITLE
attachShadow should fail on a slot element

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#327]
I don't think it makes sense to support `attachShadow` on slot elements since they don't even render by default due to its default style `display: contents` unless there is a compelling use case for it.

We should add it to the list of forbidden elements in https://w3c.github.io/webcomponents/spec/shadow/#widl-Element-attachShadow-ShadowRoot-ShadowRootInit-shadowRootInitDict.

**Comment by annevk** [comment]
I'm starting to think we should make that a whitelist.

**Comment by annevk** [comment]
That is, all custom elements plus a handful of existing elements. That also allows us to add hyphenless elements in the future more easily since we don't have to worry about existing `attachShadow` usage on them.

**Comment by rniwa** [comment]
Yeah, I'm not certain what it means to attach a shadow DOM on `xmp`, `br`, `template`, `script`, `style`, etc... for example.  A small whitelist of elements might be a good start.

**Comment by hayatoito** [comment]
Let me merge this with #110.

You guys finally reached to the same conclusion to me https://github.com/w3c/webcomponents/issues/110#issuecomment-111983764

I'm okay to have a whitelist as a starting point.
