### ISSUE TITLE
inflexible extends as fixed element type

### ISSUE THREAD

**Issue by rjharmon** [WICG/webcomponents#33]
I'd like to be able to specify any type (or perhaps certain types) of tags, with is= to augment functionality of any element.  The initialization sequence I'm imagining is passed the native element instance, and then the component would be able to add its own capabilities to that instance's prototype chain (could also choose to prepare the prototype chain so that element.prototype is already distinguished from that element's native prototype, as a helpful refinement to developers).

A similar technique could be used to add multiple mixins to a tag, assuming they'd been designed them to be complementary/concerned with orthogonal aspects of the markup/content.  I think of that as with= rather than is=.

**Comment by dglazkov** [comment]
@rjharmon, this bug tracker is not used for spec bugs. Please use the link in the spec to file new bugs. Transferred your bug over there: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28158
