### ISSUE TITLE
Event path trimming should only happen for mouseover and mouseout

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#330]
It's very strange for the [event path trimming algorithm](https://w3c.github.io/webcomponents/spec/shadow/#dfn-event-path-trimming-algorithm) to apply trusted events with `relatedTarget`.

Why don't we just do this for all `mouseover` and `mouseout` events and nothing else.  Alternatively, we can add a new constructor option to MouseEvent's init dictionary like `stopsAtLowestCommonShadowRoot` to explicitly set this behavior so that authors can adjust it.  If we did the latter, we'd just make UAs create MouseEvents with that flag set to `true` when firing trusted events.

@travisleithead @annevk: any opinions?

**Comment by rniwa** [comment]
If we (in some off chance) were to keep the currently spec'ed behavior, then the following text belongs to an informative note, not a normative text since this trimming behavior applies to all trusted events.

> to avoid the appearance of spurious `mouseover` and `mouse out` events firing from the same node

**Comment by annevk** [comment]
Doing this flag-based does seem more sane. Since it would actually explain what is going on. (Where did I hear that before?)

**Comment by rniwa** [comment]
Yeah, I think I like the flag-based approach best.  cc @hober @othermaciej

**Comment by hayatoito** [comment]
This is the original bug for the current spec. https://www.w3.org/Bugs/Public/show_bug.cgi?id=20017

The flag-based approach is okay to me. 
We need a better name than `stopsAtLowestCommonShadowRoot`. Any idea?

**Comment by rniwa** [comment]
An alternative to specify a boolean would be to specify a node at which the propagation stops: e.g. `highestTarget`.  This way, `mouseover` and `mouseout` can supply the common ancestor as `highestTarget` instead.  This feature will be slightly more powerful than what's needed by this use case. Although I'd imagine it could become handy in some cases, I'm not sure if it's worth the complexity.

**Comment by hayatoito** [comment]
I'm not sure how we can resolve this issue. Does someone have a preference?

**Comment by rniwa** [comment]
My preference is to add a flag instead of treating trusted events differently since the rationale for trimming the event path is semantically nothing to do with whether event should be trusted or not.

**Comment by annevk** [comment]
`untilCommonShadowRoot`?

**Comment by hayatoito** [comment]
I think we agreed on using the flag. Let me update the spec so that it uses the flag in relevant sections.

Note that the flag name is not finalized. It could change if we find a better name.
