### ISSUE TITLE
Type extensions in SVG use shadow trees--specify, or add a note if no specification is necessary

### ISSUE THREAD

**Issue by dominiccooney** [WICG/webcomponents#335]
SVG use allows an SVG subtree to be instanced multiple times. As far as I am aware, an implementation would not necessarily have to implement those instances as full-blown nodes; nor are the nodes exposed. It would be good to clear up what happens if a Custom Element is instanced into an SVG shadow tree.

**Comment by hayatoito** [comment]
How SVG and Shadow DOM should interact is not well thought. That has been an unsolved issue.

**Comment by annevk** [comment]
Elsewhere we decided that this doesn't work for now. All custom elements are HTML elements. Shadow roots can only be attached to a select few HTML elements (including custom elements).

We might extend the HTML parser so HTML custom elements can be used inside SVG.

How SVG `use` works is up to the SVG WG to define. They can easily make use of a closed shadow root to describe it.
