### ISSUE TITLE
Clarification needed :root CSS pseudo class matches ShadowRoot or not

### ISSUE THREAD

**Issue by TakayoshiKochi** [WICG/webcomponents#338]
As currently specced, CSS pseudo class `:root`

https://drafts.csswg.org/selectors-4/#root-pseudo

> The `:root` pseudo-class represents an element that is the root of the document.
> For example, in a DOM document, the `:root` pseudo-class matches the root element of the Document > object. In HTML, this would be the html element (unless scripting has been used to modify the document).

which looks unclear whether in a shadow tree it matches to its shadow root or not.
Note that I understand shadow root is a DocumentFragment (if #325 is settled down) and
is not an element, thus normally a CSS selector cannot point to it.

If `:root` is used inside shadow style, the selector never matches anything?

**Comment by hayatoito** [comment]
`:root` is not well thought for a shadow tree. We can decide the behavior. The current interpretation is "It does not match anything".

**Comment by amiller-gh** [comment]
As a thought, if we want to simplify new API changes, we can use `:root` in the context of a shadow tree to match the host element instead of `:host`.

Right now `:host` is defined as such:

> The :host pseudo-class, when evaluated in the context of a shadow tree, matches the shadow tree’s host element. In any other context, it matches nothing.
> http://www.w3.org/TR/css-scoping-1/#selectordef-host0

It seems odd to have two selectors that share similar concepts, but are mutually exclusive in two different contexts. Granted, `:host` is a little more descriptive given the terminology used in the discussion so far, but its not a stretch to refer to a shadow tree's host node as its "root element". It also may be easier for devs not following these conversations to use a familiar and existing term/mental-model when describing shadow dom.

**Comment by rniwa** [comment]
I think it would be rather confusing to reuse `:root` for `:host` since `:root` implies the root node and the shadow host isn't the root node of its shadow root.

**Comment by amiller-gh** [comment]
If we're considering the shadow root to be a DocumentFragment that is not selectable by CSS, then the end-consumer of shadow dom (everyday web developers) will never actually interact with, or need to know and care about, the shadow root node itself - it will just be a boundary that their selectors can't cross. I think that re-naming host element to root element is a good mental model for developers not savvy to the implementation under the hood.

**Comment by amiller-gh** [comment]
Frameworks will probably be the largest users of the shadow dom api (Polymer, Ember, etc), so many users won't even ever interact with the Javascript API. To them, the element that contains the shadow node _will_ be their root. 

To enable styling like what @TakayoshiKochi mentions in https://github.com/w3c/webcomponents/issues/314#issuecomment-143645023, using the `:scope` psudo-class would semantically make the most sense to me - if shadow nodes are DocumentFragments. The word `:root` implies an actual DOM Element, `:scope` does not.

**Comment by TakayoshiKochi** [comment]
As `ShadowRoot` is a DocumentFragment (settled in #325), do we all agree that `:root` in a shadow
style does not match anything in shadow root?

**Comment by hayatoito** [comment]
It sounds reasonable that `:root` matches neither the shadow root nor the shadow host.
We don't have to extend the meaning of `:root` here because that is confusing.

**Comment by TakayoshiKochi** [comment]
Okay, let's close this issue.
The comment from @hayatoito above is the conclusion here.
