### ISSUE TITLE
Is there going to be a Chinese version?

### ISSUE THREAD

**Issue by gimm** [WICG/webcomponents#34]
I was wondering is there any plan for non-english version of the specs.
I'd like to do a Chinese version of these if you're going to accept my pull request.

**Comment by gimm** [comment]
just found out there's a Chinese already
http://www.w3.org/html/ig/zh/wiki/Web-Components

**Comment by hax** [comment]
@gimm If you interest in the Chinese translation plan, you could follow https://github.com/w3c-html-ig-zh/webcomponents

**Comment by hayatoito** [comment]
I'm not aware of any plan to translate to other languages.
As @hax mentioned, that might be done in another repository.
