### ISSUE TITLE
Typo in semantics

### ISSUE THREAD

**Issue by prushforth** [WICG/webcomponents#349]
Typo:

Also the visual styling may also be modified to visually indicate it the element is disabled.

Correction:

Also the visual styling may also be modified to visually indicate if the element is disabled.

**Comment by chaals** [comment]
Having "also" twice in the sentence isn't that great either. The first one could happily be removed.

**Comment by TakayoshiKochi** [comment]
Is the same applicable to visual/visually as well?

e.g.
Also the styling may be modified to visually indicate if the element is disabled.

**Comment by chaals** [comment]
Yep.
