### ISSUE TITLE
Restrict the types of nodes that could be assigned to a slot

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#351]
It seems that we only want Text and Element nodes to be assigned to a slot.  There is currently no mechanism to assign non-element nodes to a slot other than via the default slot so this is only relevant to default slots.  Since only Text and Element nodes are visible, we can probably not even expose `assignedSlot` on non-Text CharacterData nodes.

**Comment by rniwa** [comment]
@annevk @travisleithead @hayatoito

**Comment by hayatoito** [comment]
I do not have a strong opinion on this. This sounds a minor issue and does not cause a real issue, IMO.

Do we really want to introduce this restriction? I'm fine that non-Text CharacterData is assigned to a slot, which is harmless.

If we want to introduce the restriction, that's easy, I think. We have to:
1. Change the IDL

From:

``` idl
partial interface NonDocumentTypeChildNode {
    readonly        attribute HTMLSlotElement? assignedSlot;
};
```

To:

``` idl
partial interface Element {
    readonly        attribute HTMLSlotElement? assignedSlot;
};
```

``` idl
partial interface TextNode {
    readonly        attribute HTMLSlotElement? assignedSlot;
};
```
1. Tweak the slotting algorithm in the spec. Additional one sentence is enough.
2. UA has to introduce "if () { } else {}" in implementing slotting algorithm . :)

**Comment by rniwa** [comment]
This actually reduces the amount of code needed in our engine (WebKit) so it's highly desirable for us.

**Comment by hayatoito** [comment]
Okay. Then, it is worth doing. I'm okay to this minor change.

Out of curiosity, could you have a chance to share your experience briefly? Why does this change impact WebKit? I've not encountered such an issue in Blink. I'm afraid that I might have missed something.

**Comment by rniwa** [comment]
It's something to do with the way our style resolution works, and that has changed quite a bit between Blink and WebKit since Blink fork so I'm not certain how relevant our issue is.

**Comment by hayatoito** [comment]
I got it. Thanks.
