### ISSUE TITLE
It is unclear how tree of tress whose root tree is not a document tree should behave.

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#356]
After I replaced "node tree" with "component tree" in https://github.com/w3c/webcomponents/commit/588ecdf984deba5a42b9d2b22e750fe96583b42d, I realized that it would affect the behavior of "tree of trees", in a sense before the commit, whose root tree is not a document tree.

The current spec does not say anything how such a _disconnected_ (from a document) tree of trees should behave.

e.g.

``` html
const host = document.createElement('div');
const child = document.createElement('div');
const shadowRoot = host.attachShadow({mode: 'open'});
shadowRoot.appendChild(document.createElement('slot'));
// Note that host is not inserted into a document.
console.log(child.assignedSlot);  // What should be?
```

FYI. in current Blink's implementation, the distribution is correctly calculated even for such a disconnected  _tree of trees_.

**Comment by hayatoito** [comment]
I think this is a minor issue. Let me label this with v2.

**Comment by annevk** [comment]
This is something we should have defined though, no? These are all v1 features.

**Comment by rniwa** [comment]
Indeed. This will impact interoperability of v1 API.

**Comment by hayatoito** [comment]
I got it. Let me use v1 label for all issues which may impact interoperability.

**Comment by hayatoito** [comment]
I'm going to fix the wording of the spec so that slot assigning API should work even in a such a disconnected _tree of trees_, whose root tree is not a document tree.
