### ISSUE TITLE
Unclear regarding Shadow boundary-piercing combinators

### ISSUE THREAD

**Issue by AVGP** [WICG/webcomponents#357]
So I'm a bit lost and I'd like your help to clear up something that confuses me:

In the f2f meeting in April there's been some disagreement regarding the Shadow boundary-piercing combinators (`/deep/',`>>>`,`::shadow') and [Chrome](https://www.chromestatus.com/features/6750456638341120) talks about them as deprecated.

What confuses me is to see them mentioned in the Shadow DOM Spec:

> The editor's draft of CSS Scoping specification [css-scoping-1] defines the selectors which are related to Shadow DOM. Specifically, it defines the following selectors related to Shadow DOM:
> 
> ::shadow pseudo element
> /deep/ combinator, which was replaced with a >>> combinator (or shadow piercing descendant combinator)

Then again the cited CSS-Scoping spec states "It’s been suggested to remove this feature." about `::shadow` and "It’s currently disputed whether this combinator should exist." for `>>>`.

So it looks like it's possibly going to be removed, but the Shadow DOM spec doesn't say so.
So, shall I make a PR to clarify this issue in the Shadow DOM or is it just me who got puzzled by this?

**Comment by TakayoshiKochi** [comment]
Probably it makes sense to add a note about `/deep/`, `>>>`, and `::shadow` removal in
Shadow DOM spec.

**Comment by hayatoito** [comment]
I don't have any strong opinion. :)

AFAIR, I added this non-normative paragraph when I heard a complaint such as:

> "Hey! I can not _Find in a page_ by a keyword, such as "/deep/" in the Shadow DOM spec! Where are the definitions? ... Ops, these are defined in CSS Scoping spec? Who can notice that! It's reader unfriendly!"

So this paragraph is purely non-normative and just telling reader, "Please consult CSS Scoping spec for these selectors, including the current status of that".

It's okay to make a PR, but please make the duplication minimum. We might not want to update the Shadow DOM spec when something happens on these selectors on the CSS Scoping spec.

**Comment by hayatoito** [comment]
Let me close this issue. Please feel free to send a PR.

**Comment by AVGP** [comment]
Thanks to you all! Will propose a small addition noting that there's dispute about those selectors
