### ISSUE TITLE
Combining :host-context and :host

### ISSUE THREAD

**Issue by pemrouz** [WICG/webcomponents#359]
Is there a way to combine the `:host-context` and `:host` selectors according to the spec? If it's not currently supported, what would the correct syntax look like?

``` css
:host-context(.foo) :host(.bar) { }
:host-context(.foo :host(.bar)) { }
:host-context(.foo).bar { }
/* .. etc .. */
```

**Comment by hayatoito** [comment]
It looks :host-context(.foo):host(.bar) { } is the correct syntax. I have not verified whether it works or not in Blink. Does it work in Blink?

**Comment by hayatoito** [comment]
Let me close this issue. Please feel free to re-open this.

**Comment by pemrouz** [comment]
Thanks :+1:

Can confirm it works in Blink too. Paste into address bar:

```
data:text/html, <x-foo id="el" class="bar"></x-foo><script>el.createShadowRoot().innerHTML="<style>:host-context(html):host(.bar) { color:red }</style>should be red"</script>
```
