### ISSUE TITLE
Use FrozenArray<T> in WebIDL

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#361]
See the context: https://lists.w3.org/Archives/Public/public-webapps/2015JulSep/0165.html

We might want to switch to use `FrozenArray<T>` in the spec if that's preferred.

**Comment by hayatoito** [comment]
Please feel free to re-open this issue if FrozenArray<T> is not appropriate in the commit https://github.com/w3c/webcomponents/commit/6d79c8997caf2762751e20314c1c110110d8dc73

**Comment by annevk** [comment]
I think for `deepPath` it potentially is, but it's not for the method. Having said that, perhaps we should make `deepPath` a method too instead of requiring that user agents allocate an array for each event with the path on it.

**Comment by hayatoito** [comment]
Thanks. I'm fine to make `deepPath` method, e.g. `Event.deepPath()`, however,
I'm afraid that I do not understand why user agents have to allocate an array for each event if it is an attribute. User agents can create an array lazily only when event.deepPath attribute is actually accessed?

FYI. I remember we had the similar discussions in the past, event.path vs event.path():
- https://code.google.com/p/chromium/issues/detail?id=234030#c22
- https://www.w3.org/Bugs/Public/show_bug.cgi?id=25458

@dglazkov , WDYT?

**Comment by annevk** [comment]
Yeah, that's true, they can allocate lazily and it cannot change, so I guess that is fine.

I don't think we should have changed the other one though to return a `FrozenArray`. Returning a normal `Array` there which `sequence<>` does is fine.

**Comment by hayatoito** [comment]
Yeah, I think that we don't get a significant benefit by changing `sequence<T>` to `FrozenArray<T>`.

I'm just wondering which is preferred in general? If the immutability is not important, using `sequence<T>` is a recommended practice in terms of the recent Web Standard?

**Comment by domenic** [comment]
If it's a method `sequence<T>` works best. (Return a new array each time the method is called.) If it's a property it does not work very well, and `FrozenArray<T>` is better.

**Comment by hayatoito** [comment]
Thanks. I got it. Let me use `sequence<T>` for methods.

I'm also wondering that we should change Event.deepPath to a method, `Event.deepPath()`, unless there is a strong objection.

Is there any opinion about changing Event.deepPath from a property to a method?

**Comment by domenic** [comment]
I think it is probably a good idea to change it to a method. It makes it more obvious that (in some UAs at least) it will perform a computation. And then there is no `FrozenArray<T>` stuff which is probably slightly nicer for developers.

**Comment by hayatoito** [comment]
Thanks. Let me use `sequence<T>` for methods, and change Event.deepPath to a method.

**Comment by hayatoito** [comment]
Done at:
- https://github.com/w3c/webcomponents/commit/4f8e45fffb04c96043ba0aa6cfd1e995d6eb7558
- https://github.com/w3c/webcomponents/commit/ed93413f9a37a6bfbd774cb2e09e14a76c87d56c
  (The issue number was wrong in the commit)

**Comment by foolip** [comment]
`Event.deepPath()` came up in a [Shadow DOM v1: Status updates](https://groups.google.com/a/chromium.org/d/msg/Blink-dev/BUGxw_Yx5Lo/tunJEUYXAQAJ) blink-dev thread, where I question why this is a method and why we can't just stick with `Event.path`.

The core of my concern is that there's no particular reason to think it will ever be possible to remove `Event.path` from Blink. The [usage](https://www.chromestatus.com/metrics/feature/timeline/popularity/345) (~2.5%) is almost certainly inflated by enumeration (making copies of events) but that still means we have no idea about how risky such a change would be.

I think only a `readonly attribute FrozenArray<EventTarget> path` with deep semantics should be very seriously considered. There are two warts that I know of:
- All other things in DOM operate on the "local" tree, so using the generic name `path` for the deep event path is a bit inconsistent.
- A method makes it more obvious that a computation required.

Still, at least in my mind, this is not terrible enough to risk yet another duplicated API in the long run, like `document.characterSet`+`document.charset` and innumerable prefixed APIs.

**Comment by foolip** [comment]
Let me know if should file a new issue for this.

**Comment by annevk** [comment]
I think that would be clearer. Please also address in that issue whether Blink includes WindowProxy in the path.
