### ISSUE TITLE
Disallow extension of subclasses of HTMLElement and SVGElement/MathMLElement

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#363]
As summarized in https://wiki.whatwg.org/wiki/Custom_Elements#Subclassing_existing_elements, subclassing existing built-in subclasses elements of `HTMLElement` pose many issues.  We should remove this feature (`extends` on the custom element definition and `is` content attribute) at least from v1.

**Comment by jarek-foksa** [comment]
According to the spec using type extension approach is the only way to create renderable components in SVG namespace.

**Comment by rniwa** [comment]
> According to the spec using type extension approach is the only way to create renderable components in SVG namespace.

I'm proposing to remove that in v1.

**Comment by rniwa** [comment]
Actually, this is a duplicate of the issue #133.
