### ISSUE TITLE
Add attributeFilter

### ISSUE THREAD

**Issue by domenic** [WICG/webcomponents#367]
At defineElement time,
1. Do a `Get(PassedConstructor, "attributeFilter")`.
2. If it is undefined,
   1. never queue attribute changed callbacks
   2. if attributeChangedCallback is present, throw a "what are you doing?" error
3. Run the Web IDL "convert to `sequence<DOMString>`" algorithm on it, rethrowing any errors
4. Store the resulting sequence as the attribute filter and use it to dispatch attributeChangedCallbacks.

There's no provision in v1 for "all attributes".

**Comment by hayatoito** [comment]
Bikeshed: Can we avoid to use the term of 'filter' in `attributeFilter`?
Because "never queue attribute changed callbacks" is now the default behavior, 'filter' sounds weird to me.

`observedAttributes` or something might be better.

**Comment by hayatoito** [comment]
I found that the term of `attributeFilter` is used also in MutationObserver. Then, it might make sense for consistency. :)

**Comment by domenic** [comment]
I understand the confusion; a filter makes more sense when the default is to allow all. I am OK with `observedAttributes`. @annevk, @rniwa, any thoughts?

**Comment by chaals** [comment]
`observedAttributes` does sound like a clear explanation that "this is where the bikes go"… (is `observeAttributes` clearer, or just serious bikeshedding?)

**Comment by rniwa** [comment]
> `observedAttributes` does sound like a clear explanation that "this is where the bikes go"… (is `observeAttributes` clearer, or just serious bike shedding?)

I don't think it should be a verb given it's a property.

**Comment by domenic** [comment]
Went with observedAttributes in https://github.com/w3c/webcomponents/commit/3286f0085ce3ee20e5f0fe03b7f6f09179696555. Relevant sections:
- https://w3c.github.io/webcomponents/spec/custom/#extensions-to-document-interface-to-register step 10 and 11.
- https://w3c.github.io/webcomponents/spec/custom/#dfn-enqueue-lifecycle-callback step 6
