### ISSUE TITLE
Link to CSS Scoping module spec?

### ISSUE THREAD

**Issue by sole** [WICG/webcomponents#37]
Looking for "scope" or "/deep" or similar terms in the spec doesn't produce any meaningful result--because there is no mention to said selectors in the Shadow DOM spec.

But as a developer I would expect at least a mention to: http://dev.w3.org/csswg/css-scoping/

This is the web, right? we link things together :globe_with_meridians:

**Comment by dglazkov** [comment]
@sole, this bug tracker is not being used for spec bugs. Use the one linked in the spec (the W3C Bugzilla one). I transferred your bug there: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28157

**Comment by hayatoito** [comment]
Thank you for reporting.
Just for record. Fixed at fc058000d0cf3e2350aa5c467fa59e684d1358b1
