### ISSUE TITLE
HTML Imports typo: s/altorighm/algorithm

### ISSUE THREAD

**Issue by MarkWaka** [WICG/webcomponents#370]
In https://www.w3.org/TR/html-imports/, under the section "Import Dependent", there is a sentence: "The list is empty at beginning and the item is added as import request altorighm specifies". "Algorithm" is misspelled here. It should probably also read "the import request algorithm" (ie insert "the").

**Comment by plehegar** [comment]
This has been fixed.
Sentence now says "The list is initially empty, and items are added to it as specified by the import request algorithm."
