### ISSUE TITLE
HTML Imports bug link is wrong

### ISSUE THREAD

**Issue by MarkWaka** [WICG/webcomponents#371]
https://www.w3.org/TR/html-imports/ has a "File bugs" link to https://www.w3.org/Bugs/Public/enter_bug.cgi?comment=&blocked=20683&short_desc=%5Bimports%5D%3A%20&product=WebAppsWG&import=import%20Model. After filing a bug there (https://www.w3.org/Bugs/Public/show_bug.cgi?id=29397) a comment indicated that bugs should instead be filed here. If that's the case, the link should be updated.

**Comment by plehegar** [comment]
The link to bugzilla has been removed.
