### ISSUE TITLE
Event path trimming should use `scoped` flag and not rely on trustedness

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#372]
[5.8 Event Path Trimming](http://w3c.github.io/webcomponents/spec/shadow/#event-path-trimming) says:
"In cases where both `relatedTarget` and `target` of a trusted event are part of the same shadow tree, the conforming UAs **must** _stop_ events at the shadow root to avoid the appearance of spurious `mouseover` and `mouseout` events firing from the same node."

Any event dispatched by UA is a [trusted event](https://w3c.github.io/uievents/#trusted-events).  Either this description or inaccurate or we should be using `scoped` for UI events such as `mouseover`, `mouseout` and trimming the path when `scoped` is set to true.

**Comment by hayatoito** [comment]
Do you mean `untilCommonShadowRoot` instead of `scoped`?
See https://github.com/w3c/webcomponents/issues/330#issuecomment-171627338

Can we merge this to #330?
