### ISSUE TITLE
Section 5.7. Retargeting Focus Events is unclear

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#374]
[Section 5.7 Retargeting Focus Events](http://w3c.github.io/webcomponents/spec/shadow/#retargeting-focus-events) says:
"The `focus`, `focusin`, `blur`, and `focusout` events **must** be treated in the same way as events with a `relatedTarget`, where the corresponding node that is losing focus as a result of `target` gaining focus or the node that is gaining focus, and thus causing the blurring of `target` acts as the related target."

I don't know what this means.  Are you saying that we should be firing `blur` and `focus` events starting at the old/new focused element until they reach the common ancestor tree?

**Comment by hayatoito** [comment]
This section has been there for years without being rewritten, I think.
I think we can rewrite the section after we can spec https://github.com/w3c/webcomponents/issues/330.
