### ISSUE TITLE
Composed child not correctly defined

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#383]
Since the `ShadowRoot` is not actually part of the composed tree, it should not be a composed child. Also, this does not seem to account for distribution.

I thought the composed tree was the tree where everything is distributed, i.e., what CSS operates on.

**Comment by hayatoito** [comment]
The meaning of "composed tree" was changed in this commit.
https://github.com/w3c/webcomponents/commit/9b7f16e90b88594ed783ff7e0f971fad084e5f4d

Shadow DOM spec is starting to use the terminology of _flat tree_, which is a new name for _composed tree_

**Comment by annevk** [comment]
When is this difference supposed to matter?

**Comment by hayatoito** [comment]
The difference between "in a composed document" and "in a document flat tree" matters when:
- if a node is _in a composed document_, but not in a _document flat tree_, the node should behave as if it was specified `display: none`.

Some parts of the spec are using "document flat tree" to specify such a node.
- _Inert unless being rendered_, such as `<applet>`, `<embed>`, `<object>`. I guess we do not want to load resources for this element if it's not in a document flat tree. See http://w3c.github.io/webcomponents/spec/shadow/#inertness-of-html-elements-in-a-shadow-tree
- If a node is not in a document flat tree, the node does not join a sequential focus navigation (pressing tab key). See http://w3c.github.io/webcomponents/spec/shadow/#focus-navigation

**Comment by annevk** [comment]
Closing this in favor of #382. Thank you @hayatoito.
