### ISSUE TITLE
"Let SLOT be the most preceding slot in TREE whose slot name is NAME if it exists. Otherwise null."

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#386]
I think you want "Let SLOT be the first slot element in TREE whose slot name is NAME if it exists, in tree order, and null otherwise." (Similar to get how `getElementById()` is defined.)

To use "preceding" you need two nodes and a tree.

**Comment by hayatoito** [comment]
Thanks. I've fixed it.
