### ISSUE TITLE
Input to flat tree children calculation algorithm seems wrong

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#387]
If the node is already in a flat tree, it cannot be a `slot` element, yet the algorithm checks for that. It seems more like this is an algorithm to create the flat tree out of a composed tree.

**Comment by hayatoito** [comment]
Yea, it's an algorithm to create the flat tree out of a composed tree, actually, in a declarative way.
Should I clarify that?

**Comment by annevk** [comment]
Yeah, I think you should just make the input the composed tree and the output the flat tree.
