### ISSUE TITLE
Exposing a CanvasImageSource hidden by a Shadow Tree

### ISSUE THREAD

**Issue by andyearnshaw** [WICG/webcomponents#388]
One of the things we're using Custom Elements/Shadow DOM for is a video player with custom controls.  An issue came up yesterday where a client wanted to render the video onto a canvas like this simplified version:

``` html
<x-video name="vid1" autoplay>
```

``` javascript
var vid = document.querySelector('x-video');
canvasContext.drawImage(vid, 0, 0, vid.width, vid.height);
```

Currently, we actually expose the `<video>` element because I actually foresaw problems like this one, so I was able to tell them to use `vid.player` instead.  However, I'd certainly prefer not to let developers have access to elements in the shadow tree for obvious reasons.

I'm wondering if we could spec something like `shadowRoot.canvasImageSource = htmlVideoElement;` to allow drawing custom elements with shadow trees to canvases.

**Comment by annevk** [comment]
So it sound like what you want is some kind of protocol for `drawImage()` to support. So you can pass in arbitrary objects and `drawImage()` will poke at something which returns something `drawImage()` understands. That might be better filed at https://github.com/whatwg/html/issues/new though I suppose we could keep a tracking issue here.

**Comment by andyearnshaw** [comment]
Yeah I was in two minds whether to approach the problem from a web components perspective or `drawImage`.  I posted here because it's a problem specific to web components right now, but I guess any changes will affect the spec for `drawImage` or CanvasImageSource anyway.  

I've filed an issue on the whatwg/html repo too.

**Comment by TakayoshiKochi** [comment]
@andyearnshaw is your problem solvable by Houdini's [custom CSS paint spec](https://drafts.css-houdini.org/css-paint-api/)?

**Comment by andyearnshaw** [comment]
@TakayoshiKochi I don't think so.  While the spec is quite interesting, it merely extends the CSS `<image>` type and doesn't address security concerns that would apply to rendering arbitrary elements (for example, a `<div>` that contains an `<iframe>`) onto a canvas.  Even if it would work, it seems like it would add unnecessary complexity.

What I need is a way to allow people who are using my custom video/image elements to render them onto a canvas and apply their own filters.

**Comment by annevk** [comment]
This is https://github.com/whatwg/html/issues/706 on the HTML side. Closing as this is not really a shadow DOM issue. That is, I don't see us ever adding anything to the shadow DOM API to address this.
