### ISSUE TITLE
MutationObserver and attachShadow()

### ISSUE THREAD

**Issue by rodneyrehm** [WICG/webcomponents#390]
I'm looking for a way to keep track of ShadowRoots being created. Neither does the current implementation of ShadowDOM/MutationObserver in Firefox 44 and Chrome 48 register a mutation for `element.createShadowRoot()` (renamed to `attachShadow()`), nor does either specification mention this situation specifically.

To the best of my knowledge it is currently not possible to get identified when a ShadowRoot is created for an element.

(originally raised at whatwg/dom#170)

**Comment by hayatoito** [comment]
Right. There is no way to observe attachShadow().

I'm not sure this is a question or a feature request... Please feel free to reopen if this is a feature request.

**Comment by rodneyrehm** [comment]
It is a feature request. But I'm unable to reopen the issue…

**Comment by hayatoito** [comment]
Thanks. Let me reopen this.

**Comment by annevk** [comment]
This is a duplicate of #204. Sorry for not realizing that earlier. Forgot to search.
