### ISSUE TITLE
Unable to get Custom Elements working in a static page.

### ISSUE THREAD

**Issue by ghost** [WICG/webcomponents#392]
(EDIT: I posted with the wrong username, I am also @trusktr)

Hello,

I'm working on a library (at http://infamous.io, for now at least) in which I'm creating a set of Custom Elements for rendering a 3D scene. The library registers two elements, `[<motor-scene>](https://github.com/infamous/infamous/blob/master/src/motor-html/scene.js)` and [`<motor-node>`](https://github.com/infamous/infamous/blob/master/src/motor-html/node.js). The library depends on [this](https://github.com/WebReflection/document-register-element) document.registerElement polyfill for non-supporting browsers.

I have a small problem. Everything works fine when I use the custom elements in the `<body>` of a Meteor app, but when I try doing the exact same thing with a static HTML page and the scripts manually included in the `<head>`, it fails and doesn't work as expected. I'm not sure if I'm doing something wrong and don't know something about Custom Elements, or if there's a problem with the API.

To see the working demo, just

``` sh
git clone git@github.com:trusktr/site.git
cd site
git checkout infamous-motor-html # it's on this branch.
npm install
meteor # meteor is really easy to install, meteor.com
# visit localhost:3000
```

The result looks like this, the teal and pink elements positioned as expected in 3D space:

![working](https://cloud.githubusercontent.com/assets/16913311/13231453/d1dc4baa-d95e-11e5-8bf1-62a83c1f9488.jpg)

Now, if you look in the `public` folder, you'll see the static version in `html-demo.html`. You can open this directly in your browser with `file://`, or visit `localhost:3000/html-demo.html` while running the Meteor app. I have double checked, and I believe that I am doing the same exact thing as in the Meteor version, but I simply cannot get the expected result, and it looks like this:

![not-working](https://cloud.githubusercontent.com/assets/16913311/13231486/f0104626-d95e-11e5-8e64-844c377cda60.jpg)

I'm not sure what the problem is, and why it works in the Meteor version (Meteor 1.3 compiles the code with Babel) and doesn't work in the static version (also compiled with Babel via Webpack).

Any ideas?

**Comment by rniwa** [comment]
This Github issue tracker is used to track the issues with Web components **specifications**, and it's not a general forum for asking questions about web components.  Please take your question elsewhere like stackoverflow.

Please re-open the issue if this is about reporting a specific issue with the currently proposed API or issues with the specifications.

**Comment by ghost** [comment]
@rniwa I feel like stackoverflow is too generalized sometimes, and that I might not get good feedback on something specific like this, so I thought I'd ask here where the experts on the topic might be able to help. In general, I wish W3C had an official online forum. I don't know if there's a problem in my code, or in the Custom Elements API (something I might not be aware of).

**Comment by ghost** [comment]
I've added `console.logs` to the `createdCallback`, `attachedCallback`, etc methods in the `registerElement` calls. This shows two different orderings of output. 

This is the output for the Meteor version:

![meteor-output](https://cloud.githubusercontent.com/assets/16913311/13233040/bd72c074-d966-11e5-8204-a65f85b11961.jpg)

This is the output for the static version:

![static-output](https://cloud.githubusercontent.com/assets/16913311/13233050/c891ce82-d966-11e5-83b4-019aedaa2568.jpg)

Could there be a load-order problem? Are there any rules on when `registerElement` should be called? I tried placing the static scripts at the end of the page, which changes the output order, but still renders the same thing (broken, not like the Meteor version).

**Comment by ghost** [comment]
Moved to http://stackoverflow.com/questions/35564154/why-doesnt-custom-element-work-properly-on-static-page
