### ISSUE TITLE
cloneNode on ShadowRoot interface should throw NotSupportedError instead of DATA_CLONE_ERR

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#393]
That's what `importNode` throws so we should be consistent and throw `NotSupportedError` instead.

**Comment by annevk** [comment]
We should probably fix this directly in the DOM Standard given that https://dom.spec.whatwg.org/#dom-document-importnode does so too.

**Comment by rniwa** [comment]
Yeah, it's a bit odd that only cloneNode checks this condition in the shadow dom spec.

**Comment by rniwa** [comment]
WebKit does this as of http://trac.webkit.org/changeset/196998.

**Comment by annevk** [comment]
I fixed this in the DOM Standard. Leaving this open so the corresponding statement in the Shadow DOM specification can be removed.

**Comment by rniwa** [comment]
Great.  Thanks, @annevk!
