### ISSUE TITLE
Adding Declarative Import

### ISSUE THREAD

**Issue by dret** [WICG/webcomponents#398]
has there been a discussion about adding declarative ways of using the "HTML Import" functionality, i.e. with simple HTML elements? it could be something similar in design to XInclude.

**Comment by hayatoito** [comment]
Could you elaborate? I appreciate if you have the concrete example.

**Comment by dret** [comment]
On 2016-02-26 11:59 , Hayato Ito wrote:

> Could you elaborate? I appreciate if you have the concrete example.

generally speaking, i am asking about binding the functionality to 
markup as well, not just to an API. this is what XInclude has been doing 
for the XML world: https://www.w3.org/TR/xinclude/

for HTML, you very likely don't want the exact same syntax, but 
something similar. something like

<include href="..." mode="html"/>

for including an external snippet of HTML.

<include href="..." mode="text"/>

could be used to include a file as plain text (i.e., as a text node).

and finally, fallback behavior could look like this:

<include href="...>
   <p>it seems like the include failed...</p>
</include>

none of this probably is exactly what the markup really should look 
like, but that's the general idea behind this issue.

**Comment by davidmaxwaterman** [comment]
It reminds me of this :

https://customelements.io/chris-l/html-include/

**Comment by dret** [comment]
On 2016-02-26 16:03 , Max Waterman wrote:

> It reminds me of this :
> https://customelements.io/chris-l/html-include/

yes, this looks similar. i think there are several scripted versions of 
it. maybe it would be interesting to compare them in terms of features 
and adoption). looking further back, something as historical as IE5's 
"data islands" (which only supported XML includes) comes to mind.

**Comment by hayatoito** [comment]
I remember we had a similar discussion. Let me merge this with  https://github.com/w3c/webcomponents/issues/280.

**Comment by dret** [comment]
On 2016-02-29 2:17 , Hayato Ito wrote:

> I remember we had a similar discussion. Let me merge this with #280

yes, this looks like the exact same discussion. i still think that 
having an "HTML include" facility would be nice, as also argued in that 
issue. but i do see the point that is made about the difference between 
import and include.
