### ISSUE TITLE
A negative tabindex on shadow host should be respected

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#399]
Related to the issue #375, both in the [current specification](https://www.w3.org/TR/shadow-dom/#focus-navigation) and in [the proposal](https://docs.google.com/document/d/1mNV2Z231SrAZuMJvBVNfVNHfULkMwUZOZ75vZM1K9zY/edit) in the issue #381, contents inside a shadow tree is treated as if its shadow host has the tabindex of 0.

However, when the shadow host has a negative tabindex, its contents should be not be in the sequential focus navigation order.

The `input` element doesn't place focus in its editable region when it has a negative tabindex for example, and it's very counterintuitive for the tabindex on an element to be ignored just because it contains a focusable element.

**Comment by hayatoito** [comment]
Yeah, I think we can agree on this change. We should skip an entire shadow tree if the host has a negative tabindex. I guess @TakayoshiKochi already have this behavior in his proposal clearly, or not?

That's actually what I wanted to change in v0, but it was too late to change. For v1, we should not do the same mistake.

**Comment by TakayoshiKochi** [comment]
Yeah, this was #86, which was merged to #105 then #126 :(
I'll try to incorporate the tabindex=-1 part to spec update, so probably we all agree on that?

@annevk @travisleithead

**Comment by annevk** [comment]
Makes sense that if a host is intentionally not focusable its descendants are not either.

**Comment by TakayoshiKochi** [comment]
Let me merge to #375.
