### ISSUE TITLE
Add dfn.js

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#402]
https://resources.whatwg.org/ hosts a useful tool called dfn.js that lets you figure out where a particular defined term is referenced from. This makes it easier to find algorithms referenced through different names and makes it overall clearer how globally important something is.

I would love to see this added to Shadow DOM.

**Comment by rniwa** [comment]
Yeah, this will be a super useful addition to the spec.

**Comment by hayatoito** [comment]
Thank you. I did not know that. Let me use that.
