### ISSUE TITLE
Should HTML parser instantiate custom elements inside a template element?

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#406]
It seems that we'd instantiate custom elements inside a template element in the parser as things stand.  Is this intentional?  Is everyone okay with it?

@annevk @domenic @dglazkov @travisleithead

**Comment by dglazkov** [comment]
No, that shouldn't be happening. It would be bad if custom elements were waking up in templates. The template doc should have no registry (or an empty registry, as the v0 spec said).

**Comment by annevk** [comment]
Ah yes, this follows neatly from `template` element's contents having their own node document. That's great. And if we ever wanted to support this that would be through the registry API.

**Comment by annevk** [comment]
So OP is incorrect. As things stand we don't instantiate custom elements inside a `template` element.

**Comment by domenic** [comment]
It seems like someone could cause template elements to wake up though by doing `document.createElement("template").content.ownerDocument.defineElement(...)`. IIRC the template owner document is shared between all template elements.

That is probably something we want to disallow? Even though it goes against the idea of every document having a registry?

**Comment by dglazkov** [comment]
In the v0 spec, if the document has no registry, you can't register new elements. Would something like that work?

**Comment by domenic** [comment]
Sure, but the question is what documents should get registries. At the F2F we decided "all documents", but we were mainly thinking about allowing `document.implementation.createHTMLDocument(...)` to work. I imagine we all forgot about this use case, so "all documents" is probably not correct anymore.

**Comment by dglazkov** [comment]
Sounds about right. Maybe template doc is a special duck.

**Comment by annevk** [comment]
What is the problem with simply allowing this for `template` element documents (and other documents)? First I thought this would be problematic with XMLHttpRequest, but that document is only exposed after all network activity is over.

**Comment by rniwa** [comment]
> In the v0 spec, if the document has no registry, you can't register new elements. Would something like that work?

Ah, I see.  I think instead of making the document not having a registry, it's probably better for `defineElement` to exit early if the context object is the document for the a `template` element if we wanted to disallow that.

> What is the problem with simply allowing this for `template` element documents (and other documents)?

I don't have any problem with instantiating custom elements inside template elements so that authors can make `instanceof` check work on nodes inside a template element.  All builtin elements inside a template are "real" elements so it's rather odd for custom elements to not work that way.  (Note that I'm not saying that registry of template element's document should be shared with that of template's document).

There is an extra cognitive stress for authors to avoid doing expensive work or start fetching stuff over network inside custom elements created for a template.  But if the authors are calling `defineElement` on `template.content.ownerDocument`, then they better know what they're doing.

**Comment by travisleithead** [comment]
This is a problem for both instantiation via the parser, and for upgrade, right? I think I land on the side of not instantiating merely because the expectation of template content in the first place is to deep-clone it for later use. The cloning process will [maybe?] instantiate a new custom element anyway--why do the work twice?

**Comment by domenic** [comment]
I tend to agree, but on the other hand if an author really did `document.createElement("template").content.ownerDocument.defineElement(...)`, they probably really know what they're doing. I'm not sure we should add an exception to the system specifically to prevent that from working.

**Comment by domenic** [comment]
This should be fixed by https://github.com/w3c/webcomponents/commit/58a2f7b6d1853b92001b5651228a8177447a7cb3 which gives template contents owner documents a null registry, so `defineElement` will throw on them, and the HTML parser will never instantiate them.
