### ISSUE TITLE
Travis build is always broken and seems completely useless

### ISSUE THREAD

**Issue by domenic** [WICG/webcomponents#407]
Every time I push something to a branch I get an email about how the Travis build failed. It's trying to do something with Ruby. There's not even a .travis.yml in this repository. Can someone with admin rights turn it off? @plehegar?

**Comment by rniwa** [comment]
I think we should just add `.travis.yml` instead.

**Comment by domenic** [comment]
Why? What would it build?

**Comment by rniwa** [comment]
There is a RSpec validation step.  It checks the meta data, etc... @plehegar can tell you about it.

**Comment by domenic** [comment]
Sure, if someone wants to actually set that up, sounds reasonable.

**Comment by rniwa** [comment]
@siusin

**Comment by annevk** [comment]
Is this issue still relevant or can it be closed?

**Comment by siusin** [comment]
Yes please, the script works well for the recent commits.

**Comment by annevk** [comment]
Yes it's still relevant or yes it can be closed? I'm guessing the latter?

**Comment by siusin** [comment]
Oh, sorry, please close this issue.
