### ISSUE TITLE
Clarify shadow DOM algorithms 

### ISSUE THREAD

**Issue by kjax** [WICG/webcomponents#410]
My group has found shadow DOM spec to be confusing about the order that the slotting and flattening algorithms are applied.  Is each step applied to all of the nodes before continuing to the next step?

Perhaps changing to this statement:
The slotting algorithm must be used to determine the assigned slot for **each** node and must be equivalent to processing the following steps

**Comment by hayatoito** [comment]
Thank you for the suggestion!

**Comment by hayatoito** [comment]
I have also made the Flatting Example more readable at https://github.com/w3c/webcomponents/commit/b8567cfcecb582aab9e40574ac480025fa97bd63

If you have any other idea which make the spec understandable, I appreciate it. Any minor fixes are welcome.
