### ISSUE TITLE
Shadow DOM and comment nodes

### ISSUE THREAD

**Issue by kjax** [WICG/webcomponents#411]
Currently a node is called slot assignable if it is either Text or Element.
knockout.js uses comment nodes as "virtual elements"
Would it be possible to add comment node to the list of slot assignable?

**Comment by rniwa** [comment]
We just removed the support for assigning those nodes in the issue 351.  I would not like to reverse it.

**Comment by hayatoito** [comment]
Yeah, according to #351, WebKit has a technical constraint.
I do not have a strong opinion, however, if WebKit can resolve a technical constraint, I'm totally fine to make all nodes _slots assignable_. It's up to WebKit, as of now.

@rniwa, I'm assuming that a technical constraint still exists in WebKit, right?

**Comment by rniwa** [comment]
Yes, if there is a strong use case for assigning comment nodes, we could add the support though.

**Comment by annevk** [comment]
What exactly is the constraint? It seems like if we do more than Element, we should do Element and everything CharacterData. E.g., there's a strong chance CDATASection makes a comeback, would be weird to support Text but not CDATASection.

**Comment by rniwa** [comment]
@annevk the constraint is that we don't currently have a mechanism to assign anything but Element and Text node at the moment, and adding the support for other types of Node is rather difficult.

But I would be okay with supporting it if there is a valid use case (i.e. end user / developer scenario) that requires those node types to be assigned to a slot.

**Comment by annevk** [comment]
Well, if you still support CDATASection... that's semantically equivalent to Text. It would be very weird if CDATASection didn't end up in the flattened tree. And I guess the use for Comment / ProcessingInstruction is to hack around limitations of the DOM. Annotations that can be used for further processing as per OP.

**Comment by hayatoito** [comment]
@kjax, could you elaborate the use case? If that's reasonable, let me reverse the change and make every node slots assignable. That will make things simple in terms of the spec, and make you happy.

**Comment by annevk** [comment]
I don't think every node should have this. There's no reason to assign, e.g., a ShadowRoot or DocumentType object, is there?

**Comment by hayatoito** [comment]
Yeah, they never be assigned to a slot.
I meant that I will relax a _necessary condition_ - called _slot assignable_. Even if ShadowRoot or Document meets the relaxed necessary condition, they never be assigned to a slot, as per the slotting algorithm. That does not change.

**Comment by annevk** [comment]
I meant that I don't think we should give every node an `assignedSlot` property. Just those that need it. But maybe I still misunderstood you.

**Comment by hayatoito** [comment]
Ops. I understand. Regarding IDL, I am going to revert this commit: https://github.com/w3c/webcomponents/commit/f986bf803e6bf092a2f23ea08359abd8722f9aac. Thus, only NonDocumentTypeChildNode will have `assignedSlot` property.

**Comment by kjax** [comment]
After further analysis I determined that the knockout.js case that I was worried about does not need the comment nodes to be assigned to slots.  While knockout does use comments as active nodes, all of the action occurs in the light DOM.  There is no need for the comments to appear in the flattened tree.

However please confirm that CDATA is treated as text.

**Comment by hayatoito** [comment]
@kjax Thanks. The most reasonable choice for us is to just revert this change: https://github.com/w3c/webcomponents/commit/f986bf803e6bf092a2f23ea08359abd8722f9aac.

I'm assuming that WebKit would be okay, though it might be painful. I'm not 100% sure.

**Comment by rniwa** [comment]
I think what https://github.com/w3c/webcomponents/issues/411#issuecomment-193506989 says is that we still don't need to assign non-Text/CDATA/Element nodes to a slot.  I think we would be fine with supporting CDATA.

**Comment by hayatoito** [comment]
Yeah, supporting CDATA is the bottom line.

Do you still think that we have to restrict other nodes types, such as comment nodes?

**Comment by rniwa** [comment]
We would still prefer that.  Since CDATASection is a subclass of Text, it's given that we support both Text and CDATASection nodes by the fact every CDATASection is a Text node.

**Comment by hayatoito** [comment]
Then, we do not have to do anything, right?
At least, until WebKit can resolve a technical constraint, which is unlikely to happen soon, I am assuming.

**Comment by hayatoito** [comment]
Let me close this issue without any action.

**Comment by rniwa** [comment]
Yup, thanks.

If someone comes up with a valid use case for assigning `Comment` and `ProcessingInstruction` to a default slot, then we can re-visit this.
