### ISSUE TITLE
Remove `Callback` suffix from custom elements callbacks

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#414]
As discussed during Jan F2F and the issue #362, we should not have "Callback" suffix at the end of each lifecycle callback.

Authors and frameworks shouldn't be overloading the meaning/semantics of those callbacks for other purposes (since this is a new feature in the first place) and authors prefer shorter names according to https://github.com/w3c/webcomponents/issues/362#issuecomment-179729388.

**Comment by annevk** [comment]
I thought the conclusion from the F2F was that we'd add *Callback back because we didn't end up with Symbol names and therefore that suffix would help to reduce ambiguity.

**Comment by rniwa** [comment]
Huh, my recollection was that we decided that this whole idea of trying to not populate the namespace of a class is not worthwhile because frameworks / libraries shouldn't be reusing it for other purposes, and it's better for all custom elements to use the same callback names.

**Comment by annevk** [comment]
If we are using strings for names they need to be sufficiently long that we can add new ones in the future without much trouble. E.g., it's fairly likely for a framework to create an `adopt()` method, making it difficult for us to introduce an adopt callback later.

**Comment by domenic** [comment]
Yeah I also recall us saying that the Callback suffix would need to stay. Maybe it even made it into the minutes.

**Comment by annevk** [comment]
https://www.w3.org/2016/01/25-webapps-minutes.html#item04 does say so indeed.

**Comment by rniwa** [comment]
Yeah, now I recall that discussion. Closing this.

**Comment by devingfx** [comment]
Hi,

@annevk 
> we didn't end up with Symbol names and therefore that suffix would help to reduce ambiguity.

Why do you didn't end up with Symbol names btw? IMHO Symbols are exactly suited for the purpose of 
> would help to reduce ambiguity.

**Comment by annevk** [comment]
Keeping things simple, I think. Been a while...

**Comment by rniwa** [comment]
I think the argument was that symbol doesn't buy us anything because there isn't any existing custom elements in the wild, and if we required people to type in something like `[customElements.connected]` then that's no much better than `connectedCallback`.

**Comment by devingfx** [comment]
With ES6+ object destructuring it will become less a pain to do so:
```es6
let { connected, attributeChange, disconnected } = customElements.symbols;

export class MyClass extends HTMLElement {
    [connected]() {}
    [attributeChange]() {}
    [disconnected]() {}
    normalMethod() {}
}

// or an object in well known symbols

let { connected: onAdded, observedAttributes: attrs, disconnected: onRemove } = Symbol.elements;

export class MyClass extends HTMLElement {
    static get [attrs]() { return ... }
    [onAdded]() {}
    [onRemove]() {}
    normalMethod() {}
}
```
Still in plain old es5 you can write less than `[customElements.connected]` if you choose to:
```js
var S = customElements.symbols;
function MyClass() {}
MyClass.prototype = Object.create(HTMLElement.prototype);
MyClass[S.observedAttributes] = 'attr1 attr2 attr3'.split(' ')
MyClass.prototype[S.connected] = function() {}
...
```

This is highly customisable by web developpers using the Symbols.

**Comment by annevk** [comment]
We're not going to change it now so...

**Comment by devingfx** [comment]
Is the spec V1 final yet? Validated and immutable?

If not please, tell me how to get involved... And also please tell me the steps to get involved in specification process as I'll like to praticipate ! At least for V2 ...
I can create real world proposal for you to validate (or not). 
I can understand that random comments on issues are not relevant...

Otherwise why not in V2? (this issue is not so relevant to me, but I have others breaking case that I'm cooking issues for)

I can read in this [wiki page](https://wiki.whatwg.org/wiki/FAQ#Is_there_a_process_for_adding_new_features_to_a_specification.3F), that new issues are to be opened in [whatwg/html](https://github.com/whatwg/html/issues) not here can you confirm that point?

**Comment by annevk** [comment]
v1 is more or less final yes. New issues can be filed here, whatwg/html, or perhaps whatwg/dom. Depends on a bit on what it is about. Here is probably best.

**Comment by domenic** [comment]
It's a bit more accurate to say that there's no real division between "v1" and "v2"; see https://wiki.whatwg.org/wiki/FAQ#What_does_.22Living_Standard.22_mean.3F to learn about the actual working mode. "Versions" are fiction in spec-land.

The things that are widely implemented and shipping are what will not change, and so far that's every part of the spec except customized built-in elements---although even those are under development in multiple browsers and so we'd need a very good reason to tell those browser vendors to throw away all the work they've done so far.

Sometimes we use "v1" as a shorthand for "things we wrote down based on a certain meeting and then spent a bunch of time finalizing" and "v2" for "things we're still thinking about", and I can understand how that's confusing for people new to this. Sorry about that.

In general we don't make breaking changes to the web, unless required for security, and even then it's a long hard process with lots of teeth-gnashing ([example](https://bugs.chromium.org/p/chromium/issues/detail?id=669800)).

**Comment by rniwa** [comment]
As far as I know, Chrome has already shipped v1 custom elements API to public in their stable release, so it's a bit too late to change this semantics.

**Comment by rniwa** [comment]
As far as I know, Chrome has already shipped v1 custom elements API to public in their stable release, so it's a bit too late to change this semantics. Although we've replaced v0 with v1 but that was because other browser vendors had a significant problem with it, and new API had some benefits (e.g. integration with ES6 class syntax). Also note that we've implemented the v1 API and turned it on by default on Safari Technology Preview.

In contrast, using `Callback` suffix was discussed multiple times in the past, and we had reached a consensus on this matter a while ago so unless there is a strong support from multiple browser vendors for making this change, I don't think it will happen.

**Comment by devingfx** [comment]
I know I arrive too late, I wish I could be aware of custom elements spec discussion earlier to partipate...

@rniwa I assume you discussed a lot on the subject! My first question was a "why not the symbols?" just to understand the decision, not to refute it ! BTW annevk answered it: for simplicity...

@domenic If I understand well: 
- there is no such thing that spec version, a thing is specified or not.
- the web component are specified officially, so authors can use it from today.
- the web component spec is open to changes that wont break any already designed specs.

Thank you very much guys for taking time to explain this points to me!

**Comment by rniwa** [comment]
See https://github.com/w3c/webcomponents/issues/414#issuecomment-274183053

The question is why use symbols for this purpose? If we are worried about name conflicts, then that's kind of a moot point because we can't make existing framework-dependent component a custom element.

There was also a school of thought that it's actually desirable for all classes defining a custom element to have the same set of methods instead of making them customizable.

**Comment by devingfx** [comment]
I have to admit that I was thinking in the past:
```
Don't care of name conflict, if you use my library, you should know the names I provide! 
Even if it's overrided ones! And take care of your naming to don't conflict with the library.
```
But I changed my mind since I read about new `Symbol` type. The point is not about naming conflict, but more about namespacing. Kinda "hide" some API for user to don't worry about it.
A library author may want to configure the custom element with this symboled method or property, and expose only high level API for the component that internaly use the symbols. The component inspection would not show the symbols property ( I know that it's still accessible with `Object.getOwnPropertySymbols` ) because it need's the user to use some component API and not the native directly (let's say for custom behavior).

PS: I continue to answer here because the discussion about symbols it's interesting, but I don't really mind of symbolised CEReactions ...

**Comment by devingfx** [comment]
@rniwa 
> that's kind of a moot point because we can't make existing framework-dependent component a custom element.

May you please explain this point? I'm afraid that I don't understand why ?
