### ISSUE TITLE
I need clarity on the document license before I can continue editing

### ISSUE THREAD

**Issue by domenic** [WICG/webcomponents#415]
The custom elements spec says

> Copyright © 2016 W3C® (MIT, ERCIM, Keio, Beihang). W3C liability, trademark and permissive document license rules apply. 

linking to

https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document

which is an unorthodox license that seems to want to impose a lot of restrictions on how text reuse must be marked.

I would of course prefer CC0, or failing that CC-BY. But if we must stick with the license I need a clear statement of how the work must be cited, i.e. what must appear in the acknowledgements. The linked page at https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document is not clear to me. I know for CC-BY I can attribute like 

> The image of two cute kittens in a basket used in the context menu example is based on a photo by Alex G. (CC BY 2.0)

but that document seems to want me to include a lot more notices (perhaps unacceptably many) when using the text elsewhere. Since this document is largely destined for upstreaming into other specs, this is a real concern.

@plehegar can you clarify whether we can change the license, or failing that whether https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document has a short (one-sentence) attribution form like CC-BY does?

I cannot make any further edits until this is resolved favorably.

**Comment by hayatoito** [comment]
I think the same issue also applies to other specs, Shadow DOM and HTML Imports.
AFAIK, we have never tried to use different licenses for these specs. They would have used the same license.

**Comment by domenic** [comment]
I have received confirmation from Google legal that the following will suffice:

> Part of the revision history of the custom elements feature can be found in [the w3c/webcomponents repository](https://github.com/w3c/webcomponents),  which is available under the [W3C Permissive Document License](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document).

This would be placed in the Acknowledgements section, underneath the destination spec's copyright declaration.

Our lawyer pointed out that https://www.w3.org/Consortium/Legal/IPR-FAQ-20000620#software_publisher (especially item 2) makes it clearer that this is sufficient.

Editing can now continue! (After lunch.)
