### ISSUE TITLE
The algorithm "invoke callbacks" must halt as soon as one of callbacks throw an exception

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#421]
The algorithm to [invoke callbacks](https://w3c.github.io/webcomponents/spec/custom/#dfn-invoke-callbacks-in-element-queue) should halt as soon as one of these callbacks throw an exception, and re-throw that exception.  Otherwise the whole idea of re-throwing exceptions from DOM API is non-sensical.

This has an interesting implication that if there were multiple unresolved elements queued up for upgrades and one of constructor calls throws an exception, then all subsequent elements would never be upgraded.

**Comment by rniwa** [comment]
@annevk @bzbarsky @travisleithead @domenic @dglazkov

**Comment by annevk** [comment]
I'm not sure that makes sense. E.g., when setting `innerHTML` the operation will have succeeded by the time you propose we throw an exception from the setter. It makes more sense to me to handle these callbacks similar to event listener callbacks and use the "report the error" mechanism. And therefore not failing when a callback throws an exception either.

**Comment by rniwa** [comment]
Indeed, that would avoid leaving some elements unresolved due to one of prior elements failing to upgrade.  I'm fine with that approach too but we should definitely update the spec to do that though.

**Comment by domenic** [comment]
Yeah, there's an older bug on this somewhere I think. "Report an exception" makes the most sense to me.
