### ISSUE TITLE
Should :unresolved apply to elements that failed to upgrade? 

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#422]
According to the [current spec text](https://w3c.github.io/webcomponents/spec/custom/#unresolved-element-pseudoclass), `:unresolved` should only apply to custom elements on which the constructor had yet to be invoked upon.

This would mean that if `:unresolved` would stop applying to custom elements that had failed inside a constructor (e.g. resulted in an exception).

Also see the issue #421.

**Comment by annevk** [comment]
Perhaps it would make more sense to have a CSS selector that takes an argument. E.g., `:resolved(no)`, `:resolved(yes)` (yes is the default value if no argument is passed), `:resolved(fail)`. @tabatkins, @fantasai?

**Comment by domenic** [comment]
I think it seems totally fine to say that something that fails to upgrade is unresolved/unupgraded. I don't see a need for a more granular distinction. Failing to upgrade should be a very exceptional thing that is figured out at development time; nobody should be asking a designer to design a "our programmers made an error and this widget is broken" UI that would need a `:resolved(fail)` selector.

**Comment by rniwa** [comment]
I'd also prefer if the spec explicitly defined `upgraded` or `resolved` flag for each element which is set and cleared at an explicit time.  As it's currently written, it's ambiguous as to whether we should be clearing the flag before `Construct` call or after.

**Comment by domenic** [comment]
Yes, I'm working on that.

**Comment by domenic** [comment]
I am going to close this in the direction of the current spec (failed upgrades = does not match :unresolved) and open a new tracking issue for adding an explicit "upgraded" or "resolved" flag. Please reopen and tag "needs consensus" if you think we should change that, or add a third state.

**Comment by tabatkins** [comment]
Sounds good to me.

(Note for the future that a selector taking arguments is totally reasonable, even if it has a default form that doesn't - see  [:drop / :drop()](https://drafts.csswg.org/selectors/#drag-pseudos) for an example.)

**Comment by rniwa** [comment]
I want `:unresolved` to apply to the elements that have failed to upgrade.

**Comment by domenic** [comment]
Wow, yeah, I misphrased that. I meant to say it should match (like the current spec says).
