### ISSUE TITLE
Custom elements need an explicit "upgraded" or "resolved" flag

### ISSUE THREAD

**Issue by domenic** [WICG/webcomponents#425]
This will be used for CSS to match against.

Questions:
- Is it "upgraded", or "resolved"? See #418.
- Are there any concerns with setting this flag immediately upon upgrade? (That is, at nanotask time.) It seems like it would cause sync layout, which is usually not great?

**Comment by annevk** [comment]
@jakearchibald suggested having a promise attached to this state too.

**Comment by jakearchibald** [comment]
Example use-case: hiding (opacity 0) a component until all the child components it uses in its shadow DOM upgrade

**Comment by domenic** [comment]
Settled on "defined" in https://github.com/w3c/webcomponents/commit/243281977b99838528e838e534f463f1426c9515 since the method is indeed named defineElement. Please see https://w3c.github.io/webcomponents/spec/custom/#dfn-element-defined and use the dfn.js popups to follow links.

If there's interest in a new API for knowing when an element (or tag name, perhaps?) becomes defined, let's file a new issue proposing that.
