### ISSUE TITLE
Integrate events with "get the parent" model

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#429]
https://dom.spec.whatwg.org/ now defines "get the parent" as a way to build up an event path. I think it would be great if we defined in Shadow DOM how node's "get the parent" algorithm would be altered to account for Shadow DOM.

If that requires more hooks than I accounted for please let me know.

**Comment by hayatoito** [comment]
Done at https://github.com/w3c/webcomponents/commit/0457494032c6668291319df843a7a62faca214c5

Do you think we have to mention `Window` object in "get the parent" for Node?
I mean, if the root node of a document tree is given as an input for "get the parent", should we return a "Window" object?

I think we should not return a  `Window` here and let other specs to handle it.

**Comment by annevk** [comment]
The way the DOM standard handles this is by giving document its own "get the parent" algorithm. You only replace the algorithm for nodes in your patch so whenever document comes up it should still do the right thing as far as I can tell.

**Comment by hayatoito** [comment]
Ah. Now I understand the intention of "Nodes and _documents_ override the get the parent algorithm."
That makes sense.
You are ahead of me. :) :+1:
