### ISSUE TITLE
Should relatedTargetScoped flag be set on mousedown/mouseup events?

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#433]
Do we really want `mousedown` and `mouseup` events to have `relatedTargetScoped` flag set?  The following [definition in the current spec](http://w3c.github.io/webcomponents/spec/shadow/#dfnReturnLink-0) seems to indicate any event that uses [`MouseEvent` interface](https://w3c.github.io/uievents/#mouseevent) to have this flag set:

> A trusted event's relatedTargetScoped flag must be initialized to true if the event has a relatedTarget property

Is this an intentional (that any mousedown/mouseup would not propagate out of a shadow root)?

**Comment by hayatoito** [comment]
`mousedown` and `mouseup` events has a _non-null_ related target?

> if the event has a relatedTarget property

I think this should be:

> if the event has a non-null relatedTarget property value.

**Comment by rniwa** [comment]
Yeah, that makes more sense to me.

**Comment by rniwa** [comment]
On my second thought, other event such as `mousemove` can also have `null` so I'm not certain if that's right either.

**Comment by hayatoito** [comment]
If it's `null`, I think it's okay not to set relatedTargetScoped flag to true. This does not affect the actual event path, anyway. The observable difference is the value of Event.relatedTargetScoped flag, which is a minor issue, I think.
