### ISSUE TITLE
Group registry related terminology under a heading

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#437]
Currently it is under the "Custom Elements" heading (should maybe be "Custom elements" to match style of documents it'll be merged into). However, the paragraphs that describe it are not all adjacent. I guess this is done to first introduce the concepts before the other concepts that reference them, but it makes it harder to figure out what the model of a registry is.

**Comment by domenic** [comment]
In general the "Custom Elements" heading is a grab-bag of things I haven't figured out where they'll be put when migrating to HTML/DOM. The resolution of this in particular will depend on how I solve #369.

**Comment by domenic** [comment]
This has all been pretty drastically reorganized. The concepts are split between:
- https://w3c.github.io/webcomponents/spec/custom/#custom-elements-core-concepts
- https://w3c.github.io/webcomponents/spec/custom/#custom-elements-api
