### ISSUE TITLE
Open/closed is associated with ShadowRoot, not shadow tree

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#440]
That's how I ended up specifying it in the DOM Standard: https://dom.spec.whatwg.org/#shadowroot-encapsulation-mode. Trees are just a concept used to define traversing, they don't really carry state. The nodes carry the state.

**Comment by hayatoito** [comment]
Yeah, having _something_ in ShadowRoot is better than having _something_ in a tree. I support it.

**Comment by hayatoito** [comment]
Closing as per https://github.com/w3c/webcomponents/commit/aa057264bee22d2ebde0ba128f19db77e5b02ae2#commitcomment-16759302
