### ISSUE TITLE
Move innerHTML from ShadowRoot to DocumentFragment?

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#441]
If we're going to support this, why not support it directly on `DocumentFragment`?

**Comment by domenic** [comment]
People have been asking for this for a long time: https://lists.w3.org/Archives/Public/public-webapps/2011OctDec/0663

**Comment by domenic** [comment]
See https://lists.w3.org/Archives/Public/public-webapps/2011OctDec/0766.html for some of the complexities

**Comment by annevk** [comment]
The advantage from it being on `ShadowRoot` is that there's a context element? I guess that makes sense.

**Comment by hayatoito** [comment]
Yes, we can use the shadow host as the context object.

**Comment by hayatoito** [comment]
Let me close this.

**Comment by annevk** [comment]
Sorry for forgetting about that. I guess we should add a note in the specification. Because if we ever introduce `new ShadowRoot()`, this would become problematic.

**Comment by hayatoito** [comment]
Yeah, I've added a note.
