### ISSUE TITLE
ShadowRoot innerHTML different from Element innerHTML

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#443]
Per https://w3c.github.io/DOM-Parsing/#widl-Element-innerHTML Element's innerHTML does not always use HTML's algorithms. It can use those of XML too. Is there a reason ShadowRoot's innerHTML is different here? I think ideally we make these work the same way.

**Comment by hayatoito** [comment]
I do not think there is a reason. I guess the definition of Element's inner HTML diverged since the shadow dom spec referred to it.

They should work the same way.

@dglazkov , just in case.

**Comment by dglazkov** [comment]
Should just work the same way.
