### ISSUE TITLE
Upgrades need to run attributeChangedCallbacks and connectedCallback

### ISSUE THREAD

**Issue by domenic** [WICG/webcomponents#450]
Right now upgrades do not do this per spec, but I am pretty sure everyone wanted this.

This is a bit trickier than I might expect due to the way in which most places that do upgrade enqueue it. But maybe enqueuing from inside an enqueued callback works out fine. Need to work on it.

**Comment by rniwa** [comment]
I think we should enqueue them inside the concept [to upgrade an element](https://w3c.github.io/webcomponents/spec/custom/#dfn-upgrade-a-custom-element).
