### ISSUE TITLE
When does the base element queue matter?

### ISSUE THREAD

**Issue by domenic** [WICG/webcomponents#457]
@dglazkov @coonsta, could use your help here. Maybe @rniwa has also run into this while implementing.

I can't think of a situation in which the current element queue = the base element queue. I think maybe in the past that would be true during initial HTML parsing, but since we moved to synchronous construction during parsing that should no longer be the case.

Are there other cases that I am missing? It seems quite possible.

**Comment by dglazkov** [comment]
Base element queue is necessary when you have async parsing/construction. It's probably not necessary in the v1 world.

**Comment by domenic** [comment]
That is truly great news. Thanks @dglazkov!

**Comment by annevk** [comment]
Don't we have "async" parsing with `innerHTML`?

**Comment by domenic** [comment]
Sure, but in that case the element queue is the one created when entering the innerHTML setter.

**Comment by annevk** [comment]
I was thinking about `.innerHTML = "<base href=/x/><custom-x href=...></a><base href=/y/><custom y href=..>"` but I might be missing something.

**Comment by domenic** [comment]
Yes. In that case an element queue is pushed onto the stack when you enter the innerHTML setter. When you exit the innerHTML setter, the current element queue popped is the one you just pushed, and that is the one that gets executed.

**Comment by annevk** [comment]
The base element queue is not for pretending there is a different base URL for each element while we invoke its constructor and attribute callbacks?

**Comment by domenic** [comment]
The base element queue has nothing to do with base URL... are you assuming that it did just based on the presence of the word "base"?

**Comment by domenic** [comment]
It was a base (element queue), not a (base element) queue. It was the bottommost element queue in the stack of element queues (i.e. at the base of the stack).

**Comment by annevk** [comment]
I was assuming that. Sorry. I do now wonder what happens in those scenarios, but I guess I can test at some point.
