### ISSUE TITLE
Editorial: create an element's "new element" step

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#463]
This algorithm has 4 fairly equivalent steps to create a new element. Is there a way to do the top-level conditionals differently so this can be a shared step? It seems that might be a little cleaner.

**Comment by domenic** [comment]
I kind of doubt it, because the timing needs to vary for each. Happy to take a concrete suggestion or PR, but I think this is fine as-is personally.

**Comment by annevk** [comment]
It seems reasonably doable. Would have to think about it a little bit, but if you know it's not the 4.1 substeps (through a conditional that seems like it can be created) and you make sure "element interface" returns HTMLElement to handle the 4.2 substeps case you can allocate an element early (and an otherwise statement to handle the constructor dance).

Then the following steps can handle details around is="" attributes and whether or not to queue something.

**Comment by domenic** [comment]
The algorithm has changed a decent bit at this point. Still not a fan of this kind of change but you're welcome to make a PR. Untagging v1 to get it off my hotlist.

**Comment by annevk** [comment]
Mu.
