### ISSUE TITLE
createElement and createElementNS() should check is attribute

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#466]
We should throw an exception I think if it's not a "valid custom element name".

**Comment by annevk** [comment]
"create an element" should maybe also branch on that being true here and there? Let me know if you need a distinct issue for that or disagree.

**Comment by domenic** [comment]
Hmm yeah, good catches. So my fixes would be:
- createElement(NS) should check any present `is` dictionary member against the valid custom element name production
- All callers of "create an element" should be sure to only send valid custom element name type extensions.

**Comment by domenic** [comment]
Part of the question here is what the parser should do when encountering `<button is="x">`, or even `<button is="un-defined">`. Should it give a `HTMLUnknownElement`, or a `HTMLButtonElement`? I think I lean toward `HTMLButtonElement` since for `<button is="un-defined">` that is clearly what we want (to allow later upgrades).

**Comment by annevk** [comment]
I think the parser should do the same as it did before, but perhaps it should not treat `is` as a type extension when it's not valid.

**Comment by domenic** [comment]
OK, here are all the edge cases I can think of:
- non-browsing context document `<p is="x-b">`
- `<svg:g is="x-b">`
- `<custom-el is="x-b">`
- `<p is="x-b">` with `x-b` not yet defined
- `<p is="x-b">` with `x-b` not defined to extend `p`.
- `<p is="notvalid">`

I will attempt to make all these cases just treat `is` as a normal attribute. I believe that is consistent with the older less-precise verisons of the spec.

The alternative would be turning the result into HTMLUnknownElement.
