### ISSUE TITLE
Editorial: inconsistent use of authors/developers

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#470]
I suggest to stick with developers throughout and use "developing" rather than "authoring".

**Comment by domenic** [comment]
HTML uses authors. So I am trying to stick with authors for those sections. I can ensure the DOM sections use developers though.

**Comment by annevk** [comment]
Okay, I think those sections are not consistent either since I was reviewing those today. E.g., https://w3c.github.io/webcomponents/spec/custom/#custom-element-conformance uses "authoring" and "developers".
