### ISSUE TITLE
Element interfaces

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#472]
The way `define()` and element interfaces are defined, it seems like you cannot use a type extension for a custom tag. Is that intentional? I thought that was something we would allow.

**Comment by domenic** [comment]
No, this was intentional and has always been the case, I am pretty sure. I can check old spec versions though. I think there's even a closed bug asking for this feature.

**Comment by annevk** [comment]
https://www.w3.org/TR/2016/WD-custom-elements-20160226/ I can't really find it saying anything one way or another.

I think it'd be useful to have a sentence saying that these are mutually exclusive, if they indeed are.

**Comment by domenic** [comment]
That link contains

> If both types of custom element types are provided at the time of element's instantiation, the custom tag MUST win over the type extension.

so it seems like they are mutually exclusive. I wonder if that's correctly implemented in the element creation stuff though. Related to #466 which I am about to embark on fixing.
