### ISSUE TITLE
define() could use [[GetPrototypeOf]]?

### ISSUE THREAD

**Issue by annevk** [WICG/webcomponents#473]
Any reason it doesn't? Or even simply grab the [[Prototype]] internal slot value?

Might be worth pointing out why if I'm not missing obvious and this was intentional.

**Comment by rniwa** [comment]
You mean in step 11: "Let prototype be Get(constructor, "prototype"). Rethrow any exceptions."?

What we need to get here is `CustomElement.prototype`, not `CustomElement.__proto__` which is what `[[GetPrototypeOf]]` returns.

**Comment by annevk** [comment]
Aaah right, we're looking at the constructor. Thanks!
