### ISSUE TITLE
Consider simpler alternative to the "type extension elements" 

### ISSUE THREAD

**Issue by jarek-foksa** [WICG/webcomponents#478]
The concept currently known as **type extension elements** is rather complicated. Could it be replaced with something simpler that relies on composition rather than inheritance?

I would just define a simple extension mechanism that allows authors to augment elements. For example, first define the extension:

``` js
  class MaterialButtonExtension {
    constructor(button) {
      this._button = button;
      this._shadowRoot = this._button.attachShadowRoot();
      this._shadowRoot.addEventListener("pointerdown", () => ...);
    }
  }

  document.defineElementExtension("material-button", MaterialButtonExtension);
```

Then use it:

``` html
  <button extension="material-button"></button>
```

Major differences from the current approach:
1. No `createdCallback()` - extension constructor is always called after the element has been fully setup.
2. No `attributeChangedCallback()` - extension author can use mutation observer.
3. Extension can be added to standard elements, as well as to the custom elements.
4. Extension is not bound to any specific element name or class (though its name might suggest that it is intended to work only with e.g. buttons)

**Comment by annevk** [comment]
I'm confused, the specification doesn't have `createdCallback()`.

**Comment by domenic** [comment]
If there's no lifecycle callbacks, there's no point in the feature at all, and you might as well just build this in user space. The entire point of type extensions is to give you lifecycle callbacks on existing elements.

**Comment by domenic** [comment]
I also think it's exceedingly late in the process to propose such overhauls of the existing agreed-upon and already-prototyped design.

**Comment by jarek-foksa** [comment]
@annevk Right, I was thinking about the earlier definition that didn't rely on constructors.

After having thought about it more, the API that I proposed doesn't really look that much simpler than what is currently in the spec (while being much less powerful), so never mind.
