### ISSUE TITLE
 {DocumentOrShadowRoot or Slot}.activePath

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#479]
The context is https://github.com/w3c/webcomponents/issues/358#issuecomment-202655660

**Comment by rniwa** [comment]
We don't support this API proposal as documented in https://github.com/w3c/webcomponents/issues/358.

**Comment by annevk** [comment]
We decided to close this at the Tokyo F2F. If there continues to be a need for this we'll need a new issue with a concrete outline of the problem so we can figure out a good API.

**Comment by tomalec** [comment]
To avoid compatibility problems with already shipped API, it could be better to propose new API, like `.activePath` instead of changing the current one.
