### ISSUE TITLE
Where is the spec?

### ISSUE THREAD

**Issue by EisenbergEffect** [WICG/webcomponents#481]
I was recently reading a version of the custom elements spec that involved changes in the callback names, registration api, etc. I've been searching for that again and haven't been able to find it. The readme here points to a version of the spec which has the apis I'm familiar with, but which I thought were recently changed. Can someone point me to "current" specification for custom elements?

Also, can anyone shed any light on the changes? Is there a summary of the changes anywhere and some explanation? Some of them seem sensible but other changes seem problematic to me, so I'd like to get an understanding of the rationale involved.

**Comment by domenic** [comment]
See https://github.com/w3c/webcomponents/commit/750542cf636319d8438ab28bf0a0dabb4749c1b5. We are in the process of upstreaming to the DOM and HTML Standards, and should have a better answer for you within a day or so.

The rationales are documented in the commits and in this very issue tracker.

**Comment by EisenbergEffect** [comment]
@domenic Thanks. I'll certainly go through the commits, just wanted to check if there was a summary somewhere to ease the process :smile: Would you mind pinging this issue when the upstreaming is done? Thanks for the work you all are doing!

**Comment by chaals** [comment]
@EisenbergEffect We put the more recent spec content back in place, so you can easily find it where it was again

**Comment by EisenbergEffect** [comment]
Beautiful. Thank you very much for the quick turn around on that. I'm presenting web components at a major conference in one week. I really wanted to have my information accurate to the latest, so this helps tremendously. Again, thank you!

**Comment by domenic** [comment]
> I really wanted to have my information accurate to the latest, so this helps tremendously. Again, thank you!

I would not refer to this spec then, as it was not produced by a member of the Web Platform working group and so its process/IPR status is unclear. Instead, refer to https://github.com/whatwg/dom/pull/204 and https://github.com/whatwg/html/pull/1012.

**Comment by EisenbergEffect** [comment]
@domenic Can you clarify that a bit more? Are you basically saying to point them towards the whatwg DOM spec rather than the custom elements spec linked above?

**Comment by domenic** [comment]
@EisenbergEffect the DOM spec contains supporting infrastructure; the HTML spec will contain (as soon as that PR is merged---on the order of a day or two, certainly before your conference) the main definition of custom elements.

This repo now contains some monkeypatches to the DOM and HTML specs, but they were not produced under proper Process requirements, so their status going forward is in question. This repo will certainly not be maintained as we resolve the outstanding issues. And several editorial issues and minor bugs have already been fixed during the upstreaming pull requests (bugs especially around removing an element).

**Comment by EisenbergEffect** [comment]
Ok. Excellent. That makes sense. Thank you for the clarification.

**Comment by chaals** [comment]
Actually, this repo _will_ be maintained, so you will have the choice of a couple of specs that between them cover almost everything in the Web platform, or a modular set of specs that that let you look up stuff in more self-contained pieces.

Of course, modular and monkey-patch are parts of the same continuum - the difference being largely in the quality of writing and "information architecture". And which approach suits you depends on your needs.

**Comment by annevk** [comment]
Except that modular set of specs has been promised since whenever Jeff Jaffe joined W3C and not actually become any kind of reality. If I were a betting type of person…

Also, we all want modular, but getting there is hard, and taking features that are extensions of existing features and putting them in separate drafts is not any kind of modular architecture. It's a hack.
