### ISSUE TITLE
Make Slot.assingedNodes({flatten: true}) return an empty array if the slot is in a document tree

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#482]
Given that a flat tree now includes a slot, and a slot is `display: contents` by default,
I think we no longer needs to support "get distributed nodes" algorithm for a slot in a document tree.

Until now, "get distributed nodes" is required for a slot in a document tree because we have to construct the flat tree correctly, in case when the slot has a child node. Such child nodes are known as "fallback contents".

I am going to make Slot.asignedNodes({flatten: true}) return an empty array if the slot is in a document tree. It would make sense, I think.

**Comment by rniwa** [comment]
I don't understand this issue. You say we should return `null` in the title but then you say we should return an empty array in the comment.  Could you clarify?

**Comment by hayatoito** [comment]
It should be an empty array. :)

**Comment by hayatoito** [comment]
After thinking further, let me close this issue without any action.

We still need to support get distributed nodes for a slot, A, in a document tree because such a slot A can be assigned to another slot, B, in a shadow tree, where A's distributed nodes is required to get B's distributed nodes.

I thought that we do not need to calculate A's distributed nodes because it is observable only via A.assingedNodes({flatten: true}), but it is observable also via B's distributed nodes (and slotchange event, of course).

Then, we do not need to get any benefits by not supporting A.assignedNodes({flatten: true}... Let me close this.

Sorry for the noise. :(
