### ISSUE TITLE
Return constructor from customElements.define

### ISSUE THREAD

**Issue by jessetane** [WICG/webcomponents#484]
For aesthetic reasons, it might be nice to be able to do:

``` javascript
export default customElements.define('my-element', class extends HTMLElement { // ...
```

Currently this isn't possible though since define does not return anything. Any reason not to just pass constructors through?

**Comment by domenic** [comment]
This was discussed at the most recent F2F and decided against, although I don't quite recall the reasons. Maybe @rniwa does.

Personally I find this (and other "convenience" chaining patterns) distasteful as they violate [command-query separation](https://en.wikipedia.org/wiki/Command%E2%80%93query_separation).

**Comment by domenic** [comment]
Another consideration is that it's not clear that modules which declare custom element classes should be the same as the module that defines them. It may be a better pattern (not yet proven in the ecosystem) to simply export the class, and let the consumer decide what local name to use for that class in their document. So the pattern in the OP may be an antipattern.

**Comment by jessetane** [comment]
I see, thanks for the explanation. Good point about the local name issue, I hadn't thought of that. Closing since it sounds like this was already discussed.
