### ISSUE TITLE
Why allow shadow root style to access :host?

### ISSUE THREAD

**Issue by trusktr** [WICG/webcomponents#490]
Why is this allowed? It seems like if I place DOM from an unknown source in my shadow root that one of the main advantages would be encapsulating that unknown DOM so it can not escape the encapsulation. Likewise, I wouldn't want it to apply arbitrary style to my shadow host and have it escape the encapsulation in order to style the light-tree host.

What's the advantage of allowing `:host` access via CSS?

**Comment by rniwa** [comment]
The use case is for the component to style itself.  e.g. a toolbar component may want to set `display: block` with a border, puddings, and margins.

We've discussed the possibility of restricting the kind of properties `:host` accepts in the case of strong encapsulation, which involves a different realm for scripts.

**Comment by trusktr** [comment]
I think a better option is keeping styles in shadow roots encapsulated completely, with no option to style even the `:host`, and that a new feature for encapsulating styles on custom elements may be needed, but that raises questions which I'll post in #468 since it fits better there.

**Comment by hayatoito** [comment]
Let me close this issue.
