### ISSUE TITLE
Retargeting algorithm shouldn't set relatedTarget to null even when target and relatedNode are in two distinct disconnected trees

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#494]
It looks like the [retargeting algorithm](http://w3c.github.io/webcomponents/spec/shadow/#dfn-retargeting-algorithm) as currently spec'ed ends up setting `relatedTarget` to `null` if `target` and `relatedTarget` belong to two distinct disconnected trees.

More formally, let A be `target`'s tree and B be `relatedTarget`'s tree.  When A and B are distinct and disconnected from one another (that is, it doesn't share any [shadow-including inclusive ancestor](http://w3c.github.io/webcomponents/spec/shadow/#dfn-shadow-including-inclusive-ancestor)), then the current algorithm adjusts `relatedTarget` to `null`.

I don't think this is a Web compatible behavior as authors can clearly dispatch a mouse event with `relatedTarget` set to whatever node they please to today.

**Comment by rniwa** [comment]
@hayatoito @annevk @travisleithead

**Comment by annevk** [comment]
Note that `relatedTarget` might not participate in a tree either. I haven't studied `relatedTarget` in detail yet and I suspect I'll wait until next Monday since getting feedback from @hayatoito is invaluable.

**Comment by hayatoito** [comment]
My bad for not responding this issue...

I think the problem here is that we have not considered seriously how such a disconnected tree should be treated in Shadow DOM world so far. We have to make a decision.

I think the root cause is the definition of unclosed node:

> A node A is an unclosed node of a node B, if A's root is a shadow-including inclusive ancestor of B, or A's root is a shadow root whose associated mode is "open" and the root's host is an unclosed node of B.

We might want to extend this definition so that it includes the following condition too:

A node _A_ is _also_ an unclosed node of a node _B_ if:
- _A_'s root is not a shadow root, and
- _B_'s root is not a shadow root, and
- _A_'s owner Document and _B_'s owner Document are same.

WDTY? Does this make sense? Is it okay that A can _see_ B? (or vice-verse)

**Comment by annevk** [comment]
I don't think you need the third check there.

**Comment by hayatoito** [comment]
I see. Let me rewrite:

A node _A_ is also an unclosed node of a node _B_ if:
- A's root is not a shadow root
- B's root is not a shadow root

In other words, a _disconnected tree_ behaves as a part of a document tree in terms of _visibility_.

_visibility_ is not well-defined, but I hope that makes sense. :)

**Comment by annevk** [comment]
Yeah that makes more sense to me. We don't restrict relatedTarget to have the same node document today either.

**Comment by hayatoito** [comment]
Thanks.

Because `relatedTargetScoped` has not been upstreamed yet, let me try to update Shadow DOM spec, reflecting the conclusion.

**Comment by hayatoito** [comment]
Ops. I meant to add a comment in https://github.com/w3c/webcomponents/issues/486. 
Anyway, I will resolve both issues, #486 and #494, updating the spec.

**Comment by annevk** [comment]
I'm happy to take a PR upstream for this if you want to work on it.

**Comment by hayatoito** [comment]
That makes sense. Let me send a PR.
