### ISSUE TITLE
Umbrella bugs for shadow DOM related issues in other specifications for v1 API 

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#495]
This is the umbrella issue that tracks issues in other specifications that need to be addressed for v1 API:
- [HTML](https://github.com/whatwg/html/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+shadow%22+)
- [DOM](https://github.com/whatwg/dom/issues?q=is%3Aissue+is%3Aopen+label%3Ashadow)

**Comment by annevk** [comment]
(Created a shadow label for DOM and updated your comment.)

**Comment by annevk** [comment]
Closing in favor of #661.
