### ISSUE TITLE
What does the construct stylesheets proposal mean for web developers?

### ISSUE THREAD

**Issue by straker** [WICG/webcomponents#501]
I've been trying to figure out the best way to implement a global style guide inside of a web component, and stumbled upon different issues in this repo that all mention how http://tabatkins.github.io/specs/construct-stylesheets/ will make style sharing easier. However, in trying to read the proposal I'm at a loss as to how it would be used to share styles. Could I get a layman's terms definition of what it does and how it would be used to share styles? Also, how is the proposal going, is it gaining traction?

The reason I ask is because I'm trying to implement a solution now that tries to predict the future and hopefully doesn't have to change too much when this problem is solved. At the moment, trying to add global styles across multiple web components is non-performant.

**Comment by rniwa** [comment]
This is not the right working group to track issue tracker for this.  [www-style](https://lists.w3.org/Archives/Public/www-style/) or [Bugzilla](https://www.w3.org/Bugs/Public/enter_bug.cgi?product=CSS&component=CSSOM) would be the appropriate forum to bring that up.
