### ISSUE TITLE
Voting for/against proposals

### ISSUE THREAD

**Issue by trusktr** [WICG/webcomponents#503]
Where, how? It would be nice to be able to leave a vote (for or against) a [proposal](https://github.com/w3c/webcomponents/tree/gh-pages/proposals) along with a comment associated with the vote, as well as to have the ability to modify the vote before the voting period expires. It'd be a discussion-based voting mechanism.

**Comment by domenic** [comment]
Interest in a proposal is not based on the number of people who like it, but instead on the reasoned arguments they present. You're best off presenting reasoner arguments.

**Comment by domenic** [comment]
The majority of documents in that directory are obsolete and reflect old discussions, by the way. Maybe we should do some deletion.

**Comment by chaals** [comment]
The question was where to put such comments.

The standard answer is that they should be raised as issues if they have not been - and if they have, your comments and +1/-1/etc should be a comment in the relevant issue.

As Domenic said, W3C does not generally work by voting, but by developing a consensus - which in turn is based on a reasoned technical argument that can get a consensus.
