### ISSUE TITLE
A proposal to help with testing/SEO/accessibility of closed ShadowDOM

### ISSUE THREAD

**Issue by BronislavKlucka** [WICG/webcomponents#505]
Hi as mentioned above, this is to help with those issues, not to solve them all, but how about adding

DocumentFragment Element.prototype.cloneShadowDOM()

I hope the signature is self-explanatory and the usecases are quite clear, since we've been discussing those issues for a quite some time.

This would allow closed ShadowDOM to remain closed, but allow crawling copy by script

Brona

**Comment by rniwa** [comment]
I'd prefer making `cloneNode` take a dictionary and make add this as an option instead if we can make the first argument polymorphic between `boolean` and a dictionary:
e.g. `element.cloneNode({shadow: true})`, `element.cloneNode({deep: true, shadow:true})`.

**Comment by annevk** [comment]
I don't understand "allow crawling copy by script". Are you suggesting that returns a deep copy of the shadow root that is now accessible and no longer a shadow root but a `DocumentFragment` node? Why would that be good?

@rniwa that makes more sense to me...

**Comment by hayatoito** [comment]
Yeah, I think the proposal does not solve an issue at all... :(
You will get yet another instance of "something which is closed". Both instances should stay closed.

**Comment by treshugart** [comment]
Is it possible to return a readonly tree from `shadowRoot` if it's `closed` instead of returning `null`?

**Comment by annevk** [comment]
@treshugart I don't know what that means. What is a readonly tree?

**Comment by treshugart** [comment]
Immutable representation of the current state of the shadow root.

**Comment by annevk** [comment]
1. That's not possible without inventing all sorts of new data structures.
2. That goes against what "closed" means.

**Comment by BronislavKlucka** [comment]
Appearently it was not as obvious as I assumed
The intent is not to clone shadowRoot, but the content of the shadowRoot

```
<x-user>
  #shadowRoot
     <h1>Brona</h2>
     <span>Czech Republic</span> 
</x-user>
```

var docFrag = document.querySelector("x-user").cloneShadowDOM()

docFrag:

```
#DocumentFragment
  <h1>Brona</h2>
  <span>Czech Republic</span> 
```

the copy is of the content of the shadowRoot, not the shadowRoot itself. No open, closed mode applies. It is regular DocumentFragment This allows for content to be crawled for testing/SEO/accessibility purposes while leaving the original closed shadowRoot intact

**Comment by annevk** [comment]
That is what I assumed you meant in https://github.com/w3c/webcomponents/issues/505#issuecomment-221177141. As far as I can tell that still leaks the kind of thing "closed" does not want to leak.

**Comment by BronislavKlucka** [comment]
I assumed, the reason for closed is "not to be tempered with", not necessary "not to be read"

**Comment by andyearnshaw** [comment]
Reading it means that your program could become dependant on the internal state of the tree, which defeats one of the advantages _closed_ provides.

For automated testing, consideration for shadow trees really needs adding to the WebDriver spec.  This has to be done regardless of any new methods that could be added to web components, so there's little point in adding them purely for that purpose.
