### ISSUE TITLE
customElements.define not working

### ISSUE THREAD

**Issue by hasan3ysf** [WICG/webcomponents#506]
I tried the example and the command line
`customElements.define("flag-icon", FlagIcon);` did not work with me, once I replaced it with the `document.registerElement("flag-icon", FlagIcon);` command, it worked fine!

**Comment by domenic** [comment]
This is the spec bug tracker, not the Chrome bug tracker. You may enjoy https://crbug.com.

**Comment by hasan3ysf** [comment]
So, at what browser this spec . define could work?

**Comment by rniwa** [comment]
As far as I know, no browser has fully implemented the latest custom elements API so none at the moment.
