### ISSUE TITLE
shadow tree -> iframe <- contentWindow.frameElement encapsulation issue

### ISSUE THREAD

**Issue by andyearnshaw** [WICG/webcomponents#507]
We provide a custom element that contains an iframe in a shadow tree.  Before the iframe content loads, we register custom elements and ensure our API is globally available to the child document.  For example's sake, it looks something like this:

``` html
<x-foo src="bar.html">
    #shadow-root
        <iframe src="bar.html"></iframe>
</x-foo>
```

As a closed tree, the user can't pierce the shadow tree from outside `<x-foo>`, but from inside _bar.html_, the user can access `window.frameElement`.  I think this is a mistake, as it undermines the encapsulation that the closed tree provides.

As a solution, I'd like to propose that if the iframe element is inside a shadow tree, `window.frameElement` returns the host.

**Comment by TakayoshiKochi** [comment]
The `<iframe>` is already in the closed shadow tree and `window.frameElement` returns it, as they are in the same node tree.

So this is working as expected.

**Comment by TakayoshiKochi** [comment]
If you think this way:
`"bar.html"` is given from outside the shadow tree, but it can peek inside closed shadow tree - therefore it breaks encapsulation

Then it's wrong.  What breaks the encapsulation is that you pull the `src` parameter from shadow host and put it in the closed shadow tree in the first place.

**Comment by andyearnshaw** [comment]
> The `<iframe>` is already in the closed shadow tree and window.frameElement returns it, as they are in the same node tree.

Right, I get that.

> Then it's wrong. What breaks the encapsulation is that you pull the src parameter from shadow host and put it in the closed shadow tree in the first place.

I get that too.  The problem is there's no specified way of transparently providing a custom iframe that is encapsulated from both sides.  In my situation the `contentWindow.frameElement` is useless to the content and is, essentially, a stumbling block to both our library and the content author.  For all intents and purposes of the content author, the custom element _is_ the frame element.

It's possible that in the frame setup, we could override the property (it's non-configurable in some browsers, though, so that's not feasible right now), but I feel that this would be better as the default.

**Comment by annevk** [comment]
Does sandboxing not cover this?

**Comment by andyearnshaw** [comment]
No, sandboxing would allow me to cut off access between the parent and child completely, but that's not the goal.  The goal is for the custom element to work in a similar manner as an iframe, leaving access between the parent and child alone whilst hiding the implementation details of the custom element.

**Comment by andyearnshaw** [comment]
Perhaps a better solution would be for `frameElement` to be `null` if it's in a shadow tree, leaving the custom element implementation to define a property.

```
window.frameElement;
// -> null

window.xfooElement;
// -> <x-foo ...>
```

**Comment by annevk** [comment]
I wonder what @smaug---- and @rniwa think of this scenario.

**Comment by smaug----** [comment]
what has this to do with shadow DOM? The document inside shadow iframe is loaded just like a normal document in iframe and has access to the containing iframe if that is accessible with non-shadow iframe.
So, this doesn't seem to have anything to do with shadow DOM encapsulation.

Perhaps iframe could have a property/attribute indicating that window.frameElement should be null in the contained window. Or hmm, still sounds more like a sandboxing thing. Should the iframe's document just be treated as a cross-domain document, so communication would need to happen via postMessage.

But it is a bit unclear to me what the goal is here.

**Comment by andyearnshaw** [comment]
> what has this to do with shadow DOM? The document inside shadow iframe is loaded just like a normal document in iframe and has access to the containing iframe if that is accessible with non-shadow iframe.
> So, this doesn't seem to have anything to do with shadow DOM encapsulation.

This is purely Shadow DOM related as this use case wouldn't appear in any other scenario.  Like I said in previous comments, the problem is that it's not possible to close off access to the shadow tree if you're loading third-party content in the iframe.  The content isn't relevant to the component and, whilst sandboxing it would be an option, you lose the benefits that a same-domain iframe would provide.

> Perhaps iframe could have a property/attribute indicating that window.frameElement should be null in the contained window. Or hmm, still sounds more like a sandboxing thing. Should the iframe's document just be treated as a cross-domain document, so communication would need to happen via postMessage.

No, as I explained in another comment, this doesn't allow me to match the features of an iframe.  I want to provide what is, essentially, a custom iframe that provides some extra features.  Just like a standard iframe, the component user would provide the `src` to be loaded in the shadow iframe.  I don't think that content should be able to access the shadow tree of the component, but I think that it should be able to access the parent as normal (via `window.parent`).  I'm not sure how I can make it any clearer than this.

I thought this might be able to work as a patch to the [HTML spec](https://html.spec.whatwg.org/multipage/browsers.html#dom-frameelement) along the lines of

> 1. If _container_ is within a (closed?) shadow tree, then return null and abort these steps.
> 2. Return _container_.

A component author can always provide access back to the shadow tree if necessary.

**Comment by annevk** [comment]
The thing is though is that shadow tree encapsulation is downwards. If you have a tree, encapsulation prevents access to descendants, but never to ancestors. What you are arguing for here is a different kind of feature from that perspective.

**Comment by andyearnshaw** [comment]
That's correct.  But I feel like my reasoning makes sense and it really only applies to Shadow DOM.

The easiest way to look at it is this: third-party content loaded in an iframe that is attached to a closed shadow tree exposes implementation details of the component via `window.frameElement`.  That seems like something you generally wouldn't want.

**Comment by smaug----** [comment]
Cross domain content in iframe cannot access frameElement. So I'm still wondering what use case you have in mind here.
Also, what kind of widget would need to pass pointer to itself to the iframe content.

This still feels like a sepatate feature from shadow dom, and something to opt-in.

**Comment by andyearnshaw** [comment]
I didn't mention cross domain content.  Just third-party.  Damn, this is hard 😅.  Instead of using an iframe, a developer would use my component to load same origin content.

> Also, what kind of widget would need to pass pointer to itself to the iframe content.

The use case for that is the same as the reason an iframe content page might want to access `window.frameElement`.  In this case, it doesn't make any sense to expose the iframe element and the other implementation details of the shadow tree.

> This still feels like a sepatate feature from shadow dom, and something to opt-in.

Like I said, it only applies to iframes in a shadow tree, so I don't see how it could be separate.  Opt-in, maybe, but that's easy if WebKit fix their non-configurable `frameElement` binding.  I was merely pitching the idea as this seems to me like the option we'd want to use to keep implementation details hidden.

**Comment by smaug----** [comment]
Why does it apply to shadow tree only? One can create all sorts of components without any shadow DOM usage.

**Comment by andyearnshaw** [comment]
Right, but if you're not using shadow DOM then you're probably not bothered about encapsulation or hiding the implementation details...

**Comment by smaug----** [comment]
> Opt-in, maybe, but that's easy if WebKit fix their non-configurable frameElement binding.

How would that help with anything? the iframe can load another same origin page and frameElement gets set back to the original value. Or document.open() used after parsing the page creates a new Window object too and ends up replacing frameElement.

I would expect that usually if one has iframe in shadow DOM for same-origin stuff, one actually wants to let that iframe contents to access the iframe, since that content is now part of the (possibly encapsulate) component. 
But adding something like iframe.setFrameElement(Element anyElement); doesn't feel too bad.
Then it would be up to the custom element ctor or some such to call that method if one wants to override the frameElement. And it would work whether or not iframe is in shadow DOM. No special cases there. Just working the same way consistently everywhere.

**Comment by andyearnshaw** [comment]
> How would that help with anything? the iframe can load another same origin page and frameElement gets set back to the original value. Or document.open() used after parsing the page creates a new Window object too and ends up replacing frameElement.

`document.open` can be overridden and the window _unload_ event can be handled.  I'm not sure how easy timing would be in the latter case but if `postMessage` is used it should be possible to rerun your initial setup on the iframe immediately after the new window is created.

> I would expect that usually if one has iframe in shadow DOM for same-origin stuff, one actually wants to let that iframe contents to access the iframe, since that content is now part of the (possibly encapsulate) component. 

Yeah I'm not sure about this since, typically, a component would use an iframe for either encapsulation—which is superseded by shadow DOM—or cross-origin/sandboxing where `frameElement` would be null anyway.  Now that we have shadow DOM, I can't imagine many use cases for an iframe inside a shadow tree that another shadow tree wouldn't solve, except for working like a custom iframe.  But maybe they're there and I just can't think of them right now.

> But adding something like iframe.setFrameElement(Element anyElement); doesn't feel too bad.
> Then it would be up to the custom element ctor or some such to call that method if one wants to override the frameElement. And it would work whether or not iframe is in shadow DOM. No special cases there. Just working the same way consistently everywhere.

I'm not against this idea, or one that looks at a larger picture by simplifying providing persistent custom elements, methods and properties to an iframe window (which would also cover other aspects of my use case).  Perhaps an event that triggered when the iframe's document object is created but before any parsing is done.

**Comment by rniwa** [comment]
So you want the iframe inside a closed shadow tree to be able to access to the tree outside the shadow tree?

I think the best way to do something like that would be put all your shadow tree's implementation into another closed shadow tree. e.g.

``` js
var outerShadow = outerElement.attachShadow({mode: 'closed'});
outerShadow.appendChild(document.createElement('iframe'));
var innerHost = document.createElement('div');
outerShadow.appendChild(innerHost);
var innerShadow = innerHost.attachShadow({mode: 'closed'});
innerShadow = ... // your implementation details
```

If that's not possible, then we need a new opt-in API for this. We can't change the behavior of all iframe like this because that would make it impossible for inner iframe to access shadow tree.

**Comment by annevk** [comment]
Closing this due to lack of follow-up.

**Comment by andyearnshaw** [comment]
Sorry, I thought I'd replied to this.  

I still don't think @rniwa's solution is great.  It partially solves the problem, but consider that I create a custom component that uses an iframe and I give that component to one of you guys.  The shadow dom used by the component is closed so that you can't manipulate the contents and I comfortably know that I can make updates without breaking your page.  You use the component to load some content but you don't quite like the style of the component, but instead of asking me to add a new feature, you decide to hack something in yourself.  From within the loaded content, you access `window.frameElement` and change something with the 'innerHost'.  Now updates to my component risk conflicts with your hack which could potentially break something.

An API to change where `frameElement` points to would be fine.  In reality, this is another part of the awkwardness of trying to do things with iframes before their document scripts run, which I raised over at https://github.com/whatwg/html/issues/2161.  If WebKit fixed the non-configurable issue and there were easier ways to customise iframes before script elements are run then I suppose this wouldn't be needed.  Unfortunately, that issue also went stale.
