### ISSUE TITLE
Best practices for styling web components

### ISSUE THREAD

**Issue by straker** [WICG/webcomponents#510]
What I'm hoping to gain from this question is an idea of what those who are in the trenches believe is/are the best practices for styling web components (taking into account future specs).

There seems to be two competing philosophies in terms of styling web components. On one hand, we have the philosophy that all web components should encapsulate all their styles and you should not allow style sheets to penetrate them (aka. a style guide). On the other had, there's the philosophy that shared / common styles should penetrate web components so a style guide on a site can style them.

At the moment, penetrating web components with a style sheet is difficult and not performant, but the [constructable stylesheet proposal](http://tabatkins.github.io/specs/construct-stylesheets/) would fix those issues. However, encapsulated styles for web components could also be problematic as the more styles you put in a web component, the slower it is to parse every time it's used. 

So taking into account the probable future, which philosophy do you believe is or will become the best practice?

**Comment by Nevraeka** [comment]
@straker - I've never seen the Contructable Stylesheet Proposal. How might one use that as opposed to using [CSS Custom Properties (variables)](https://drafts.csswg.org/css-variables/) & the [CSS Apply Rule](https://tabatkins.github.io/specs/css-apply-rule/)?

**Comment by straker** [comment]
Contructable Stylesheets have been referenced by this group [a](82) [few](99) [times](282) as a solution for shared styles across web components. From what [I could gather](https://lists.w3.org/Archives/Public/www-style/2015Mar/0320.html), it would allow a web component to link a stylesheet into the shadow dom via JavaScript, essentially allowing a web component to apply a stylesheet from the DOM or URL without having to reparse it or add it as an inline stylesheet.

Because it's just a stylesheet that you link to the web component, it doesn't disallow CSS Custom Properties once those are supported natively.

**Comment by rniwa** [comment]
Please move this discussion to https://discourse.wicg.io.  This is an issue tracker for web components specifications.

**Comment by Nevraeka** [comment]
@straker  - https://discourse.wicg.io/t/best-practices-for-styling-web-components/1550 . Thanks @rniwa

**Comment by straker** [comment]
Thanks
