### ISSUE TITLE
Idea: ComposedTreeProxy

### ISSUE THREAD

**Issue by trusktr** [WICG/webcomponents#516]
After the previous issues I've posted and after reading the [contentious bits](https://github.com/w3c/webcomponents/wiki/Shadow-DOM:-Contentious-Bits#b-the-default-value-of-closed-shadow-tree-flag), it got me thinking.

What if there was a way to get access to a "composed tree proxy" that would be a mirror of the composed tree at any time, but would allow only certain things to be accessed. The things that are accessible would be those things the user can interact with.

For example, if I can click a button on the screen, and that button is nested deeply in some deep shadow root, then I should also have equal script access to trigger that click event.

The composed tree would (obviously) allow one to learn the structure of the composed tree, and each node in this tree would be a proxy to the actual elements. Some things would be possible, like triggering a click event, while other things like accessing methods and properties would not be possible.

It could be retrieved starting at any element, and going X number of shadow trees deep:

``` js
element.getComposedTreeProxy(3) // 3 shadow-tree levels deep.
```

The proxy nodes could be very limited: It might not be possible to even set attributes on them if their shadow tree is closed, and other things like that.

**Comment by hayatoito** [comment]
Could you elaborate what is the benefit of the proxy?
What use cases does this solve?

**Comment by rniwa** [comment]
This would still have an undesirable effect of websites / tests relying on third party components' internal structures.

**Comment by trusktr** [comment]
@rniwa 

> tests relying on third party components' internal structures.

Yes indeed, e2e testing. How would such a test query a button (if it is many shadow tree layers deep inside the component structure) in order to trigger a click if the trees are closed?

@hayatoito Basically for testing, or possibly for other sorts of things like people wanting to use jQuery to trigger a click on some button. If the user can click the button on the screen, then it should also be doable with code (via the proxy). It is currently not possible if the shadow tree containing the button is closed.

The ComposedTreeProxy enables top-level code to do anything that the user can do, so such logic should be fine (even if the shadow layers are closed). A component nested deep inside shadow layers may still want a button to be clicked, and being able to trigger that with code is fair game (and doesn't defeat anything that the closed state of the tree provides).

**Comment by hayatoito** [comment]
Thanks, however, I am afraid that it is unacceptable to add an API which exposes an internal structure of a closed shadow tree in any way, even if it is _read only_, given that it is inconsistent with the reason why a closed shadow root was introduced.

**Comment by trusktr** [comment]
@hayatoito How do we do e2e testing on an app

``` html
<app></app>
```

where the whole app is made of closed shadow trees from 3rd party components?

**Comment by hayatoito** [comment]
I think there are similar questions posted in this issue trackers.
e.g. https://github.com/w3c/webcomponents/issues/499
It would be nice to use the same issue so that similar questions are not posted in various places.

**Comment by hayatoito** [comment]
Let me close this issue.

**Comment by trusktr** [comment]
Polymer has an idea called [`FlattenedNodesObserver`](https://www.polymer-project.org/2.0/docs/devguide/shadow-dom#observe-nodes), which provides a way to observe the flat tree (composed tree) of a component.

> `Polymer.FlattenedNodesObserver.getFlattenedNodes(node)` returns a list of flattened nodes for the specified node.

I haven't looked at source, but it seems that this would traverse the flat tree of Polymer components. Not sure if it will work with non-Polymer components though.
