### ISSUE TITLE
To notify mutation observers should make a copy of signalList before delivering mutation records

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#518]
In [**notify mutation observers**](https://dom.spec.whatwg.org/#notify-mutation-observers), step 4 (making a copy of `signalList`) should happen before step 3 (executing a compound microtask subtask to deliver mutation records) for consistency.

Otherwise, all slot changes made while invoking mutation observers would be dispatched in step 6 even though the logical ordering would first delivering any pending mutation records to other mutation observers before doing so.

**Comment by rniwa** [comment]
@annevk : I'm filing in this issue tracker for the better visibility for now but feel free to move it to the DOM issue tracker.

**Comment by annevk** [comment]
We should move step 5 too then, no? Otherwise we lose out on a bunch of slot changes...

**Comment by rniwa** [comment]
Oh yes! 4 & 5 should both be moved.

**Comment by annevk** [comment]
Thanks.

**Comment by rniwa** [comment]
Thanks of the fix!
