### ISSUE TITLE
Allow or prohibit observedAttributes to observe 'style' attribute?

### ISSUE THREAD

**Issue by kojiishi** [WICG/webcomponents#521]
I understand we made this explicit opt-in because observing `style` attribute is so expensive.

We'll need additional code to observe `style` attribute, and I suppose other vendors do too. If this is so expensive and we don't want authors to use it, wouldn't it make more sense to prohibit observing `style` attribute, at least in v1?

@domenic @dominiccooney @rniwa

**Comment by domenic** [comment]
I'm not sure my recollection is perfect, but if I recall the conclusion was that if authors want to opt in to the slow thing, they should be able to observe style attribute changes. We shouldn't have exceptions in the platform that simply reflect specific implementation difficulties for some browsers.

**Comment by kojiishi** [comment]
Ok, let's focus on the spec side.

The style is the only attribute that:
1. is the dynamic mirror of another object model, and
2. is the only animatable attribute.

If author wants to observe style changes, s/he should observe the source object model, not the mirrored string. Houdini has the tools to do this with specific design points, such as:
- It can opt-in to observe specific CSS properties.
- It fires per animation frame (Houdini paint) or per layout cycle (Houdini layout).
- The values are passed by values, not as serialized strings, thanks to CSS Typed OM.
- It is designed to work in Worklets.

I hope you get the picture that Houdini is trying very hard to avoid style serialization in main thread, but Custom Elements allowing to observe style attribute undoes all these efforts.

I don't know whether we fire mutation observer in 60fps today or not, but if we did, I think it was a design done before Houdini was born. I hope we don't repeat that.

**Comment by annevk** [comment]
This is really a debate about whether the `style` attribute deserves special status in various APIs or not, due to the way it works. I know @smaug---- is not convinced it should. I personally would be okay with it, even though such exceptions are rather ugly.

We should really try to come to an agreement around that I think. Special casing it here but not elsewhere doesn't really help your fast paths much.

**Comment by rniwa** [comment]
FWIW, I don't think we should treat `style` attribute differently from other attributes.

**Comment by annevk** [comment]
Would help if @travisleithead shared Edge's thinking on this.

**Comment by kojiishi** [comment]
"Observing styles should belong to Houdini" is my personal opinion, if controversial, I'd like Houdini people to join the discussion. @ojanvafai @shans @bfgeek

**Comment by annevk** [comment]
As stated, I doubt that is controversial. What is controversial is special casing a content attribute.

**Comment by kojiishi** [comment]
Thanks Anne, I think I understand your previous comment better now. But knowing how badly other people are trying to avoid it is good to know before we conclude, no?

**Comment by domenic** [comment]
It would be good to drive a resolution on this, one way or the other.

I'd like to get a better sense of what various parties opinions are, and how strongly they are held. Here's what I have so far:
- @domenic would weakly prefer style be observable
- @kojiishi would strongly prefer style be non-observable
- @annevk would be OK either way
- @rniwa would prefer style be observable (unclear how strongly this opinion is held)

If @rniwa's preference is not strong, maybe we should make style non-observable. We can always make it observable later if we hear of an author actually asking for that ability with a use case.

It would be good to hear from Edge (@travisleithead) and Gecko's implementation side (@smaug----).

**Comment by smaug----** [comment]
> We'll need additional code to observe style attribute, and I suppose other vendors do too.

Gecko will need additional code if we special case ´style´ for custom elements. That is because ´style´ hasn't been special cased elsewhere, like in MutationObserver or Mutation Events.

But current spec requires one to explicitly define which attributes to observe, so what is the issue here?

**Comment by rniwa** [comment]
I don't think we should special case `style` given that the author has to opt-in to observe the changes to `style` already.  Given there is no reason to believe the same author wouldn't use CSS OM and simply call `this.style.cssText`, I don't see a point in preventing author from observing `style` attribute.

**Comment by kojiishi** [comment]
Can someone please point me the spec that defines when MutationObserver fires on style changes via CSS Animation? Do we fire it on every rAF, check if the serialized value changes on every rAF, or something else? I haven't read through MutationObserver spec yet, but I can't find it at the moment.

**Comment by smaug----** [comment]
MutationObserver spec shouldn't say anything about it, since it talks about all the attributes.

But I'm not aware style attribute changing for CSS Animation, since that doesn't have similar effect as what element.style.fooProperty = "newValue"; has.

**Comment by kojiishi** [comment]
Apologies, you're right, it was my misunderstanding that CSS Animation/Transition affects style attributes. Ran a simple test and it's interoperable.

So I'm ok to close this as Won't Fix.

**Comment by domenic** [comment]
OK, thanks everyone for a good discussion! Closing then.
