### ISSUE TITLE
When to invoke custom element reactions that were enqueued outside of DOM operations?

### ISSUE THREAD

**Issue by kojiishi** [WICG/webcomponents#522]
By reading [invoke custom element reactions](https://html.spec.whatwg.org/multipage/scripting.html#invoke-custom-element-reactions), I understand after `[CEReactions]` is when we should invoke reactions.

What should we do when DOM was mutated outside of DOM operations? Such operations could happen:
1. `contenteditable` can split (clone) or delete elements.
2. Depends on the conclusion of #521, `style` attribute can change by CSS OM or CSS Animations.

I thought `checked` and `value` in form elements do too, but as far as I tested, they change properties but do not change attributes, so these two are the only cases that came up to me atm, but spec experts here might know more.

**Comment by kojiishi** [comment]
@domenic @dominiccooney

**Comment by domenic** [comment]
This was discussed in #186 with the solution being specified at https://github.com/whatwg/html/pull/1412

**Comment by kojiishi** [comment]
Thanks for the pointer, will discuss there.
