### ISSUE TITLE
Is custom elements constructor allowed to attachShadow?

### ISSUE THREAD

**Issue by kojiishi** [WICG/webcomponents#524]
The create an element step 6 (synchronous flag set) disallows attributes nor children, but does not disallow attachShadow. Is this intentional, or overlook?
@domenic

**Comment by annevk** [comment]
Setting up the internal layout seems appropriate for a constructor (versus setting up content).

**Comment by domenic** [comment]
Intentional: https://html.spec.whatwg.org/multipage/scripting.html#custom-element-conformance

**Comment by rniwa** [comment]
We object to this. We should allow attaching shadow root in the constructor.

**Comment by domenic** [comment]
I think you misunderstood. It is intentional that it is allowed (not disallowed, as the OP put it). I will let you close since I don't want to get in a closing war, but I think we are in agreement.

**Comment by rniwa** [comment]
Ah, okay. sorry, I misread it.
