### ISSUE TITLE
Should innerHTML propagate custom element constructor exceptions?

### ISSUE THREAD

**Issue by domenic** [WICG/webcomponents#525]
As currently specced, innerHTML uses the HTML parser. If element creation throws an exception in the HTML parser, we report the exception (window.onerror etc.) instead of propagating the exception, because normally when using the parser there is nowhere to propagate it to.

This is certainly easiest to spec, but seems like it might be against the original intent. That is, I would kind of expect this to catch the exception:

``` js
customElements.define("x-foo", class extends HTMLElement {
  constructor() {
    throw new Error("boo");
  }
});

try {
  document.body.innerHTML = "<x-foo></x-foo>";
} catch (e) {
  // do we get here?
}
```

If we did want this to propagate the exception, I'm not sure the best way to spec it... we can't just say "in the fragment case, propagate the exception" since the fragment case is also used in other places that aren't DOM APIs. We could cheat and say something like "if the JS execution context stack is not empty, propagate the exception" but I might imagine stack inspection is not desirable for implementers? Otherwise I guess we could explicitly set a flag...

/cc @rniwa @dominiccooney @kojiishi @annevk

**Comment by dominiccooney** [comment]
There could be multiple exceptions; propagating up to one seems arbitrary.
Authors should follow the Pokemon trainer principle: if you're interested
in exceptions, you should use onerror to catch 'em all.

**Comment by domenic** [comment]
Well, presumably we'd propagate up the first one that occurs, and interrupt the parsing process at that point...

**Comment by rniwa** [comment]
Didn't we decide to use upgrades for fragment parsing, etc... for DOM APIs?  Then, you can just re-throw exceptions at the next reaction timing before reactions.

**Comment by domenic** [comment]
Hmm, so if I am understanding, the idea is to introduce some kind of test, and:
- If there is an element queue in the custom element reactions stack, store some kind of "throw an exception reaction" in the queue
- If there is no element queue in the custom element reactions stack, report the error
- When running custom element reactions at the end of a [CEReactions] algorithm, shuffle all "throw an exception reaction"s to the back of the queue (after all other reactions), and throw the first one of them?

This has the advantage of not causing throws in the middle of algorithms that might not expect it (which could help #512) but seems like a lot of complication...

**Comment by kojiishi** [comment]
I think I agree with @dominiccooney that reporting errors is more appropriate here.

Exceptions are not only about reporting errors but also aborting the steps. In this case, exceptions occur in upgrade reactions, so innerHTML is set, so we're not aborting.

Web authors interested in seeing errors can still listen to error events.

**Comment by annevk** [comment]
innerHTML should not throw. Upgrades should happen after the setter returns.

**Comment by rniwa** [comment]
I don't think that makes sense given the timing of reactions is right before `innerHTML` returns.

**Comment by annevk** [comment]
Oh right. But the reactions should work like event listeners and therefore report, not rethrow.

**Comment by rniwa** [comment]
I'm not sure about that.  As far as authors are concerned, we threw an exception during a call to `innerHTML`.  It would be very confusing for that exception to be not propagated to the call site of `innerHTML`.  That seems too magical for a feature that supposedly explains how the platform works.

**Comment by annevk** [comment]
How is that different from `dispatchEvent()`? Note that I agree we should expose the capability, see https://github.com/whatwg/html/pull/1196 for that. Voicing your support for that would help.

**Comment by domenic** [comment]
I find the analogy with dispatchEvent fairly persuasive. @rniwa are you OK with closing?

**Comment by rniwa** [comment]
Okay, I guess just reporting the error would be more consistent with event dispatching and mutation observers.
