### ISSUE TITLE
Invalid constructor when invoking the constructor directly

### ISSUE THREAD

**Issue by 0815fox** [WICG/webcomponents#531]
I tried to use the constructor variant as described in 2.1.1 Creating an autonomous custom element in current implementation of webcomponents.js / chrome:

```
const flagIcon = new FlagIcon()
flagIcon.country = "jp"
document.body.appendChild(flagIcon)
```

That currently throws `Invalid constructor`, because it tries to invoke the constructor of `HTMLElement`. Will the HTMLElement-constructor change in future, such that it will be callable? Are there any resources to read up on this?
For the moment, the way as described on [MDN](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements/Custom_Elements_with_Classes) works, when I use the constructor returned by `document.registerElement`. However, this implies, that I cannot use a Custom Element programmatically only (without assigning it a tag name) - is that correct or will it be possible in future to have unnamed custom elements (meaning a named ES6 class extending HTMLElement, but not having a tag name)?

**Comment by domenic** [comment]
If I am understanding correctly, this is a bug report against Chrome, not the spec, and this is not the correct repo. I'm not surprised you're having problems since Chrome has not shipped an implementation of the current spec.

**Comment by hayatoito** [comment]
Yeah,
@0815fox could you use https://bugs.chromium.org/p/chromium/issues/list to file a bug for Chrome?

**Comment by treshugart** [comment]
@0815fox there's a related issue in the webcomponentsjs custom element polyfill https://github.com/webcomponents/webcomponentsjs/issues/563. As noted there, Chrome 39 and above should be fine. That issue is for static props, but the fix for that fixes this problem. Sounds like either a bug for the webcomponentsjs polyfill, or Chrome.
