### ISSUE TITLE
Are document fragments "inert"?

### ISSUE THREAD

**Issue by trusktr** [WICG/webcomponents#532]
Seems like document fragments are intended to hold inert node trees, that will become active when the fragment tree is inserted into live DOM. This would make it good for temporary structuring until finally ready to be inserted into DOM.

A couple questions:
1. Is are disconnected and connected callbacks called when custom elements are appended into a document fragment?
2. Can custom elements know when they are in a fragment in order to (or not to) do certain things?

Just wondering, because it seems like we want to prevent connected and disconnected callbacks from firing until the fragment content is inserted into actual DOM, as those callbacks are currently _the only_ callbacks for initializing and de-initializing things when a custom element enters and leaves the DOM. We might not want to enact certain behaviors when the element is in a document fragment.

**Comment by rniwa** [comment]
`connectedCallback` and `disconnectedCallback` won't be called when a custom element is inserted or removed from a document fragment.

**Comment by trusktr** [comment]
@rniwa Thanks, sounds good. I didn't see this in the spec, unless I missed it or it wasn't clear.
