### ISSUE TITLE
The custom element state when constructor thrown

### ISSUE THREAD

**Issue by kojiishi** [WICG/webcomponents#533]
The [create an element for a token](https://html.spec.whatwg.org/multipage/syntax.html#create-an-element-for-the-token) step 7 says when [create an element](https://dom.spec.whatwg.org/#concept-create-element) thrown:

> let element be instead a new element that implements HTMLUnknownElement, with no attributes, namespace set to given namespace, namespace prefix set to null, custom element state "undefined", and node document set to document.

Then when this element is inserted, the [insert a node](https://dom.spec.whatwg.org/#concept-node-insert) tries to upgrade this element.

Shouldn't we prevent to upgrade elements whose constructor thrown?

@domenic @dominiccooney

**Comment by domenic** [comment]
Interesting. So the concrete test case is

``` html
<script>
let shouldThrow = true;
customElements.define("x-bad", class XBad extends HTMLElement {
  constructor() {
    super();
    if (shouldThrow) {
      throw new Error("bad");
      shouldThrow = false;
    }
  }
});
</script>

<x-bad></x-bad>
```

Per the current spec this will try to create an XBad, then fail, but then upon insertion, try to "upgrade" from HTMLUnknownElement to XBad, and succeed. This is especially weird since the "upgrade" goes laterally across the hierarchy (i.e. from HTMLUnknownElement to XBad, instead of from HTMLElement to XBad).

One "solution" would be to say that this is an OK edge case that emerges from the semantics, but we should probably clean up the potential for a lateral transition, so make it HTMLElement instead of HTMLUnknownElement.

Otherwise, if we want to say that throwing in your constructor means we should never try to upgrade you, then the most straightforward solution I can think of is to add a new custom element state, "unupgradeable", which we set if the constructor fails. Then any future upgrades or try-to-upgrades would bail out if they see this state. We would probably also use this in other cases, such that if upgrading fails once, we should never try it again.

What do people think would be better?

**Comment by trusktr** [comment]
> We would probably also use this in other cases, such that if upgrading fails once, we should never try it again.

Probably should still try again, as the error may have been due to something missing or not in place at runtime, but could be in a future point in time, in which case upgrading would work (`new` constructor may not throw at that point).

**Comment by rniwa** [comment]
I don't think we should try to update an element in the case it had failed to construct.

**Comment by domenic** [comment]
@rniwa so just to make sure I understand, you are in favor of adding an "unupgradeable" state, to ensure that any constructors that fail are never invoked again?

**Comment by kojiishi** [comment]
I agree with @rniwa that we shouldn't run constructor mulitple times on the same element.

One more thing we need to take care of, if we were to add a new state, is that whether the new state is [defined](https://dom.spec.whatwg.org/#concept-element-defined) or not. Semantically, it is not _defined_. However, the expected most common use case of _defined_ is `not(:defined)` to find elements yet to be upgraded, as in the example in [element definition](https://html.spec.whatwg.org/multipage/scripting.html#element-definition). From this purpose, I would like it to be _defined_.

I mildly prefer it be _defined_ for the reason above, but I'm ok either way.

And if we were to make it as _defined_, we could use _uncustomized_ too. I'm ok either way on this too.

**Comment by domenic** [comment]
Hmm. I think it would be better to be not defined. After all, it will not work like a defined element would. It has not yet been upgraded (and never will be). `:not(:defined)` would be better off matching it, I think. For example if people are trying to hide elements until they are interactive.

**Comment by domenic** [comment]
PRs up to fix this at https://github.com/whatwg/dom/pull/282 and https://github.com/whatwg/html/pull/1558. It turned out to be fairly straightforward and fit with existing mechanisms nicely.

**Comment by trusktr** [comment]
It seems to me like preventing the constructor from ever running again is not the best thing to do. What if some error state elsewhere in the app causes the constructor to fail, and then that error state goes away, in which case the element should come alive again the next time it is used.

Or, does this explicitly prevent the constructor from running twice on a specific element such that if I removed `<some-element>` then attached a new `<some-element>` then the new one will have it's constructor called?

``` js
class SomeElement extends HTMLElement {
  constructor() {
    if (!someStateInTheApp) {
      throw SomeError('...')
    }

    // ...
  }
}
```

Would the best practice for a library that writes a constructor like that be to encourage the failed element to be removed and for the user to try again by adding a new element?

**Comment by andyearnshaw** [comment]
> Or, does this explicitly prevent the constructor from running twice on a specific element such that if I removed <some-element> then attached a new <some-element> then the new one will have it's constructor called?

Yes.

> Would the best practice for a library that writes a constructor like that be to encourage the failed element to be removed and for the user to try again by adding a new element?

I think the best practice would be not to rely on specific states the app may or may not be in while your constructor is running.  Keep your constructor as light as possible (only setting up its own state and tree, for instance) to avoid potential errors.  Add initialisation and cleanup routines to callbacks.
