### ISSUE TITLE
Let's make document.write()/open() throw during parser invocations of custom element constructors

### ISSUE THREAD

**Issue by domenic** [WICG/webcomponents#537]
Right now the spec says to make them silently do nothing. (Although there are some small bugs in how that's specced due to reusing existing machinery slightly wrong; see https://github.com/whatwg/html/issues/1630 and https://github.com/whatwg/html/issues/1603.) When working through this with @dominiccooney, I realized that it's probably more author-friendly to make these methods throw instead. I'm not sure why we didn't think of this before.

This is only for when the parser creates the custom element; it does not apply for `new XTag()` or `document.createElement("x-tag")`.

Does throwing sound good to everyone? @smaug----, @rniwa, @travisleithead

**Comment by rniwa** [comment]
Yeah, I think throwing here is okay although adding an explicit check of being inside a custom element constructor in `document.open`/`write` is kind of weird.

**Comment by domenic** [comment]
I'd spec it by adding a new "throw-on-writes-and-opens" counter to the parser, which gets incremented while the parser is creating a custom element, and which document.open/write throw when it is nonzero.
