### ISSUE TITLE
Broken wikipedia link for "Green Eye"

### ISSUE THREAD

**Issue by jfw7** [WICG/webcomponents#538]
https://w3c.github.io/webcomponents/spec/shadow/#shadow-dom-example

"After getting another cup of **[Green Eye](https://en.wikipedia.org/wiki/List_of_coffee_drinks)**, he quickly mocks up the following shadow tree, to be hosted by the ul element"

"Green Eye" appears to have been removed from "List of coffee drinks" in January 2015.

**Comment by hayatoito** [comment]
WONTFIX as of now.
