### ISSUE TITLE
Should :defined match <x-foo> in browsing-context-less documents?

### ISSUE THREAD

**Issue by domenic** [WICG/webcomponents#540]
Originally https://bugs.chromium.org/p/chromium/issues/detail?id=635402

In documents without a browsing context, the whole custom elements machinery is offline. So `<x-foo>` is equivalent to `<asdf>`: both are never going to become customized. They are just simple unknown elements.

Currently step 7.3 of ["create an element"](https://dom.spec.whatwg.org/#concept-create-element) recognizes this and does not mark `<x-foo>` as "undefined". So in such documents, `:defined` will match `<x-foo>`, even though in the main document with a browsing context, `:defined` will not match `<x-foo>`.

Probably nobody will encounter this in practice.

I think the spec makes sense as-is. But the consequences are a bit unintuitive. So if anyone has opinions on this let me know and we can certainly change the spec.

If nobody has opinions on this over the next couple of weeks I will close and leave things with the status quo.

**Comment by annevk** [comment]
If we are ever going to offer custom elements in those contexts, I think we want to change this. Otherwise there's more potential for breakage when that time comes (because the default behavior flips).

**Comment by domenic** [comment]
Hmm. I can't really see how we ever would, but that's a reasonable thing to be careful about, so we might as well fix this.

**Comment by rniwa** [comment]
We can easily add an optional `document` argument to custom element constructor to support that.
