### ISSUE TITLE
Step 13.3-4 in element definition should clarify the ordering

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#542]
Steps 13.3 and 13.4 of the [element definition](https://html.spec.whatwg.org/#dom-customelementsregistry-define) algorithm doesn't explicitly state the ordering of `Get` other than implicitly defining it via a map.

We should either call it an ordered map, or explicitly state the order by which these properties are obtained as they're observable via `Proxy` objects or getter.

**Comment by rniwa** [comment]
@domenic @annevk

**Comment by domenic** [comment]
Makes sense, I was assuming with my JavaScript background that it was an ordered map, but I should definitely should clarify.

**Comment by rniwa** [comment]
Yeah, it was pretty obvious that's what you meant from JS semantics but I think it's good to be explicit in specifications :)
