### ISSUE TITLE
Steps in element definition that throw an exception should abort

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#543]
In [customElements.define](https://html.spec.whatwg.org/#dom-customelementsregistry-define), we should clarity we're supposed to keep invoking `Get(prototype, callbackName)` when one of the get calls or the conversion (in step 13.4.2) throws.  I think we're aborting here immediately but that's not entirely obvious from the text.

**Comment by kojiishi** [comment]
It's in 13.4.1, the step before it, says:

> Let callbackValue be Get(prototype, callbackName). Rethrow any exceptions.

...or did I misunderstand the question?

**Comment by rniwa** [comment]
It does say to throw but it doesn't say to abort the steps. So it's somewhat ambiguous as to whether we should keep executing `Get(prototype, callbackName)` on other callback names or not.

Now, it's quite obvious from the semantics of JavaScript that we can't keep issuing `Get`s when there is a pending exception being thrown but we should explicitly state that in the specifications.

**Comment by rniwa** [comment]
@domenic @annevk

**Comment by annevk** [comment]
Slowly all specification text is starting to assume that throw means abort. So I think we want to leave this as-is, and eventually define these kind of semantics in IDL, as the keeper of specification-algorithm semantics.

**Comment by domenic** [comment]
Yeah, we've been trying to move toward a world where you don't have to put "... and abort these steps" after every "return" or "throw"...

**Comment by rniwa** [comment]
Okay.
