### ISSUE TITLE
Forbid reentrance to `customElements.define`

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#545]
The current spec defines the notion of a [_set of being-defined names_](https://html.spec.whatwg.org/#set-of-being-defined-names) and a [_set of being-defined constructors_](https://html.spec.whatwg.org/#set-of-being-defined-constructors) to deal with the situation in which `CustomElementsRegistry.prorotype.define` is called inside `Get` invocations; i.e. a re-entrant call to `define`.

However, this situation is more easily avoided if we just added a global flag indicating whether we're inside `define` or not.  I can't think of a situation in which one would need a re-entrant behavior in `define` since making a call to `define` invokes trapping `Get(constructor, "prototype")` or other `Get`s to callback and `observedAttributes`.

**Comment by rniwa** [comment]
@annevk @domenic

**Comment by domenic** [comment]
The problem was originally filed in https://github.com/whatwg/html/issues/1329 and fixed in https://github.com/whatwg/html/pull/1333. Upon reflection I agree that your proposed solution would be simpler. @dominiccooney, do you agree? If so, sorry I made you implement the sets...

**Comment by dominiccooney** [comment]
I'm fine with making this a reentrance guard. It's simpler that way!
