### ISSUE TITLE
"The problematic position" when Custom Elements throw errors?

### ISSUE THREAD

**Issue by kojiishi** [WICG/webcomponents#547]
There are two places where Custom Elements [report the exception](https://html.spec.whatwg.org/multipage/webappapis.html#report-the-exception):
1. Step 7 of [create an element for a token](https://html.spec.whatwg.org/multipage/syntax.html#create-an-element-for-the-token)
2. Step 1.2.1 of [invoke custom element reactions](https://html.spec.whatwg.org/multipage/scripting.html#invoke-custom-element-reactions)

To [report the exception](https://html.spec.whatwg.org/multipage/webappapis.html#report-the-exception), the spec requires "the problematic position (line number and column number) in the resource containing the script". However, in Custom Elements, UA validates the return value from JS and throws errors, and thus "the problematic position" is ambiguous.

This affects:
1. File name, line number, and column number reported in error event and to console.
2. Whether the script has [muted errors](https://html.spec.whatwg.org/multipage/webappapis.html#muted-errors) or not to determine what to [report the error](https://html.spec.whatwg.org/multipage/webappapis.html#report-the-error).

We tentatively use the position of the constructor function, but some reviewers pointed out that it is not exactly true and should be clarified in the spec.

Thoughts?

The original discussion was at [crrev.com/2244203002](http://crrev.com/2244203002) in case it helps.

**Comment by domenic** [comment]
In general this area is a mess and we don't really have any good answers. See https://github.com/whatwg/html/issues/958.

Per the latest plan at https://github.com/whatwg/html/issues/958#issuecomment-226309871 I think that for UA-created exceptions there is no file name, line number, or column number, and there is no script so there is no muted errors check.

I'll add a note to https://github.com/whatwg/html/issues/958 that we should be clear on how UA-created errors work.

**Comment by kojiishi** [comment]
Thank you for the pointer, I understand it's not easy to define "the relevant script" in generic way, but for custom elements, it is obvious, isn't it?

I think, at least in this case, the UA-created exceptions should indicate which constructor produced the invalid results. Otherwise developers would have hard time to figure out which custom elements failed. A colleague indicated we could embed such information into message, but it won't work with source map.

What about muted? The muted is defined against script IIUC, but the exception is not thrown by scripts. I guess we should copy the muted state of the script that returned invalid value, no?

**Comment by kojiishi** [comment]
After reading your plan again, I'm ok for filename/column number/line number to be left undefined, we believe providing it is important but ok if other implementers believe differently.

We should at least give constructor's script as the "optional script" so that it won't be muted when it should not be.

**Comment by domenic** [comment]
If no optional script is provided, there is no muting, at least in the new plan.

I guess you are right that browsers somehow determine the filename/colno/lineno even for UA-created scripts. Here is a simple example http://jsbin.com/mediwuwodu/edit?html,console. That is annoying... There's going to be some sort of algorithm that traces back to the nearest author code on the stack, or something. We should figure out how to spec that when we fix whatwg/html#958.

**Comment by kojiishi** [comment]
The demo still has the JS that calls UA code to cause the exception, so Blink uses the caller JS. I guess it's not so hard for other browsers too, if the caller had try/catch, it should catch the UA-created exception, so UA must know the caller context.

In custom elements. when the parser calls the constructor, there's no JS that calls the UA code, so we needed the special casing. I'm not sure if there are such cases already in the spec, at least I could not find any.

**Comment by domenic** [comment]
I see. I guess from my perspective they are equally magical, in that in both cases the exception object is not created in the place given by filename/lineno/colno---in both cases it is created in C++, not in JS.

When I work on whatwg/html#958 I'll see if I can find a way to integrate this specific situation, or point out that it's special. Maybe it will even be natural to pass in the position of the constructor function. But I think this probably falls under the general area of there being not-great interop around filename/lineno/colno/error.stack.

**Comment by rniwa** [comment]
Closing this in favor of https://github.com/WICG/webcomponents/issues/635.
