### ISSUE TITLE
Rename interface CustomElementsRegistry to CustomElementRegistry

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#548]
We don't use the plural form of the noun for a thing when naming a collection of things. e.g. `NodeList`,  `StyleSheetList`, `CSSRuleList`, etc...

**Comment by rniwa** [comment]
@domenic @dominiccooney @annevk

**Comment by rniwa** [comment]
I've done the rename in WebKit already: https://trac.webkit.org/changeset/204732

**Comment by domenic** [comment]
Thanks. Still waiting on https://github.com/whatwg/html/pull/1674 to get sign-off before working on this, to avoid conflicts.

**Comment by kojiishi** [comment]
This is about just interface name, not property name, correct? Not an opinion, just wanted to confirm.

**Comment by domenic** [comment]
Correct.

**Comment by rniwa** [comment]
Yes, we'd keep `window.customElements` but we'll change its interface name to `CustomElementRegistry`.

**Comment by TakayoshiKochi** [comment]
Done for Blink: https://codereview.chromium.org/2277713002/

**Comment by WebReflection** [comment]
Done (2 days ago) for my standalone polyfill: https://github.com/WebReflection/document-register-element/commit/51db0d71e4daf050e2f338dcc2d4bfddd306289b#diff-27e2f089a8f6e83fee5d63beb9ca4acdL1162
