### ISSUE TITLE
What's the expected behavior of a class with observedAttributes but no attributeChangedCallback?

### ISSUE THREAD

**Issue by JanMiksovsky** [WICG/webcomponents#555]
I inadvertently created a component that defined `observedAttributes` without an `attributeChangedCallback` to handle the changes. Trying out this component (in the latest Custom Elements v1 polyfill) caused an error, which wasn't surprising, but it lead me to wonder: what _is_ the standard behavior expected in that situation?

I couldn't infer what would happen from the spec: an exception at `define` time? Or should `observedAttributes` with no callback just be a no-op?

**Comment by domenic** [comment]
We can answer this by looking at the spec, in particular https://html.spec.whatwg.org/multipage/scripting.html#dom-customelementregistry-define step 10. In this case, the observedAttributes property is ignored (step 10.6 is false, so 10.6.1 doesn't even run). Even if you put a getter, it is not supposed to be triggered, i.e. given

``` js
customElements.define("x-x", class extends HTMLElement {
  static get observedAttributes() { console.log("does this happen?"); }
});
```

nothing should be logged to the console (and no error thrown).

Sounds like a bug with the polyfill :)

**Comment by JanMiksovsky** [comment]
@domenic Thanks for helping interpret the spec for me.
