### ISSUE TITLE
A custom element should be marked as "failed" if a constructor returns a wrong object

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#561]
Step 10 of [upgrading an element](https://html.spec.whatwg.org/multipage/scripting.html#concept-upgrade-an-element):

> If `SameValue(constructResult.[[value]], element)` is false, then throw an "`InvalidStateError`" `DOMException` and terminate these steps.

should also set the custom element state to "failed" so that we don't try to upgrade it again.

**Comment by rniwa** [comment]
@annevk @domenic @dominiccooney

**Comment by kojiishi** [comment]
+1, blink already does this, sorry for not noticing this before.
