### ISSUE TITLE
Make createElement report an exception instead of propagating an exception

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#569]
Per 2016 TPAC discussion, make `createElement` report an exception instead of propagating it so that it would be more consistent with the parser and other DOM APIs.

**Comment by domenic** [comment]
There are two possibilities:
1. keep using the sync flag, try/catch the exception, report it, and return HTMLUnknownElement like the parser does
2. use upgrade-like semantics and [CEReactions]

The observable differences here are subtle and minimal. (1) will return HTMLUnknownElement; (2) will return HTMLElement. And then there's the subtle constructor-vs.-upgrade issues, mostly around error cases.

I don't have a strong preference. I think @rniwa was leaning toward (1). It would be good for someone (probably me, maybe I can get @dominiccooney to do it) to enumerate all the differences in more depth, just to be sure there isn't a clear winner hiding there.

**Comment by dominiccooney** [comment]
I haven't investigated in depth but option 1 sounds fine. Blink will try to implement this; I have filed [CR652157](https://crbug.com/652157) for it.

**Comment by rniwa** [comment]
Right now, this is the largest compat risk for v1 so I'd appreciate if you could update the spec sooner than later.

**Comment by domenic** [comment]
I should be able to get to this next Monday.

**Comment by rniwa** [comment]
Great!  The new behavior is [being implemented in WebKit](https://bugs.webkit.org/show_bug.cgi?id=162996) now.
