### ISSUE TITLE
integrity attribute in <link rel="import"/>

### ISSUE THREAD

**Issue by zourzouvillys** [WICG/webcomponents#575]
As with link rel="stylesheet" and script tags, it would be good to have imported resources protectable with the integrity attribute for the same reasons as stylesheets and scripts.

It doesn't seem like it's mentioned in this draft, nor in the [SRI](https://www.w3.org/TR/SRI/) rec or draft.  let me know if there is somewhere better to submit this!

**Comment by nektro** [comment]
+1 Sounds like a great idea!

**Comment by TakayoshiKochi** [comment]
Let me close this issue as we do not spend time on HTML Imports moving forward.

**Comment by nektro** [comment]
> we do not spend time on HTML Imports moving forward.

What do you mean?

**Comment by TakayoshiKochi** [comment]
As no one except Chrome/Opera implements HTML Imports, we do not invest effort on adding / fixing any feature in the existing HTML Imports spec.  Maybe only exception is security fixes for the existing implementation, which will live for some time.  Currently the discussion around HTML modules sounds it will not use `<link rel=>` form and the original proposal doesn't apply as is.
