### ISSUE TITLE
[Idea] Distant ShadowDOM.

### ISSUE THREAD

**Issue by trusktr** [WICG/webcomponents#576]
Currently, we can only distributed elements into a shadow root that is sibling to those elements. It'd be nice to be able to distribute elements into any shadow root, perhaps using an ID.

f.e.

``` html
<div>
  <span root-host="root-containing-element" slot="some-slot"></span>
</div>
...
<div id="root-containing-element">
  #ShadowRoot
    <slot name="some-slot">
    </slot>
</div>
```

In that example, the `span` would be distributed into the shadow root of `#root-containing-element`.

The reason I would want this is because it solves the problems that are introduced by me having to workaround the [breaking changes](https://bugs.chromium.org/p/chromium/issues/detail?id=646993) of the css-transforms spec introduced in Chrome 53.

**Comment by rniwa** [comment]
Also see #574.

**Comment by rniwa** [comment]
This proposal would significantly worsens the performance characteristics of our shadow DOM implementation because ordering all those slotted elements in the tree order (or maybe insertion order?) would require O(n) traversal of the entire tree.

**Comment by hayatoito** [comment]
Hmm. It is not clearly demonstrated what problem this idea is trying to resolve.

@trusktr
Could you elaborate?  In addition to that, any new idea should work with the rest of Shadow DOM APIs. e.g. how an event path should be.

Unless there is a clear proposal, it might be difficult to discuss.

**Comment by hayatoito** [comment]
Let me close this since it is not clearly demonstrated what problem this idea is trying to resolve.
