### ISSUE TITLE
The get-the-parent algorithm shouldn't return null until we reach the root of the current tree

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#577]
Even when `target` and `relatedTarget` are identical, we still need to dispatch an event and bubble it at least until the root of the current (shadow) tree.  This matches the behavior of a disconnected non-shadow tree and WebKit's implementation.

Both the [spec](https://w3c.github.io/webcomponents/spec/shadow/#get-the-parent) and Blink currently trims the event path whenever `target` and `relatedTarget` becomes identical inside a shadow tree but this behavior doesn't match the event path outside shadow trees.

**Comment by rniwa** [comment]
@annevk @hayatoito @bzbarsky @travisleithead

**Comment by rniwa** [comment]
[One of the test cases](https://github.com/w3c/web-platform-tests/blob/master/shadow-dom/event-composed-path-with-related-target.html#L51) in the web platform tests added by Google tests this behavior.

**Comment by annevk** [comment]
I think this is correct in https://dom.spec.whatwg.org/ no? This is probably something that hasn't been removed from Shadow DOM yet as it's been upstreamed.

**Comment by rniwa** [comment]
@annevk : I'm not sure what you mean the algorithm is correct in the DOM specification.  It doesn't define what happens when the event has a related target.  Are you saying that we no longer trim the event path when the event has a related target and a target in the same shadow tree?

**Comment by annevk** [comment]
The DOM Standard does deal with "relatedTarget" these days (as an abstract concept of the event, to be exposed to script by UI Events for certain events).

**Comment by rniwa** [comment]
Okay, then where does the event path get _trimmed_ when both the target and the related target reside in the same tree?

**Comment by annevk** [comment]
As part of dispatch?

**Comment by rniwa** [comment]
Yes, the one in shadow DOM spec has the step to _trim_ the event path when we've reached a point where both the target and the related target reach the same tree so that e.g. `blur` dispatched inside a shadow tree in response to another element in the same tree getting `focus` would not propagate beyond that tree.  Otherwise, you get a superfluous blur & focus pair which indicates the focus moved to the same element which lost the focus.

**Comment by annevk** [comment]
https://dom.spec.whatwg.org/#concept-event-dispatch step 6.3 does that?

**Comment by rniwa** [comment]
Ah, okay, then this issue is about step 6.3. having to read instead:

> Otherwise, if _parent_ is _relatedTarget_'s root, then set _parent_ to null.

Basically, we can't stop immediately when parent and relatedTarget match in a tree. Instead, we need to keep going up until the root of that very tree.

**Comment by annevk** [comment]
@hayatoito can you fix that? ^^

**Comment by hayatoito** [comment]
Yeah, I can update the spec, if everyone wants to change the current spec as proposed. Either is fine to me. Blink is also okay to change the behavior, I think. There is no significant compatibility risk, given that the use case is very minor. I can not think of any use case. Only web-platform-tests would be affected, I think.

For the record, the current behavior is intentional because:
- I do not want to dispatch an event _whenever_ target and relatedTarget are identical.
- However, I could not change the behavior of a document tree for the backward-compatibility.

But, again, I am okay to change the behavior. That might be more consistent than the current one.

**Comment by annevk** [comment]
@smaug---- opinion? ^^

**Comment by smaug----** [comment]
yeah, I think spec could be changed, since before shadow DOM stuff relatedTarget didn't prevent event dispatch, even if it was same as target.

**Comment by hayatoito** [comment]
Thanks. Let me update the spec.

BTW, I have found another (orthogonal) bug in the spec.

For example, when a mouse pointer moves from an element in a shadow tree to its shadow host,
a "mouseover" event should not be dispatched on the shadow host. In this case, the event path should be empty. However, the current spec allows a non-empty event path. That's an unintentional bug to me. Let me fix these together.

**Comment by hayatoito** [comment]
It looks that the current spec already handles a case of a synthetic event well. Thus, WONTFIX.
See https://dom.spec.whatwg.org/#dispatching-events carefully.

The only problem is a case of an UA event as I mentioned. Because that is a separate issue, let me file another issue.

**Comment by rniwa** [comment]
No, the spec is broken for non-trusted events.  In fact, Chrome has upstreamed a test which asserts that the event path is trimmed before reaching the root of the tree as I pointed out in https://github.com/w3c/webcomponents/issues/577#issuecomment-250051706.

**Comment by rniwa** [comment]
Ah, okay, in the case I care about, 6.2. "If target’s root is a shadow-including inclusive ancestor of parent, then append (parent, null, relatedTarget) to event’s path." would be true so 6.3 and 6.4 won't apply.

So this is really just a big in Blink's implementation and the test.
