### ISSUE TITLE
Synthetic click activation steps should state whether the event is composed or not

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#578]
To [run synthetic click activation steps](https://html.spec.whatwg.org/#run-synthetic-click-activation-steps) or more broadly the definition of [firing a `click` event](https://html.spec.whatwg.org/#fire-a-click-event) should clarify when if ever the event is fired with [`composed` flag]() set to true.

Also, the definition of [initializing an event](https://dom.spec.whatwg.org/#concept-event-initialize) should take _composed_ as an argument.

As things stand, the specifications are extremely unclear about when & how this flag is set.

**Comment by rniwa** [comment]
@annevk @domenic @hayatoito @bzbarsky @travisleithead

**Comment by rniwa** [comment]
Note that the last test case in [`event-composed.html`](https://github.com/w3c/web-platform-tests/blob/master/shadow-dom/event-composed.html#L76) tests that _composed_ flag is set to true when a synthetic click event is fired via [HTMLElement.prototype.click](https://html.spec.whatwg.org/#dom-click).

**Comment by annevk** [comment]
"initialize" is used to define `initEvent()` and similar legacy methods. It doesn't need updating. Just use event constructors (which do take a composed dictionary member in the second argument).

I agree that we should clarify "click" however. And I think it should be composed because it's user input. We mainly considered UI Events and forgot HTML dispatches some of those too.

**Comment by rniwa** [comment]
Well, UI events already spec that user-initiated click is composed.  The question is whether synthetic click event fired by [HTMLElement.prototype.click](https://html.spec.whatwg.org/#dom-click) should be composed or not.

**Comment by annevk** [comment]
We also fire a synthetic click for keyboard-initiated "clicks", no? In any event, I think they should be composed.

**Comment by hayatoito** [comment]
An UI Event which is not dispatched via `new Event("", {...})` should be composed, I think.

In other words, if users do not have any chance to specify whether the event is composed or not via an explicit parameter, it should be considered composed.

**Comment by rniwa** [comment]
> In other words, if users do not have any chance to specify whether the event is composed or not via an explicit parameter, it should be considered composed.

That's a pretty good easy-to-follow principle!

**Comment by annevk** [comment]
But that only applies to non-synthetic UI events, right?

**Comment by hayatoito** [comment]
Ah, yeah. I have found that `element.click()` does not dispatch trusted events.
It is a synthetic event, but users do not have a chance to specify it is whether composed or not.

We have a kind of contradiction. :(

**Comment by rniwa** [comment]
That's okay. The principle you stated in https://github.com/w3c/webcomponents/issues/578#issuecomment-251311413 doesn't concern trusted-ness at all. The only question is whether author script can specify `composed` or not. It can't so it must be composed unless we're adding a new option to `click()` e.g. `click({composed: true})`.

**Comment by annevk** [comment]
How do you tell something is a UI event? But yeah, given what @smaug---- said elsewhere about his views on `click()` it would not make sense for it to use composed.

**Comment by smaug----** [comment]
Not sure how my comment elsewhere about click() applies here. Hadn't thought about .composed. I don't have strong opinion on this. https://github.com/w3c/webcomponents/issues/578#issuecomment-251311413 doesn't sound bad, so click() would dispatch .composed set to true.

**Comment by annevk** [comment]
Do we still want to flip this? What do implementations do and do we have tests? HTML still ends up setting composed to false by not talking about it.

**Comment by annevk** [comment]
Ah okay, we have a test at https://github.com/w3c/web-platform-tests/blob/master/shadow-dom/event-composed.html#L76 as pointed out earlier.

**Comment by annevk** [comment]
WebKit fails that test and Chrome passes it. It seems that everyone thinks it should be composed so I'll fix that.

**Comment by rniwa** [comment]
The implementation bug in WebKit is tracked as https://bugs.webkit.org/show_bug.cgi?id=170211.
