### ISSUE TITLE
importNode and cloneNode should upgrade cloned resolved custom elements

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#584]
When a cloned custom element had already been well defined in the current global object, `importNode` and `cloneNode` should immediately upgrade the cloned elements.

Otherwise, we get into a bizarre situation like calling `cloneNode` on a synchronously constructed or upgraded custom element isn't another instance of the same custom element until it gets inserted into a document.  That is, `(new CustomElement).cloneNode() instanceof CustomElement` is `false`.  That's just unintelligible.

I'm already [getting a bug report about this](https://bugs.webkit.org/show_bug.cgi?id=163147) in WebKit.

**Comment by rniwa** [comment]
@domenic @annevk @travisleithead @dominiccooney

**Comment by rniwa** [comment]
Oh, actually, the spec might be already doing this in step 6.2. of [creating an element](https://dom.spec.whatwg.org/#concept-create-element). This might be just bugs in WebKit and Blink.

**Comment by lin7sh** [comment]
@rniwa good work! it worth time to make it right

**Comment by rniwa** [comment]
Closing this issue since this turned out be just an implementation issue.
