### ISSUE TITLE
Can <label> in shadowdom active checkbox from slot?

### ISSUE THREAD

**Issue by lukasoppermann** [WICG/webcomponents#591]
Hey, 

so currently this does not work in `chrome`. I am wondering if this is as per spec or not.

I am getting the label and the checkbox. Wrapping a label around the custom element lets me activate the checkbox, but clicking on the label within the custom element does not do anything. Is this correct?

``` javascript
constructor() {
      super();
      // Attach a shadow root to the element.
      let shadowRoot = this.attachShadow({mode: 'open'});
      shadowRoot.innerHTML = `
            <label class="checkbox"><slot></slot></label>
      `
}

connectedCallback() {
      var checkbox = document.createElement('input');
      checkbox.type = 'checkbox';
      this.appendChild(checkbox);
}
```

**Comment by hayatoito** [comment]
This is as per spec, as of now.
Form's functionality is per node tree. `<label>` and `<input>` in the example are in the different node trees, and there is no relationship between them.

**Comment by SerkanSipahi** [comment]
> "... but clicking on the label within the custom element does not do anything"

@lukasoppermann please post the full code example. What do you mean with? 

> Can <label> in shadowdom active checkbox from slot? 

I tried your code sniped and it works for me `(Chrome v54, Canary V56)`. I can activate by clicking the checkbox!

``` js
customElements.define('x-focus', class extends HTMLElement {
    constructor() {
        super();
        // Attach a shadow root to the element.
        let shadowRoot = this.attachShadow({mode: 'open'});
        shadowRoot.innerHTML = `
            <label class="checkbox"><slot></slot></label>
            `
    }

    connectedCallback() {
        let checkbox = document.createElement('input');
        checkbox.type = 'checkbox';
        this.appendChild(checkbox);
    }
});

let XFocus = customElements.get('x-focus');
let xFocus = new XFocus;
document.body.append(xFocus)
```

will produce:

``` html
<x-focus>
    #shadow-root(open)
      <label class="checkbox">
          <slot>
               <input>
          </slot>
      </label>
      <input  type="checkbox" />
</x-focus>
```

Well for me it works! i dont know your code and case. Maybe you forgot to pass the delegateFocus property?

``` js
let shadowRoot = this.attachShadow({mode: 'open', delegatesFocus: true});
```

see resource: https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom#focus

**Comment by lukasoppermann** [comment]
Hey @hayatoito thanks for the clarification.

@SerkanSipahi Thank you I did indeed, not use the `delegatesFocus: true`. However, when I use it, the label only focuses the checkbox, while normally it activates (checks / unchecks) the checkbox.

Is this working for you?

**Comment by SerkanSipahi** [comment]
What do you mean? you cant checks / unchecks the checkbox? it works for me: http://codepen.io/SerkanSipahi/pen/WGLOEp

**Comment by lukasoppermann** [comment]
Ahh, now I see. No it does not, see: http://codepen.io/lukasoppermann/pen/mAawvP the 'outer label' works, but the 'inner label' does not. The checkbox works of course but the shadow dom label can't activate the light dom checkbox.

**Comment by SerkanSipahi** [comment]
@lukasoppermann oh i see ( http://codepen.io/lukasoppermann/pen/mAawvP). Strange behavior!
