### ISSUE TITLE
slotchange not firing for changes to single text node

### ISSUE THREAD

**Issue by micahscopes** [WICG/webcomponents#592]
I want to detect changes to a slot by listening to the `slotchange` event.  My slot element only contains a single line of text, and so just a single text node.  When I update the host element's innerHTML with a new, different single line of text, I expect that a `slotchange` event should fire, but it doesn't.

If I change a host element's innerHTML from `123\n 456` to `567\n 89`, a `slotchange` event does fire, as I'd expect. 

I'm not sure if this is a bug? feature? in Chromium (53.0.2785.143)... or something about how `slotchange` is related to Mutation Observers in the spec, so I figured I'd file it here.

An example of this: https://jsbin.com/xivunad/15/edit?html,js,console,output

**Comment by annevk** [comment]
If removing and then inserting a text node does trigger the change that would indeed be a bug.

**Comment by rniwa** [comment]
Are you removing & inserting a new text node?  Or you overriding the value of the existing text node?  They're do different mutations, and I don't expect the latter mutation to fire `slotchange` event.

**Comment by annevk** [comment]
They are setting `innerHTML` which should replace the text node since it uses https://dom.spec.whatwg.org/#concept-node-replace. So I suspect this is just a bug.

**Comment by rniwa** [comment]
Yeah, that's an optimization we have in WebKit/Blink. I should probably write a test for that.

**Comment by micahscopes** [comment]
So to clarify, editing innerHTML should replace the the existing TextNode, which _should_ fire a slotchange event?

Here's my understanding...

MDN says about the `childList` element: 

> Set to true if additions and removals of the target node's child elements (including text nodes) are to be observed.

 From what I gather, listening for slotchange is akin to using a MutationOberserver with `{childList: true, subtree: false}`.

So given an element containing a single TextNode: if setting its innerHTML to a single line of text is supposed to remove the old TextNode and add a new one, then it sounds like a MutationObserver with `subtree: false` would notice that, and that a slotchange event _should_ fire.

Of that's the case, do I need to file a bug report somewhere? Also seems like something that might need to be polyfilled.

**Comment by annevk** [comment]
Against browsers that don't do the right thing.

**Comment by rniwa** [comment]
> Of that's the case, do I need to file a bug report somewhere? Also seems like something that might need to be polyfilled.

Yes, in this particular case, it's a bug in Chrome.

**Comment by micahscopes** [comment]
I filed a bug report for Chromium here: https://bugs.chromium.org/p/chromium/issues/detail?id=658605#

Thanks :smile:

**Comment by micahscopes** [comment]
So to clarify, editing innerHTML should replace the text node, which
_should_ or _shouldn't_ fire a slotchange event?

Here's my understanding:

MDN says about the `childList` element: >> Set to true if additions and
removals of the target node's child elements (including text nodes) are to
be observed.

My naive understanding is that listening for slotchange is akin to using a
MutationOberserver with `{childList: true, subtree: false}`?

So, given an element containing a single TextNode: if setting its innerHTML
to a single line of text is supposed to remove the old TextNode and add a
new one, then it sounds like a MutationObserver with `subtree: false` would
notice that, and that a slotchange event `should` fire.

Of that's the case, do I need to file a bug report somewhere? Also seems
like something that might need to be polyfilled.

**Comment by rniwa** [comment]
It **should** fire a slotchange event.
