### ISSUE TITLE
Allow attachShadowRoot for <main>

### ISSUE THREAD

**Issue by cyrilletuzi** [WICG/webcomponents#593]
Following @annevk demand in #110, I open an issue to allow `attachShadowRoot` with the `<main>` tag 

It's a trivial element like `header`, `article` and so on, but it's missing in the current spec safelist.

**Comment by annevk** [comment]
I don't think I demanded, but thanks for doing it! This seems fine to me. @hayatoito @rniwa?

(FYI, we try to avoid the terms "whitelist" and "blacklist" as the connotation that "white" is good and "black" is bad is inappropriate. "Safelist" and "blocklist" are a bit more descriptive.)

**Comment by cyrilletuzi** [comment]
Edited.

**Comment by rniwa** [comment]
Allowing it on `main` seems fine with me.

**Comment by hayatoito** [comment]
I am okay. `main` looks harmless. We can support `main` without any difficulty.
