### ISSUE TITLE
HTMLTableRowElement's insertCell doesn't need CEReactions

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#595]
[`HTMLTableRowElement`](https://html.spec.whatwg.org/#htmltablerowelement)'s [`insertCell`](https://html.spec.whatwg.org/#dom-tr-insertcell) doesn't need `CEReactions` because it never creates or connects a custom element.

**Comment by domenic** [comment]
Nice find, thanks. Somehow I missed this in https://github.com/whatwg/html/pull/1398.
