### ISSUE TITLE
document.close doesn't need CEReactions

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#597]
I don't think [`close()`](https://html.spec.whatwg.org/#dom-document-close) on [`Document`](https://html.spec.whatwg.org/#document) need `CEReactions` because it doesn't mutate attributes or insert/remove nodes.

**Comment by domenic** [comment]
Doesn't it insert a bunch of nodes, if you've previously done `document.open() document.write('some nodes')` and then do `document.close()`?

**Comment by rniwa** [comment]
`document.write` insert nodes, not `document.close` as far as I know.

**Comment by domenic** [comment]
Hmm, I thought that if you've done document.open(), then document.write() won't insert them; it'll wait until document.close() happens. But some testing makes it clear that I am wrong. The thing I am worried about is what the effect of

> Insert an explicit "EOF" character at the end of the parser's input stream.

and

> Run the tokenizer, processing resulting tokens as they are emitted, and stopping when the tokenizer reaches the explicit "EOF" character or spins the event loop.

is. Do you know what that could impact? They seem likely to cause nodes to be added...

I think this might be an issue with different behavior before and after the document is loaded, as well.

@bzbarsky, could you help us? I at least appear to not understand document.close at all :(.

**Comment by bzbarsky** [comment]
`document.close()` can definitely cause nodes to be added to the DOM in general.  Simple testcase (for some values of "simple"):

```
<!DOCTYPE html>
<iframe></iframe>
<script>
  onload = function() {
    var doc = frames[0].document;
    var kids = doc.getElementsByTagName("*");
    doc.open();
    console.log(kids.length);
    doc.write("<span");
    console.log(kids.length);
    doc.close();
    console.log(kids.length);
  }
</script>
```

That `close()` call just added the html, head, and body elements.

Now this isn't general node addition, so maybe it doesn't need custom element reactions anyway?

**Comment by bzbarsky** [comment]
Looking through the spec, there are various other cases in which close() can cause nodes (like comments, say, or doctypes) to be inserted into the DOM.  Again, not sure whether it matters in practice.

**Comment by domenic** [comment]
OK, it sounds like close() cannot insert or remove any author-created nodes, so it sounds like @rniwa is indeed right. Thanks for the help, as always, @bzbarsky.

**Comment by bzbarsky** [comment]
It can insert author-created nodes (e.g. comments).

I _think_ it can't insert elements with author-defined names.  At least probably.

Is element insertion the only thing CEReactions need to handle?

**Comment by domenic** [comment]
Sorry, yeah, I should have been more specific. Elements with author defined names, or elements with author defined attributes, are what we're worried about.

**Comment by bzbarsky** [comment]
OK.  So as I said, I _think_ that can't happen based on briefly skimming the parser state machine, but....

Whats the downside of triggering cereactions on close()?  Just extra code?  Seems like it should be a no-op if we're lucky, so the only reason to not be doing it is optimization or something, right?

**Comment by annevk** [comment]
@bzbarsky yeah, though the whole reason we are specifying [CEReactions] is because user agents want us to tell them those optimizations since they all want to implement them. Otherwise we could have done with a simple tweak to IDL's algorithms. But perhaps it's indeed not worrying about APIs like this too much.

**Comment by zcorpan** [comment]
`close()` _can_ insert elements with author-defined attributes, e.g. as follows:
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4618

**Comment by bzbarsky** [comment]
> But perhaps it's indeed not worrying about APIs like this too much.

Right, given the lack of certainty in this case, and the fact that micro-performance of document.close() is not exactly important, it seems better to err on the side of safety/correctness.

**Comment by rniwa** [comment]
> `close()` _can_ insert elements with author-defined attributes, e.g. as follows:
> http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4618

Someone who cares about customized builtin element should add that as a test case.

FWIW, I'm not writing any tests for CEReactions with regards to customized builtin element since we're not going to implement that feature in WebKit.

**Comment by annevk** [comment]
Note that if we add custom global attributes you will need this too.

**Comment by rniwa** [comment]
Indeed.

**Comment by bzbarsky** [comment]
@domenic So in the end, do we have [CEReactions] on document.close() or not?

**Comment by domenic** [comment]
@bzbarsky we do, as per @zcorpan's test case it's necessary.
