### ISSUE TITLE
When to PUBLIC?

### ISSUE THREAD

**Issue by yanlee26** [WICG/webcomponents#599]
I can't wait,thanks!

**Comment by hayatoito** [comment]
Could you elaborate? What do you mean by _public_?

**Comment by matthewp** [comment]
I think they are asking when these features will be available, and this is not the appropriate place to ask that. Instead follow these links:

http://caniuse.com/#feat=shadowdomv1
http://caniuse.com/#feat=custom-elementsv1
http://caniuse.com/#feat=template
