### ISSUE TITLE
[BUG?] Setting visibility:hidden on a Custom Element causes attachedCallback not to be executed.

### ISSUE THREAD

**Issue by trusktr** [WICG/webcomponents#601]
I found a strange behavior. I have some elements on the page, f.e.

```html
<script src="./path/to/infamous.js"></script>
<motor-scene>
  <motor-node>
    Hello 3D
  <motor-node />
</motor-scene>
```

It works just fine. If I add the following style:

```css
motor-scene {
  visibility: hidden
}
```

then it breaks, and the custom elements don't work. It appears that the `attachedCallback` is never fired, which is very unexpected because CSS should not have any effect on JS logic; CSS is only styling.

**Comment by trusktr** [comment]
Wait, nevermind, it seems I might have a race condition somewhere, and coincidentally it happened while I enabled `visibility:hidden`.

**Comment by matthewp** [comment]
v0 bugs don't really belong here, that's something to report to Chromium/Blink.

**Comment by rniwa** [comment]
Yes, **please don't report implementation bugs on this Github issue tracker**.

For Blink issues, use https://bugs.chromium.org/p/chromium/issues/list
For WebKit issues, use https://bugs.webkit.org
