### ISSUE TITLE
"is" attribute for autonomous custom elements

### ISSUE THREAD

**Issue by olanod** [WICG/webcomponents#603]
Based on my concerns raised in this [SO question](http://stackoverflow.com/q/40171535/931340) where I ask for a way to have custom elements behave as normal input elements, I didn't get any satisfying answer and I still think that's a big use case that should be solved by the custom elements standard. Current solutions to this limitation involve wrapping native inputs with a custom element and manually syncing the state of this input with the state of the custom element; but the problem with wrapping is ... well it's wrapping.
  
Please note that I ask for the 'full package', that is, a way to create an element that can have custom behavior, extend/be treated like an existing native element(e.g. `<input>`) AND be able to define it's own shadow root to have any arbitrary inner structure and rendering. Unfortunately custom built-in elements can not fulfill the last condition since there is a very limited white list of native elements that can have shadow roots attached(basically any interesting element is excluded). Besides that the strong position of some browser vendors about not implementing the later creates a lot of friction in the community and puts that the standard in the same path HTML Imports or Object.observe are.  

The only thing that comes into my mind to solve this issue right now is to allow autonomous custom elements define the `is`(or any other name) attribute(e.g. `<my-input is="input"`) then the browser will treat this element as the native one but probably skipping the rendering part. From my perspective, the one of a normal developer who doesn't know much about the inner workings of the browsers nor have a full picture of all of the tiny details, seems simple and doesn't look like it would conflict with anything on the currently standard, maybe custom elements would have to implement some extra interface required for the browser to treat them as the native ones but in general looks like something do-able.

**Comment by WebReflection** [comment]
FWIW this looks like the worst from both worlds:
- neither graceful enhancement nor backward compatibility are applicable
- elements like `template`, `tr`, `td`, `li`, `dt` or others are still impossible to extend

Last, but not least, if this proposal is possible, I don't understand why the current specification with `<input is="my-input">` wouldn't be as well.

My 2 cents, Best Regards.

**Comment by olanod** [comment]
Because we have the limitation on the shadow DOM spec side of not being able to attach a shadow root on the blacklisted elements? That limitation is not present on normal custom elements. I imagine that at parsing time the browser could treat a custom tag with an `is` attribute as if it were that element that is trying to extend, maybe have it's prototype be the the one of the native tag instead of `HTMLUnknownElement`, except for the part of attaching it's own shadow root and then wait for the usual upgrade process. If having no blacklisted elements in the shadow DOM spec and being able to tell the browser not to add a shadowDOM to native elements(native randering) then there is no need for this and custom built-in elements should be enough, but it doesn't look like it's going to be the case.  
As I've mentioned I don't know a lot about the the way different elements work and why cannot be extended, can you elaborate more on the two points you mentioned?  
Also I'm open to ideas and alternatives, don't you think is something that should be and can be solved? (built-in custom(blacklisted) element + shadowDOM)

**Comment by mightyiam** [comment]
FWIW, this is the only thing I currently see myself attracted to use, in regards to custom elements: `<increment-button is="button">+</increment-button>`.

**Comment by annevk** [comment]
Something like this would have been the way to do subclassing of built-ins had UAs and lots of the platform not been centered around local names. But because it is, we ended up with the current solution.

And even if those concerns were somehow lifted, shadow trees would remain restricted.

So unfortunately this is not a viable option.
