### ISSUE TITLE
Constructing a custom element synchronously drops prefix from its name

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#607]
Namely, 
```js
let x = document.createElementNS('http://www.w3.org/1999/xhtml', 'h:div');
```
then `x.prefix` is `"h"` but

```js
class Custom extends HTMLElement {};
customElements.define('my-custom', Custom);
let y = document.createElementNS('http://www.w3.org/1999/xhtml', 'h:my-custom');
```
then then `y.prefix` is `null`.

**Comment by domenic** [comment]
What is the problem exactly?

**Comment by rniwa** [comment]
The problem here is that the custom element constructor drops the prefix (in its qualified name) on an element name whereas other elements don't.  This also makes the behavior inconsistent with upgrading case in that the prefix will be preserved when an element with an existing prefix in its qualified name is upgraded.

**Comment by domenic** [comment]
What prefix is dropped? In the example no prefix is given.

**Comment by rniwa** [comment]
Oops, fixed the example.

**Comment by domenic** [comment]
OK. And why do you think the spec does not correctly set the prefix? It seems to do so just fine by my reading.

**Comment by rniwa** [comment]
Because the html element constructor just looks up and uses the name used in `customElements.define`, not the one passed to `document.createElementNS`.

**Comment by domenic** [comment]
Sure. But then create an element step 6.1.10 sets the prefix.

**Comment by rniwa** [comment]
Oh, I missed that part. Okay, so this is just an implementation bug in Chrome.

**Comment by rniwa** [comment]
Will fix this in WebKit with a test.
