### ISSUE TITLE
createElement step 5 is inconsistent with parser-created customized built-in elements

### ISSUE THREAD

**Issue by dominiccooney** [WICG/webcomponents#608]
I'm looking at [document createElement](https://dom.spec.whatwg.org/#dom-document-createelement) step 5 which says:

> If is is non-null and definition is null, then throw a NotFoundError.

However autonomous custom elements don't throw this error, but create an element that is upgraded later. I think parser created custom elements (of both kinds) are upgraded later.

Why are customized built-in elements handled differently? I think they could just rely on [concept create element](https://dom.spec.whatwg.org/#concept-create-element) step 7 ("otherwise ...") like parser-created customized built-in elements, and all autonomous custom elements, do.

Sorry if I'm missing some history here. I'd be interested to hear what Mozilla thinks about this since I see code for custom elements including customized built-in elements landing in Firefox. We are implementing this in Blink now and we can implement this step but it seems semantically odd.

**Comment by annevk** [comment]
@smaug---- @inscriber?

**Comment by domenic** [comment]
This seems like just an oversight/bug. I will prepare a PR to remove it.
