### ISSUE TITLE
Copying global `<style>` textContent into ShadowDOM roots is not ideal.

### ISSUE THREAD

**Issue by trusktr** [WICG/webcomponents#609]
f.e., suppose we're using bootstrap's global stylesheet `<link>`ed in the `<head>`. What's the best way to make those styles apply inside shadow roots (i.e., [this question](http://stackoverflow.com/questions/25211111))?

Is using `<link>` inside the shadow root to link to the same style sheet the best way in the case of external styles?

But, suppose the global style is defined in `<style>` element. In that case what's the best way to apply those styles to all (or some) shadow roots?

Things I've tried when using global `<style>`:

- Global style in the head:

  ```html
  <style>
  :root {
    all: inherit;
  }
  </style>
  ```
  
  EDIT: :root is not a shadow root, but the root-most element of the document, so obviously this is wrong.
- Adding this into the shadow root causes some inheritance, but I'm not sure it's the desired way to do it, as everything will inherit from its parent, but I simply want everything to inherit global styles, not styling from parents:
  
  ```html
  <style>
    * {
      all: inherit
    }
  </style>
  ```
  
  But this also styles the `<style>` element!

Is there perhaps a need for a way to apply global stylesheets? Would something like the following make sense, or would it defeat ShadowDOM encapsulation?

```html
<style global="true"></style>
```

Libraries like Bootstrap or Foundation give us simple global stylesheets, so web-platform features like CSS custom properties don't really help here.

**Comment by trusktr** [comment]
Or, suppose the global style is defined in `<style>` element. Then in that case what's the best way to apply those styles to all (or some) roots?

**Comment by domenic** [comment]
This doesn't appear to be a spec issue, but instead a question about how to program. I'd suggest taking such questions to StackOverflow.com or similar forums, as this issue tracker is an inappropriate place for them.

**Comment by trusktr** [comment]
@domenic If there's no clear way to do this, then this may in fact be a spec issue.

One solution in the community (by Polymer) is to make ["style modules"](https://www.polymer-project.org/1.0/docs/devguide/styling#style-modules), and with the `dom: 'shadow'` option to `window.Polymer`, that boils down to simply copying the `textContent` into the shadow root.

Is that the best solution currently, just copying `textContent` into a `<style>` element of a shadow root? If so, it seems a little hacky and wasteful (imagine having hundreds or thousands of elements that all have styles copied into them). So, this may in fact be a spec issue, although I'm not yet sure what the ideal solution would be.

Honestly, allowing questions to be posted in the very place where something is developed is most helpful for community members. The cost of having to add `question` labels to such issues is not very high compared to the gain for the community around a technology.

On top of that, people at StackOverflow [think the question is too broad to exist on SO](http://stackoverflow.com/questions/40695324/best-way-to-distribute-global-styles-into-shadow-roots?noredirect=1#comment68620332_40695324), which means my question will be closed if that sentiment gets enough votes.

**Comment by trusktr** [comment]
There, does that new title make this more of a spec discussion?

**Comment by domenic** [comment]
I'll let the shadow DOM editor decide, but in general no, asking how to do something is not an appropriate spec issue. You're meant to be reporting issues with the current spec, not asking how to program.

**Comment by domenic** [comment]
Let me reopen this, since it I should be letting the shadow DOM editor handle maintaining the shadow DOM issue backlog. Apologies.

**Comment by tomalec** [comment]
@trusktr I have rephrased your SO question, so hopefully it would not be too broad to exist there http://stackoverflow.com/questions/40973471/how-to-apply-common-css-styles-to-many-shadow-roots-at-once

**Comment by rniwa** [comment]
Is this a request for a new feature? Or is this simply asking how to accomplish this with the existing API?

**Comment by tomalec** [comment]
For me, it would be great to find the way to accomplish this with existing API, but in the way that does not look like a hack or have a big performance penalty.

1. The lest hacky solution that comes to my mind is to add `<link>`  in (custom) elements Shadow DOM - http://jsbin.com/samegefezo/2/edit?html,output. But it sends a request for shared stylesheet twice.

2. Solution that could solve double request problem is to wrap it with HTML Imports, but it becomes hacky, and HTML Imports are rather unsafe to rely on.

3. Another solution that could solve double request problem is to use `<style>@import` http://jsbin.com/veruki/edit?html,output 
The question is could we rely on such de-duping, and if importing it twice is relatively cheap.

4. We can also request shared style together with custom-element definition, then in constructor clone it to the shadow root. But it works only for custom elements and adds a question, how expensive such cloning would be.

We could also talk about cases when those styles are to be applied externally - not by the author of shadow root. Then, I would say that if you want to break the element's Shadow DOM encapsulation, hacking is what you want. Therefore, personally, I would feel fine to rely on hacky solution.


If there is no good solution to achieve that with current spec, I would ask for new feature.
If there is, I would say it would be nice to have it mentioned in an example in spec. 
The popularity of CSS frameworks shows that it's potentially a common case.
Even tough, latest specs (Web Components, CSS Grid, etc.) reduces the need for them, we can safely assume developers will keep using frameworks, anyway.

**Comment by hayatoito** [comment]
You might be interested in Constructable Stylesheet Objects.
See http://tabatkins.github.io/specs/construct-stylesheets/

I think that is the only idea we have, as of now.
Since it looks there is an issue tracker for the spec (https://github.com/tabatkins/specs/issues/), let me close this issue.

**Comment by whitslack** [comment]
In case anyone else searching for an answer comes across this thread, here is what I ended up doing, which works great:

```javascript
const copiedStyleSheet = new CSSStyleSheet();
document.addEventListener("DOMContentLoaded", () => {
    if (copiedStyleSheet.replace)
        copiedStyleSheet.replace(
            [...document.styleSheets].flatMap(
                sheet => [...sheet.cssRules].map(rule => rule.cssText)
            ).join(" ")
        );
    else
        for (const sheet of document.styleSheets)
            for (const rule of sheet.cssRules)
                copiedStyleSheet.insertRule(rule.cssText, copiedStyleSheet.cssRules.length);
});

class MyCustomElement extends HTMLElement {
    constructor() {
        super();
        this.attachShadow({ mode: "open" });
        this.shadowRoot.adoptedStyleSheets = [copiedStyleSheet];
    }
}
```

It's wasteful in that it constructs an independent stylesheet containing copies of all of `document`'s stylesheet rules, but at least all shadow roots can share the one `copiedStyleSheet` instance. It would be really fantastic if we could do `shadowRoot.adoptedStyleSheets = [...document.styleSheets]`, but alas, the spec inexplicably does not allow that.
