### ISSUE TITLE
[idea] [shadow-dom] Provide a version number on shadow roots so they can be distinguished.

### ISSUE THREAD

**Issue by trusktr** [WICG/webcomponents#610]
For example, `root.version`should return `0` if the root was created with `createShadowRoot()`, `1` or `2` if it was created with `attachShadow` and is one or the other.

I am making a library, and I'd like for that library to work with roots of varying versions while the API stabilizes (it is currently possible in Chrome to create v0 or v1 roots and my library can't assume which version the end user uses). For example:

```js
if (root.version == 'v0') {
    // find and observe <content> elements
}
else if (root.version == 'v1') {
    // find and observe <slot> elements
}

if (root.version == 'v1' || root.version == 'v2') {
    // use slot.assignedNodes()
}

if (root.version == 'v2') {
    // use slot.assignedElements()
}
```

**Comment by trusktr** [comment]
Seems like v2 will be backwards compatible with v1? If so, then there will probably be just v0 and v2 roots when v2 is out.

**Comment by matthewp** [comment]
Since no other DOM APIs have versioning I don't think it makes sense to add it here, personally.  I think normal feature detection is the way to go, as with everything else in the browser.

**Comment by domenic** [comment]
Furthermore, we generally don't add features to the standard to work around the fact that one vendor ships a nonstandard API.

**Comment by trusktr** [comment]
@matthewp If you could demonstrate such feature detection here, that'd be awesome: http://stackoverflow.com/questions/40004064

**Comment by matthewp** [comment]
You should post a bug on Chromium if they don't provide a way to detect v0 vs. v1 and you need that, they own createShadowRoot(), not this repo.  There's no reason to need to know v1 vs. v2 vs. v3, that I can think of at least.

**Comment by annevk** [comment]
Agreed. Standards should not consider proprietary implementations (unless they need to be implemented by all for some reason, but that is not the case here).

**Comment by trusktr** [comment]
I'd also like to suggest that since a non-standard feature is shipped,
shipping an additional non-standard feature for detecting differing
versions of the first non-standard feature would also be highly appreciated
in light of the fact that living real world applications might be using one
version or the other.

**Comment by andyearnshaw** [comment]
Why bother supporting v0 in your library? It's not widely implemented and
you'll likely be supporting browsers with no shadow DOM long after market
share of v0-only browsers has dwindled to nothing.

Adding a version identifier isn't very useful beyond detecting v0 as future
versions will always be backwards compatible and feature detection is the
best way to work with new specs.

**Comment by matthewp** [comment]
@trusktr Shadows created via attachShadow and createShadowRoot are both instancesof ShadowRoot, so I don't think there *is* any way to distinguish them.

**Comment by trusktr** [comment]
> Why bother supporting v0 in your library?

Because if I document that my library "is compatible with ShadowDOM" when I release documentation soon, I would not want even one person finding otherwise. 

I suppose I might just say "compatible with ShadowDOM v1 and up" at this point.
