### ISSUE TITLE
Shadow DOM Example 1 without slot attribute applied, select by class

### ISSUE THREAD

**Issue by lcchueri** [WICG/webcomponents#626]
Hi,

in "Example 1", section  "8. Shadow DOM Example", it comes with slot applied, as indicated in "issue 1".

What about in "Example 4" apply it imperatively :

function makeShadowTree(storyList)
{
    **storyList.querySelectorAll('il.breaking').forEach(function(element) {element.slot = 'breaking';});**
    var root = storyList.attachShadow({mode: 'open'});
    root.appendChild(createStyle());
    root.appendChild(createStoryGroup('breaking', 'breaking'));
    root.appendChild(createStoryGroup('other', ''));
}

So, it would be more similar of approach of version 0: <content select="breaking"> , isolating original HTML from knowing about internal about the slots in "example 2".

Any achanges in presentation in "Example 2" will not imply in changes in "Example 1".

**Comment by hayatoito** [comment]
Thank you for the feedback. Yeah, that might be another approach. However, that would decrease the readability of the example, I am afraid.

I don't have a strong opinion, either. I am not planning to update the example.  Could we leave the example as is? This is a minor issue, I guess.

**Comment by lcchueri** [comment]
Hi,

"Example 1" would be:

```
<ul class="stories">
    <li><a href="//example.com/stories/1">A story</a></li>
    <li><a href="//example.com/stories/2">Another story</a></li>
    <li class="breaking"><a href="//example.com/stories/3">Also a story</a></li>
    <li><a href="//example.com/stories/4">Yet another story</a></li>
    <li><a href="//example.com/stories/5">Awesome story</a></li>
    <li class="breaking"><a href="//example.com/stories/6">Horrible story</a></li>
</ul>

```
without of  "slot", as indicated at "Issue 1"

**Comment by hayatoito** [comment]
Thanks, however, I wont fix this, as you proposed.

> storyList.querySelectorAll('il.breaking').forEach(function(element) {element.slot = 'breaking';});

I am afraid that this would mislead the usage of slots, which should have a declarative nature.
e.g. If we append host's children later, after the shadow tree is created, inserted elements are never assigned to a slot, in a proposed approach.
Thus, I am not a fan of adding slot attribute to host's children in an imperative way, in our example, because people might think that this is a recommended approach.
