### ISSUE TITLE
[Shadow]: Shadow trees should somehow contain base URL information (bugzilla: 22255)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#63]
Title: [Shadow]: Shadow trees should somehow contain base URL information (bugzilla: 22255)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=22255

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=22255#c0
_Dimitri Glazkov_ wrote on 2013-06-03 23:06:43 +0000.

See this thread for context: http://lists.w3.org/Archives/Public/public-webapps/2013AprJun/thread.html#msg782

I like Jonas' internal state idea.

**Comment by annevk** [comment]
See discussion in https://www.w3.org/Bugs/Public/show_bug.cgi?id=20976 for why this additional state is not sufficient and still leads to weird results. I think we should close this issue until someone comes with a coherent proposal for how this should work.

**Comment by annevk** [comment]
Closing per my own comment.
