### ISSUE TITLE
Using slot="" attribute on <link rel="import"> (Imports without JavaScript)

### ISSUE THREAD

**Issue by jourdanritchey** [WICG/webcomponents#636]
I suppose this is somewhat a proposal, but I'm also wondering whether this is a good idea if I were to make it possible with JavaScript…

The documentation available for the `slot` attribute indicates that this attribute may be placed on any element. In the interest of working with partials loaded via `<link rel="import">`, I'm wondering whether the `slot` attribute with its associated `<slot>` element could be used to simplify the placement of partials by only needing to write declarative HTML:

```
<html>
  <head>
    <link rel="import" href="partial.html" slot="partial" />
  </head>
  <body>
    <slot name="partial">No content found.</slot>
  </body>
</html>

```

…whereby `<body>` is acting as a Shadow DOM for imports.

Are there potential problems with doing this that I'm not seeing?

It seems to me that having to require JavaScript for basic compositional functionality is overkill. Has the possibility of enabling HTML imports for basic composition — without requiring authors to write and users to load JavaScript — been considered?

**Comment by rniwa** [comment]
What you're proposing here is very much a different content attribute than what shadow DOM uses `slot` attribute. There has been numerous discussions about adding a declarative syntax for defining a custom element, or simply attach a shadow tree. I don't think it's useful to jump onto a concrete proposal like this without first enumerating the list of use cases and requirements we'd like to satisfy.

**Comment by hayatoito** [comment]
Yeah, it sounds that the usage of `<slot>` in a proposal is totally different the current usage of `<slot>`.

If you have the list of use cases and a concrete proposal, I would recommend not to use `<slot>` there , unless there is a relationship with the current usage of `<slot>`.

**Comment by TakayoshiKochi** [comment]
@jourdanritchey I think you misunderstand HTML Imports - it is not for importing inline HTML snippet.
HTML Import (`<link rel="import" href="..">`) loads referenced HTML file but its document is separate
from the main document, although they are connected via `link.import` property. So it doesn't work as what you expected in Chrome. Usually primary usage for HTML Imports is to load a definition of web components, by running `<script>` in the imported HTML file, using some `<template>`s inside its body. HTML Imports' contents are never rendered unless some script explicitly moves the content into the main document.

What you proposed is like what [SSI](https://en.wikipedia.org/wiki/Server_Side_Includes) (server-side include) does in client side, without `<iframe>`?

**Comment by jourdanritchey** [comment]
@rniwa @hayatoito @TakayoshiKochi Thank you all for your comments and suggestions!

@TakayoshiKochi You are correct, server-side includes are **exactly** what I'm looking to replicate client-side. Thanks for inferring that!

Although I might be misunderstanding the purpose of HTML Imports, it seems to me that *a very common use case* for web components, generally, will be to replicate server-side includes — whether or not encapsulation is considered. The ability to compose HTML from different files (i.e. 'partials') together into a single page (without `<iframe>`) seems to be one of the possibilities developers see web components providing, e.g:

- http://starcounter.io/html-partialsincludes-webcomponents-way/
- https://www.webcomponents.org/element/Juicy/juicy-html
- https://www.linkedin.com/pulse/html-5-web-components-john-peters
- http://www.baasic.com/2014/10/18/Designing-for-the-future-Baasic-meets-Polymer-part-1/
- https://teamtreehouse.com/community/do-html-partials-exist

Further, I believe that in many situations imported `<template>` content *will* be attached to the main document. A web component, after all, will likely in many cases be an encapsulated piece of UI.

Composing an HTML file from many smaller HTML files (i.e. 'partials') is, I believe, a *very* common requirement, and *web components are and will be looked at as a way to do this*. @rniwa mentioned there have been discussions about a declarative syntax for defining custom elements and attaching a Shadow DOM. Has there been any discussion, or is any work being done, on a declarative syntax that would allow us to achieve "client-side includes" without running JavaScript?

**Comment by domenic** [comment]
I don't see what this has to do with web components. You can just use iframe. If you have feature requests to make iframe better, you can file them on https://github.com/whatwg/html/issues (after searching for existing such requests, of course). But there's no point in reinventing iframe using web components just because web components are cool and new.

**Comment by jourdanritchey** [comment]
@domenic Composing an HTML file from many smaller HTML 'partials' (or 'components', albeit sans the custom tag) is not the same thing as embedding completely separate pages. An `<iframe>` introduces a separate browsing context. What I'm publicly thinking about here is **same browsing context** — whereby CSS and JavaScript loaded by the main page will apply to the composed result as though it were a single page to begin with.

This isn't about "cool and new", but rather what is **already seemingly being done** with web components (see links in my previous comment). I don't think I am misunderstanding web components, I just think that there must be a reason for four separate specifications (e.g. we don't need to use custom elements just because we want to use Shadow DOM), and that some ***inevitable*** uses might be supported without requiring JavaScript. What I'm trying to do is contribute some thinking, and hopefully gain and share some understanding, around how these new standards might be used with respect to a specific case (i.e. 'client-side includes') that is *apparently already being pursued by developers*.

Thanks for the comment!

**Comment by hayatoito** [comment]
@jourdanritchey 
This request seems to the dup of https://github.com/w3c/webcomponents/issues/280.
Could you have a chance to look at it ?
