### ISSUE TITLE
'attributeChangedCallback' not working with a data attribute on Firefox or Edge

### ISSUE THREAD

**Issue by liam-swinney** [WICG/webcomponents#637]
I've created a custom element with the 'attributeChangedCallback' function and added a attribute to the 'observedAttributes'.

The component is ran, however when changing the data attribute, the callback does not fire which it does for none data attributes in Firefox and Edge.  This also works in Chrome and Safari.

The issue was spotted in both Firefox 52.0.2 (64-bit) and 53.0 (64-bit) (Mac), this previously used to work however I cannot get the version it was working in.  It was also spotted in Microsoft Edge 38.14393.0.0

Please find the example code below and observe the console.  (the version of webcomponent polyfill does not make a difference, I've tried them between  1.0.0-rc.1 and 1.0.0-rc.8)

https://jsfiddle.net/t8rbucvd/7/

I've also filed a report to mozilla and edge forums incase this is not an issue with webcomponents

**Comment by annevk** [comment]
Could you point to the bug reports here? Judging from your code this is a bug in implementations.

**Comment by liam-swinney** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1357730
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11715748/

**Comment by domenic** [comment]
Firefox and Edge don't implement custom elements yet, so this is probably an issue with the web components polyfill, and thus off-topic for this repository.

**Comment by Nashorn** [comment]
on FF 60.5.1 -- 'attributeChangedCallback' callback on a custom component never fires for observed attrbs. I understand the polyfill fixes this, no?

**Comment by rniwa** [comment]
> On FF 60.5.1 -- 'attributeChangedCallback' callback on a custom component never fires for observed attrbs. I understand the polyfill fixes this, no?

If it works on other browsers, it likely is a bug in Firefox. Please file a bug on https://bugzilla.mozilla.org/

This is not an appropriate forum to report bugs in specific Web browser engine implementation (e.g. any bug in WebKit, Blink, or Gecko), nor is an appropriate forum to inquire questions about a specific JS library or a polyfill. Such questions should be directed towards Web browser engine implementors and JS library / polyfill authors & maintainers.

**Comment by annevk** [comment]
I think this was fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1334051 FWIW, so if this is still broken a bug + test would be great.
