### ISSUE TITLE
Consider adding CSS reset attributes

### ISSUE THREAD

**Issue by drazenbaric** [WICG/webcomponents#638]
Something useful could be added, which I personally used is custom CSS reset attribute in `html` tag.
If we used `<html style-reset>` it would add link to a CSS reset file. By default (if none is selected or is style-normalize) it adds a link to normalize file. Such attributed do not need attribute="value" as they are just booleans if option is selected.

**Comment by matthewp** [comment]
You're proposing an attribute that automatically adds a stylesheet link? What's the URL for this stylesheet link, where does the user specify this?  What's the advantage of this over adding the link yourself?

Also, is this really related to webcomponents? Doesn't sound like it, but I might be misunderstanding.

**Comment by drazenbaric** [comment]
Why would you need to worry about a CSS normalize file? By default it gets included for you. Such links should be located on the browsers itself if they are planning to support such function. If user wants to use his own link to such file he would write it down inbetween tags `<html style-normalize="www.domain.com/filepath">`

Edit: Just realized you edited your comment, as it is stated on the offical site ["Web components are based on existing web standards. Features to support web components are currently being added to the HTML and DOM specs, letting web developers easily extend HTML with new elements with encapsulated styling and custom behavior."](https://www.webcomponents.org/introduction) this might not a new element, however it is a little exstension which helps developers.

**Comment by matthewp** [comment]
If it is included in the browser then what is the benefit of this feature over just changing the default styles? I think you'd have more success with the latter (though that might be hard too) as you could convince them to change them one-by-one rather than blessing a "reset" mode stylesheet. I'm my experience following standards browser vendors really dislike adding modes for things.

**Comment by drazenbaric** [comment]
That was not the case for other web components, was not it? Is that the only problem you think there is regrading the suggestion?

**Comment by matthewp** [comment]
What do you mean? What you're proposing is not a web component but is a special attribute that turns on a css stylesheet, no? Or am I misunderstanding the proposal?

**Comment by rniwa** [comment]
You can accomplish this by a single line of CSS4:
```css
* {all: revert;}
```
See https://developer.mozilla.org/en-US/docs/Web/CSS/all
