### ISSUE TITLE
Extending from a component with shadow dom may be difficult.

### ISSUE THREAD

**Issue by trusktr** [WICG/webcomponents#643]
Suppose a `SomeComponent` component defines a `<some-component>` custom element, and it makes it's own shadow dom to hide internals, and accepts children (maybe the component is a layout component that distributes children into the internal layout).

Then another author wants to `class NewComponent extends SomeComponent {}`. 

It seems difficult for extending author to extend SomeComponent and perhaps modify internals, or something.

---

Or suppose `SomeComponent` from `some-library` has no shadow DOM at first (it is not a layout component), and another author wants to extend `SomeComponent` to add a shadow dom and make a layout using `SomeComponent`. Perhaps `SomeComponent` is a drawing element (like a-frame's webgl drawing elements), and depending on what you put as children inside the `<some-component>` element something will be rendered.

The extending author is able to extend SomeComponent to make a new element that can accept children and distribute them into the tree. The distributed children, let's say, are also drawing elements (like a-frame's).

Now, suppose the original author of `SomeComponent` decides that in order to render something properly, it needs to use a shadow dom.

For example, the original author of `SomeComponent` might decide to use shadow dom in order to hide the fact that a canvas is used for rendering, so that the end user (or other app code) only sees HTML elements in the DOM, not the internal canvas used for rendering.

This suddenly breaks the extending author's new component, without an obvious way to fix the problem.

A possible workaround can be for the extending author to make a wrapping element with a new shadow dom, place the original `<some-component>` inside the new outer element's shadow dom, with a slot inside of the some-component, then distribute children into the some-component so that some-component can further distribute as needed.

But, this might not work in all cases.

---

It seems like shadow dom components may be difficult to extend. Any thoughts on patterns that you may have already encountered?

**Comment by hayatoito** [comment]
It sound a general issue when using a inheritance pattern.

We already removed multiple shadow roots from the spec, which we introduced to support a part of *extend* use case. We are unlikely to bring it back to the spec. It failed.

**Comment by trusktr** [comment]
I can see how multiple-shadow-dom fails, because it will change completely how the component works, and may just completely break everything. In other words, an extending author would have to replicate internal functionality, not just add custom functionality, and that may be super complicated (especially for a 3D rendering component, for example).

I will be experimenting in this area, because the custom elements I'm making at [`infamous`](http://github.com/trusktr/infamous) are having WebGL rendering soon where the canvas is hidden in the shadow dom, and may also have a translation from nested DOM hierarchy outside of the shadow dom to an internal flat DOM inside the shadow dom for CSS 3D rendering without `preserve-3d`. So I will post back any patterns I may find.

**Comment by Mr0grog** [comment]
FWIW, I‘d agree with @hayatoito that this isn’t really a Custom Elements or Shadow DOM problem—it’s a generalized problem with inheritance. It’s usually called the “fragile base class” problem and there’s lots of literature on it.

@rniwa actually brought this issue up specifically as a reason for not wanting to implement inheritance of built-in elements last year: https://github.com/w3c/webcomponents/issues/509#issuecomment-230700060 (He focused on “Liskov Substitution,” which is a fairly specific flavor of the broader “fragile base class” issue.) The browser isn’t a dependency your code controls, so it can’t feasibly provide many of the tools and signals, like semantic versioning, that are meant to address the problem.

**Comment by trusktr** [comment]
I guess it is what it is. If the super class exposes the shadow dom on a property, f.e. `this.root`, then the extending class can modify the internals (hopefully, without ruining private super code that may be relying on a particular structure to be present in the shadow root).
