### ISSUE TITLE
[css-scoping]  Confusion regarding >>> 

### ISSUE THREAD

**Issue by Ollie-w** [WICG/webcomponents#644]
In the current version of the spec (Editor’s Draft, 19 June 2017) it says:

"For a stylesheet in the outer document, the selector x-foo >>> span selects all three of <span> elements: #top, #not-top, and #nested." 

Yet in the very next paragraph it says it "is invalid when used in stylesheets".

**Comment by hayatoito** [comment]
You might want to see https://github.com/w3c/webcomponents/issues/78.
In short:
- CSS selectors used in stylesheets => CSS dynamic profile
- CSS selectors used in querySelector-sh => CSS static profile

**Comment by Ollie-w** [comment]
Well in the current Chrome Canary implementation,  the selector x-foo >>> span in a stylesheet selects nothing, seeing as its invalid and only works for making selections in Javascript, so the wording in the spec is wrong.

**Comment by Ollie-w** [comment]
querySelector() is not a stylesheet
