### ISSUE TITLE
Custom Elements as submittable elements

### ISSUE THREAD

**Issue by nektro** [WICG/webcomponents#646]
The HTML spec currently defines [submittable elements](https://html.spec.whatwg.org/#category-submit) as the set list of elements that can be used in a form to submit data. That list being `<button>`, `<input>`, `<output>`, `<select>`, and `<textarea>`.

Is there currently any way to make a Custom Element could add itself to this list?

**Comment by annevk** [comment]
No, I think this is a duplicate of #187.

**Comment by domenic** [comment]
Indeed.
