### ISSUE TITLE
Explanation required : Why only direct children of the shadow host can be slotted? 

### ISSUE THREAD

**Issue by praveenpuglia** [WICG/webcomponents#647]
Over at the CSSWG drafts repository, [I asked the same question](https://github.com/w3c/csswg-drafts/issues/1530) and was told that that's how the Shadow DOM spec is defined. 

So, I couldn't find any explanation as to why it's restricted to only direct children. Should it be mentioned in the spec somewhere as a note or a reference link which expands on it?

Please tell me if I am missing something really obvious.

**Comment by annevk** [comment]
I think in part it was done because of performance concerns and in part to make the initial version a bit simpler to implement.

**Comment by hayatoito** [comment]
@praveenpuglia  See https://github.com/w3c/webcomponents/issues/574, which you might be interested in.
