### ISSUE TITLE
Form autocompletion is broken when form elements are encapsulated within a Shadow DOM

### ISSUE THREAD

**Issue by vlukashov** [WICG/webcomponents#649]
HTML forms have a number of features based on association between controls and forms. To name a few: [form autofill](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill), [implicit submit](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission) and [form submission](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#form-submission) in general.

As browsers start to ship native Shadow DOM implementations it becomes apparent that Shadow DOM is not designed to work well with these HTML form features. E.g. it has been already noted in this repo, that the way how forms submission works with custom elements should be improved (see the issue #187).

This issue is to improve the web components specs in the part of _forms autofill_ and _implicit submit_. Please either specify how that should work across Shadow DOM boundaries, or make an explicit statement that these features of HTML forms are not expected to work with Shadow DOM.

Here is a live demo for this issue: https://github.com/vlukashov/polymer-forms. It shows that in the browsers that support the native Shadow DOM (Chrome, Safari) neither _forms autofill_ nor _implicit submit_ work as expected.

However, without a spec it is difficult to call this behavior a browser bug.

**Comment by domenic** [comment]
The spec is pretty clear on this. Form autofill:

> A user agent prefilling a form control must not discriminate between form controls that are in a document tree and those that are connected; that is, it is not conforming to make the decision on whether or not to autofill based on whether the element's root is a shadow root versus a Document.

Implicit submit:

> A form element's default button is the first submit button in tree order whose form owner is that form element.

Form submission:

> Let controls be a list of all the submittable elements whose form owner is form, in tree order.

(Elements in the shadow tree are not in tree order.)

So, closing this, as the spec is already as clear as can be. But happy to continue discussing in the closed thread.

You may also enjoy https://github.com/w3c/webcomponents/issues/187.

**Comment by vlukashov** [comment]
Thanks for a detailed reply in under ten minutes!

Did I understand it right, that since elements in a shadow DOM are not in the tree order, they have no way of participating in most of HTML forms features (including _autofill_ and _implicit submit_)?

Then what would be a way to create custom elements that should be able to work with forms? Maybe you can give some pointers for where to look.

**Comment by domenic** [comment]
> they have no way of participating in most of HTML forms features (including _autofill_ and _implicit submit_)?

Autofill works. It's implicit submit and form submission that don't.

> Then what would be a way to create custom elements that should be able to work with forms? Maybe you can give some pointers for where to look.

Well, you can create a custom element without using shadow DOM to encapsulate the form parts. But assuming you want to use shadow DOM, what we need here is basically #187 for form submission.

I haven't heard of anyone requesting implicit submit support. For that I suppose you could use keydown event listeners and such to emulate the behavior.

**Comment by ibinev** [comment]
I understood most of the issue, but I see [this ](https://codepen.io/kjantzer/pen/rNBEyEP)example and I can't figure out how this is fine behaviour on Chrome.
When the input is in shadow DOM and autofill options appear only hovering upon any of them "ghost selects" the one.
Is there any workaround to avoid this behvaior on Chrome, or the only way is to disable autofill (which I don't want)
