### ISSUE TITLE
Resolve the worker path within a link rel="import"

### ISSUE THREAD

**Issue by rianby64** [WICG/webcomponents#651]
If you've a worker within a ```<link rel="import">``` then its address will be resolved without taking in count CORS.

Let's suppose the following:
_index.html_ (from //localhost)
```html
<!doctype html>
<html>
  <head>
    <link rel="import" href="//far-away.co/import.html">
  </head>
</html>
```

_//far-away.co/import.html_
```html
<!doctype html>
<html>
  <head>
    <script src="script.js"></script>
  </head>
</html>
```

_script.js_
```javascript
'use strict';
new Worker('a-worker.js');
```

I see that browser resolves the _script.js_ from ```//far-away.co/script.js```, but the worker won't resolve as expected. Browser will resolve its address from ```//localhost/a-worker.js``` instead of ```//far-away.co/a-worker.js```.

What the spec states about the worker's URL?

**Comment by snuggs** [comment]
Interesting catch @rianby64

**Comment by rianby64** [comment]
/cc @annevk @domenic 

As I expect as HTML consumer, if I do import then all files within this import may be relative, and their URL should be resolved against the import's URL. Scripts work as expected. But workers don't :disappointed:

**Comment by annevk** [comment]
HTML Imports is a Chrome-only feature that's no longer being developed. We recently closed all bugs against it and the same applies to this bug as far as I can tell.

**Comment by rianby64** [comment]
That's a shame. How to do import then?

**Comment by TakayoshiKochi** [comment]
If you consider this a problem for Chrome, please file a new bug at http://crbug.com.

Apologies for the hassle, but as @annevk said, the standards will not make further effort to fix
existing implementation or spec bugs.
