### ISSUE TITLE
Consider defining inertness in terms of the composed tree

### ISSUE THREAD

**Issue by TakayoshiKochi** [WICG/webcomponents#653]
Manually migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24379

---

_Matt Falkenhagen_ wrote on 2014-01-24 06:26:11 UTC
(This bug was originally https://www.w3.org/Bugs/Public/show_bug.cgi?id=22898)

In the HTML spec, any node that is not an ancestor or descendant of the active modal dialog is marked inert.[1]

It seems the ancestor/descendant relation should be based on the composed tree (a Shadow DOM concept). Otherwise, children that have been transposed into a modal <dialog>'s subtree are considered inert, although they are rendered as if they are real children of the <dialog>. This is surprising to the user interacting with the dialog.

I guess to spec the desired behavior, the HTML spec will need to make a mention of the Shadow DOM spec.

See also https://code.google.com/p/chromium/issues/detail?id=269842

[1] http://www.whatwg.org/specs/web-apps/current-work/multipage/editing.html#inert

---

_Ian 'Hixie' Hickson_ wrote on 2014-01-24 23:32:33 UTC
The way I did this in XBL, IIRC, was to define a merged tree that CSS works on, and to say that certain algorithms work on that tree instead of the "real" tree.

I'd rather not have to mention shadow trees in all the relevant algorithms in HTML, at least not until the Shadow DOM stuff is far more established (at which time maybe we would just merge it into the DOM spec and update HTML accordingly).

---

_Anne_ wrote on 2016-03-23 12:55:26 UTC

Matt, is this something you'd be willing to patch in HTML?

**Comment by annevk** [comment]
This issue should probably move to HTML? (Also, to be clear, Ian's comment above no longer applies. Shadow trees are far enough along that we do want the relevant algorithms to be modified.)

**Comment by domenic** [comment]
This is *almost* fixed already, as at some point we did switch to shadow-including descendants for the dialog case. Remaining potential issues:

- tests
- browsing context container inertness uses vague unlinked term "in that Document", implying iframes are broken here.

**Comment by annevk** [comment]
Should maybe mark https://github.com/whatwg/html/issues/1175 as fixed then if that's true?

**Comment by annevk** [comment]
`<iframe>`s are https://github.com/whatwg/html/issues/763 btw and most certainly broken.

**Comment by domenic** [comment]
I guess so, and I'll move the iframe inertness issue into 763. So we can close this and 1175.
