### ISSUE TITLE
Allow custom `input` element content

### ISSUE THREAD

**Issue by baocang** [WICG/webcomponents#659]
Input has an agent shadow where can't access by javascript, But there anyway to access it or apply custom template for it, can make it works with custom content?
As there we can use file api to access file, a lot way to create custom input, why do not open the api to make easy to custom the build in element?
```javascript
this.shadowRoot.querySelector('#calendar');
```
or
```html
<input type="datetime">
    <template slot="calendar"></template>
</input>
```

**Comment by hayatoito** [comment]
Three is no such APIs, as of now.

**Comment by annevk** [comment]
Browsers don't want to open up `<input>` elements as it's too complicated to do so in a way that works across all the various platforms. Instead the idea is that you create `<my-own-input>`.
