### ISSUE TITLE
Clarify upgrading element's properties

### ISSUE THREAD

**Issue by bedeoverend** [WICG/webcomponents#660]
I've come across what I think is a bug in CE Upgrades, however I'm not sure if it's intended, and apologies if I'm missing something in the spec.

Basically, if my Custom Element definition uses a getter and setter, these will be overwritten with the corresponding property _value_ that exists on the element when that element is upgraded, losing those getters and setters. See [this JSBin](http://jsbin.com/ribused/2/edit?js,console) - the element that's created before defining CE loses its getters and setters, being instead replaced with the initial `foo` value.

Reading the [upgrades definition](https://html.spec.whatwg.org/multipage/custom-elements.html#upgrades) I can't quite figure out intended behaviour? Not sure if in fact I should just be reporting this to Blink / WebKit.

**Comment by rniwa** [comment]
I don't know what you mean by "the element that's created before defining CE loses its getters and setters", as far as I read that JSBin code, there's nothing unexpected happening there.

Could you describe what behavior you're expecting, and what you're observing?

**Comment by bedeoverend** [comment]
Sure, so these are the steps:

- The first element I create it before I've defined `my-element`
- I then set the property `foo` to `a`, that's all fine and expected
- I then define `my-element` and so my `elementBeforeUpgrade` is now upgraded to the definition
- I then set the property `foo` on it again, I expect it to call the setter, but it doesn't

The property definition for `foo` on the element is now just a `value`, without the getters and setters. I'd them to be set as the definition for `foo` when `my-element` is defined.

~~Apologies for the confusing example, I'll try come up with a more practical and understandable one.~~ _Edit:_

[This JSBin](http://jsbin.com/raguhah/edit?js,console) might illustrate my problem a little better. The label element has property getter / setters for 'name' which just map to it's attribute. Before the element is upgraded, I've set the 'name' property, after upgrading, it doesn't use the getters and setters, so the attribute / property goes out of sync.

**Comment by rniwa** [comment]
Ah, this is because when you did `label.name = 'John Doe'`, you created a property on `label` element object itself. So even the element got later upgraded, the only thing that had happened is that `label.__proto__` now has `name`. Since any property lookup first looks at the property of the context object first, and then go through properties on the prototype chain, you're effectively overshadowing the property on `XLabel.prototype.name` by `label.name`.

Here's basically what's happening behind the scenes using just pure JS:
```js
class Element {}
class XLabel extends Element {
    get name() { return this._name; }
    set name(name) { this._name = name; }
}
let beforeUpgrade = new Element;
beforeUpgrade.name = 'foo'; // <- 1. This created "own" property on beforeUpgrade
beforeUpgrade.__proto__ = XLabel.prototype; // 2. This introduces name getter on the prototype chain.
beforeUpgrade.name; // <- 3. This still gets the "own" property added in (1).
```

**Comment by bedeoverend** [comment]
Ahh ok. Thanks very much for clarifying. Ok so there's nothing untoward happening here? This is expected behavior both from the browser and specifications point of view?

Understand if it is, it's a nasty gotcha but I can't think of any other way to handle it.

**Comment by baocang** [comment]
Something lucky we can avoid this by using custom element after they defined.
```javascript
customElements.whenDefined('x-label').then(() => { /* .. */ });
```
But I still like after upgrading, pass the value to custom element, but property keep custom element defined.

**Comment by rniwa** [comment]
Yes, this behavior is expected per ECMAScript & HTML specifications.

**Comment by bedeoverend** [comment]
Understood. Thanks very much for taking the time to clarify :)
