### ISSUE TITLE
Upstreaming Custom Elements and Outstanding v1

### ISSUE THREAD

**Issue by snuggs** [WICG/webcomponents#664]
Related: #661 _(nay #377, #495)_

Standard: https://w3c.github.io/webcomponents/spec/custom/

Outstanding Issues in DOM and HTML: 
- [ ] https://github.com/whatwg/dom/labels/custom%20elements
- [ ] https://github.com/whatwg/html/labels/topic%3A%20custom%20elements

Outstanding Issues in This Repository:
 - [ ] https://github.com/w3c/webcomponents/issues?q=is%3Aopen%20label%3Av1%20label%3Acustom-elements

Current Vendor Status:
[Google Chrome](https://www.chromestatus.com/feature/4642138092470272) _(shipped [`#594918`](https://bugs.chromium.org/p/chromium/issues/detail?id=594918))_
[Mozilla Firefox](https://platform-status.mozilla.org/#custom-elements) _(in progress [`#889230`](https://bugzilla.mozilla.org/show_bug.cgi?id=889230))_
[Safari _(autonomous CE only)_](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html#//apple_ref/doc/uid/TP40014305-CH12-SW5) _(resolved/fixed [`#150225`](https://bugs.webkit.org/show_bug.cgi?id=150225))_
[Opera](https://dev.opera.com/blog/opera-41/#web-components-custom-elements-v1) _(shipped [`#594918`](https://bugs.chromium.org/p/chromium/issues/detail?id=594918))_
[Edge _(Under Consideration)_](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/customelements)
[Internet Explorer _(Not Supported)_](http://caniuse.com/#feat=custom-elementsv1)

Also have taken the liberty to update MDN Browser Compatibility for Custom Elements ~as they still reflected Custom Elements v0 vendor status. From adopter feedback was causing some confusion in the wild~:
- [x] Update [`MDN CustomElementRegistry.define()` matrix](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define)
- [x] Update [`MDN CustomElementRegistry.get()` matrix](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/get)
- [x] Update [`MDN CustomElementRegistry.whenDefined()` matrix](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined)

I hope this at least helps initiate moving forward.

Peace :peace_symbol:

**Comment by annevk** [comment]
I removed the detailed checklist as every section in Custom Elements is already upstreamed. There's just some remaining things that need to be fixed. Hope that's okay. Will make a couple further tweaks.

**Comment by snuggs** [comment]
More than ok @annevk. Tweak away! The due diligence was actually a needed exercise _(stored personal copy)_. I would have been cool even with a close. What is the next step after that? Assuming updating html & dom spec respectively where needed? Are there links to this where we can ref this issue?

Thanks in advance.

**Comment by annevk** [comment]
I'm not sure I understand. The main purpose of this issue as I see it is to inform those interested of the work that remains to be done on custom elements v1.

**Comment by rniwa** [comment]
This work has been completed.

**Comment by snuggs** [comment]
@rniwa thank you so much!
