### ISSUE TITLE
delegatesFocus is in bad shape

### ISSUE THREAD

**Issue by jyasskin** [WICG/webcomponents#666]
There's no IDL defining `delegatesFocus` in https://w3c.github.io/webcomponents/spec/shadow/, and it didn't make it to https://dom.spec.whatwg.org/#dictdef-shadowrootinit. Is it intentionally being removed, or does it need to be rescued?

**Comment by TakayoshiKochi** [comment]
Sorry about that - I'm on it to upstream the Shadow DOM spec (user interaction and focus section) to WHATWG HTML spec.

**Comment by TakayoshiKochi** [comment]
It will be tracked at whatwg/html#2013.
