### ISSUE TITLE
[Shadow]: elementFromPoint should return the host when you hit a Text node (bugzilla: 24638)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#67]
Title: [Shadow]: elementFromPoint should return the host when you hit a Text node (bugzilla: 24638)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24638

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24638#c0
_Elliott Sprehn_ wrote on 2014-02-12 23:33:23 +0000.

Seeing as we don't want to throw an exception when you put a Text node as a child of a ShadowRoot, we should at the very least return the host element so that hit testing in a ShadowRoot that has direct text children does something sensible.

We probably need to make it return the host if you hit a border/background color too?

(this also makes sense since you can querySelector(":host"), so the host really is in the same scope as the ShadowRoot.

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24638#c1
_Daniel Freedman_ wrote on 2014-02-12 23:57:33 +0000.

This is conceptually similar to the fact that document.elementFromPoint will return the documentElement if the x,y target is within the document's bounds.

---

comment: 2
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24638#c2
_Anne_ wrote on 2014-02-13 10:05:18 +0000.

Instead of defining it this way, someone should define hit testing on layout boxes.

---

comment: 3
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=24638#c3
_Anne_ wrote on 2014-02-13 10:05:59 +0000.

I'm not sure we want radically different behavior for elementFromPoint() and mouse events and :hover and such for instance.

**Comment by hayatoito** [comment]
I think we should return the most nearest ancestor element in the composed tree, rather than the host element. A text node can be distributed to somewhere.

**Comment by hayatoito** [comment]
I think we can agree that we should return "composed parent" if TextNode is the result of the _hit testing_.

However, if the TextNode is distributed, the composed parent of the TextNode might be an element in a child tree. In such a case, the composed parent should not be returned in terms of encapsulation.

We should adjust the result.

**Comment by hayatoito** [comment]
Hmm. I realized that we can get the same result by the following the simple rule. We don't need a complex rule for adjusting. :)
1. If the TextNode is the child of the shadow root, return the shadow host of it.
2. Otherwise, return the parent element.

However, in the case of issue #131, we can use just the composed parent of the TextNode because we don't need to worry about encapsulation.

**Comment by annevk** [comment]
Please include a node in that hit testing section that this eventually needs to be part of some general hit testing specification.

**Comment by hayatoito** [comment]
What do you mean by "include a node"? I'm assuming that we should include "Note" to explain we should upstream this eventually, correct?

**Comment by annevk** [comment]
Yeah.

**Comment by hayatoito** [comment]
I got it. Let me add a note.
