### ISSUE TITLE
Detecting finally-distributed nodes.

### ISSUE THREAD

**Issue by trusktr** [WICG/webcomponents#675]
This is a new issue for the idea mentioned here: https://github.com/w3c/webcomponents/issues/611#issuecomment-265013833.

It is useful to know when nodes are finally-distributed (knowing when distributed nodes ultimately rest at a slot and are not forwarded to any more slots).

**Comment by hayatoito** [comment]
@trusktr 
Could you clarify what is new? Is there any new idea which hasn't been discussed in #611?

**Comment by trusktr** [comment]
That issue is closed, so this re-opens it.

I think this is a legitimate issue, useful for people who want to do custom rendering, as they need to render based on the composed tree.

Leaving this issue open and providing needed API changes will encourage custom elements authors (f.e. A-Frame authors) to support ShadowDOM (currently A-Frame does not work with ShadowDOM), and thus will help bring Web Components forward.

---

Do you prefer discussion in closed threads? People often associate closed threads with ideas that were decided to be not worth pursuing.

**Comment by hayatoito** [comment]
> That issue is closed, so this re-opens it.

Unless there is a new idea or a new proposal, I don't think filing a new issue for a closed issue is a good idea. It's still unclear to me that what is new in this issue.

**Comment by annevk** [comment]
Closing per last comment.
