### ISSUE TITLE
[proposals]: Template Instantiation typo?

### ISSUE THREAD

**Issue by danatcofo** [WICG/webcomponents#690]
Source: [Template Instantiation Proposal](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Template-Instantiation.md)
@rniwa for the following examples

```
// Template content is '`<section><h1>{{name}}</h1>Email: <a href="mailto:{{email}}">{{email}}</a></section>'`
shadowRoot.appendChild(template.createInstance({name: "Ryosuke Niwa", email: "[rniwa@webkit.org](mailto:rniwa@webkit.org)"}));
```
and 
```
let content = template.createInstance({name: "Ryosuke Niwa", email: "[rniwa@webkit.org](mailto:rniwa@webkit.org)"});
shadowRoot.appendChild(content);
...
content.update({email: "[rniwa@apple.com](mailto:rniwa@apple.com)"});
```
the use of `"[rniwa@webkit.org](mailto:rniwa@webkit.org)"` here seems like some markdown was inadvertently introduced.  I do not see any other usages of this value in other examples.

**Comment by stramel** [comment]
Dupe of #689

**Comment by danatcofo** [comment]
I'd call first, but it just wouldn't be true.  Thanks stramel, TimvdLippe's ticket hadn't been posted before I started writing this.
