### ISSUE TITLE
[templates] Do not specify template binding syntax in spec, make configurable 

### ISSUE THREAD

**Issue by vidhill** [WICG/webcomponents#697]
Library authors and users will all have their own preferences and opinions on binding syntax,
Rather that specifying  `{{foo}}` or ${bar} within the proposal, 
the Constructor should allow the user to configure the syntax..

In the same way that angularJS supports such..
This proposal could easily getting diverted by nitpicking on such issues..

**Comment by rniwa** [comment]
I don't think we should do this. One of the major motivation for standardizing template API is to make the parsing easy & predictable. With a configurable syntax, we won't be able to apply various CSP constraints or protect websites against XSS.

**Comment by domenic** [comment]
At TPAC, all participants in the discussion that spoke up agreed that we should decide on a standardized syntax. Note that we did not insist on double-curlies, but did insist on nothing that would require escaping when using in conjunction with CSS or JS. (So, single-curlies and dollar-curlies are no good.)

Given @rniwa's good reasons above, let's close this, as we can be pretty confident the proposal will not end up with configurable syntax.

**Comment by vidhill** [comment]
Fair enough
