### ISSUE TITLE
[Shadow]: Isolated Shadow trees (bugzilla: 28442)

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#72]
Title: [Shadow]: Isolated Shadow trees (bugzilla: 28442)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28442

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28442#c0
_Dimitri Glazkov_ wrote on 2015-04-08 15:51:26 +0000.

From https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0052.html

"Isolated shadow DOM. This is the idea of having a "DOM worker" so
that instead of ten <iframe>s with ten globals you can have one global
with ten somethings. This would give applications more parallelization
opportunities and would hopefully enable a large number of companies
from moving away of the practice of using cross-origin <script> with
all its security implications."

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28442#c1
_Dimitri Glazkov_ wrote on 2015-04-08 16:26:07 +0000.

Old proposal: https://docs.google.com/document/d/1V7ci1-lBTY6AJxgN99aCMwjZKCjKv1v3y_7WLtcgM00/edit?pli=1

**Comment by annevk** [comment]
This needs a clear proposal.
