### ISSUE TITLE
Sequential Focus Navigation uses undefined "For each node tree TREE in DOCUMENT" 

### ISSUE THREAD

**Issue by smaug----** [WICG/webcomponents#720]
I couldn't find the definition what "For each node tree TREE in DOCUMENT" might mean.
I assume it means light DOM + all the shadow DOMs (nestedly)

**Comment by hayatoito** [comment]
fyi: @TakayoshiKochi

**Comment by annevk** [comment]
See also https://github.com/whatwg/html/issues/2013.

**Comment by domenic** [comment]
This is fixed in https://github.com/whatwg/html/pull/4735
