### ISSUE TITLE
Selectors in ::slotted don’t change specificity

### ISSUE THREAD

**Issue by surma** [WICG/webcomponents#728]
Let’s say I have a custom element `<my-elem>`, that has the following shadow root markup:

```html
<style>
  /* ... */
  ::slotted(main) {
    background-color: blue;
  }
  ::slotted(*) {
    background-color: red;
  }
</style>
<slot></slot>
```

```html
<my-elem>
  <div>DIV!</div>
  <main>MAIN!</main>
  <aside>ASIDE!</aside>
</my-elem>
```

I’d argue most authors would expect `<main>` to have a blue background color, but it is in fact red. It seems the selectors passed to `::slotted()` don’t affect specificity. So precedence is defined by order of declaration.

Was this intentional? If so, why? If not, is it changeable?

([Live demo](https://slotted-specificity.glitch.me/), [code](https://glitch.com/edit/#!/slotted-specificity))

**Comment by emilio** [comment]
I think per spec pseudo-elements are only counted when computing specificity (there's no special rule for ::slotted):

https://drafts.csswg.org/selectors-4/#specificity-rules

That being said there are already other issues with specificity `css-scoping` selectors, and also of selectors that allow more than one argument: https://github.com/w3c/csswg-drafts/issues/2158, https://github.com/w3c/csswg-drafts/issues/1027, https://github.com/w3c/csswg-drafts/issues/1915.

It'd be nice to get this part of the spec properly defined to match both reality and / or what authors expect...

**Comment by annevk** [comment]
It's probably best to file this against w3c/csswg-drafts, especially now Selectors is getting some editor attention. This is not really something that this repository can solve.

**Comment by surma** [comment]
Understood.

**Comment by surma** [comment]
Continued in w3c/csswg-drafts#2271
