### ISSUE TITLE
Input requested on ARIA/HTML role parity

### ISSUE THREAD

**Issue by LJWatson** [WICG/webcomponents#729]
The ARIA WG is working on achieving [role parity](https://github.com/w3c/aria/projects
) with HTML. They've [asked for help](https://lists.w3.org/Archives/Public/public-aria/2018Feb/0006.html) from the Web Components community.

Initial triage has already been done, and elements put into several categories. A summary is given below, but please check the [original request](https://lists.w3.org/Archives/Public/public-aria/2018Feb/0006.html) for more information and better explanations.
 
#### Elements with no ARIA role and no accessibility API mapping
* `Assumption:` if no platform has a need for them to be mapped, there is no need to create a role for them.
* `Input needed:` Confirmation that the assumption is valid.
* `Issue for comment:` w3c/aria#693

#### Elements with an ARIA role and with consistent accessibility API mappings
* `Assumption:` we have parity and no new roles are needed.
* `Input needed:` confirmation that the assumption is valid.
* `Issue for comments:` w3c/aria#694

#### Elements with no ARIA role and without consistent accessibility API mappings
* `Assumption:` a role is probably needed, but a generic role will suffice.
* `Input needed:` confirmation that the assumption is valid.
* `Issue for comments:` w3c/aria#698

#### Elements with an ARIA role but without a 1-1 accessibility API mapping
* `Assumption:` some elements may need a dedicated role, others may not.
* `Input needed:` consensus on the elements that need new roles, and those that don't (and that can be added to w3c/aria#694)
* `Issue for comments:` w3c/aria#696

#### Elements without an ARIA role  but with consistent accessibility API mappings
* `Assumption:` if all platforms map them, all platforms need them, and thus a role is needed for each.
* `Input needed:` consensus on which elements need a dedicated role, and which can use the generic role (mentioned above).
* `Issue for comments:` w3c/aria#697

**Comment by annevk** [comment]
Thanks for raising this, I think @domenic adequately captured the concerns around ARIA and custom elements. Since everything already has a dedicated issue I'll close this so discussion can continue there.
