### ISSUE TITLE
If a Custom Element is used as a placeholder for an HTML heading, would it be interpreted as a heading for SEO purposes?

### ISSUE THREAD

**Issue by TimeDropsSB** [WICG/webcomponents#730]
I have a Custom Element, `<our-h1>`.  `<our-h1>` is a placeholder such that when it is upgraded, it becomes a regular `<h1>` through DOM manipulation - that is, `<our-h1>` is replaced with `<h1>`.

In terms of SEO, would the constructed `<h1>` from `<our-h1>` be the same as if it was using an `<h1>` directly?

**Comment by domenic** [comment]
It depends on whether the search engine in question understands custom elements. That's not going to have a single easy answer, unfortunately.

**Comment by trusktr** [comment]
This is a problem that can be solved by [Element Behaviors](https://github.com/w3c/webcomponents/issues/727). See the section "augment existing HTML applications".

If you don't really _need_ to extend from a heading element, you can just apply functionality as a behavior. (see working implementation)

**Comment by trusktr** [comment]
> It depends on whether the search engine in question understands custom elements.

Probably that's a problem right now. F.e., @Sylphony, a bot that just reads HTML strings (without looking at the JavaScript DOM objects) could not possibly know that `<my-header-1>` is an extended `<h1>`.

**Comment by annevk** [comment]
This is already addressed by the standard: https://html.spec.whatwg.org/#custom-elements-autonomous-drawbacks.

**Comment by OvermindDL1** [comment]
And for note, this is one thing that the `is="..."` solves.
