### ISSUE TITLE
Consider adding user-defined attributes to slots

### ISSUE THREAD

**Issue by billmoser** [WICG/webcomponents#733]
I apologize in advance for my lack of proper terminology.  Here's the issue:  I have an element A, whose template has a slot.  I'd like to fill the slot with another element, B, annotated with attributes which can only be computed by A.  For example, A's template looks like this:
```
<slot name='myslot' cool-attr='Super Cool'></slot>
```
I would like to use element A like this:
```
<element-a>
  <element-b slot='myslot'></element-b>
<element-a>
```
with element B picking up the attribute cool-attr.
I don't see how to do this currently.  I can achieve the effect I want easily with some code generation, but it would be great to see this as a 'native' feature

**Comment by hayatoito** [comment]
Can this be resolved by a user-land solution?

e.g.
```javascript
slot.addEventListener('slotchange', (_) => {
  slot.assignedElements().forEach((e) => {
    e.setAttribute('cool-attr', slot.getAttribute('cool-attr'));
  });
});
```

**Comment by billmoser** [comment]
Hmm, not sure how it will play with Polymer data binding, but that looks like it might work.  I'll give it a try.
