### ISSUE TITLE
elementsFromPoint behavior is unclear

### ISSUE THREAD

**Issue by smaug----** [WICG/webcomponents#735]
Per spec ShadowRoot.elementsFromPoint may return an array which contains host element several times, since retargeting is done for each elements in the result array.

**Comment by hayatoito** [comment]
FYI. There is an issue filed for csswg: https://github.com/w3c/csswg-drafts/issues/556

I remember that Blink recently tried to fix the broken behavior in https://chromium-review.googlesource.com/c/chromium/src/+/808446.

> Per spec ShadowRoot.elementsFromPoint may return an array which contains host element several times, since retargeting is done for each elements in the result array.

That sounds fair argument.

@TakayoshiKochi  @rakina WDYT? Does blink return an array which has several same elements for elementsFromPoint?

**Comment by rakina** [comment]
Right now elementsFromPoint doesn't return multiple identical elements (https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/dom/TreeScope.cpp?sq=package:chromium&l=276)

**Comment by smaug----** [comment]
Yeah, it doesn't and Gecko won't either, but per spec it should. So implementing the API is guess work atm.

**Comment by rniwa** [comment]
Closing this in favor of https://github.com/WICG/webcomponents/issues/736
