### ISSUE TITLE
How to determine when to do the manual allocation when using Imperative Shadow DOM Distribution API

### ISSUE THREAD

**Issue by caridy** [WICG/webcomponents#746]
Proposal: https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Imperative-Shadow-DOM-Distribution-API.md

@hayatoito, the proposal is looking good from the perspective of doing the manual allocation, but it is not providing enough information, or end-to-end examples.

My main concern is that with `manual`, no auto allocation/slotting will be done, which probably mean that you cannot use `slotchange` event to observe changes in your slots. The question is, how will the developer know when to do the manual allocation? And the answer cannot be: "just use mutation observer".

I think from our side, we will like to have a reliable signal for changes on the light tree so the allocation can happen accordingly. The most dummy example could be:

```html
<fancy-menu>
     <menu-item>one</menu-item>
     <menu-item>two</menu-item>
</fancy-menu>
```

When adding a new menu item (e.g.: `myFancyMenuElement.appendChild(menuItemThreeElement)`), we should be able to detect that operation, and take care of the manual slotting on the spot.

/cc @diervo

**Comment by annevk** [comment]
Could you please mention this in https://github.com/whatwg/html/issues/3534 instead. Seems good to keep discussion a bit centralized for now.

**Comment by caridy** [comment]
too many notifications to keep up with everything :), will post there!
