### ISSUE TITLE
changing slot text node is overly verbose

### ISSUE THREAD

**Issue by o-t-w** [WICG/webcomponents#753]
API wise, including text in a slot seems a lot nicer than using an attribute. 
e.g.
`<copy-paste>lorem ipsum</copy-paste>`
is preferable to
`<copy-paste text="lorem ipsum"></copy-paste>`

However, if the user of the custom element then wants to programmatically change the text, the only way seems to be the ultra-verbose `document.querySelector('copy-paste').shadowRoot.querySelector('slot').assignedNodes()[0].data = 'something completely different'`

The `slotchange` event does not fire when this change occurs, so I guess the only way to monitor the change is with MutationObserver? (which again feels like an OTT solution).

Why does `slotchange` not include changes to node contents?

**Comment by tomalec** [comment]
`document.querySelector('copy-paste').shadowRoot.querySelector('slot').assignedNodes()[0].data = 'something completely different'` will not work for closed shadow roots, plus will not work with distributed content, more nodes, etc.

AFAIK, you need to check/attach MutationObserver to all `slot.assignedNodes({flatten: true})` as you may have text divided into many nodes and distributed from nested slots.

**Comment by tomalec** [comment]
> Why does slotchange not include changes to node contents?

I believe, it's consistent as it also does not include changes made to non-text nodes, like changing character data or attributes of distributed `<div>`s.

For some of my elements, I took slightly different approach. I use wrapper pattern, for example:
```html
<decorative-editor>
   <!-- could be distributed from more slots-->
   <textarea>Lorem ipsum</textarea>
</edcorative-editor>
```

So, as a to use my custom element (`<decorative-editor>`) I require to insert the content into single `textarea`. Then, I only observe single element. May look limitting, but at least give a bit of progressive enhancement, and simplifies code a little.

**Comment by rniwa** [comment]
What are use cases of mutating text nodes assigned to a slot?  That comes off as an anti-pattern.  If a component exposes an API to set some text (e.g. label) for rendering, then that text should exist as a regular text node inside the component's shadow tree.  If the API is instead a slot, then the user of the component should be mutating the text nodes directly.

There is literally no builtin element that behaves this way. e.g. `textarea` element uses its children as the default value of the text field but what the setter of [`defaultValue`](https://html.spec.whatwg.org/multipage/form-elements.html#dom-textarea-defaultvalue) does is to replace all children of `textarea` element, not just text nodes.

**Comment by o-t-w** [comment]
@rniwa Well my component is copying the text to the clipboard, so clearly it needs to be able to get at the text for this use case.

**Comment by tjmonsi** [comment]
Hi @o-t-w 

Actually slot change fires whenever you do an `innerHTML` or `textContent` equation on the component. So I don't understand why it is verbose...

See example

```
const { HTMLElement, customElements } = window;

class Component extends HTMLElement {
  static get is () { return 'simple-component'; }

  constructor () {
    super();
    const shadow = this.attachShadow({ mode: 'open' });
    this._boundSlotChange = this._slotChange.bind(this);
    this._slot = document.createElement('slot');
    this._slot.addEventListener('slotchange', this._boundSlotChange);
    shadow.appendChild(this._slot);
  }

  _slotChange (e) {
    console.log(e);
    console.log(this._slot.assignedNodes());
  }
}

if (!customElements.get(Component.is)) {
  customElements.define(Component.is, Component);
} else {
  console.warn(`${Component.is} is already defined somewhere. Please check your code.`);
}
```

and then I fired it off with

```
const simple = document.querySelector('simple-component'); // given that it is in the document
simple.innerHTML = 'Hello there'
```

I just tested it now

![image](https://user-images.githubusercontent.com/2645718/41973765-8a44f2e6-7a48-11e8-88e3-a7d4d0a32512.png)

![image](https://user-images.githubusercontent.com/2645718/41973831-bb1819a2-7a48-11e8-8ce9-811ae84ba7b3.png)

**Comment by o-t-w** [comment]
I managed to solve my problem... Thanks :)

**Comment by o-t-w** [comment]
[MDN](https://developer.mozilla.org/en-US/docs/Web/Events/slotchange) says about slotchange:

> Note that it doesn't fire if you change the node contents — only if you change (e.g. add or delete) the actual nodes themselves.

I have found that to be accurate. 

For the record, my copy to clipboard function looked like 
```
		connectedCallback() {
			let copyButton = this.shadowRoot.querySelector('button');
			let svg = this.shadowRoot.querySelector('svg');

			var cp = document.querySelector('copy-paste')
			var slot = cp.shadowRoot.querySelector('slot');
			var textToCopy = slot.assignedNodes()[0]
			let span = this.shadowRoot.querySelector('span');

			function selectElementContents(el) {
    		var range = document.createRange();
    		range.selectNodeContents(el);
    		var sel = window.getSelection();
    		sel.removeAllRanges();
    		sel.addRange(range);
			}

			function copyText() {
			selectElementContents(textToCopy);
   		 	document.execCommand('copy');
    		svg.classList.remove('opacity0');
      	 	setTimeout(function() {
         	svg.classList.add('opacity0');
       		}, 700); 
		}

			copyButton.addEventListener('click', copyText);
			span.addEventListener('click', copyText);
		}	
```

**Comment by tjmonsi** [comment]
I see, node contents... meaning:
```
<simple-component>
  <div>
    Hello
  </div>
</simple-component>
```

to 

```
<simple-component>
  <div>
    Hello 2
  </div>
</simple-component>
```

I get it :)

**Comment by annevk** [comment]
Closing this as it's suggested as resolved above. If there's still something to be done here please leave a comment.
