### ISSUE TITLE
[CSS Scoping] Support two types of pseudo-elements with ::slotted() selectors

### ISSUE THREAD

**Issue by Ronaldo-Maciel** [WICG/webcomponents#756]
Is not working when I use two pseudo-elements in ::slotted expression. Example:

`::slotted(.element):last-child:after {
     content: none;
}`

But is working when:
`::slotted(.element):after {
    content: '-';
}`

Is there a way to solve this?

**Comment by emilio** [comment]
`:last-child` and `:after` are different things. `:last-child` is a pseudo-class, not a pseudo-element.

**Comment by Ronaldo-Maciel** [comment]
Oh, sorry.
But, should it is working when I use both together in a rule CSS right?
Example:
https://stackoverflow.com/questions/2351623/combining-css-pseudo-elements-after-the-last-child

**Comment by morbidick** [comment]
@Ronaldo-Maciel just guessing but since `last-child` is a pseudo-class shouldnt the first rule be `::slotted(.element:last-child):after { content: none; }`

**Comment by Ronaldo-Maciel** [comment]
Perfect @morbidick it is working now. Sorry for the mistake.
