### ISSUE TITLE
deepRelatedTargets and touch.deepTargets

### ISSUE THREAD

**Issue by hayatoito** [WICG/webcomponents#76]
Title: [Shadow] investigate if there should be deepRelatedTargets and touch.deepTargets (bugzilla: 28560)

Migrated from: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28560

---

comment: 0
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28560#c0
_Olli Pettay_ wrote on 2015-04-26 18:25:01 +0000.

.

---

comment: 1
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28560#c1
_Hayato Ito_ wrote on 2015-04-27 01:30:58 +0000.

The motivation is that we can't use event.deepPath[0] in either case, isn't it?

---

comment: 2
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28560#c2
_Anne_ wrote on 2015-04-27 03:06:02 +0000.

Yes, these properties are changed but their original values are not otherwise exposed.

(There might also be value in event.deepTarget as a clearer event.deepPath[0], just like event.target is short for a conceptual event.path[0]...)

---

comment: 3
comment_url: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28560#c3
_Anne_ wrote on 2015-04-27 11:25:19 +0000.

Also:

  deepOffsetX/Y

**Comment by hayatoito** [comment]
I think it's easy to add deepRelatedTarget and so on. However, I'd like to see the actual use cases.
Let me defer this to v2. If someone has a use case, please update this issue. I'm okay to have this in v1.

**Comment by annevk** [comment]
What worries me a bit is that we have a weird mix with retargeting while also wanting event delegation. If you want actual event delegation, you want the original values for all these properties (also offset*).

**Comment by hayatoito** [comment]
Let me close this issue since there is lack of interest. Please feel free to reopen if you are interested in.

**Comment by annevk** [comment]
What I would like to know is how you can use `deepPath` without the corresponding `deepRelatedTargets`, etc. Perhaps the latter is only relevant for a subset of events, but it seems the model is inconsistent here.

**Comment by hayatoito** [comment]
I think deepPath is useful itself, without having `deepRelatedTarget`.
For consistency, we might want to have `deepRelatedTarget`, however, I have never heard a demand for that.
I'm okay to have `deepRelatedTarget`, but I thought we should add it when we hear a demand for that.

**Comment by hayatoito** [comment]
Let me keep this open. If someone has a use case for `deepRelatedTarget`, please let us know that.

**Comment by annevk** [comment]
Maybe it's just that we don't have many usage scenarios for `relatedTarget`?

**Comment by annevk** [comment]
I think you were right for closing this. The inconsistency still puzzles me, but that's not enough reason to keep this open. Apologies.
