### ISSUE TITLE
Web Components F2F topics for 2018 TPAC

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#763]
Now we have [3-hour slot at TPAC](https://github.com/w3c/WebPlatformWG/issues/120).

We should gather topics which needs F2F discussion. I propose the following topics:
 - [<iframe> and the History API](#184)
 - [How should various document internal references work when SVG is being used in shadow DOM](#179)
 - [How to define APIs only for custom element authors](#758)

Please add more topics to this issue so that each browser vendor can have their internal discussion upfront (this seems to have helped a lot in the past).

@domenic @tkent-google @hayatoito @annevk @bzbarsky @smaug---- @travisleithead

**Comment by smaug----** [comment]
Selection handling + shadow DOM is something to figure out, https://github.com/w3c/webcomponents/issues/79

**Comment by hayatoito** [comment]
I think we need to have a consensus on:
- [It is unclear how directionality should be inherited into Shadow DOM](https://github.com/whatwg/html/issues/3699)

And other attributes:
- [It is unclear how title attribute should work in Shadow DOM](https://github.com/whatwg/html/issues/3821)
- https://w3c.github.io/webcomponents/spec/shadow/#attributes

**Comment by hayatoito** [comment]
One more topic candidate:
- [elementFromPoint, elementsFromPoint, and caretPositionFromPoint should not return an element inside a shadow tree](https://github.com/w3c/csswg-drafts/issues/556)

cc: @rakina, @yosinch

**Comment by hayatoito** [comment]
One more: [Custom Elements Default Style](https://github.com/w3c/webcomponents/issues/468)

cc: @emilio, @lilles

**Comment by rniwa** [comment]
I'd add my own: [Presence of disconnectedCallback can expedite an invocation of connectedCallback](https://github.com/w3c/webcomponents/issues/760)

**Comment by matthewp** [comment]
@rniwa That link is to your own comment in this issue, I assume this was a mistake and you intended to link to something else?

**Comment by abdonrd** [comment]
@rniwa @matthewp probably to: https://github.com/w3c/webcomponents/issues/760

**Comment by rniwa** [comment]
Yeah, fixed.

**Comment by rniwa** [comment]
[DOM APIs which replace all children end up firing superfluous slotchange events](https://github.com/w3c/webcomponents/issues/764)

**Comment by annevk** [comment]
https://github.com/w3c/webcomponents/labels/needs%20implementer%20interest are presumably worth discussing as well, in particular "CSS Modules".

And then there's always all of these:

* https://github.com/search?q=label%3A%22topic%3A+shadow%22+is%3Aopen
* https://github.com/search?q=label%3A%22topic%3A+custom+elements%22+is%3Aopen

**Comment by rniwa** [comment]
Given how many topics we have to discuss, I suggest we schedule some time on Wed breakout sessions if we don't get an extra room on Tuesday.

**Comment by chaals** [comment]
(Note that we have requested extra space if there is any... but there are no guarantees)

**Comment by rniwa** [comment]
Here's the list of explicitly requested topics. Please call out other issues as you see fit. Let's finalize the list beforehand so that each participating organizations can have their own internal discussion first.

 - [<iframe> and the History API](https://github.com/w3c/webcomponents/issues/184)
 - [How should various document internal references work when SVG is being used in shadow DOM](https://github.com/w3c/webcomponents/issues/179)
 - [How to define APIs only for custom element authors](https://github.com/w3c/webcomponents/issues/758)
 - [Selection APIs for Shadow DOM](https://github.com/w3c/webcomponents/issues/79)
- [It is unclear how directionality should be inherited into Shadow DOM](https://github.com/whatwg/html/issues/3699)
- [It is unclear how title attribute should work in Shadow DOM](https://github.com/whatwg/html/issues/3821)
- [elementFromPoint, elementsFromPoint, and caretPositionFromPoint should not return an element inside a shadow tree](https://github.com/w3c/csswg-drafts/issues/556)
- [Provide a lightweight mechanism to add styles to a custom element](https://github.com/w3c/webcomponents/issues/468)
- [Presence of disconnectedCallback can expedite an invocation of connectedCallback](https://github.com/w3c/webcomponents/issues/760)
- [Mechanism for setting the tabindex focus flag without sprouting tabindex attribute?](https://github.com/w3c/webcomponents/issues/762)
- [HTMLElement.prototype.offsetParent leaks a node inside a shadow tree](https://github.com/w3c/webcomponents/issues/497)
 - [Scoped Custom Element Registries](https://github.com/w3c/webcomponents/issues/716)

More issues:
* https://github.com/search?q=label%3A%22topic%3A+shadow%22+is%3Aopen
* https://github.com/search?q=label%3A%22topic%3A+custom+elements%22+is%3Aopen

**Comment by rniwa** [comment]
Propsing two more topics:
- [Mechanism for setting the tabindex focus flag without sprouting tabindex attribute?](https://github.com/w3c/webcomponents/issues/762)
- [HTMLElement.prototype.offsetParent leaks a node inside a shadow tree](https://github.com/w3c/webcomponents/issues/497)

**Comment by rniwa** [comment]
One more:
 - [Scoped Custom Element Registries](https://github.com/w3c/webcomponents/issues/716)

**Comment by rniwa** [comment]
Hi all, thanks to @LJWatson, we now have a room available on Tuesday in addition to Friday but the room for Tuesday doesn't have a teleconference capability.

Do people have preference over which topic to be discussed on Tuesday (in-person only) vs. Friday (allows remote participation)?  Please comment here ASAP.

**Comment by chaals** [comment]
The space we have is for **THURSDAY** (9.00 - 13.30). Also note that it is a fairly small room (space for ~15, no phone bridge)... /@rniwa

**Comment by rniwa** [comment]
@chaals : Ah, okay. Thanks for correcting my mistake & clarification!

**Comment by yoichio** [comment]
I want to have a brainstorming session for "(better) Selection APIs for Shadow DOM" .

**Comment by rniwa** [comment]
@yoichio : [Selection APIs for Shadow DOM](https://github.com/w3c/webcomponents/issues/79) is listed as a topic.

**Comment by rniwa** [comment]
Here's my proposal for Thursday / Friday breakdown. Please raise your concerns if the topic you care about is placed in a wrong day. I've tried to place all accessibility & CSS related topics on Friday since Houdini and ARIA WG are meeting on Thursday.

Thursday morning :
 - [<iframe> and the History API](https://github.com/w3c/webcomponents/issues/184)
 - [Selection APIs for Shadow DOM](https://github.com/w3c/webcomponents/issues/79)
 - [Scoped Custom Element Registries](https://github.com/w3c/webcomponents/issues/716)
 - [It is unclear how title attribute should work in Shadow DOM](https://github.com/whatwg/html/issues/3821)
 - [Presence of disconnectedCallback can expedite an invocation of connectedCallback](https://github.com/w3c/webcomponents/issues/760)
 - Issue triaging as the time permits

More issues:
  * https://github.com/search?q=label%3A%22topic%3A+shadow%22+is%3Aopen
  * https://github.com/search?q=label%3A%22topic%3A+custom+elements%22+is%3Aopen

Friday afternoon:
 - [How should various document internal references work when SVG is being used in shadow DOM](https://github.com/w3c/webcomponents/issues/179)
 - [elementFromPoint, elementsFromPoint, and caretPositionFromPoint should not return an element inside a shadow tree](https://github.com/w3c/csswg-drafts/issues/556)
 - [Provide a lightweight mechanism to add styles to a custom element](https://github.com/w3c/webcomponents/issues/468)
 - [HTMLElement.prototype.offsetParent leaks a node inside a shadow tree](https://github.com/w3c/webcomponents/issues/497)
 - [Mechanism for setting the tabindex focus flag without sprouting tabindex attribute?](https://github.com/w3c/webcomponents/issues/762)
 - [How to define APIs only for custom element authors](https://github.com/w3c/webcomponents/issues/758)
 - [It is unclear how directionality should be inherited into Shadow DOM](https://github.com/whatwg/html/issues/3699)
 - Other exploratory ideas

**Comment by rniwa** [comment]
Update: [How should various document internal references work when SVG is being used in shadow DOM](https://github.com/w3c/webcomponents/issues/179) may need to move to Monday afternoon if Tab Atkins can't attend it on Thursday. If you have any concerns about this agenda change, please comment here ASAP.

**Comment by hayatoito** [comment]
Let me share [the brief summary of “Google’s position”](https://docs.google.com/document/d/1HP4f-vYZ29uUlHDqxHdftoAFBnhQZ-UFnks3m5bRfA4/edit?usp=sharing)  on each topics of Web Components at TPAC 2018.

Please consider this *one-pager* as just on-going efforts. Anything is not finalized, and can be changed, given recent increased discussion on several topics.
