### ISSUE TITLE
Effect of removing 'Object.setPrototypeOf(MyEl, HTMLElement)' while using ES5 prototype pattern for web components

### ISSUE THREAD

**Issue by IbrahimTanyalcin** [WICG/webcomponents#766]
@justinfagnani, your example works as well if we remove the <code>Object.setPrototypeOf(MyEl, HTMLElement);</code>  Why is it necessary anyway?

This works:

```js
function MyEl() {
  return Reflect.construct(HTMLElement,[], this.constructor);
}

MyEl.prototype = Object.create(HTMLElement.prototype);
MyEl.prototype.constructor = MyEl;
/*Object.setPrototypeOf(MyEl, HTMLElement); --> is there any need for this?*/

MyEl.prototype.connectedCallback = function() {
  console.log('my-el connected');
};
customElements.define('my-el', MyEl);
document.body.appendChild(document.createElement('my-el'));
```

_Originally posted by @justinfagnani in https://github.com/w3c/webcomponents/issues/587#issuecomment-378684197_

**Comment by rniwa** [comment]
What's happening with this issue? What's the question being asked?

**Comment by IbrahimTanyalcin** [comment]
For webcomponents, I was just experimenting with @justinfagnani post, and it seems to work properly even if we remove <code>Object.setPrototypeOf(MyEl, HTMLElement);</code>.

I am aware that for some reason (maybe to override default <code>apply</code> or <code>call</code> etc), DOM constructor's \_\_proto\_\_ points to its prototype's constructor's prototype owner (ex: <code>Element.\_\_proto\_\_ === Element.prototype.\_\_proto\_\_.constructor</code> goes to <code>Node</code>)  instead of Function.prototype, for instance:

<code>
HTMLElement.__proto__ === Element //true
Element.__proto__ === Node  //also true
</code>

Normally, I would expect a constructor's \_\_proto\_\_ to point to <code>Function.prototype</code> immediately instead of going through \_\_proto\_\_ chain and finally through Event.\_\_proto\_\_, so I "presume" @justinfagnani used <code>Object.setPrototypeOf(MyEl, HTMLElement);</code> for consistency in the way the Browser laid out their inheritence. 

Question is this:
> Apart from "static" properties not being inherited (such as <code>Element._someStaticProperty === MyEl._someStaticProperty</code>) by the custom element, is there any side effect of removing <code>Object.setPrototypeOf(MyEl, HTMLElement);</code> all together?

**Comment by justinfagnani** [comment]
@IbrahimTanyalcin the title of this issue is incredibly long and not clear...

If you're asking about ES5 subclassing patterns, setting or not setting the prototype of the constructor to its super constructor has exactly the same effect with custom elements as it does for any other subclass - statics aren't inherited. Since `Element` and `HTMLElement` don't add anything to `Node`s static interface, and the one's on `Node` are generally used as direct references off of `Node`, this probably won't have much of a noticeable effect. It is correct and what a compiler would output though.

**Comment by IbrahimTanyalcin** [comment]
- Great thank you! So it wouldn't affect anything then. 
- I changed the title btw. 
- So to recap, removing Object.setPrototypeOf(MyEl, HTMLElement) will not cause any issues. If there is nothing to add, I'll close the issue. Thank you for your time.

**Comment by IbrahimTanyalcin** [comment]
So to recap, removing Object.setPrototypeOf(MyEl, HTMLElement) will not cause any issues. If there is nothing to add, I'll close the issue. Thank you for your time.

**Comment by IbrahimTanyalcin** [comment]
@justinfagnani , thank you for your clear answer Justin, I'm closing this issue now. Also thank you @rniwa.
