### ISSUE TITLE
Use Case: Would like multiple use of slot by same name

### ISSUE THREAD

**Issue by anaran** [WICG/webcomponents#778]
I haven't been able to find explicit documentation on slot name use restrictions.

I checked
https://html.spec.whatwg.org/multipage/scripting.html#htmlslotelement

Anyway, I think it would be useful to be able to populate slots of a web component from a single Slotable.

My testcase below, when run from a scratchpad against `about:newtab` in Firefox Nightly, results in only the first slot getting assigned the slotted host node.

What is the correct approach to "parameterize" a web component instance with a single piece of recurring information short of creating uniquely named slots and providing slotables for each?

```
FOO Overview

Much has been said about SUBJECT.

SUBJECT References
```

```javascript
'use strict';

class SlotTestUI extends HTMLElement {
  constructor() {
    try {
      super();
      this.shadow = this.attachShadow({ mode: 'open' });
      this.shadow.innerHTML = `
<h2><slot id="slot1" name="subject">SUBJECT</slot> Overview</h2>
<p>Much has been said about <slot id="slot2" name="subject">SUBJECT</slot>.</p>
<h2><slot id="slot3" name="subject">SUBJECT</slot> References</h2>
        `;
    }
    catch (e) {
      console.log(e);
    }
  }
  connectedCallback() {
    try {
    }
    catch (e) {
      console.log(e);
    }
  }
}

class SlotTestHostUI extends HTMLElement {
  constructor(api_name, generator_name) {
    try {
      super();
      this.shadow = this.attachShadow({ mode: 'open' });
      this.shadow.innerHTML = `
<slot-test>
  <span slot="subject">FOO</span>
</slot-test>
`;
    }
    catch (e) {
      console.log(e);
    }
  }
  connectedCallback() {
    try {
    }
    catch (e) {
      console.log(e);
    }
  }
}

if (!customElements.get('slot-test')) {
  customElements.define('slot-test', SlotTestUI);
}

if (!customElements.get('slot-test-host')) {
  customElements.define('slot-test-host', SlotTestHostUI);
}

let sth1 = new SlotTestHostUI();
document.body.appendChild(sth1);

**Comment by rniwa** [comment]
I think you'd need to clone the node or set the value in an attribute and create nodes yourself. Fundamentally, a single DOM node can't rendered at two different locations simultaneously. That's a fundamental limitation of all major browser engines.

**Comment by GeorgeTailor** [comment]
I've came across same issues as described in the first post.
I am using Svelte to generate custom elements, so the syntax is quite different, but the workaround would be applicable for vanilla JS as well:
The HTML part:
```
<div class="box">
	<div class="list-holder" ref:listHolder>
		<slot ref:navslot name="navslot">
		</slot>
		<NavigationSlot ref:innernavslot>
		</NavigationSlot>
	</div>
</div>
```
The JS part:
```
const slot = this.shadowRoot.querySelector("slot");
this.refs.navslot.addEventListener("slotchange", e => {
let node = slot.assignedNodes()[0];
	if (node) {
		this.links.forEach(link => {
			const cloned = node.cloneNode(true);
			cloned.href = link.href;
			cloned.text = link.text;
			this.refs.innernavslot.appendChild(cloned);
		});
		this.refs.listHolder.removeChild(slot);
	}
});
```

The HTML for `NavigationSlot`:
```
<div class="box">
	<slot name="navslot"></slot>
</div>
```

The user would use it as follows:
```
<navigation-wc ref:nav>
	<link-wc text="text" href="https://google.com" slot="navslot">
	</link-wc>
</navigation-wc>
```
Also the used has to supply `links` array as a property:
```
this.refs.nav.links = [ ... ];
```

Although this seems to work, I am kind of unsure about such way of dealing with multiple slots. Seems too 'hacky' for me. Plus, I am also unsure whether Edge would implement it the same way other browsers did (Chrome, Safari and Firefox seem to work the same way with those cloned slots).

I would like to have the ability to handle arbitrary slotted elements and just apply some styles to them. While for simple use-cases this would work (eg. either using components which I've prepared, for example `link-wc` or by just using standard `<a>` element), but for more complex examples this becomes really cumbersome. For example, something like Angular's `routerLink` directive, or even a fully separate `<Route>` element in case of React.

Is support for dynamic slots planned ? For v2 maybe ?

**Comment by rniwa** [comment]
No, again, browsers can't render a single element in multiple places. What would, for example,  `offsetLeft` & `offsetTop` return? Or `assignedSlot`. This is simply not a configuration browser vendors would like to support.
