### ISSUE TITLE
[Shadow]: return of multiple shadow roots?

### ISSUE THREAD

**Issue by andyearnshaw** [WICG/webcomponents#780]
Multiple shadow roots were removed as per https://github.com/w3c/webcomponents/issues/90, because Apple didn't want them and others were [happy](https://www.w3.org/wiki/Webapps/WebComponentsApril2015Meeting) to defer them to a later version of the spec.  Complexity aside, there were plenty of great things about multiple shadow roots, not least the ability to transparently attach multiple behaviours to an element without fear of collisions in styles, ids or other attributes.

Take the `<body>` element, for instance.  A 3rd-party library wants to add a positioned tooltip, another wants to add some popups, another some dialogues.  Maybe a browser addon wants to decorate parts of the body without interfering with a website.  Without multiple shadow roots, none of these parties can act transparently, with 100% certainty that they won't introduce side effects by adding elements and styles to the dom.  One of them could create a shadow root, but that prevents the others (or the page owner) from doing the same.  If each could own a shadow tree on the body, they could add their own stylesheets or manipulate elements with full confidence in the encapsulation.

Is there still vendor interest in returning nested shadow roots in the future?

**Comment by hayatoito** [comment]
Hmm. I can say that Google is no longer interested in supporting multiple shadow roots. :(

**Comment by annevk** [comment]
I think I can somewhat safely say that Mozilla isn't either at least for the next five years or so. There's a lot more work to be done on shadow roots and custom elements in making them more robust and an integral part of the web platform. And then in terms of new features modules and perhaps templating are more interesting to us.

**Comment by rniwa** [comment]
Indeed, again, Apple is not interested in adding back multiple generations of the shadow DOM.

I don't think that kind of *transparent* enhancement never really works because sooner or later, they would start interfering with one another regardless of whether they use a separate shadow tree or not. At the end of the day, if some script is showing a tooltip, then other script which shows overlays, dialog, etc... needs to be aware of it; e.g. to avoid showing another overlay on top of it.

**Comment by andyearnshaw** [comment]
Fair enough, thanks for the clarification from the main vendor representatives.
