### ISSUE TITLE
Allow attribute changes/child creation on custom element creation

### ISSUE THREAD

**Issue by Snugug** [WICG/webcomponents#781]
I'm working on a set of custom elements where I would like to have standard set of light DOM elements  and classes enclosing the shadow DOM of the custom element I'm creating; think master slides for a slide deck. I'd like to have the following HTML:

**User-written HTML**
```html
<my-slide><p>My awesome slide content<p></my-slide>
```

**Expanded custom element**
```html
<my-slide class="slide">
  <div class="slide--container">
    #shadow-root
      <slot>…<p></slot>
  </div>
</my-slide>
```

I've tried two ways to get this to work:
* Adding the inner Light DOM container and adding the parent attribute in `constructor()` (which fails because manipulation like that isn't allowed)
* Doing the manipulation during `connectedCallback`, which puts everything in place correctly _except_ any slots I include are never slotted and stay as their original Light DOM
* Various attempts at nesting custom elements which all result in the Light DOM I want being covered by the Shadow DOM

The reason for needing this mixture of Light DOM and Shadow DOM is, during distribution, I want users to be able to style the `slide` and `slide--container` class with regular CSS and without needing to manipulate the components, but also want the inside of the Shadow DOM to be controlled via the component.

I think the solution to this is either allowing attribute/child manipulation on custom element creation, _or_ ensuring that slots activate correctly during `connectedCallback`

**Comment by domenic** [comment]
There is intentional no way to accomplish this. Elements are supposed to accept arbitrary light DOM, and react to it, like all built-in elements do. They should not cause any light DOM children to "sprout into existence" upon creation/connection.

In other words, HTML elements in general, and custom elements in particular, are not meant as "template macros" that expand into larger portions of DOM. They are a single piece of DOM---an element---whose consumers control their children, attributes, etc.

This is, of course, why we introduce shadow DOM: so that element creators can add arbitrary shadow-children which are under the _element_'s control, instead of the element _consumer_'s control.

Hope this helps!

**Comment by domenic** [comment]
> The reason for needing this mixture of Light DOM and Shadow DOM is, during distribution, I want users to be able to style the slide and slide--container class with regular CSS and without needing to manipulate the components

This sounds like a use case for [CSS shadow parts](https://github.com/fergald/docs/blob/master/explainers/css-shadow-parts-1.md)!

**Comment by Snugug** [comment]
Thanks for the very quick reply! I understand the intention even though my initial reaction is that the intention seems designed to be able to replicate, say, a `<select>` element as opposed to how many consumers (myself included) may consider components in the current React/Vue paradigm. CSS Shadow Parts may be what I'm looking for here; I'll experiment a bit

**Comment by Snugug** [comment]
Ok, confirmed that CSS Shadow Parts _will_ resolve my issue. I couldn't find a clear issue tracking Shadow Parts' inclusion; if there is one I'm happy to close this issue in favor of that one.

**Comment by domenic** [comment]
If you look through the explainer, you'll eventually find a link that says "proposal" that links to a the spec at https://drafts.csswg.org/css-shadow-parts-1/ . That spec, and its associated issue tracker, are the best places to follow progress on shadow parts. Glad to hear it's working out; /cc @fergal!
