### ISSUE TITLE
Web Components F2F Spring 2019

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#786]
We had a pretty productive meeting last spring in Tokyo. I solicited some interests and there appears to be a strong interest in having another F2F this spring around April.

**Update**: This F2F will take place on Thursday, April 25th and Friday, April 26th at [Mozilla's Toronto office](https://www.mozilla.org/en-US/contact/spaces/toronto/). Start time is 9AM both days.

**Agenda** : https://github.com/w3c/webcomponents/issues/802.

**Minutes**: raw minutes are available: https://www.w3.org/2019/04/25-components-irc

**Comment by rniwa** [comment]
Location & dates questionnaire: https://docs.google.com/forms/d/e/1FAIpQLSfTUHAsiORuh00Emc-B9CO_8cpyn3oO_WoTWniN-Nj_jtko5Q/viewform?usp=sf_link

**Comment by rniwa** [comment]
Ugh... creating forms is too hard. Why don't we vote for dates here instead:

My availability with **preferred**.
- [ ] Last week of March (3/25 - 3/29)
- [ ] First week of April (4/1 - 4/5)
- [x] **Second week of April** (4/8 - 4/12)
- [x] **Third week of April** (4/15 - 4/19)
- [x] **Fourth week of April** (4/22 - 4/26)
- [x] Last week of April & first week of May (4/29 - 5/3)
- [x] Second week of May (5/8 - 5/12)

**Comment by rniwa** [comment]
Ugh... creating forms is too hard. Why don't we vote for dates here instead.

My availability with **preferred**.
- [ ] Last week of March (3/25 - 3/29)
- [ ] First week of April (4/1 - 4/5)
- [x] **Second week of April** (4/8 - 4/12)
- [x] **Third week of April** (4/15 - 4/19)
- [x] **Fourth week of April** (4/22 - 4/26)
- [x] Last week of April & first week of May (4/29 - 5/3)
- [x] Second week of May (5/6 - 5/10)

**Comment by travisleithead** [comment]
Of the above weeks, I'm good for almost all of them excepting Second week of April (my kids' spring break).

**Comment by annevk** [comment]
I can do second week of April and onward. (And once we have a week I can check with Mozilla's Toronto office about hosting.)

**Comment by smaug----** [comment]
Not first week of April.
And I'd prefer not May.

**Comment by JanMiksovsky** [comment]
Me:

* [x]  Last week of March (3/25 - 3/29)
* [x]  First week of April (4/1 - 4/5)
* [ ]  Second week of April (4/8 - 4/12)
* [ ]  Third week of April (4/15 - 4/19)
* [x] Fourth week of April (4/22 - 4/26)
* [ ]  Last week of April & first week of May (4/29 - 5/3)
* [x]  Second week of May (5/6 - 5/10)

(@rniwa: the dates for 2nd week of May should be 5/6–10, not 5/8–12.)

**Comment by rniwa** [comment]
Looks like the fourth week of April (4/22 - 4/26) is the winner right now.

**Comment by hayatoito** [comment]
Me:

- [x] Last week of March (3/25 - 3/29)
- [ ] First week of April (4/1 - 4/5)
- [ ] Second week of April (4/8 - 4/12)  (This week, we have BlinkOn10 conference)
- [x] Third week of April (4/15 - 4/19)
- [x] Fourth week of April (4/22 - 4/26)
- [ ] Last week of April & first week of May (4/29 - 5/3)
- [ ] Second week of May (5/6 - 5/10)

**Comment by caridy** [comment]
Last week of March (3/25 - 3/29) conflicts with TC39 (New York).
Fourth week of April (4/22 - 4/26) sounds good. Salesforce can host it on Vancouver or Paris if needed. /cc @diervo

**Comment by rniwa** [comment]
@caridy Thanks for the host offer. It would be great if you can host us in Vancouver. Maybe we should start polling. @justinfagnani offered that Google may be able to host us in Waterloo as well. And @annevk said Mozilla might be able to host us in Toronto.

**If anyone else is willing to offer a location to host us, please do so now.**

Given the forth week of April seems like the week that works for most people, why don't we figure out the exact date & location. Could everyone who offered to potentially host us check to see if that's a viable option for these days?

Let's start collecting the preferred number of days to meet, preferred dates, & locations. Here's mine:

Preferred number of days to meet: 2 days

Preferred dates:
- [ ] Mon, 4/22
- [ ] Mon, 4/23
- [ ] Mon, 4/24
- [x] Mon, 4/25
- [x] Mon, 4/26

Preferred Locations:
- [ ] Paris
- [x] Toronto
- [x] Vancouver
- [x] Waterloo

**Comment by diervo** [comment]
I can confirm that Salesforce can happily host in Vancouver.
The early we can confirm the better.

**Comment by annevk** [comment]
It seems in principle Mozilla could host in Toronto (I've tentatively reserved a large room). Vancouver seems rather far to me for a two-day meeting. Avoiding Wednesday would make hosting easier, but it's not necessarily a deal-breaker. I'm flexible on days myself. My strong preference would be Paris by the way.

(Do we know how many people will attend?)

**Comment by rniwa** [comment]
Probably 15-20 people? Maybe @hayatoito would remember how many people attended it last year?

**Comment by chaals** [comment]
[Last year about 25](https://github.com/w3c/WebPlatformWG/blob/gh-pages/meetings/18-03-Web-components.md)

**Comment by annevk** [comment]
(Neither of those numbers should present a problem for Mozilla Toronto as I understand it.)

**Comment by caridy** [comment]
(Neither of those numbers are a problem for Salesforce Vancouver or Paris).

**Comment by rniwa** [comment]
Anyone else has preferred dates / locations?

**Comment by hober** [comment]
Technically, all of the proposed dates work for me, but I'd rather not do March or May. Any of the April dates are great.

**Comment by rniwa** [comment]
How about April 24-25 in Toronto, everyone? (Not Vancouver since @annevk said it might be too far away for him).

**Comment by hober** [comment]
How about the week before that (the 17th & 18th I guess)? I can make either work for me but that week’s a bit better.

**Comment by smaug----** [comment]
Looks like I'll need to be in Toronto for other things at the end of April, so having web components meeting around the same time would be great. I think I'd prefer either beginning of the week or end of the week, so that I could spend the rest of the week for the other thing.
Would 25-26 work?

**Comment by annevk** [comment]
Let's try to get this settled by March 7. It seems Mozilla Toronto is preferred. And it seems we'll meet in April either 24-25 or 25-26 (the latter somewhat preferred by us). Anyone opposed to this? Anyone with conflicts for those dates?

**Comment by annevk** [comment]
Perhaps everyone planning to attend can reply. That'll also make things easier when the tentative plans become definitive. Options:

1. 24-25 and 25-26 work for me.
2. 24-25 works for me.
3. 25-26 works for me.
4. I'd rather ...

**Comment by annevk** [comment]
24-25 and 25-26 work for me.

**Comment by smaug----** [comment]
24-25 and 25-26 work for me, but prefer 25-26.

**Comment by dogoku** [comment]
Hi guys, is anyone from the public allowed to attend these meetings?

**Comment by annevk** [comment]
@dogoku absolutely, though please see https://notapattern.net/2014/10/14/ways-men-in-tech-are-unintentionally-sexist/.

**Comment by muan** [comment]
Hello! I'm from the frontend team at GitHub and would love to attend this meeting. 

1. 24-25 and 25-26 work for me.

No dietary restrictions.

**Comment by dogoku** [comment]
> @dogoku absolutely, though please see https://notapattern.net/2014/10/14/ways-men-in-tech-are-unintentionally-sexist/.

My apologies if I offended anyone. That was definitely not my intention. (the linked article is aptly named...)

**Comment by rniwa** [comment]
(3) 25-26 works better for me although I could do 24-25 (1)/(2) if I absolutely have to.

**Comment by justinfagnani** [comment]
(1) 24-25 and 25-26 work for me, but probably prefer 24-25

**Comment by travisleithead** [comment]
25-26 is best for me. 

@dandclark for his preference.

**Comment by dandclark** [comment]
25-26 is best for me but could also do 24-25.

**Comment by caridy** [comment]
25-26 is best for me but could also do 24-25.

**Comment by hayatoito** [comment]
24-25 and 25-26 work for me

**Comment by rniwa** [comment]
Sounds like 25-26 is the winter?

**Comment by annevk** [comment]
It's spring in Europe, at least, but yeah, seems like 25-26 will be the dates of the meeting. 😊

Thus far I count 9 people. If you haven't replied yet and do plan to attend, reach out soon or you may lack lunch, a seat, or some such.

**Comment by JanMiksovsky** [comment]
@annevk I plan to attend as well.

**Comment by hober** [comment]
I'll be there.

**Comment by slightlyoff** [comment]
I plan on attending.

**Comment by rniwa** [comment]
Alright, I've made a new issue for the agenda: https://github.com/w3c/webcomponents/issues/802

**Comment by josh** [comment]
@muan and I, representing @github, would love to attend as well. Thanks ❤️

**Comment by ruphin** [comment]
I would like to attend.

**Comment by littledan** [comment]
Would it be possible for me to dial in? I am especially interested in the different module types.

**Comment by annevk** [comment]
Yeah, that should be doable, perhaps even via video (via Vidyo).

**Comment by rniwa** [comment]
@annevk:

Is this the address for the venue? If not, where would it be? (I want book flights & hotels soon)

366 Adelaide St W Suite 500, Toronto, ON M5V 1R9, Canada

**Comment by bkardell** [comment]
I'm interested in dialing in as well

**Comment by annevk** [comment]
https://www.mozilla.org/en-US/contact/spaces/toronto/ has the address and it indeed matches that one!

**Comment by tomalec** [comment]
I'd like to attend as well.

**Comment by MylesBorins** [comment]
I have heard you might be talking about modules, which is relevant to my interests. I'm already going to be in Toronto the weekend before this event and can stick around if it would be helpful for me to attend.

**Comment by rniwa** [comment]
> I'm already going to be in Toronto the weekend before this event and can stick around if it would be helpful for me to attend.

Only *you* can decide whether it would be helpful to attend F2F or not. I'd imagine that the most of discussions will be about HTML/CSS side of semantics in HTML modules. But you should let @annevk know ASAP since it's getting really close and you may not have a lunch, etc... otherwise.

**Comment by robwormald** [comment]
@annevk I'd like to attend in-person as well on behalf of Angular, if that's still possible?

**Comment by hayatoito** [comment]
@annevk

I wouldn't work on this area anymore, so I would like to cancel to attend the f2f meeting. I'd appreciate if you could take this into account.

If you have any further questions, please reach to @chrishtr, as the new point of contact.

**Comment by annevk** [comment]
@hayatoito so sorry to hear. It's been great working with you! Thanks for all the effort you put into this over the years.

@robwormald yup. (Also goes for everyone else thus far who commented "late".)

**Comment by rniwa** [comment]
@hayatoito : Is anyone working on web components implementation / bug fixes in Blink from Google attending?

**Comment by hayatoito** [comment]
@rniwa 
I'd appreciate if you could reach @chrishtr, the new point of contact in Google, for further questions. Thanks.

@annevk @rniwa and other folks,
I was happy and am proud of having worked with you in this area! I hope we can work together again some day in the future!

**Comment by vmpstr** [comment]
Hi, I'd like to attend as well. I'm from Google, working on Display Locking implementation for Chromium.

**Comment by rniwa** [comment]
@hayatoito: Okay. Thanks for all your work over the years!

@chrishtr: Can anyone from Google working on web components implementation come to the meeting?

**Comment by chrishtr** [comment]
@rniwa I will be able to dial in if that is available, but unfortunately we won't have someone working
on web components attending in-person this time.

**Comment by rniwa** [comment]
@chrishtr: Okay, @annevk says that should be available.

@justinfagnani: You're still attending in person, right? Other than @vmpstr, who else is attending from Google?

**Comment by pmdartus** [comment]
I am planning to attend in person as well, representing Salesforce.

**Comment by annevk** [comment]
Apologies, I've forgotten to ask about dietary restrictions. Please indicate one of

* Omnivore (I'm not sure this is the correct term, but hopefully it's clear from context)
* Vegetarian
* Vegan

You're also welcome to message me directly if you rather not share that information here. Also, to be clear, everyone who replied thus far is welcome and accounted for.

**Comment by rniwa** [comment]
I'm Omnivore.

**Comment by flackr** [comment]
I'd be interested in attending as well. I'm from Google, working on animations and composited rendering for Chromium. I am omnivorous.

**Comment by ruphin** [comment]
I would prefer a vegan option if available

**Comment by pmdartus** [comment]
I am omnivore.

**Comment by ghost** [comment]
I would like to attend in person as well (representing salesforce) if that's possible.

**Comment by JanMiksovsky** [comment]
Omnivore

**Comment by annevk** [comment]
@sfdciuie no problem, please list your dietary preference.

**Comment by ghost** [comment]
@annevk thank you! dietary preference is: vegetarian

**Comment by dandclark** [comment]
+1 for vegan option.  Thanks!

**Comment by dgraham** [comment]
I'd like to join @josh and @muan from GitHub if there's still room.

_Update: I have an expired passport so I won't be able to make it this time. 😞_

**Comment by annevk** [comment]
@dgraham that'd be great, please list your dietary preference.

**Comment by tomalec** [comment]
I'm omnivore.

**Comment by NavidZ** [comment]
> who else is attending from Google?

@rniwa, I'd be interested in attending as well.

**Comment by annevk** [comment]
@NavidZ you're most welcome, but again, dietary preference please. 😊

**Comment by justinfagnani** [comment]
@annevk omnivore here :)

**Comment by NavidZ** [comment]
> @NavidZ you're most welcome, but again, dietary preference please. 😊

Thanks for asking. Vegetarian should work for me. :)

**Comment by rniwa** [comment]
I've gotta say I'm very psyched about the prospect of meeting so many web developers who are using web components. It's going to be great 😁.

**Comment by dbatiste** [comment]
@annevk I'd like to attend.  Is it too late?  If it's ok, my food preference would be omnivore.  :)

**Comment by annevk** [comment]
@dbatiste yeah, that's fine.

Also, whoever wants to attend remotely: I need your contact details (probably email address) for instructions I'll email somewhere next week. My contact details are at https://annevankesteren.nl/about (email or Twitter DM works).

(I updated OP with the start time, 9AM both days.)

**Comment by dbatiste** [comment]
Thanks @annevk!  :)

**Comment by svanherk** [comment]
Hi @annevk, sorry for the last minute request but I'd also like to join @dbatiste in attending. :)
If that's possible, my food preference would be omnivore.

**Comment by diervo** [comment]
We will have one more person from Salesforce, Brandon Ferrua (omnivore I believe)

**Comment by nyaxt** [comment]
I'd like to attend remotely for the HTML modules discussion.
Email: kouhei@google.com or GitHub/twitter @nyaxt

**Comment by annevk** [comment]
@svanherk please come!

@diervo @nyaxt noted.

**Comment by annevk** [comment]
Instructions for those attending remotely have been emailed. Looking forward to seeing everyone tomorrow, 9AM Toronto time!

**Comment by ruphin** [comment]
For those who are already in Toronto, perhaps we can meet this evening for dinner / drinks somewhere downtown. :)

**Comment by rniwa** [comment]
For those who were in the photo we took on the last day, I have it ready. Please email me (same username as my Github account) at webkit.org, and I'll send it to you privately since I'm not certain if everyone wants their pictures being distributed publicly.

**Comment by diervo** [comment]
Seems that Web Components is not in the schedule for Fukuoka, I would have swear it was a couple of weeks ago... Anyone knows? Are we meeting anyway? @annevk @rniwa?

**Comment by annevk** [comment]
I don't think it ever was on the schedule, but I would like to meet up. If only for triaging. We can always meet there informally somehow.

@hober @ljwatson perhaps some of this can be discussed as part of a meeting on HTML? Or is too late to have one at this point?

**Comment by LJWatson** [comment]
There isn't a plan to hold an HTML meeting at TPAC.

**Comment by annevk** [comment]
Should we make one?

**Comment by rniwa** [comment]
Yeah, I've love to have a time allocated to discuss web components related issues since there are a number of CSS & SVG related issues to resolve as well.

What would be the avenue through which we can request a time slot / meeting room for this?

**Comment by travisleithead** [comment]
I personally would love to see some time allocated to continue conversations about various web component proposals and discussions we had in Toronto.

I've been working with @plehegar to get room/slots for some specific discussions at TPAC with good success. One avenue is to use a community group slot for this--I think there are still CG slots available in the schedule--and leverage the old WHATWG CG making it clear that it is for web components? (Or maybe it's just time to create an official web components CG, and link it to w3c/webcomponents? I don't think anyone would object to that--then ask for a slot using that CG?)

Lots of options.

**Comment by annevk** [comment]
Those slots seem rather short though. Also, I don't think we need yet another CG (or resurrect one). There's already a new HTML WG for coordination with WHATWG and all of this is well within scope of that.

**Comment by domenic** [comment]
At the risk of throwing things in to more disarray, I continue to think that moving this repo to WICG would reduce confusion about its status (i.e. make it more clearly an incubation venue), in which case using the WICG banner to meet at TPAC would make sense to me.

**Comment by LJWatson** [comment]
Irrespective of where this fits into the scheme of things, there is the 
logistical matter of finding space and resources (when the room 
assignments have already been made).

Making no promises, it would help to know:
* How many people do you anticipate would participate?
* How long would you want to meet for?

**Comment by annevk** [comment]
15-20 at most I suspect and ideally a day for Web Components. If we also want to have a general HTML session to discuss the HTML Standard in some capacity that'd require additional time (and probably involve a different set of people, perhaps more).

**Comment by diervo** [comment]
If venue is an issue (per the comments above), and if we figure logistics soon, I think I can get Salesforce to sponsor and rent some room somewhere close to the main event and get food for the day.

**Comment by LJWatson** [comment]
It looks like we can have a room at TPAC for two days, with space for about 20 people. It'll likely be the Monday and Tuesday (16 and 17 September), but I'll keep you posted.

Questions:
* Do we want a general HTML meeting as well as a Web Components meeting?
* Do we need wipeboards and/or remote dial-in capability in the room?
* How/where do we want to handle agenda bashing for either/both days?

**Comment by rniwa** [comment]
> * Do we want a general HTML meeting as well as a Web Components meeting?

I can't answer that but:
> * Do we need wipeboards and/or remote dial-in capability in the room?

We most certainly want to be able to project and/or have whiteboards.

> * How/where do we want to handle agenda bashing for either/both days?

I think we can file a new issue in this issue tracker like we did for this F2F and last TPAC. Most of folks who are interested in web components are active in this repo's issue tracker anyhow.

**Comment by LJWatson** [comment]
The room wasn't available after all. We do have a room for 15 people on Tuesday though, and this should be added to the registration form soon. @Hober has offered to chair, so hopefully it's all set for a Web Components meting.

**Comment by rniwa** [comment]
@LJWatson : Thanks as always! So we have a room on Tuesday for web components? @hober

**Comment by hober** [comment]
> So we have a room on Tuesday for web components? @hober

Yup!

**Comment by rniwa** [comment]
Filed https://github.com/w3c/webcomponents/issues/826 to track the agenda. Closing this issue since F2F in Toronto has happened already.

**Comment by LJWatson** [comment]
@rniwa Yes, you have a room for about 15 people on Tuesday for Web Components.
