### ISSUE TITLE
Question: where to incubate HTML modules?

### ISSUE THREAD

**Issue by travisleithead** [WICG/webcomponents#794]
We'd like to move our [explainer](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/HTMLModules/explainer.md) and spec-related content into a more dedicated repo for continued incubation at this point. One obvious home for that incubation is here in w3c/webcomponents, where we already have a variety of modules-related issues tracked.

Alternately, we could start a new dedicated repo for html modules, which would be a discoverable home for future html-modules issues and spec development until such time as the feature would graduate into WHATWG/HTML and TC39 for their respective parts.

Do folks here have a preference?

**Comment by hayatoito** [comment]
Hi Travis!
I don't have any strong preference. I think it's okay to move the explainer to a better repo.

You might want to see the discussion in the past, https://github.com/w3c/webcomponents/issues/652, where we tried to close this w3c/webcomponents repository, though that doesn't happen yet.

**Comment by bkardell** [comment]
I think a new repo is better, personally. wc has a lot in it and it feels a little outside that anyways.. To me.

**Comment by rniwa** [comment]
Moving them to this repository seems okay to me. Creating a new repository in WHATWG is fine too.

**Comment by travisleithead** [comment]
Tell me more about a new repository in WHATWG... would that be the start of a new workstream?

**Comment by rniwa** [comment]
That's a question for @annevk / @domenic.

**Comment by annevk** [comment]
As far as I can tell HTML modules require some changes to ECMAScript and mostly changes to HTML. I don't really see what part would be standalone given how tightly coupled it is.

**Comment by annevk** [comment]
Seems per discussion in #783 I hadn't read yet this should eventually only be changes to HTML, once refactoring of ES has been completed.

**Comment by travisleithead** [comment]
Everyone, thanks for your feedback. After mulling this over, we think the best course of action is to start the spec work directly as a PR against HTML and incubate there, while using the issue tracker at whatwg/html and the other issues that are already here in w3c/webcomponents.

**Comment by markcellus** [comment]
That is great! Can you all drop a link to the new PR in this thread?

**Comment by travisleithead** [comment]
...we're still working on adapting [these proposed spec changes](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/html-module-spec-changes.md) into PR format, but stay tuned.

**Comment by rniwa** [comment]
Instead of making a PR, could you give us the updated proposal? It's hard to read the spec changes as one coherent proposal. I think for a big proposal like this, I think it's probably a good idea to have an explainer / spec change document until we come to a consensus.

**Comment by annevk** [comment]
Note that creating a PR will produce readable diff documents. But yeah, it depends a bit on how spread out the changes become.

**Comment by travisleithead** [comment]
Hmm, well, it would be good to update the explainer regrardless. We have our explainer [here](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/html-modules-explainer.md), if it helps.

**Comment by travisleithead** [comment]
@rniwa Explainer is up-to-date, now with a list of significant open-issues at the end. If there are ways you think it could be improved, we'd love your feedback!
