### ISSUE TITLE
Using private fields and methods in template instantiation

### ISSUE THREAD

**Issue by xlaywan** [WICG/webcomponents#808]
I have created an [issue](https://github.com/tc39/proposal-class-fields/issues/236) in TC39, but they are skeptical about it. What do you think?

**Comment by JPtenBerge** [comment]
Not a fan myself. In general, `private` in OO  means you can't access it outside of that class. Your template has to be parsed by a parser, which is outside of your class. It feels odd to me that this parser should need to access private members.

I know that Angular requires your members to not be private if you're going to use them in a template (for performance reasons, these errors only appear when running `ng serve` or `ng build` with `--prod`).
