### ISSUE TITLE
Deprecation warning misleading.

### ISSUE THREAD

**Issue by SanderElias** [WICG/webcomponents#818]
In the [Custom Elements Editor draft page](https://w3c.github.io/webcomponents/spec/custom/)
Are a couple of warnings prominently visible
![image](https://user-images.githubusercontent.com/1249083/58318000-3c264780-7e17-11e9-845e-ac6bcfd37af2.png)
and
![image](https://user-images.githubusercontent.com/1249083/58318013-42b4bf00-7e17-11e9-8660-8f4f7d8d3584.png)

While those are correct, they are incomplete and might give a visitor the idea that Custom Elements are no longer supported. (Got questions along that line!)
Perhaps it is a good idea to add some context and a URI to the current place of the spec.

Or at least mention that it's no longer active there because it's merged into HTML/DOM
cc: @domenic

**Comment by kenchris** [comment]
@annevk

**Comment by annevk** [comment]
I'm happy to land a PR that replaces that entire document with forwarding pointers.

It's a little harder for Shadow DOM I suspect as that still contains some bits that are not uplifted elsewhere. 😟

**Comment by Westbrook** [comment]
Page no longer exists.
