### ISSUE TITLE
Resolve what elements of a page we look at for LayoutStability

### ISSUE THREAD

**Issue by ehanley324** [WICG/webcomponents#819]
Right now in the spec we include shadow elements: https://dom.spec.whatwg.org/#concept-shadow-including-descendant

Need to determine whether or not it is ok if we look at shadow elements.

**Comment by rniwa** [comment]
Exposing elements inside shadow trees in global object / performance observer is not okay unless there is an explicit opt-in by the component itself.

**Comment by rniwa** [comment]
Closing unless you have further questions.
