### ISSUE TITLE
input radio name isolation in shadow DOM

### ISSUE THREAD

**Issue by hsablonniere** [WICG/webcomponents#824]
Hi folks,

1. Create a custom element with shadow DOM
2. Add some `<input type=radio>` in the shadow DOM with a `name` that is always the same for all instance of the component. (ex: `name=foobar`)

IMO, shadow DOM boundaries should isolate "radio groups".
It is the case in Firefox and Chromium but not in Safari.
I looked for a definitive/specific reference to this is the spec without luck.

## Spec questions?

* Can someone confirm Firefox and Chromium are correct and Safari has a bug?
* Can someone refer to a part of the spec that would clarify this?

I created a reduced test/demo:

https://jsbin.com/wequqojaca/1/edit?html,css,js,output

I also commented on this Webkit issue:

https://bugs.webkit.org/show_bug.cgi?id=199568

## Best practices questions?

I discussed this in the polymer Slack and someone mentioned it was not a good idea to rely on this.

Obviously this fails in Safari right now and in other browsers that rely on polyfills so I used a random unique name for each instance of my component to fix the problem.

* If we were in a world where this behaviour was the same everywhere, would it we bad practice to rely on the isolation and have the same static name for all instance?
* I mean, I rely on the isolation of ids and other CSS stuffs so why not input radio names?
* Am I missing a11y problems with this?

Thanks :wink:

**Comment by annevk** [comment]
It's a bug in Safari.

https://html.spec.whatwg.org/#dom-form-nameditem defines the `form.foobar` getter. https://html.spec.whatwg.org/#association-of-controls-and-forms defines that a form owner can only be in the same tree (shadow trees are distinct trees).

**Comment by hsablonniere** [comment]
Thanks a lot @annevk ;-) I'll follow the WebKig bug tracker. I will close my issue but I would love some feedbacks on my "best practices questions".

**Comment by annevk** [comment]
Sorry, I skipped that initially. I'd say that the whole point of encapsulation is allowing developers to rely on it.

And as far as accessibility goes that should operate mostly on the final flattened tree, but it's still somewhat early days so there might be issues there and there are some issues with web components and accessibility in general that need to be resolved.

**Comment by hsablonniere** [comment]
@annevk thanks ;-)

**Comment by pookage** [comment]
Hi folks - I'm having the opposite problem; I have a `<custom-radio-input>` component and want to be able to group them, but the shadow-dom is rightly isolating them - is there anything I can do to actively prevent this functionality so that they can become mutually exclusive again?
