### ISSUE TITLE
[idea] Lifecycle method: beforeDisconnectedCallback

### ISSUE THREAD

**Issue by BennyHinrichs** [WICG/webcomponents#825]
I have a component that needs to affect the previous and next element siblings when it gets disconnected. However, by the time we hit `disconnectedCallback`, the element has already been removed from the DOM, so there's no context. Is there any way to do something similar to a `beforeDisconnectedCallback`, or if not would it be possible to get the method?

Edit: I should perhaps say I have a current solution with `MutationObserver`, but I noticed on other issues like #809 that's considered a lesser way.

**Comment by rniwa** [comment]
That would require some kind of sync callback and that's not possible. See https://github.com/whatwg/html/issues/4599 for an alternative solution being proposed for that use case.

**Comment by rniwa** [comment]
F2F Resolution: We can't add this because it would be equivalent to mutation events.
