### ISSUE TITLE
observedAttributes should be converted to ASCII lowercase

### ISSUE THREAD

**Issue by starak** [WICG/webcomponents#838]
Since both `Element.setAttribute` and `Element.getAttribute` is converting the Attribute name to ASCII lowercase by default,  the `sequence<DOMString>` returned from `observedAttributes` should also be converted the same way.

If we take the flag as an example:
```HTML
<flag-icon selectedCountry="no"></flag-icon>
``` 
And then do this
```javascript
class FlagIcon extends HTMLElement {
    constructor() {
        super();
        //...
    }

    static get observedAttributes() { return ["selectedCountry"]; }

    attributeChangedCallback(name, oldValue, newValue) {
        //...
    }

    //...
}

customElements.define('flag-icon', FlagIcon);
```

This example will not work since the the name in the tag is converted to ASCII lowercase, and the observedAttribute list is not.

**Comment by domenic** [comment]
This isn't a great idea, because although some of the common attribute-setting methods convert to lowercase, the attribute data model allows mixed case. Consider, for example, https://jsbin.com/vemuyibode/edit?html,output

**Comment by rniwa** [comment]
I do remember this discussion coming up in the past, and decided not to due to non-HTML elements in XML documents.

**Comment by rniwa** [comment]
F2F resolution: This is working as intended.
