### ISSUE TITLE
Should host with `delegatesFocus` true keep the previous focused element focused if it's a shadow-including descendant of the host?

### ISSUE THREAD

**Issue by rakina** [WICG/webcomponents#840]
Just noticed this behavior in Blink when re-reading the focus code one last time for `delegatesFocus` specs https://github.com/whatwg/html/pull/4796.
So the case is like this:

```html
<div #host>
 #shadowRoot delegatesFocus=true
  <div tabindex=0 id=foo>foo</div>
  <div tabindex=0 id=bar>bar</div>
```
The currently focused element is `#bar`, and then we call `host.focus()`. In Blink right now we would keep the focus on `#bar` and not focus on anything else. In fact we would keep the focused element whenever we try to focus on `#host` and any of `host`'s shadow-including descendant is the currently focused element.

This seems weird and we aren't doing the "keep the current focused element" in any other case (CMIIW), so I propose we don't spec this behavior, and instead do the focus delegation in `host` no matter what (with the delegation methods from https://github.com/w3c/webcomponents/issues/830#issuecomment-532514644)

cc @domenic @rniwa @smaug---- @annevk @ekashida

**Comment by rniwa** [comment]
Hm... that might be annoying behavior for users though. If page's script kept focusing a component, it would always reset the focus in the component.

I guess the current processing model returns early if the current focus is already at where `focus()` is called: https://html.spec.whatwg.org/multipage/interaction.html#focus-processing-model so maybe we need an equivalent check for shadow hosts so that if you'd call focus() on an already focused shadow host, then we'd just simply return early.

**Comment by rakina** [comment]
You mean we would keep the current focused element in all case where shadow host is already a shadow-including ancestor of the focused element, regardless of `delegatesFocus`?

**Comment by rniwa** [comment]
I mean that [focusing step](https://html.spec.whatwg.org/multipage/interaction.html#focusing-steps) should bail out as it does in step 4.

**Comment by smaug----** [comment]
Yeah, I agree focus shouldn't change.
When testing internal widgets, looks like Firefox' type=date does move focus to the first internal field, but I consider that a bug.

**Comment by rakina** [comment]
Hmm, interesting. Though I don't really understand cases where the page would try to focus on a host multiple times, if you both think this behavior is actually justified I guess that's fine (+ no need to worry about the risk of changing Blink behavior, yay).

So we'll check "If new focus target is a shadow host whose shadow root's delegates focus is true, and new focus target is a shadow-including ancestor of the currently focused area of a top-level browsing context, then return."?

**Comment by rniwa** [comment]
Yeah, something like that.

**Comment by rniwa** [comment]
Has the PRs been updated to reflect this?

**Comment by rniwa** [comment]
The PR which got merged for this issue seems to have a bug as I pointed out in PR.

The current spec also seems to take care of the nested delegation: https://github.com/whatwg/html/issues/5052
