### ISSUE TITLE
Provide a declarative way for customElement/template binding

### ISSUE THREAD

**Issue by esarbe** [WICG/webcomponents#850]
There is currently no way to use the `template` element without Javascript. This makes templating only useful for application developers (and since Javascript can already achieve templating without the template tag, the `template` element kinda superfluous).

I propose to add a way to declaratively bind a template element to a custom element.

**Comment by rniwa** [comment]
See
https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Template-Instantiation.md
https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Declarative-Custom-Elements-Strawman.md

**Comment by esarbe** [comment]
Nice! I didn't see that strawman.

Thanks for pointing to it.
