### ISSUE TITLE
Considering Shader Module Types

### ISSUE THREAD

**Issue by guybedford** [WICG/webcomponents#853]
Shaders are loaded in WebGL in the browser by passing the shader source code string through JS (https://developer.mozilla.org/en-US/docs/Web/API/WebGLShader).

If we could extend module types to handle shader loading, it seems like module types would work out very naturally and directly for shader loading use cases as another language that runs on the web.

While we are considering the different module types, I wanted to mention this possibility as another data point to consider when it comes to the security and shape of the sorts of integrations we might expect here. The list of all possible module types for the web probably isn't more than 10, let alone what will be implemented. So understanding the use case examples, and what general thoughts are on them, can only help.

**Comment by annevk** [comment]
cc @littledan @litherum @beaufortfrancois @jdashg

**Comment by kdashg** [comment]
What are module types?

I know an extremely common pattern is the non-js <script> shader pattern:
```
    <script id='e_vs' type='none'>
attribute vec3 aPosition;

void main(void) {
  gl_PointSize = 50.0;
  gl_Position = vec4(aPosition, 1.0);
}
    </script>
    <script>
[...]
const vs = gl.createShader(gl.VERTEX_SHADER);
gl.shaderSource(vs, e_vs.innerHTML.trim());
gl.compileShader(vs);
[...]
```
One restriction of this is inability to use `src=` with arbitrary types. Is this proposal a formalization of something like this?

**Comment by guybedford** [comment]
Yes this would avoid the need for inline custom source handling exactly.

It might make sense to allow separate `vertex_shader` and `fragment_shader` module types to support the above.

**Comment by guybedford** [comment]
The output module would then contain a default export corresponding to the compiled shader.

**Comment by Jamesernator** [comment]
Based on the spec it seems shaders are associated with a specific rendering context: https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.8

We'd need do something about that, or alternatively just a way to import plaintext e.g. `import shader from './shader.glsl' as string;` then they can instantiate the shader objects in each context themselves.

**Comment by shannon** [comment]
I was wondering about this is as well. Maybe it could export a function that compiles the shader for a given context.

Something like:

```js
const type = 'VERTEX_SHADER'; // or 'FRAGMENT_SHADER' accordingly
const source = `<the file contents>`;

/**
  * Compiles the shader.
  * @param {WebGLRenderingContext} context - The WebGL context to create the shader with.
  */  
export default function compile(context) {
  const shader = context.createShader(context[type]);
  context.shaderSource(shader, source);
  context.compileShader(shader);

  if (!context.getShaderParameter(shader, context.COMPILE_STATUS)) {
    const log = context.getShaderInfoLog(shader);
    context.deleteShader(shader);
    throw new Error(`Error compiling shader: ${log}`);
  }

  return shader;
}
```

Then there is the linking boilerplate. I don't know how you would manage this because it can be any combination of fragment and vertex shader. So you would almost need another type to import from (a WebGL Program file, a single file that refers to a fragment and vertex shader). As far as I know there is no convention for this, I could be wrong though. 

That boiler plate usually looks something like this:
```js
function createProgram(context, vShader, fShader) {
  const program = context.createProgram();
  context.attachShader(program, vShader);
  context.attachShader(program, fShader);
  context.linkProgram(program);
  context.validateProgram(program);

  if (!context.getProgramParameter(program, context.LINK_STATUS)) {
    const log = context.getProgramInfoLog(program);
    context.deleteProgram(program);
    throw new Error(`Error linking program: ${log}`);
  }

  return program;
}
```

**Comment by kdashg** [comment]
That doesn't look like a compelling improvement to me over js modules, and moving boilerplate into each shader module is a step backwards for conciseness.

Also unfortunate: WebGLShaders are not only specific to a WebGLContext, but compilation depends on mutable WebGLContext state as well. Compilation is unfortunately not (presently) idempotent. 

NB: WebGPU will be giving us yet another shader type, coincidentally called `GPUShaderModule`.

**Comment by guybedford** [comment]
@jdashg do you know if `GPUShaderModule` is tied to a rendering context? Looking at Vulkan APIs it seems like shader compilation there is a thin compile wrapper - so far-future shader APIs on the web might well be similar.

This issue was more to start discussion around whether the design of modules types would want to incorporate shaders in future - to understand the sorts of edges of the module types proposal. Either way we have a data point.

**Comment by kdashg** [comment]
GPUShaderModule is expected to be GPUDevice-specific.

Adding ability to request arbitrary `<script src=` resources seems like the biggest bang for the buck.

**Comment by guybedford** [comment]
Right I see that, is the device already known in the browser? Or is the idea that device selection would be possible at the browser level?

If there are unknown inputs into compilation I agree the benefits of a loader are lost, since it would end up having to wrap a new API to provide that context anyway as @shannon describes.

**Comment by kdashg** [comment]
A page 0-N different `GPUDevice` objects, each object is more of a context, not an actual device.

**Comment by guybedford** [comment]
Ok that seems to settle this then as a non-goal for module types... will go ahead and close.
