### ISSUE TITLE
2020 Spring Virtual F2F

### ISSUE THREAD

**Issue by hober** [WICG/webcomponents#855]
# Web Components Spring 2020 Virtual F2F

Where: https://github.com/w3c/webcomponents/wiki/2020-Spring-Virtual-F2F#conference-call-information
When: Monday 23 & Tuesday 24, 3 PM - 7 PM UTC
Agenda and summary of conclusions: https://docs.google.com/document/d/1lpy6k_ZlI5iVo-Y0vJaDfFAQvYRjpZqUcSlnOex2A0Q/edit#heading=h.9ut5sja3keva
Minutes: [Day 1](https://www.w3.org/2020/03/23-components-minutes.html), [Day 2](https://www.w3.org/2020/03/24-components-minutes.html)

**Comment by pmdartus** [comment]
Thanks @hober for starting the thread.

Concerning the venue, I currently have an option March 24th-25th and March 30th-31st on a meeting room at the Salesforce Paris office ([3 avenue Octave Greard](https://goo.gl/maps/AJGarVMVzG1riPLQ8)). This room can accomodate up to 25 persons.

@diervo also made sure that attendees don't need to sign a NDA to attend any standard meeting inside Salesforce buildings.

**Comment by annevk** [comment]
I can no longer do <s>23-30</s> 25-30 unfortunately and the week before is not great either, but might be doable. Sorry about that.

**Comment by rniwa** [comment]
Cc'ing more folks for visibility: @dandclark @travisleithead @justinfagnani @diervo @caridy @muan @JanMiksovsky @tomalec @tkent-google @rakina @domenic

**Comment by caridy** [comment]
Keep in mind that TC39 will be hosted by Apple in CA the week of the 31st. I prefer the week of the 16th.

**Comment by travisleithead** [comment]
We're planning to call-in for an update on JSON/CSS/HTML modules rather than attend in person. So my preference would be a North America venue for the time-zone, but that's not a deal-breaker. If the meeting follows TC39 we will likely have more to report about how [the proposal](https://github.com/littledan/proposal-module-attributes/) is coming along.

@bocupp

**Comment by justinfagnani** [comment]
I'm checking my calendar right now, but I most likely can't make March 30/31. Updated the doodle. cc @azakus @aomarks @sorvell @kevinpschaaf

**Comment by rniwa** [comment]
@annevk : Could you fill your availability in doodle?

@travisleithead  / @BoCupp : Sad to hear you're not attending in preson but could you fill doodle with your availability for call-ins?

**Comment by rniwa** [comment]
@justinfagnani : Sounds like March 30 & 31 are out since @hober, @caridy, and you can't attend it.

**Comment by hober** [comment]
As of right now, we've had 12 responses to the poll. The dates with the maximum availability are currently March 23rd and 24th.

@annevk wrote:

> I can no longer do 23-30 unfortunately and the week before is not great either, but might be doable. Sorry about that.

Did you edit your Doodle results to that effect?

**Comment by annevk** [comment]
Yeah, I reassessed and decided I could do Monday 23/Tuesday 24 if need be. Thanks for checking!

**Comment by caridy** [comment]
Same here, I can try to do Monday 23/Tuesday 24.

**Comment by rniwa** [comment]
Hm... looks like 3/23-24 are only dates @travisleithead isn't available.

@travisleithead : do you have anyone else from Microsoft who could attend those dates?

**Comment by travisleithead** [comment]
Those are dates I'm not *fully* available, but can be available at certain times--for example, I could help ensure specific topics land at certain times in the agenda :) So, don't consider my unavailable times as blocking. I do suspect that @BoCupp and @dandclark are likely available, though they'd need to confirm.

**Comment by pmdartus** [comment]
We will not be able to host in the Salesforce office on March 23rd, all the meeting rooms are already booked that day. 

I am working on fallback plan to host the meeting in a different venue in Paris. I will keep you posted once I have more information.

**Comment by pmdartus** [comment]
First of all, happy new year to everybody!

After some discussion, I was able to get some budget to host the event in Paris! It is highly likely that we will host that Salesforce will host the event at the ~[Pullman Paris Tour Eiffel](https://goo.gl/maps/CqTmgKvv8kgnk6bE7) right next to the office~ (the location has been updated see comment below).

If we were to host the event at the Pullman, I am also planning to ask for a special discount for the attendees.

Based on the doodle responses, it appears that March 23 and 24 is the most convenient date for everybody. Can we settle on those dates?

**Comment by annevk** [comment]
Thanks so much @pmdartus! Shall we give everyone until Friday and then consider it decided?

**Comment by pmdartus** [comment]
Sounds good to me.

**Comment by mfreed7** [comment]
So it sounds (from the lack of objections) like March 23-24 are the firm dates?

**Comment by hober** [comment]
Okay, great. I've updated the issue description to say that we're planning to have a two-day F2F on 23–24 March in Paris, France, hosted by Salesforce, and that the dates are fixed but the exact location is TBD.

@pmdartus, please do let us know once the venue is confirmed, and thanks again for hosting.

**Comment by pmdartus** [comment]
I will keep up you updated, once I am done with booking the venue. 
I hope to have everything approved by the end of next week.

**Comment by pmdartus** [comment]
I have some good news, I just received the confirmation from the venue! The meeting will be hosted at the [Sofitel Baltimore](https://g.page/SofitelParisBaltimore?share) in Paris on March 23-24. Please ignore the location in my previous comment.

I booked a room for 25 people. If you are planning to attend and haven't responded to the original doodle, please let me know.

I have also negotiated a small discount for the meeting attendees with Sofitel (room upgrade and breakfast). If you are interested here is [the reservation](https://github.com/w3c/webcomponents/files/4104803/Reservation.Form.SALESFORCE.PDF) form with the different pricing.

**Comment by hober** [comment]
@pmdartus wrote:

> I have some good news, I just received the confirmation from the venue!

That's great! Thank you so much for arranging this. I've updated the issue text with the latest details.

**Comment by ruphin** [comment]
I am planning to attend with @LarsDenBakker from @open-wc, on behalf of @ing-bank.
@pmdartus Is there still capacity available?

We have particular interest in scoped registries. We are deploying web components at scale, and we can share information on challenges we are facing.

**Comment by hober** [comment]
@annevk @caridy @emilio @justinfagnani @LarsDenBakker @mfreed7 @pmdartus @rniwa @ruphin @travisleithead

I've stubbed a [wiki page for the F2F](https://github.com/w3c/webcomponents/wiki/2020-Spring-F2F) to generate a list of attendees and an agenda. Please add your name and topics if you're attending.

**Comment by diervo** [comment]
@hober I don't think some of us have the right privileges to modify the wiki, which for the agenda would be handy :)

**Comment by rniwa** [comment]
Perhaps we can create another issue for agenda last year, and those of us who have edit privileges can update the wiki as we go.

**Comment by bkardell** [comment]
I certainly don't have the privileges, and unfortunately I can't recall if I filled in the doodle or not now, but I would like to attend.

**Comment by diervo** [comment]
@rniwa @annevk @hober may I ask that someone from Salesforce have some minimal privileges to update the wiki and/or issues? I think last year the agenda became hard to rationalize due to all incoming topics from everybody at the same time. At least that way I can coordinate all our proposals in case we have do update or changes things. Also since we are organizing this time around it will help so we can update logistics as changes occur.

**Comment by rniwa** [comment]
> @rniwa @annevk @hober may I ask that someone from Salesforce have some minimal privileges to update the wiki and/or issues? I think last year the agenda became hard to rationalize due to all incoming topics from everybody at the same time. At least that way I can coordinate all our proposals in case we have do update or changes things. Also since we are organizing this time around it will help so we can update logistics as changes occur.

It might be better for you to do that work & post the list of agenda either here on a new issue. Then we can add them to the list. If we give someone from Salesforce editing privilege, people from other organizations without editing privileges still won't be able to add topics.

**Comment by sideshowbarker** [comment]
@diervo, @bkardell I changed the perms on the wiki, so I think you both (and others) should be able to make edits in the wiki now. If not, lemme know

**Comment by hober** [comment]
Reminder to add your name to the wiki page so we know who's coming!

**Comment by tomalec** [comment]
I hope there is still some place left for me to join. (Just added myself to the wiki)

**Comment by pmdartus** [comment]
If you are interested in booking a room at the Sofitel for the meeting, I extended the deal until the end of next week (Friday 02/21).

**Comment by mfreed7** [comment]
What's the current thinking about whether to have this F2F, given COVID-19? It is a very small gathering, so it seems ok to me, but I just wanted to bring it up here.

**Comment by rniwa** [comment]
Few folks have told me privately that they have or are planning to cancel the travel plans. Tess and I are still planning to fly to Paris but I'm closely monitoring the situation.

We may need to have a contingency plan for having meeting over phones / video conference, and/or have a specific date to make a call as to whether we're gonna cancel the meeting or not.

Meanwhile if anyone is canceling the travel plan, please update the agenda.

**Comment by justinfagnani** [comment]
I haven't booked travel yet and I'm on the fence with new guidance from our travel office coming out and new cases in France. It's very hard to know what the situation is going to be like in a month :(

**Comment by pmdartus** [comment]
We are also closely monitoring the progress of the Coronavirus in Paris. At the time of this writing, most of the cases are contained outside Paris. While I hope it will be contained, we can expect the virus to gain some grounds in the following days and weeks.

Let's take _Monday 9 March_ as the date where we would make the final call about the meeting cancelation. I will start the discussion with Sofitel in regard to a possible last-minute cancellation.

As a contingency plan, I am proposing to do a video conference on the same date as the original in-person F2F since some of you already originally booked some time on your calendar to attend this meeting. The exact time needs to be discussed to accommodate everybody's timezone.

**Comment by mfreed7** [comment]
Well, Google's travel guidance has been updated again, and it now definitely precludes this F2F. I'd still like to VC in, though.

**Comment by justinfagnani** [comment]
Yeah, I won't be able to attend, nor @kevinpschaaf from our team. Would like to VC as well.

**Comment by rniwa** [comment]
Looks like the Louvre was closed on Sun, March 1st. I’ve started to think that perhaps we need to call it off to be on safe side.

**Comment by pmdartus** [comment]
As the number of cases in France already reached +200 peoples in France and in light of the different travel policy changes, I, unfortunately, think we will have to **cancel the in-person meeting and fallback to a virtual conference call**.

Now speaking about the logistics for the conference call, I am proposing to hold it on March 23-24. Starting at the meeting at 10 am EST is a nice middle ground since most of the participants are either located in Europe or on the West Coast.

**Comment by rniwa** [comment]
By EST 10am, you mean UTC 3pm? The U.S. will be in day light saving time by then.

That would be PDT (Bay Area) 8am, CET (Paris) 4pm, and EDT (New York) 11am.

Maybe we can have two 4 hour sessions?

**Comment by mfreed7** [comment]
So it looks like the previous agenda [has been removed](https://github.com/w3c/webcomponents/wiki/2020-Spring-F2F)? Is there a new place to put agenda items?

**Comment by rniwa** [comment]
Ugh... not sure what happened there. Filed https://github.com/w3c/webcomponents/issues/868 to track agenda.

**Comment by annevk** [comment]
I suspect Tess renamed it so now it's at https://github.com/w3c/webcomponents/wiki/2020-Spring-Virtual-F2F.

**Comment by hober** [comment]
oh ugh, sorry. I didn't know retitling would break links. ugh.

**Comment by hober** [comment]
fixed the link in the issue text

**Comment by rniwa** [comment]
Right now, declarative shadow DOM is the only topic being listed. If that's the case, we probably don't need two days.

**Comment by justinfagnani** [comment]
I just added scoped custom element registries and theming.

**Comment by JanMiksovsky** [comment]
I think it'd be worth doing more preparation than usual ahead of the upcoming meeting to compensate for the serious challenge of doing the meeting entirely remotely.

* We've often put together an agenda on the whiteboard at the beginning of the meeting and allocate time for various topics. We'll need something to replace that whiteboard.
* Additionally, I think we often spend quite a bit of time at the start of each topic trying to reconstruct who cares about the topic, why it's on the agenda, where the discussion stopped at the last meeting or how the discussion may have evolved online.
* It may be harder in an online forum to wrap up a topic and definitively move on to the next one.

Proposal:
1. Create a live agenda document that updates in real time so everyone can see where we're at.
2. Before the meeting, ensure that each proposed topic has an advocate. If that person's time allows, they'd be encouraged to prepopulate the agenda with a 1–3 sentence summary of where things stand on the topic and what people should be prepared to discuss.
3. At the start of the meeting, we'll agree on the numerical order in which we want to discuss the topics and how much time we want to allocate. That goes in the live agenda.
4. When we're ready to start a topic, the designated advocate will kick of the discussion with a concise summary of where things stand and what we need to talk about.
5. When we're ready to wrap up on a topic, an agenda secretary will record the *summary* of the discussion in the agenda. This secretary is not the scribe or the chair; they're just focused on maintaining the representation of the agenda. By being able to see the resolution or follow-up steps in writing, it should be easier for remote participants to agree on their understanding and prepare to move on to the next topic.
6. We update the agenda as we go.

If something along these lines sound useful, I volunteer to act as that agenda secretary.

I put together a sample [live agenda document](https://docs.google.com/document/d/1lpy6k_ZlI5iVo-Y0vJaDfFAQvYRjpZqUcSlnOex2A0Q/edit#heading=h.9ut5sja3keva) based on what's currently on the wiki. That document is open for anyone to edit. I prepopulated it with topics based on what was on the agenda in September 2019 and what's on the wiki page. People who want to keep adding to the wiki can obviously do so — I could move over the content before the meeting — but I think we'll want more detail before the meeting starts than just topic names and links.

A separate point we need to consider is producing meeting minutes. Historically we've had a rotating volunteer scribe record notes in IRC, then another volunteer publish those online. Doing the meeting online (Google Meet, I'm guessing?) opens up the possibility of automated transcription. It appears that Meet can generate captions, but turning those into a transcription requires a Chrome Extension. If there are other options, we could look at those. While automated transcription might not be ideal, it might suffice, and it would free up all participants to focus on the conversation.

We'll also need to make heavy use of a speaker queue. We've historically used Zakir in IRC, and could continue to do that. Alternatively, TC39 uses https://tcq.app and one of my colleagues has had a good experience with that. (TCQ has its own, much more rudimentary, representation of an agenda.)

**Comment by rniwa** [comment]
> At the start of the meeting, we'll agree on the numerical order in which we want to discuss the topics and how much time we want to allocate. That goes in the live agenda.

We'd probably need to decide the time to discuss each topic prior to the meeting (at least a few days in advance) due to the timezone differences.

**Comment by JanMiksovsky** [comment]
@rniwa Great point. I've added a Participant Time Zones table at the bottom of that document based on the time zones for declared participants, plus Tokyo and Sydney for people implicated in some of the discussions.

I've tried to highlight regular 9 am–5 pm working hours, plus 3 hours on either side of that if people can make allowances for working somewhat early or late (while staying within the bounds of sanity).

Agree that it would be good to figure out timing of specific discussions by, say, the end of this workweek.

**Comment by JanMiksovsky** [comment]
Since some people reacted positively to my agenda idea, maybe we can run with that?

If that sounds okay, then the next step would be to have the proposed advocates mentioned for specific discussions add a sentence or two to the draft [live agenda](https://docs.google.com/document/d/1lpy6k_ZlI5iVo-Y0vJaDfFAQvYRjpZqUcSlnOex2A0Q/edit) summing up where the proposal/issue stands, and how they'd like to focus the discussion during the meeting.

I took a shot at identifying the following people as advocates for proposals/issues: @tabatkins @hayatoito @justinfagnani @rakina @domenic @mfreed7 @diervo @alice @westbrook. (I put myself down for one topic as well.)

It might turn out that some topics are no longer interesting and can be dropped, or won't have enough new information gathered in time to ensure a productive discussion. In that case, feel free to pull something off the agenda.

Alternatively, if you're not going to be able to attend, or you think an issue with your name next to it would be better handled by a different person, you can remove your name and (hopefully) nominate someone else to act as the advocate for it.

**Comment by domenic** [comment]
I'm no longer working on web components, and would appreciate not being added to any agenda.

**Comment by JanMiksovsky** [comment]
@domenic Shall I pull off that "Avoiding custom element FOUC" topic then, or did you want to have someone else represent that?

**Comment by domenic** [comment]
I'm not sure who added it, but it would be best to delete things that weren't volunteered to be presented.

**Comment by JanMiksovsky** [comment]
I've removed it. I'd started the draft with topics that had been covered in September 2019 and which hadn't been resolved in that meeting, with the assumption that those would still be active topics. Sorry for the confusion.

**Comment by pmdartus** [comment]
Hi all, the virtual F2F is next week.

I took the opportunity to create the calendar invite and set up the meeting call. As discussed above, let's plan 2 sessions of discussion Monday 23 and Tuesday 24 between [3 PM](https://www.timeanddate.com/worldclock/converter.html?iso=20200318T150000&p1=1440&p2=195&p3=179&p4=224) and [7 PM](https://www.timeanddate.com/worldclock/converter.html?iso=20200318T190000&p1=1440&p2=195&p3=179&p4=224) UTC. We might revisit this schedule depending on the attendance and the agenda on Monday.

**Calendar:** [link](https://calendar.google.com/calendar?cid=OHIxbzFhcGptZ284cGcxZ2EzbXZ2c212bjRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

**Conference call information:**

> To join the video meeting, click this link: https://meet.google.com/bbj-kxox-cra
> To join by phone, look up the best number to use and the PIN on this page: https://meet.google.com/tel/bbj-kxox-cra?hs=5

**Comment by dandclark** [comment]
There is still an agenda section here: https://github.com/w3c/webcomponents/wiki/2020-Spring-Virtual-F2F#agenda

Separately there is the [live agenda page](https://docs.google.com/document/d/1lpy6k_ZlI5iVo-Y0vJaDfFAQvYRjpZqUcSlnOex2A0Q/edit#).

Have we settled on using the live agenda?  If so, should we replace the Agenda section [here](https://github.com/w3c/webcomponents/wiki/2020-Spring-Virtual-F2F#agenda) with a link to the live one?

**Comment by mfreed7** [comment]
...and if the new agenda is the [live agenda page](https://docs.google.com/document/d/1lpy6k_ZlI5iVo-Y0vJaDfFAQvYRjpZqUcSlnOex2A0Q/edit#), I presume the expectation is that we should be directly editing that doc to reflect what we're interested in discussing? Or would you prefer that change requests be made on this thread?

**Comment by JanMiksovsky** [comment]
If it's okay with everyone, let's use that live agenda. I think it's going
to be much easier for us to follow along in a live doc than a wiki page.
I'll update the wiki page to point to that doc.

Everyone should have open edit access to the doc.
If anyone, for any reason, would rather not update that doc, or hits
technical issues editing it, please just update the wiki page. I'll keep
watching that page for changes, and will move any new content over.

**Comment by justinfagnani** [comment]
Since on a virtual meeting we're not going to have a chance for serendipitous hallway conversations, should we schedule something to take that place? I'm not sure what, but maybe open-discussion, or un-conference-like breakouts?

**Comment by JanMiksovsky** [comment]
Good idea. Maybe this could be an optional block that follows the 4 hour official session that ends at 7:00 pm UTC.

Looking at the participant time zone map at the bottom of the agenda, it looks like the end of the official session falls roughly at dinnertime for CET, lunchtime for PDT, and, um, snack time for EDT. So maybe we could do this as a virtual shared meal: people gather in breakouts to eat and talk together?

**Comment by rniwa** [comment]
> Looking at the participant time zone map at the bottom of the agenda, it looks like the end of the official session falls roughly at dinnertime for CET, lunchtime for PDT, and, um, snack time for EDT. So maybe we could do this as a virtual shared meal: people gather in breakouts to eat and talk together?

Well, that's a bit problematic because I do need to get food somewhere in order to have my meal.

**Comment by Westbrook** [comment]
@pmdartus I couldn't open those calendar events, are their permissions open?

We're committed to meeting next week? There was some talk about wanting a different timeline to prepare for presenting digitally and wanted to confirm.

**Comment by rniwa** [comment]
> @pmdartus I couldn't open those calendar events, are their permissions open?
> 
> We're committed to meeting next week? There was some talk about wanting a different timeline to prepare for presenting digitally and wanted to confirm.

It's happening Monday 23 & Tuesday 24, 3 PM - 7 PM UTC.

**Comment by pmdartus** [comment]
@Westbrook Here is the [new calendar](https://calendar.google.com/calendar?cid=OHIxbzFhcGptZ284cGcxZ2EzbXZ2c212bjRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ). I made the calendar public, so you should have access to it.

**Comment by annevk** [comment]
I added a couple of comments to the live agenda. I think it would be useful if each topic had an advocate that's intimately familiar with the topic and can give a brief introduction as well as the required next steps. (Not needed for triage of course.) I'm not sure how much chairing we'll need but I'm happy to volunteer.

Using Zakim and `#components` on [W3C IRC](https://www.w3.org/wiki/IRC) seems reasonable. Automated transcription sounds great. If that's guaranteed let's use the IRC channel as a backchannel and a way to exchange links and such.

Anything else?

**Comment by tabatkins** [comment]
> On Wed, Mar 18, 2020 at 2:36 AM Pierre-Marie Dartus <notifications@github.com> wrote:
> *Conference call information:*
>
> To join the video meeting, click this link:
> https://meet.google.com/bbj-kxox-cra
> Otherwise, to join by phone, dial XXXXXXXXXXXXX and enter this PIN:
> 969 359#
> To view more phone numbers, click this link:
> https://tel.meet/bbj-kxox-cra?hs=5


 So hey pro tip, please don't include a French number in the instructions
 and hide other numbers behind a link. I, uh, may have just gotten a text
 from T-Mobile that I incurred $600 of international calling fees from
 today's meeting.

It would have been much friendlier, and less likely to catch people, to
just not have a phone number listed, and direct everyone to the link.

~TJ

**Comment by hober** [comment]
I've updated the wiki page and this page to drop references to that phone number. So sorry that happened, @pmdartus.

**Comment by tabatkins** [comment]
It was me, actually; I forgot that Markdown blockquotes pick up the following paragraphs unless you double-space, so it parsed weird here in the comment (I replied in an email and didn't see the misparse).

It's fine, if I can't get it removed I'll expense it, but thank you for fixing it for others. ^_^

**Comment by pmdartus** [comment]
Sorry for the inconvenience @tabatkins, I didn't catch this when preparing the meeting invite.

**Comment by rniwa** [comment]
This virtual F2F went pretty well! I'm now suggesting that maybe we can have [another one focused on accessibility](https://github.com/w3c/webcomponents/issues/872). Please let us know of your interests :)

**Comment by sideshowbarker** [comment]
From the people here who participated in this meeting, it would be nice to record some detailed feedback somewhere about how the logistics went: What worked well, what didn’t, etc.

For other groups who’ll be doing similar “virtual f2f” meetings over the coming months, having some such *“here’s what worked well, here’s what didn’t; based on our experiencer, here are some tips on how to make it better”* info could be really helpful.

For now https://github.com/w3c/webcomponents/wiki/2020-Spring-Virtual-F2F would be a good place to add such info. We can copy/move it to another more-general location later.

**Comment by JanMiksovsky** [comment]
Seems like we can close this issue...

**Comment by sideshowbarker** [comment]
> Seems like we can close this issue...

Yup, made it so
