### ISSUE TITLE
No point in having closed/open shadow dom creation if we cant use closed?

### ISSUE THREAD

**Issue by Ferynix** [WICG/webcomponents#859]
I'm generally confused right now, I wanted to create a hidden element inside a page with a CLOSED Shadow dom.

However, how can we even dare to make changes to a shadow if its closed and readonly.

and again, we are only able to make changes to an OPEN shadow dom, and we are unable to set the mode to closed....

So... **Whats even the point to having the "mode" if we arent even able to write to a closed dom...**

I want to write to a closed shadow dom so you cant see the elements without specifically enabling the little setting on the debugger

**Comment by rniwa** [comment]
?? You can continue to make changes to `ShadowRoot` if you have a reference to it.

```js
const host = document.createElement('div');
document.body.appendChild(host);
const shadowRoot = host.attachShadow({mode: 'closed'});
shadowRoot.innerHTML = '<p>hello, world</p>';
host.shadowRoot // This returns null.
```

**Comment by Ferynix** [comment]
> ?? You can continue to make changes to `ShadowRoot` if you have a reference to it.
> 
> ```js
> const host = document.createElement('div');
> document.body.appendChild(host);
> const shadowRoot = host.attachShadow({mode: 'closed'});
> shadowRoot.innerHTML = '<p>hello, world</p>';
> host.shadowRoot // This returns null.
> ```

Yeah I just noticed that.. Im a dumb dumb...
