### ISSUE TITLE
odd custom element placement

### ISSUE THREAD

**Issue by jutunen** [WICG/webcomponents#869]
Here's my custom element placed correctly:

http://51.38.51.120/issue/arrow.html

Here's my custom element placed oddly:

http://51.38.51.120/issue/arrow_2.html

When the wrapped text is removed from the element, placement is correct:

http://51.38.51.120/issue/arrow_3.html

Can anyone explain this behaviour? 
Is it so that one should not wrap anything in a custom element if there's no slot for it?

Element source:

http://51.38.51.120/issue/custom-arrow.js

Element github: 

https://github.com/jutunen/custom-arrow

**Comment by Westbrook** [comment]
URLs not currently public.
