### ISSUE TITLE
2020 Virtual F2F for Accessibility and Web Components

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#872]
# When: 22:00 – 26:00 UTC on Tuesday, September 15

[Localized times](https://www.timeanddate.com/worldclock/converter.html?iso=20200915T220000&p1=1440&p2=224&p3=240&p4=101&p5=195&p6=136):
San Francisco (PDT): 3pm – 7pm on Tuesday, September 15
Sydney (AEST): 8am – 12pm on Wednesday, September 16
Tokyo (JST): 7am – 11am on Wednesday, September 16
Helsinki (EEST): 1am – 5am on Wednesday, September 16
Paris (CEST): midnight – 4am on Wednesday, September 16
London (BST): 11pm Tuesday, September 15 – 3am Wednesday, September 16

# Where: Google Meet

https://meet.google.com/nnd-eqbe-fyr

# What: agenda and minutes

[Live Agenda for the September 2020 meeting](https://docs.google.com/document/d/1QTcATefkEzUIsmE3xLXb5oDuom4BNCknXiYXpBNhzjQ/edit#).

# Queue

https://tcq.app/meeting/vpn9

---

### Old summary

We had a pretty productive [virtual F2F this week for web components](https://github.com/w3c/webcomponents/issues/855).

Should we schedule another virtual conference focused on accessibility topics sometime next month?

We have a few topics for accessibly in web components:
 - [element reflection](https://github.com/whatwg/html/issues/4925)
 - [default ARIA role](https://github.com/whatwg/html/pull/4658)
 - [default tabIndex](https://github.com/w3c/webcomponents/issues/762)

**New Agenda**: https://docs.google.com/document/d/1QTcATefkEzUIsmE3xLXb5oDuom4BNCknXiYXpBNhzjQ/edit#

Vote on [Doodle](https://doodle.com/poll/3udivqy5s554yy8y) to pick the meeting week.
**Now vote on [Doodle](https://doodle.com/poll/dkssnvttf5kcrm69) to pick a specific date**.

**Comment by rniwa** [comment]
@Alice @hober @bkardell @annevk @cookiecrook @tkent-google

**Comment by muan** [comment]
Thanks for opening an issue for this. I was hoping to learn more about these topics at this F2F! I’d love to attend this call if it works out. (New York, EDT)

**Comment by justinfagnani** [comment]
I would love to attend to talk about cross-scope references in general and specially for element reflection.

**Comment by rniwa** [comment]
> I would love to attend to talk about cross-scope references in general and specially for element reflection.

Any pointers to use cases / documents about this?

**Comment by annevk** [comment]
This sounds like a good idea. And if we make the timing work for Alice it'd probably also work for @jcsteh. Probably not feasible to find a time that spans Australia, Europe, East US, and West US though?

**Comment by jcsteh** [comment]
I'd love to attend if we can make it work. Accommodating four time zones is tricky, but I can be pretty flexible for a one-off. Earliest I can really do while still being remotely useful is about 5AM my time (UTC+10:00), which is 23:00 UTC. Obviously, I'd prefer later, but that's already 9PM in Europe.

**Comment by rniwa** [comment]
My thinking is that we can probably do it around 9am Sydney, AEDT especially if we wanted someone from Tokyo at 7am JST or Taipei at 6am CST. That would be 10pm London, UTC, 11pm Paris/Zurich, CET, midnight at Helsinki EET. Definitely not Europe friendly time but then this week's meeting was super unfriendly to APAC region so I figured that would be only fair especially given where the relevant people are located for this topic.

**Comment by caridy** [comment]
please, add me too!

**Comment by bkardell** [comment]
Would love to join as well.

**Comment by dbatiste** [comment]
Would it be ok if I attended this as well?

**Comment by ekashida** [comment]
I would like to attend this as well. The last virtual F2F was a killer since it started at 0:00 JST (15:00 UTC) for me. 4:00 JST (19:00 UTC) or later would be amazing!

**Comment by rniwa** [comment]
I just added a doodle to vote on the week of this meeting in OP. Please check it out.

**Comment by alice** [comment]
@justinfagnani 
> > I would love to attend to talk about cross-scope references in general and specially for element reflection.

@rniwa 
> Any pointers to use cases / documents about this?

This may be referring to the Opaque Reference idea from https://github.com/whatwg/html/issues/4925#issuecomment-563434122

I would love a discussion on this.

**Comment by alice** [comment]
I'd love my colleagues @chrisosaurus and @dot-miniscule to join as well, if that's ok. They're both in the ~same timezone as me and @jcsteh (starting next week when the east coast of Australia becomes all one timezone again).

**Comment by rniwa** [comment]
Looks like the week of April 20th is the winner.

Alright, we should probably avoid having this on Monday AEDT or Friday PST since we don't want to make people work on Sunday afternoon or Saturday morning. That leaves Monday through Thursday PST and Tuesday through Friday AEDT.

Here's a new noodle for specific dates: https://doodle.com/poll/dkssnvttf5kcrm69

**Comment by rniwa** [comment]
Please vote on a specific date but it looks like the current winner is:
Tuesday, April 21st PDT afternoon / Wednesday, April 22nd AEDT/JST morning

My suggestion is to start it at 2020-04-21T22:00Z and continue for 4 hours. [Localized times](https://www.timeanddate.com/worldclock/converter.html?iso=20200421T220000&p1=1440&p2=224&p3=240&p4=101&p5=195&p6=136):
 - San Francisco (PDT): 3pm through 7pm on Tuesday, April 21st
 - Sydney (AEST): 8am through 12pm on Wednesday, April 22nd
 - Tokyo (JST): 7am through 11am on Wednesday, April 22nd
 - Helsinki (EEST): 1am through 5am on Wednesday, April 22nd
 - Paris (CEST): midnight through 4am on Wednesday, April 22nd
 - London (BST): 11pm Tuesday, April 21st through 3am Wednesday, April 22nd

**Comment by rniwa** [comment]
Hi all, I'm regrettably informing you all that I'm going on a medical leave of absence until mid May. As a result, I would not be able to attend this meeting if it takes place in April or early May.

I'm sorry for causing such a debacle since I'm the one who suggested to have this meeting in the first place but unfortunately I don't have a much choice at the moment. Hope to talk to you all soon again.

**Comment by ekashida** [comment]
Sorry to hear that @rniwa, I hope everything is ok. Thanks for your attempt to organize this virtual F2F and I look forward to attend the next one!

**Comment by JanMiksovsky** [comment]
@hober Since we couldn't meet in April/May, I was wondering if we could try again to arrange an accessibility-focused meeting between now and TPAC at the end of October. A pre-TPAC meeting would help insure we give accessibility the attention it deserves and leave more time for other topics at TPAC (e.g., finishing up scoped custom element registries).

Perhaps we could try for the first half of September?

**Comment by JanMiksovsky** [comment]
I've been in contact with @alice, @hober, and @cookiecrook about this, and it sounds like they'd be up for a pre-TPAC accessibility meeting.

Rough timeframe would be a date in first half of September
Would preserve the original intention of Pacific-friendly meeting time: 22:00 UTC, 4 hours in length

Pinging people cited above for their interest: @bkardell @annevk @tkent-google @muan @justinfagnani @jcsteh @caridy @dbatiste @ekashida — if you're up for this, maybe give a thumbs up on this post
Would also be good to get a signal from @mfreed7 and @travisleithead

If we can get at a quorum that includes at least one person from Mozilla, I'll follow up with a Doodle poll to pick a date.

**Comment by JanMiksovsky** [comment]
Thanks for everyone's interest!

Please select your preferred September dates for the accessibility-focused web components meeting using this Doodle poll: https://doodle.com/poll/7xw2upudh42abqe2.

I'll keep the poll open through next week to give people time to respond, then pick a date. Please feel free to forward to people who would likely want to attend.

**Comment by JanMiksovsky** [comment]
Thanks to everyone who responded to the Doodle poll. The best start time appears to be 22:00 UTC on Tuesday, September 15.

[Localized times](https://www.timeanddate.com/worldclock/converter.html?iso=20200915T220000&p1=1440&p2=224&p3=240&p4=101&p5=195&p6=136):
San Francisco (PDT): 3pm – 7pm on Tuesday, September 15
Sydney (AEST): 8am – 12pm on Wednesday, September 16
Tokyo (JST): 7am – 11am on Wednesday, September 16
Helsinki (EEST): 1am – 5am on Wednesday, September 16
Paris (CEST): midnight – 4am on Wednesday, September 16
London (BST): 11pm Tuesday, September 15 – 3am Wednesday, September 16

Please save the date!

**Comment by JanMiksovsky** [comment]
I think the [Live Agenda for the March 2020 Meeting](https://docs.google.com/document/d/1lpy6k_ZlI5iVo-Y0vJaDfFAQvYRjpZqUcSlnOex2A0Q/edit#heading=h.9ut5sja3keva) worked fairly well to orchestrate the remote meeting and summarize the results.

With that in mind, I've created a new [Live Agenda for the September 2020 meeting](https://docs.google.com/document/d/1QTcATefkEzUIsmE3xLXb5oDuom4BNCknXiYXpBNhzjQ/edit#).
* I've prepopulated the agenda with the discussion topics proposed at the top of this thread.
* I also added [Element reflection and shadow roots](https://github.com/whatwg/html/issues/5401) as a topic, which seems to be a key open question for the element reflection topic.
* We should designate an advocate for each issue who can introduce the topic — having someone ready to provide an intro definitely helped speed things up last time. @alice I put your name down next to those issues that you had originally filed, but feel free to designate someone else instead.
* Along the same lines, it would also help to add a short summary of the current state of things for each issue, particularly in cases where the issue discussion had been long.

If anyone has an accessibility + web component topic to add to the agenda, please do so!

**Comment by annevk** [comment]
I won't be able to make that time. I suspect John Dai won't be able to attend either then. We can probably chat with @jcsteh afterwards or some such.

**Comment by F1LT3R** [comment]
This is really interesting work. Are these open meetings that anyone can attend?

**Comment by JanMiksovsky** [comment]
@annevk Let me know if we should look for another date — I'd picked a date that you'd indicated was one you could make. John had also indicated that the proposed date would work. Perhaps the terrible time for Europe participation had been unclear? That's completely understandable! (I'd just been following the original suggestion to make this meeting more convenient for Pacific folks.)

In any event, there are other dates that worked nearly as well, so if the issue was the specific date, let me know.

**Comment by annevk** [comment]
Yeah, I did not realize we would keep the same time. I'm fine with reading the notes and chatting with some folks about it afterwards.

@F1LT3R in principle, yes.

**Comment by jnurthen** [comment]
Will the meeting details be posted here or is it by invite? I would love to attend.

**Comment by JanMiksovsky** [comment]
Since Google Meet seemed to generally work well last time, I've created a Google Meet link we can use for the call: https://meet.google.com/nnd-eqbe-fyr.

**Comment by leobalter** [comment]
I'm looking forward to see everyone there! The F2F is starting in less than 2 hours!

**Comment by EisenbergEffect** [comment]
I won't be able to make it but @nicholasrice from my team will be present. I look forward to reading the meeting notes afterwards. Thanks everyone for keeping web components moving ahead!

**Comment by rniwa** [comment]
Thanks for the productive discussion everyone!

**Comment by JanMiksovsky** [comment]
I've done my best to reflect the conclusions captured in the shared [meeting agenda] document as new comments on issues [4925](https://github.com/whatwg/html/issues/4925#issuecomment-693648647), [5401](https://github.com/whatwg/html/issues/5401#issuecomment-693739800), and [762](https://github.com/w3c/webcomponents/issues/762#issuecomment-694506260).

Meeting attendees: if you spot something I failed to capture accurately, please feel to comment on the relevant issue.

**Comment by rniwa** [comment]
This is done, thanks everyone!
