### ISSUE TITLE
[idea] shadowattach event

### ISSUE THREAD

**Issue by trusktr** [WICG/webcomponents#893]
A `shadowattach` event would fire on an element whenever it has a ShadowRoot attached to it (f.e. by calling `attachShadow()` on the element).

I believe it can be useful to know when an element's children may be distributed, mainly for custom rendering. I've described this before, but just throwing in this event idea in its own issue.

---

The main use case is in implementation of non-CSS-based rendering. For example, to implement ShadowDOM support for Mozilla A-Frame, the A-Frame implementation would need to be aware of the final "flat tree" or "composed tree" in order to be able to render the 3D scenes (powered by Three.js) based on the structure of the composed tree.

The engine inherently has fully knowledge of the composed tree in order to be able to render everything properly, but userland rendering systems do not have easy access to the composed tree.

Adding `shadowattach` event would be a simple way to understand when certain internal state tracking must change in order to update composed rendering.

I'm made an initial ShadowDOM implementation for my WebGL-powered elements at http://lume.io, but I'm still working on the edge cases. I've needed to monkey-patch `attachShadow` in order to implement state tracking of the composed tree.

I believe that `shadowattach` (or perhaps `distribute` on child elements, or similar) would be one way to update when we know the composed tree may have changed.

Basically what I'm thinking about is what features would allows to more easily create custom elements with custom rendering with ShadowDOM support, without requiring monkey patching. `slotchange` is an event that gets us part of the way there, but I found that I can not implement custom rendering only with `slotchange`.

Another thing that helps is reading `shadowRoot.host` which only works from the inside of a shadow root if it has `mode: 'closed'`.

Another idea is, what if elements had `composedParent` and `composedChildren` properties? This would make it simple to traverse the composed tree. We'd still need events to tell us when these properties change, which can change more often than connected/disconnected. With events, and those properties, we'd be able to easily track the composed tree.

---

The thing is, for average web apps using only CSS rendering, there's largely no need for this stuff. It's really useful for custom rendering.

---

Another question is, how can we satisfy the [Extensible Web Manifesto](https://extensiblewebmanifesto.org/) in order to explain how the CSS engine understands the composed tree, and to allow web developers to also understand it for custom rendering systems or even for CSS runtime polyfills of new CSS features/ideas?

**Comment by rniwa** [comment]
This would violate the basic encapsulation promise of shadow DOM. We don't want outside scripts to know whether the shadow DOM exists or not.

**Comment by rniwa** [comment]
2023 F2F: This issue is not to be fixed because we already have a `slotchange` event for in shadow observation and making observation from outside will be violation of encapsulation.
