### ISSUE TITLE
RfC: An alternative approach to accessibility across shadow boundaries

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#898]
Based on some concerns raised by Mozilla during the last F2F, we came up with an alternative declarative approach for solving accessibility use cases across shadow boundaries at https://github.com/WICG/aom/issues/169

**Comment by rniwa** [comment]
@LJWatson @diervo @leobalter @justinfagnani

**Comment by leobalter** [comment]
Thanks for the ping, @rniwa! This allowed me to contact @caridy who is already [in the loop](https://github.com/WICG/aom/issues/169#issuecomment-714200977).

Please, let us know if we can also help with testing it at Salesforce. cc @gregwhitworth.

**Comment by Westbrook** [comment]
Is this appropriate superseded by https://github.com/WICG/webcomponents/blob/gh-pages/proposals/reference-target-explainer.md?

**Comment by Westbrook** [comment]
Closing in preference of Reference Target which got ringing endorsements at TPAC this year.
