### ISSUE TITLE
Enable Discussions For this Repo?

### ISSUE THREAD

**Issue by bahrus** [WICG/webcomponents#910]
There are times I'd like to do something between asking a question of "how to do this," vs posting an issue --  which might or might not possibly lead to a broader discussion of a nice enhancement to the platform.

There are other forums, but it would be nice to be able to benefit from the automatic linking that GitHub provides.

**Comment by Danny-Engelman** [comment]
It is hidden in the settings, GitHub added "Discussions" recently


![image](https://user-images.githubusercontent.com/3382713/102635363-7e2e8100-4153-11eb-92a4-ee3db589b62b.png)

**Comment by rniwa** [comment]
I don't think we want to turn this repository into a general forum about web components. We should keep this a place to discuss standards.
