### ISSUE TITLE
Why is Chrome Platform Status reporting 70% usage for HTMLSlotElement?

### ISSUE THREAD

**Issue by Danny-Engelman** [WICG/webcomponents#912]
Can someone explain why these Chrome Platform Status stats are so high?

``CustomElementsRegistryDefine`` at **9.7%**  seems a fair number
https://chromestatus.com/metrics/feature/timeline/popularity/1689

But ``HTMLSlotElement`` at **70%** for the past years   
https://chromestatus.com/metrics/feature/timeline/popularity/1898

and ``NodeGetRootNode``  at  **22.3 %**
https://chromestatus.com/metrics/feature/timeline/popularity/1467

I can not explain, unless they are not related to userland Web Components usage

Screenshots:

### HTMLSlotElement
https://chromestatus.com/metrics/feature/timeline/popularity/1898
![](https://i.imgur.com/yhF8jiK.png)

### NodeGetRootNode
https://chromestatus.com/metrics/feature/timeline/popularity/1467
![](https://i.imgur.com/n8AnryF.png)

### CustomElementsRegistryDefine

**Is there an explanation for Q1 2019 and Q4 2019 -50% dips?**

https://chromestatus.com/metrics/feature/timeline/popularity/1898
![](https://i.imgur.com/0w8D35v.png)

**Comment by justinfagnani** [comment]
This is probably the wrong place to ask, I'm not sure how many people here are familiar with Chromium stats.

**Comment by rniwa** [comment]
Yeah, please ask this in some kind of Chromium / Blink forum. This issue tracker is for discussing web components standards.

**Comment by mfreed7** [comment]
Sorry, little late to the question, but that's almost surely due to UA Shadow DOM. For example, [any of these elements](https://source.chromium.org/search?q=CreateUserAgent%5Cw*Slot%20f:element.cc$%20-f:html_slot_element.cc&ss=chromium%2Fchromium%2Fsrc) uses a slot element in the UA shadow root.
