### ISSUE TITLE
[idea] New Lifecycle Callback: `willConnectCallback` for initializing attributes

### ISSUE THREAD

**Issue by Hawmex** [WICG/webcomponents#919]
Well, we can't set attributes in constructor, and if we set them in `connectedCallback` it will cause some problems with `MutationObserver` (e.g. when a custom element is added to DOM, first mutationCallback is triggered then attributes are initialized in `connectedCallback`).
So what about a lifecycle callback before element is added to DOM that is ergonomically the best way to initialize attributes?

**Comment by justinfagnani** [comment]
I think the proper solution here is to eliminate all use cases for an element setting attributes on itself _not_ in response to property changes or user input. Just like with built-in elements, a custom element shouldn't spontaneously sprout attributes.

This means we need ElementInternals to handle focus, custom CSS state, and default ARIA roles and delegation. I believe all of those are in progress.

**Comment by Hawmex** [comment]
Thanks @justinfagnani you're right. I thought it would improve the developer experience in some cases (e.g. a route component could have a path attribute which is by default set to `"*"` instead of explicitly setting it in the markup).
