### ISSUE TITLE
Issue while exporting calendar event from Microsoft Graph Api

### ISSUE THREAD

**Issue by Tulshiram1820** [WICG/webcomponents#920]
I am getting error while running script to exporting calendar event from Microsoft Graph Api

I am using code from link : 
https://github.com/spjeff/office365/blob/master/office365-read-all-calendar/O365-ReadAllCalendar.ps1

Application created in Azure with Mentioned permission.

![image](https://user-images.githubusercontent.com/82167363/114053281-70406f80-98ac-11eb-82dd-cc5a6e8402ac.png)

**Comment by Tulshiram1820** [comment]
I was able to get the Token :
![image](https://user-images.githubusercontent.com/82167363/114053641-c44b5400-98ac-11eb-91ac-3d1c92574738.png)

But while running complete command get the error as :
![image](https://user-images.githubusercontent.com/82167363/114053896-fbba0080-98ac-11eb-9be4-37b6027ae98e.png)
![image](https://user-images.githubusercontent.com/82167363/114053987-12605780-98ad-11eb-89a5-a14a76db1ffd.png)
![image](https://user-images.githubusercontent.com/82167363/114054054-2310cd80-98ad-11eb-9ac0-d114a65625ba.png)

Need help please as soon as possible.

**Comment by rniwa** [comment]
This is an issue tracker for discussing web components related standards. Question about Microsoft Graph API is off topic.
