### ISSUE TITLE
Specification of CSS @font-face at shadow DOM level scope

### ISSUE THREAD

**Issue by cypar** [WICG/webcomponents#925]
Hello,

I am looking for official documentation/specification of CSS `@font-face` at shadow DOM level scope. I know by experience that `@font-face` should be declared at global scope, outside of shadow DOM (at least on the latest Chrome), however, I cannot find any specification about it. 

Could anyone please help me find one? If there is not one yet, I would love to read through related discussions and/or memos. Please feel free to correct me if I am wrong.

Thanks,
CY

**Comment by emilio** [comment]
This is https://github.com/w3c/csswg-drafts/issues/1995.
