### ISSUE TITLE
Autofill of form inside shadow Dom - chrome bug

### ISSUE THREAD

**Issue by LukaszKiedrowski** [WICG/webcomponents#926]
My example:

I have form with username, password and submit input. All
Elements are inside shadow Dom. If I submit the form the save username/password prompt appears. Then I save the username/password - everything is fine but after refresh the page I see that username and password is not autofill. 

This problem doesn’t happen outside of shadow Dom and this problem happens in chrome but not Firefox.

is it some limitation of shadow Dom or just bug ? Do you know maybe how to fix it ?  
 
Thanks

**Comment by justinfagnani** [comment]
You can file Chrome bugs at https://crbug.com

**Comment by rniwa** [comment]
FWIW, WebKit bug is at https://bugs.webkit.org/show_bug.cgi?id=203299
