### ISSUE TITLE
TPAC 2021 Web Components Meeting

### ISSUE THREAD

**Issue by mfreed7** [WICG/webcomponents#944]
Forgive me if this is already being discussed somewhere, but are there plans for a Web Components meeting at TPAC this year?

Breakouts are October 18-22, and apparently [proposals are due in two days, Friday October 8, 2021](https://www.w3.org/wiki/TPAC/2021/SessionIdeas).

I see [one item on the agenda already](https://www.w3.org/wiki/TPAC/2021/SessionIdeas#Web_Components_Community_Group:_Community_driven_spec.2FAPI_prioritization), but nothing else. Perhaps we're just planning to propose individual sessions on topics, rather than a coordinated agenda of discussions?

@JanMiksovsky @westbrook @justinfagnani @diervo @rniwa @annevk @josepharhar @atotic

**Comment by Westbrook** [comment]
The session that the Web Components Community Group has proposed is definitely more about sharing community priorities rather than to discuss or clarify any in progress specifications. That being so, I do hope that there is appetite for sessions focusing directly on things like:

- constructible stylesheets, adoptedStyleSheets, and import assertions 
- Scoped custom element registries 
- cross root aria
- Form participation
- declarative shadow DOM
- Amongst other things

Happy to support getting additional sessions onto the wiki however I can!

**Comment by Westbrook** [comment]
@justinfagnani just added: https://www.w3.org/wiki/TPAC/2021/SessionIdeas#Web_Components_Breakout

**Comment by justinfagnani** [comment]
Yeah, I added the minimal info I could think of. I don't recall past proposals and whether they had better descriptions or whatnot. I also don't know if something special was done to request a longer half-day like we've had before and whether that's still a thing with TPAC online. So please anyone edit what I put up there if you can improve it!

**Comment by annevk** [comment]
@mfreed7 @justinfagnani do you have an idea what the agenda would be? For a longer meeting it would be easier to hold one after TPAC somewhere.

**Comment by justinfagnani** [comment]
I have a few issues I'd like to deep dives into:

* Scoped custom element registries
* Composed selection ranges
* Constructible stylesheets
* Open-stylable shadow roots
* Several issues around SSR use case: declarative shadow DOM, associating them with CSS modules, ElementInternals, etc.

Whether we need a longer session might depend on how many of those issues implementors want to talk about as well. I'm not sure what everyone's areas of interest are these days.

**Comment by annevk** [comment]
Of those, selection seems worthwhile talking about to me in light of the proposal. It's not clear to me the others made (enough) progress since the last time they were discussed.

**Comment by mfreed7** [comment]
Ok, I just added an [item to discuss the selection proposal](https://www.w3.org/wiki/TPAC/2021/SessionIdeas#:~:text=or%203PM%20UTC-,Selection%20APIs%20that%20support%20Shadow%20DOM,%5Bedit%5D,-Proposer%3A%20Mason%20Freed).

**Comment by annevk** [comment]
Notes from the general meeting: https://docs.google.com/document/d/16mttCA_N7wuMfaWyTIJnenrXz_8Ild7ndjbXXRknbNE/edit.

There was a separate meeting on selection that is summarized here: https://github.com/WICG/webcomponents/issues/79#issuecomment-946897700.
