### ISSUE TITLE
HTMLSlotElement.assign() does not work as expected

### ISSUE THREAD

**Issue by rpivo** [WICG/webcomponents#954]
It seems like the `HTMLSlotElement.assign()` method is a way for us to programmatically assign an element to a slot, but I can't seem to get it to work as expected.

[Here is a codepen as an example.](https://codepen.io/rpivovar/pen/qBPGYJY?editors=1111)

I've also added some of this code below.

HTML markup:

```html
<some-element><slot>foo</slot></some-element>
```

```js
class SomeElement extends HTMLElement {}

customElements.define('some-element', SomeElement);

const slot = document.querySelector('slot');

const p = document.createElement('p');
p.innerHTML = 'hello';

slot.assign(p); // should this work?
```

I expected `assign()` to set the slot with the given element, but I don't see any change.

Am I misunderstanding how `assign()` should work?

Thanks for the help!

On the other hand, if I do this:

```js
slot.innerHTML = 'hello';
```

This has the desired effect, and it also looks like doing this triggers the `'slotchange'` event.

**Comment by rniwa** [comment]
slot element can only function inside a shadow tree and only when the assigned node is a direct child of its shadow host.

**Comment by rpivo** [comment]
@rniwa it sounds like slots only work when they're used like portals between the light DOM and the shadow DOM. I can pass things to the slot from the light DOM, but trying to pass things to it from inside the shadow DOM itself (like programmatically from within the web component) doesn't make sense.

Is that right?

**Comment by rniwa** [comment]
Yes, you can't assign a node inside a shadow root to a slot. Only a direct child of a shadow host can be assigned to a slot inside that shadow tree.
