### ISSUE TITLE
TPAC 2022 Web Components Meeting(s)

### ISSUE THREAD

**Issue by mfreed7** [WICG/webcomponents#966]
Should we start thinking about breakout sessions for [TPAC 2022](https://www.w3.org/2022/09/TPAC/Overview.html)? The [Session Ideas page is now open](https://www.w3.org/wiki/TPAC/2022/SessionIdeas) to submissions.

Some ideas:
- [Scoped Custom Element Registries](https://github.com/WICG/webcomponents/issues/716)
- [Declarative Shadow DOM](https://github.com/whatwg/dom/issues/831)
- Perhaps a general purpose (smaller issue) breakout?

What else?

**Comment by leobalter** [comment]
Should we use this repo or https://github.com/w3c/webcomponents-cg? cc @westbrook. I'm fine either way.

I'd love to see Declarative Shadow DOM so we touch points remaining to unblock implementation of it in Firefox and Safari.

I plan to have the **Cross-root ARIA delegation/reflection** drafted by the next weeks so this might be another good topic.

My team will be happy to share the use cases and application of both proposals.

**Comment by nolanlawson** [comment]
I'm interested in all of the above, plus:

- [Declarative CSS modules](https://w3c.github.io/webcomponents-cg/#declarative-css-modules)
- [Open-stylable shadow roots](https://w3c.github.io/webcomponents-cg/#open-styling-of-shadow-roots)
- [Declarative custom elements](https://w3c.github.io/webcomponents-cg/#declarative-custom-elements)
- [Theming](https://github.com/WICG/webcomponents/issues/864)
- Native behavior mixins

(Mostly borrowing from https://github.com/w3c/webcomponents-cg/discussions/31)

**Comment by Westbrook** [comment]
I'd love to see a bunch of API focused breakouts and I invite anyone to submit a proposal for that who can lead the conversation. Some of those leaders might be the API/spec owners for the WCCG 2022 Report, or some of those leaders might just borrow from their good work, whatever is best to ensure the conversation is successful. I'll be submitting a proposal for the WCCG Report, but am not sure that I can actively lead any other conversations. However, I'd be excited to support anyone else who's interested in doing so in any way that I can.

Particularly, I'd love to partner with you @leobalter on the Cross Root Aria APIs!

**Comment by thescientist13** [comment]
I'd be happy to participate in general TPAC Report and related breakout sessions.  I'm currently tracking Declarative Shadow DOM for the report so happy to get involved on any breakouts for that one in particular.

**Comment by justinfagnani** [comment]
It think TPAC web components breakouts have generally been most useful for things we're close to consensus on. I think breakouts on scoped element registries and declarative shadow DOM might be the most in that state right now. I haven't followed along on cross-root ARIA, but maybe it is too.

For things like open-stylable shadow roots, theming, etc., I'm not exactly sure what we'd want out of the sessions. Are there any outcomes we'd aim for? Maybe implementers signaling enough interest to warrant concrete proposals?

Then, as @annevk often points out, there is a backlog of smaller items to work through. That could be its own breakout slot.

**Comment by leobalter** [comment]
> Then, as @annevk often points out, there is a backlog of smaller items to work through. That could be its own breakout slot.

I'd appreciate it if we do have a dedicated slot for those so we don't mess with the time expected for discussion on each for the smaller items or other major topics.

**Comment by mfreed7** [comment]
So there are only 3 hours of breakout session time available, which means we probably shouldn't have more than ~3 sessions total, and at least for me, I'm already booked in another session (OpenUI) and I'm guessing others might have conflicts as well. So we might be limited to ~2 sessions.

I'm happy to run a session or at least participate on Declarative Shadow DOM, perhaps mostly dedicated to Q/A and discussion, and only a brief (5 minute?) intro. Maybe we could combine this with the Cross-Root ARIA proposal, and have 1 hour for those 2 topics?

It seems like Scoped Custom Element Registries might deserve its own breakout, given the number of open issues to work through? Maybe not though. Any volunteers to run that one?

I'm not sure what the deadline for submissions is, but the schedule will be announced Sept 9, so it must be before that.

**Comment by thescientist13** [comment]
Hey @mfreed7 , I can share some updates here from the [WC Community Group](https://github.com/webcomponents-cg) at least. We've been drafting a break out session to build upon our report from last year, but a with a more "focused "narrative" compared to last year, and I think they align very well with the specs you called out.  

Basically, our abstract is
> _After a brief introduction, the Web Components CG will facilitate a discussion with implementers and community members about filling browser gaps in agreed upon features, and moving forward with the next wave of top priority asks._

And the general outline we've got going so far is
> 1. **_Introduction_** - Motivations / Aspirations
> 1. **_Browser Parity_** - Specs that just need that one final implementor to obtain ubiquitous cross-browser support
>    - Form-Associated Custom Elements
>    - Constructible Style Sheets
>    - CSS Modules
>    - Imperative slots
> 1. _**Spec Alignment**_ - Key specs we hope we to get cross-implementor buy-in on
>    - Aria
>    - Scoped Registries
>    - Declarative Shadow DOM
> 1. _**Appendix**_ - All the specifications (any particular order?)

It's mostly high level and focused on general alignment, but still leaves room for deep dive sessions on a particular topic too as more of a "workshop" session format if we want to host a second breakout?

We've been tracking them issues in our CG repo if anyone wants to jump in on those 👍 
- https://github.com/w3c/webcomponents-cg/issues/43
- https://github.com/w3c/webcomponents-cg/issues/48

We'll probably submit our first draft in the next couple of days but as it is a wiki, we can continue to refine between now and then.

Happy to hear your thoughts!

**Comment by rniwa** [comment]
> Browser Parity - Specs that just need that one final implementor to obtain ubiquitous cross-browser support
> FACE

What is FACE?

**Comment by thescientist13** [comment]
Ah yeah, I probably should have put the whole thing, just did a copy / 🍝  😅 

It is [Form-Associated Custom Elements](https://github.com/WICG/webcomponents/issues/187).  This is [our summary](https://w3c.github.io/webcomponents-cg/#form-associated-custom-elements) from our report from year.  I will update my comment to expand it out.

**Comment by mfreed7** [comment]
> It's mostly high level and focused on general alignment, but still leaves room for deep dive sessions on a particular topic too as more of a "workshop" session format if we want to host a second breakout?

That'll be a great breakout. It likely won't be the place to have debates over the technical details, but it certainly should be a good place to discuss the use cases and developer pull for these features, which is super important. Thanks.

Unfortunately, since I posted 6 days ago, it turns out I won't be attending TPAC in person this year. I will hopefully (though not definitely) be participating virtually, but that means I shouldn't be the one to sign up to drive any discussions. I'm happy to help with prep work, as much as I can. But given that, I won't be adding anything to the list of breakout sessions. Hopefully others can drive those?

**Comment by thescientist13** [comment]
Yeah, I will just be planning to participate virtually as well.

**Comment by nolanlawson** [comment]
[Meeting minutes](https://www.w3.org/2022/09/14-webcomponent-cg-minutes.html)
