### ISSUE TITLE
delegatesFocus and non-tabbable, focusable elements

### ISSUE THREAD

**Issue by mrtnmgs** [WICG/webcomponents#977]
The `delegatesFocus` API doesn't provide a way to choose which element to bring into focus. It's always the first focusable element, meaning an element with tabindex="-1" (focusable, but removed from tabbing sequence) will be focused. But in my experience handling focus programmatically is often tied to keyboard focus considerations — mouse users don't really care where focus is, but it's essential for a user tabbing through the page. Bringing focus to a non tabbable element will cause issues for these users, so it seems to me `delegatesFocus` either needs to bring focus to the first *tabbable* element (rather than focusable), OR needs to have an option for specifying which element to bring into focus (not sure if there are cases where we'd want something else than the first tabbable element).

For context, the issue I'm having is with a [roving tabindex](https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/#kbd_roving_tabindex) inside the shadow DOM.

**Comment by rniwa** [comment]
You can specify element to be focused via "autofocus" content attribute. Whichever element with autofocus will get the focus.

**Comment by mrtnmgs** [comment]
Thanks @rniwa ! Unfortunately this doesn't seem to work in Chrome... (Seems to work in FF and Safari)

**Comment by rniwa** [comment]
That sounds like a Chromium bug.
