### ISSUE TITLE
FireFox ::part styles its own shadowRoot, which it should not?

### ISSUE THREAD

**Issue by Danny-Engelman** [WICG/webcomponents#982]
This code

https://jsfiddle.net/WebComponents/wajqfk3e/

```html
<style>
  ::part(main){
    color:green;
  }
</style>
<wc-part-test></wc-part-test>
<script>
  customElements.define('wc-part-test', class extends HTMLElement {
    constructor(){
      super()
        .attachShadow({mode:"open"})
        .innerHTML = `<style>::part(main){ background-color:red }</style>` + 
                     `<h1 part="main">Hello Web Component</h1>`;
  }});
</script>
```

Produces a colored background in **FireFox** 108.01:

![](https://i.imgur.com/6mUHiqG.png)

And none in **Chrome** 108.05:

![](https://i.imgur.com/Pc6Vv5M.png)

# "documentation"

* https://github.com/fergald/docs/blob/master/explainers/css-shadow-parts-1.md  
Says: _"[::part] style inside a shadow tree, from **outside** of that shadow tree."_

* Some AI that often gives inclomplete answers says:  
_"To summarize, the ::part pseudo-element is used to style elements within a Shadow DOM shadow tree that have a part attribute. It **does not style the shadow root itself**._"

# Conclusion?

So I presume FireFox is wrong here?

.

**Comment by rniwa** [comment]
This indeed seems like a bug in Firefox.

**Comment by Danny-Engelman** [comment]
2,5 years later

still the same bug in FireFox
