### ISSUE TITLE
Is this still an "incubation"?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/webcomponents#984]
Sorry for the naive question, but it is this repo still serving as a space for incubation of "web components"?

I see the repo is still used quite a bit (and we don't need to move it or anything!), so just wondering how this space is being used etc. and how issues here might relate to what's in the HTML or DOM specs.

**Comment by rniwa** [comment]
People are using this repository to keep track long standing issues with web components as well as making new proposals before they can be formally proposed as a PR to HTML/DOM specs.

**Comment by yoavweiss** [comment]
Sounds like WAI to me :)

@marcoscaceres - do you think we should mark this repo in some special label?

**Comment by marcoscaceres** [comment]
ok, cool. Thanks @rniwa! 

@yoavweiss, I guess?... but not sure with what label though. From what @rniwa is describing, the repo is serving its intended purpose still (which is great to hear! specially as this repo has been around for almost a decade).
