### ISSUE TITLE
Chrome doesn't repaint with :last-of-type AND shadowRoot AND :host(:active) button

### ISSUE THREAD

**Issue by Danny-Engelman** [WICG/webcomponents#985]
Reporting it here and not with the Chromium team, because it seems ``:host(:active)`` is the culprit

In this code 

```javascript
<style>     
  #LIST div:last-of-type { 
    background:green;
  }
</style>
<div id="LIST"></div>
<script>
  LIST.attachShadow({mode: 'open'})
      .innerHTML = `<style>:host(:active) button { background:red }</style><slot></slot><button>ADD</button>`;
  LIST.onclick = () => LIST.appendChild(document.createElement('div')).innerHTML = `DIV`;
</script>
```

Chrome doesn't update the ``last-of-type`` CSS when clicking the ADD button

![](https://i.imgur.com/Vk3L0X5.png)

Behavior in FireFox is different (and correct I would say):

![](https://i.imgur.com/dJG9GSS.png)

Better test code at: https://jsfiddle.net/WebComponents/Lkah15wy/

* It must be a combination of ``last-of-type`` AND shadowRoot AND ``:host(:active) button``, because: if I take out any of these everything is fine
* replacing ``last-of-type`` with ``last-child`` solves the issue
* replacing ``last-of-type`` with ``nth-last-child(1)`` does NOT solve the issue
* **ADDING** a CSS selector ``div:last-child{ color:gold }`` solves the issue
* replacing ``:host(:active) button`` with ``button:active`` solves the issue 
* replacing the ``<button>`` with a any other element solves the issue
* it does NOT happen on a touch-interaction (touch screen)

**Comment by rniwa** [comment]
Please report bugs to crbug.com. This is an issue tracker for web components standards.
