### ISSUE TITLE
[scoped-registries] Proposal for registry extension

### ISSUE THREAD

**Issue by chalbert** [WICG/webcomponents#989]
I would like to propose a new `extends` option that could be passed on `new CustomElementRegistry()`.

```js
const registry = new CustomElementRegistry({
  extends: [registryA, registryB, registryC]
});
```

## Use case

As a developer, I am building a new component inside the `Products` page of my application. For this component, I will use components coming from the following scopes:

- Global components for the entire app
- Components only available to the `Products` section.
- Components coming from my company's own `Core` library.
- Components coming from 3rd party LibA and Lib2.

In turn, those component may use other component libraries.

Without registry extension, it may be quite a challenge to build a registry that defines every dependencies correctly.

With registry extension, I would do:

```js
const registry = new CustomElementRegistry({
  extends: [appRegistry, productsRegistry, coreRegistry, libARegistry, libBRegistry]
});
```

Conflicts between tag names (when 2 registries try to register the same name) would throw an error and would need to be handled manually.

## About scoped-constructor invocation

I believe that registry extension could be a good alternative to forbidding constructor on scoped elements, when combined with the restriction that constructors are registered on a single registry. 

Extending a common registry would allow reuse of component without having to subclass over and over. The only cases where subclassing would be needed would be when registering some components on a different name than the default one. But this could be handled automatically and the new registry could be cached, see `getRegistry` helper in userland extensions below.

## Userland extensions

You could see some userland ways to make life even easier, here are a few ideas.

Good practice for libraries would be to export a `getRegistry` function with an optional prefix so conflicts could be avoided.

```js
import { getRegistry as getLibARegistry  } from 'lib-a';
import { getRegistry as getLibBRegistry } from 'lib-b';

const registry = new CustomElementRegistry({
  extends: [
    // We register lib-a using predefined names
    getLibARegistry(), 
    // As lib-b conflicts with lib-a, we use a custom prefix for those elements.
    getLibBRegistry({ prefix: 'foobar' })
  ]
});
```

Libraries could build their own registries of multiple sub-registries, for when only part of the library is imported.

```js
const coreRegistry  = new CustomElementRegistry({
   extends: [
      modalRegistry,
      formRegistry,
      gridRegistry,
      titleRegistry,
     /// Etc.
   ];
});
```
Component could include a `getRegistry` static prop that would return a registry with the component's dependencies. Combines nicely with the [requiredElements proposal](https://github.com/WICG/webcomponents/issues/988).

```js
// Could be improved with registry caching and automatic subclassing.
function getRegistry({ prefix = DEFAULT_PREFIX } = {}) {
  const registry = new CustomElementRegistry({
   extends: (this.requiredElements || []).map((Element) => Element.getRegistry({ prefix }))
  });
  registry.define(`${prefix}-${this.baseName}`, this);
  return registry;
}

class ComponentA extends HTMLElement {
  static baseName 'a'
  static getRegistry = getRegistry;
}

class ComponentB extends HTMLElement {
  static baseName 'b'
  static requiredElements = [ComponentA];
  static getRegistry = getRegistry;
  connectedCallback() { this.appendChild(new ComponentA()); } 
}
```

**Comment by xiaochengh** [comment]
I see extension as a natural idea, but I don't see the exact benefit yet. Instead of
```js
const registry = new CustomElementRegistry({
  extends: [registryA, registryB, registryC]
});
```

Why can't we just do
```js
registry.define('component-a', ComponentAFromLibA);
registry.define('component-b', ComponentBFromLibB);
registry.define('component-c', ComponentBFromLibC);
```

---

There's also a contradition between:
- Resolving conflicts with prefix (`getLibBRegistry({ prefix: 'foobar' })`), which creates a copy of the original registry, which means the constructors are registered at multiple places with different names
- Restricting each constructor to a unique registry with a unique local name

**Comment by chalbert** [comment]
One important benefit would be performance, both from a memory and runtime execution point of view. 

For large applications, the number of custom registries could become very large, and many of those registries would be near identical, with only a couple of local component added to some shared components. Maybe browsers can to some magic there, so I might be wrong about the impact about memory, but if we are forced to hold in memory identical definitions, it does not feel quite right.

From a runtime performance point of view, there could be large numbers of identical `define` at startup. This is the point I am the most worried about. I did some quick perf test, see below.

---
You're correct concerning the contradiction. I will have to think about it a bit more, but my first feeling would be that either prefixing could be defined globally as a static method instead of when getting the registry, or maybe a lib could decide to subclass. I would prefer option 1, but this is userland so multiple ways of doing things would be ok.

That is unless the localName could be updated after connection. I suspect there are good reason not to and I don't think it can be polyfilled easily, but allowing localName to mutate on connection would alleviate those issues. Some kind of aliasing feature where a constructor always have a single registry, but can be aliased unto other registries.

--- 
I did some quick perf tests, nothing very scientific. Interestingly, Safari is more performant than Chrome for large number of definitions, so it'll be interesting to test on entry level Android devices.

Anyway, it seems to confirm that keeping the number of definitions as low as possible do matter.

|Device|Is extending|Registry count|Shared element count|Local element average count|Runtime|
|--|--|--|--|--|--|
|Laptop (Chrome)|false|2000|200|5|~450ms|
|iPhone 13|false|2000|200|5|~250ms|
|iPhone 6|false|2000|200|5|~2,500ms|
|||||||
|Laptop (Chrome)|false|500|50|5|~18ms|
|iPhone 13|false|500|50|5|~18ms|
|iPhone 6|false|500|50|5|~172ms|
|||||||
|Laptop (Chrome)|false|200|20|2|~2.5ms|
|iPhone 13|false|200|20|2|~3ms|
|iPhone 6|false|200|20|2|~28ms|
|||||||
|Laptop (Chrome)|true|2000|200|5|~22ms|
|iPhone 13|true|2000|200|5|~9ms|
|iPhone 6|true|2000|200|5|~177ms|
|||||||
|Laptop (Chrome)|true|500|50|5|~6ms|
|iPhone 13|true|500|50|5|~2ms|
|iPhone 6|true|500|50|5|~29ms|
|||||||
|Laptop (Chrome)|true|200|20|2|~1ms|
|iPhone 13|true|200|20|2|~1ms|
|iPhone 6|true|200|20|2|~7ms|

See methodology: https://github.com/chalbert/web-specs-utils

**Comment by justinfagnani** [comment]
fwiw, I think in practice registry inheritance is only going to be of much use when there is component inheritance and the base component uses child components itself. I think this is a fairly rare situation in the code bases I've seen, which haven't features deep class hierarchies where the base classes also creates shadow DOM.

In a fully-scoped app, the number of registries should equal the number of component _definitions_, with the registries shared across all instance of a definition (except in some rare dynamic cases). Registry inheritance probably wouldn't reduce this much. In theory you could find common subsets of dependencies among components, but this won't reduce the registry count. It might reduce the number of raw external registrations, but that might or might not give a perf benefit based on implementation.

Regarding the benchmark, it's testing a polyfill which might not scale the same as a native implementation. And 2000 component definitions is a massive number that I haven't even seen in the largest apps. Photoshop uses ~100 on most pages, YouTube a couple hundred.

**Comment by chalbert** [comment]
> fwiw, I think in practice registry inheritance is only going to be of much use when there is component inheritance and the base component uses child components itself. I think this is a fairly rare situation in the code bases I've seen, which haven't features deep class hierarchies where the base classes also creates shadow DOM.

I might be missing something here, so I'll try make sure I understand. Here a common setup I've encountered with web frameworks:

A developer works on a component that will be consumed in an unknown context. To avoid any chance of conflict, this component will use a scoped registry and avoid assuming global definitions altogether. Inside this component, elements will be used from various sources: a 3rd party component library, company level components,  department level components, and some local component private to the current component. Let's assume a couple hundred components, which is conservative in my experience.

In an ideal world, only components actually used in the component would be defined. But in real world, it may be difficult to know which components are used deeply, so this developer would like to define every known component. 

In this scenario, my understanding is that there will as many definitions on this registry as there are components available, is that correct? There may be many, many such components in an application.

> And 2000 component definitions is a massive number that I haven't even seen in the largest apps. Photoshop uses ~100 on most pages, YouTube a couple hundred.

Actually, the highest benchmark uses 2000 scoped custom element in the DOM, using 200 global definition definitions + 5 definitions specific to each registry scope. Again, nothing scientific, but still realistic I believe. 2000 custom elements may seem a lot, but if you have 100 elements in your DOM that use each 10 components that in turn use 2 elements, and each are scoped, you have 2000 scoped custom elements.

**Comment by justinfagnani** [comment]
The most common pattern with registries will be that each component class has a single registry shared among all its instances. That registry will only contain the _direct_ dependencies of the class. Those dependencies will then have their own registries, one per-class.

So if we have components A,B, and C, there will be three registries, no matter how those inter-depend on each other and no matter how many instances of each there are.

> Inside this component, elements will be used from various sources

I've basically never seen a component like this. Who makes those elements? Who provides the definitions and tag names? This just sounds exotic, and while maybe a use-case for scoped registries for the isolation, not the mainstream case.

**Comment by chalbert** [comment]
> I've basically never seen a component like this. Who makes those elements? 

It's a real-life situation, and not one so uncommon I suspect. I haven't seen this with Web Components, but in React and Angular, yes. I would like to believe that in the future it could be done using WC. 

So in summary, in large companies I have worked at, there would be a centralised team creating shared components for the whole company. A real-life company for example offered 300+ public components, but these components would sometimes in turn use private components only available in the scope of one component. This formed the "Core" component library. Those components would also use a number of libraries for common UI widget.

In addition to "Core", some other departments would offer additional components to be used across the company. For example, the security team offered some authentication-related components.

But then this company is working in a somewhat decentralised way where each department is quite independent. Some of those departments would build npm package, or sometimes federated modules, to offer functionalities specific to this department. This includes UI components, but also "business component", which are akin to views reused in multiple context. I have seen departments offer 100+ components  split in dozens of packages, developed by different teams but pulled together in the same app or high level component. Who actually develop those component would vary; some department had teams building most of those, others would be contributed by specific project teams. 

And then in the context of a single application within this department, there could be up to a half-dozen front-end dev teams working in parallel on different features with sometimes little coordination.

> Who provides the definitions and tag names?

That's the central point. With React, Angular, or most any framework, usage is defined by direct reference, which is not necessarily the case with WC. For a company like the one described above to adopt WC, the consuming component would need to have control on the tagNames. Components that use light-dom references to other components would need to do so without assuming their tagName (granted most usage would be in shadow dom, but I see many cases where light-dom reference would be needed). 

It touches also to #987 as using direct reference to components through constructor would be safer than string-based creation. String-based usage (template or createElement) depends on pre-registration and known tagName. Undefined or wrongly defined elements would not necessarily throw. For these reason, string-based usage would encourage the definition or every known elements instead of only the dependencies or a component.

**Comment by chalbert** [comment]
> The most common pattern with registries will be that each component class has a single registry shared among all its instances. That registry will only contain the _direct_ dependencies of the class. Those dependencies will then have their own registries, one per-class.

Ah right, that's good, sorry I hadn't understood correctly. It does reduce the strain on definition quite a bit.

But the point remains. I won't bore you with more stats as I don't feel much interest in the proposal, but I still see signifiant perf impact on low end device I've tested, even when reducing the number of registries. When in comes to performance of a low-level browser API, I'd just wish that "best" perf would beat "good enough".

Feel free to close the issue.
